### ISSUE TITLE
spawn-count issue

### ISSUE THREAD

**Issue by IPv5** [BG-Software-LLC/WildStacker#102]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.16.5 Airplane
**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
3.5.1build 97
**Describe the bug**
No matter how high I set the spawn-count, it will rarely spawn more than 2 per spawner in a stack. The max entities around spawner is also raised to 128 for testing purposes.
**To Reproduce**
Steps to reproduce the bug.
Upgrade tier to spawn-count of 64
Wait for them to spawn and see the issue
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

**Comment by IPv5** [comment]
Link to error I am getting, not sure if its related to this report above:
https://pastebin.com/x3dsN3T8
This error seems to happen randomly

**Comment by OmerBenGera** [comment]
The error has nothing to do with that, however it's fixed in latest dev build.
I am gonna check the spawn count issue on my localhost and get back to you. However, I need to know your java version as well.

**Comment by OmerBenGera** [comment]
I can't seem to replicate it.
Look for the spawners-override section and turn it off, let me know if it fixes the issue or not

**Comment by OmerBenGera** [comment]
Any news regarding this?
