### ISSUE TITLE
Spawner cant spawn irongolems in the air

### ISSUE THREAD

**Issue by Koudyasek** [BG-Software-LLC/WildStacker#132]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)

Papermc 1.13.2
**Plugin's Version**: -
The newest

**Describe the bug**
Irongolems not spawning in the air, I tried to solve that alr with the Ome_R at the discord.

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
https://pastebin.com/G3ty49x0

**Comment by OmerBenGera** [comment]
Just to remind myself - I said I'll check that out and if I can fix it somehow - probably a bug with how I implemented the 1.13.2 nms adapter.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
