### ISSUE TITLE
Spawners stack spawn 1 by 1

### ISSUE THREAD

**Issue by LeRoiDamien** [BG-Software-LLC/WildStacker#133]
Hello

**Minecraft's Version**
Paper1.16.5

**Plugin's Version**: -
WildStacker-b103

**Describe the bug**
It has been 2-3 weeks since the spawner stack no longer works properly
On almost all the islands the players have 30 spawners stack but it spawns 2 mobs par2 in addition there is an upgrade with superiorskyblock for the spawn of x2 mobs

**Comment by OmerBenGera** [comment]
Duplicate of #38
