### ISSUE TITLE
Dupli piglin gold

### ISSUE THREAD

**Issue by LeRoiDamien** [BG-Software-LLC/WildStacker#137]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
WildStacker-b103

**Describe the bug**

Hello, there is a duplication problem with the piglins I attach a video to show you I even tried without a stack.
https://youtu.be/805r94eQu3w

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue. I dropped gold ingots to a stack of piglins, killed them and everything was fine.

**Comment by LeRoiDamien** [comment]
Hello, I just reproduced it so I don't know how it's done: /

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed with default config.

**Comment by OmerBenGera** [comment]
Also make sure you use latest WildStacker dev build

**Comment by LeRoiDamien** [comment]
Here I give you the video or I test with only Wildstacker latest version and the basic config

https://youtu.be/vAs-COQWJmY

**Comment by OmerBenGera** [comment]
From the video it looks like it happens with baby piglins, not the adult ones. I am gonna check that out

**Comment by LeRoiDamien** [comment]
Ok ^^

**Comment by OmerBenGera** [comment]
I could replicate the issue with the baby variants of piglins, gonna check that out rn

**Comment by LeRoiDamien** [comment]
Ok thank you

**Comment by OmerBenGera** [comment]
Should be patched in latest dev build, let me know if it works for you :)

**Comment by LeRoiDamien** [comment]
it's good thank you very much
