### ISSUE TITLE
Error in the console 

### ISSUE THREAD

**Issue by Demaniaque** [BG-Software-LLC/WildStacker#138]
**Minecraft's Version**
Spigot 1.16.3

**Plugin's Version**: -
3.5.2

**Describe the bug**

I have a lot of error in console : 

> [16:44:36] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot convert PLAYER into a stacked entity.
> [16:44:36] [Server thread/WARN]: at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedEntity(SystemHandler.java:131)
> [16:44:36] [Server thread/WARN]: at com.bgsoftware.wildstacker.api.WildStackerAPI.getStackedEntity(WildStackerAPI.java:42)
> [16:44:36] [Server thread/WARN]: at com.bgsoftware.wildstacker.api.WildStackerAPI.getEntityAmount(WildStackerAPI.java:50)
> [16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:772)
> [16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:115)
> [16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254)
> [16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123)
> [16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:85)
> [16:44:36] [Server thread/WARN]: at java.util.ArrayList.forEach(ArrayList.java:1259)
> [16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:79)
> [16:44:36] [Server thread/WARN]: at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
> [16:44:36] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [16:44:36] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [16:44:36] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
> [16:44:36] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [16:44:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
> [16:44:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:309)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:268)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:238)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1219)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
> [16:44:36] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [16:44:36] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [16:44:36] [Server thread/INFO]: Failed to get amount of entities using WildStacker for mob 02f30cab-0487-3f13-a426-87c96bd9dac4

The error is triggered when a player break a block with a pickaxe.

 [Server thread/INFO]: Failed to get amount of entities using WildStacker for mob 02f30cab-0487-3f13-a426-87c96bd9dac4"

**Additional information**

I think the error appears especially when players break blocks with an efficiency 5 deck and the Haste effect

The problem appears with the default configuration plugin except the number of entities for stack which is fixed at 5 for all 

Thanks for your help !

**Comment by Skizzles** [comment]
@Demaniaque 
`[16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:772)
[16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:115)
[16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254)
[16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123)
[16:44:36] [Server thread/WARN]: at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:85)`

This looks related to AE which is Advanced Enchantments from GC, the plugin is trying to process an enchant while hooking into WildStacker. I would reach out to GC in regards to this error.

**Comment by Demaniaque** [comment]
Hello 
Thank you for your answer!
Indeed I am sorry I did not see the link with ae... 
It has two version of late on my server (for Advanced Enchantement) , I will first make the update of AE and I come back to you if the problem is still present!

**Comment by Demaniaque** [comment]
@Skizzles 
The update of AdvancedEnchantment to version 21.6 has fixed the problem

Thanks for your help! 

Demaniaque
