### ISSUE TITLE
Error spam.

### ISSUE THREAD

**Issue by Faceless0102** [BG-Software-LLC/WildStacker#139]
**Minecraft's Version**
PaperSpigot 1.12.2

**Plugin's Version**: -
b96

**Describe the bug**
https://pastebin.com/AYG69Pf5

**Comment by Skizzles** [comment]
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard

Do you have WorldGuard installed @Faceless0102? Seems your settings are looking for WorldGuard to hook into. Try installing WorldGuard or updating it.

**Comment by Faceless0102** [comment]
I’m using 6.2.2

**Comment by OmerBenGera** [comment]
Use latest version and it should be fixed.
Let me know if it works for you
