### ISSUE TITLE
Piggy spawners after restart

### ISSUE THREAD

**Issue by Koudyasek** [BG-Software-LLC/WildStacker#143]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
Paper 1.13.2

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
Newest devbuild (106)

**Describe the bug**
After restart all spawners are piggy

**To Reproduce**
Steps to reproduce the bug.
Set this value to true in the config: https://prnt.sc/1175uvw

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
-----

**Comment by OmerBenGera** [comment]
Does it only happens when spawners-override is set to true?

**Comment by Koudyasek** [comment]
Yes

**Comment by Koudyasek** [comment]
When i was set it to false, the irongolems doesn't spawn in air, but after restart they are normal igs spawners

**Comment by Koudyasek** [comment]
If you want, you can ping me on discord (Koudy#5934) and I can show you that on my server.

**Comment by OmerBenGera** [comment]
I am gonna check that out, probably an issue with the implementation of the plugin

**Comment by OmerBenGera** [comment]
I could replicate the issue with the baby variants of piglins, gonna check that out rn

**Comment by Koudyasek** [comment]
Alr thank you, i hope it will be fixed soon.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works for you

**Comment by Koudyasek** [comment]
Yes its fixed, thank you.

**Comment by Skizzles** [comment]
Closing this out since it has fixed your issue!
