### ISSUE TITLE
Spawners freezing/not-working sometimes

### ISSUE THREAD

**Issue by klaidoshka** [BG-Software-LLC/WildStacker#146]
**Hello once again! 👋😊**

**We are using:**
WildStacker 3.5.1-DEVb102
PaperSpigot 1.8.8

**The 'problem', bug, issue, weird acting of spawners:**
For some reason, I don't know why, spawners are freezing - not working anymore. It feels that spawners possibly think that there are no players around, the information menu (time before spawning/other info) isn't updating, is frozen. Mining and replacing the spawner/-s fixes the problem, they start working again. Or coming to chunk some time later also fixes the frozen-spawners act too, but that doesn't work out all the time either.

Anyways, just wanted to share this weird phenomenon with you. Maybe you could think of anything who could be actually at the fault here, if not, no problem, maybe it's something on our server's side and somehow will be fixed later on by itself 😄...
-We're not using any other plugins that could interact with spawners.

Edit: I don't think that the latest development builds would fix the problem, but I'm going to update the version tomorrow (I think) and will report if anything would change regarding this 'issue'

**Comment by OmerBenGera** [comment]
So you think the spawners aren't updating, but when replacing them or updating the chunks it fixes itself?
Sounds like something is removing the tile entity from the ticking list of the world to me.

**Comment by klaidoshka** [comment]
Hello 👋

Yes, that is correct. Updating the plugin didn't change anything and it doesn't occur 'that' often.
Server has some big problems with tileEntities, not gonna lie, is overtaking tick as hell 😅, maybe that could be the problem? Or something with spigot.yml's max-tick-time? (set to 1000)... I have no clue if that could be the main reason of this situation 😞

There is nothing else in the plugins that could play with tileEntities limits/controls, I think.

**Comment by OmerBenGera** [comment]
> 
> 
> Hello 👋
> 
> Yes, that is correct. Updating the plugin didn't change anything and it doesn't occur 'that' often.
> Server has some big problems with tileEntities, not gonna lie, is overtaking tick as hell 😅, maybe that could be the problem? Or something with spigot.yml's max-tick-time? (set to 1000)... I have no clue if that could be the main reason of this situation 😞
> 
> There is nothing else in the plugins that could play with tileEntities limits/controls, I think, at least not so visible by names or configurations in the configs.
> 
> **Edit:** Anyways, that probably means that it is not stacker's fault, someone else is at fault. Okay, I will be trying to figure it out by myself then 😄, thanks for you answer!
> 
> I'll leave the issue open if there would be anything else you would want to comment, if not, then you can close it, thanks once again! ♥

Take a spark profiler please about the tick lag issue, might be due to the plugin.

**Comment by klaidoshka** [comment]
> Take a spark profiler please about the tick lag issue, might be due to the plugin.

First time using the plugin, had a problem to take the correct profiler, because default one isn't taking fine stuff, I think? 😄
Anyways, I got this: https://spark.lucko.me/6yhEFBHNNm

**Comment by OmerBenGera** [comment]
> 
> 
> > Take a spark profiler please about the tick lag issue, might be due to the plugin.
> 
> First time using the plugin, had a problem to take the correct profiler, because default one isn't taking fine stuff, I think? 😄
> Anyways, I got this: https://spark.lucko.me/6yhEFBHNNm
> 
> **Edit**: used --combine-all flag, also, seems like hoppers are the main problem (thought so all the time, we got way too many farms with too many hoppers, after updating to 1.16 in few months this will be fixed, now don't wanna destroy the farms that people built 5-8 months ago. :|

WildStacker seems fine tbh, so yeah it's not related to the plugin.
However, the spawners not working anymore is probably an issue with the plugin
Let me know if it happens with only WildStacker installed

**Comment by klaidoshka** [comment]
After testing in a test server with no plugins, only WildStacker, it didn't occur. But as I said, it occurs not that often, quite rarely, only happened to a few players of our server. So, I can't really give any certain information, but after being AFK for 6hrs it didn't occur, so maybe it's not the stacker's fault 🤔

**Comment by OmerBenGera** [comment]
I'll check that out, and if I can't find anything I'll close it

**Comment by OmerBenGera** [comment]
If it happens again, let me know
