### ISSUE TITLE
Problem with JetsMinions

### ISSUE THREAD

**Issue by TheMartyCZ** [BG-Software-LLC/WildStacker#152]
**Minecraft's Version**
ssspigot 1.16.5 - latest

**Plugin's Version**: -
WildStacker b110 - latest

**Describe the bug**
I found a duplicate bug with items. If the minions kill 1 blaze, the items are duplicated. Thus, when blaze kills 10 minions, 30 blaze rods fall out of blaze, instead of 3. This problem only occurs with the wildstacker plugin. For example, the ultimatestacker does not have this problem.

**To Reproduce**
1. Download plugin JetsMinions
2. Download plugin WildStacker
3. Set up wildstacker stacking mobs
4. get a slayer - /minions give <nick> slayer 10 3
5. Put 10 of them
6. put 10 of on the ground
7. Take a spawn egg blaze and place it between them
8. The result should be duplication of items

**Comment by OmerBenGera** [comment]
Take a video of the issue please.
The issue might be due to how JetsMinions looking for entities and how they kill and calculate drops.

**Comment by TheMartyCZ** [comment]
https://www.youtube.com/watch?v=hMEfSzJ2Cow

Here is a video.

**Comment by OmerBenGera** [comment]
Does it happen due to the amount of minions there?
Also, does it happen only when WildStacker is installed? Because it seems like you don't spawn stacked mobs and it occurs.

**Comment by TheMartyCZ** [comment]
Yes, when there is more minion, it does. And yes, it only does this when a wildstacker is installed. When I install UltimateStacker it works normally
When I turn off mob stacking in the wildstacker plugin, it works normally.

**Comment by OmerBenGera** [comment]
Patched in latest dev build

**Comment by TheMartyCZ** [comment]
The problem still persists. :/

**Comment by TheMartyCZ** [comment]
@OmerBenGera

**Comment by TheMartyCZ** [comment]
The problem still persists. :/ @OmerBenGera

**Comment by OmerBenGera** [comment]
From my testings it doesn't happen anymore. WildStacker now listens to the SlayerSlayEvent and if the entity was killed already, and it if was it removes the entity from the list of entities to be killed by JetsMinions
Are you using latest versions of WS and JetsMinions?

**Comment by TheMartyCZ** [comment]
Yes, I use. Should I send you my test server, where am I testing this?

**Comment by OmerBenGera** [comment]
> 
> 
> Yes, I use. Should I send you my test server, where am I testing this?

Nope, there's no need for that.
Talk with Jets, let him know about the issue and the fix that I made, ask him why it could happen

**Comment by TheMartyCZ** [comment]
I will try to write to him, I have solved this problem with him before and he did not know what to do. Let's hope he knows how to fix it now.

**Comment by TheMartyCZ** [comment]
I found out that when I spawn 1 mob it works, but when I spawn more mobs it doesn't work and it still drops a lot of items.

**Comment by TheMartyCZ** [comment]
Video: https://youtu.be/tcA_j6C-Ndg

**Comment by OmerBenGera** [comment]
> 
> 
> I found out that when I spawn 1 mob it works, but when I spawn more mobs it doesn't work and it still drops a lot of items.

It doesn't help tho - did you contact him?

**Comment by TheMartyCZ** [comment]
Yes, I wrote to him. He is said to be thinking about the problem, but he doesn't know much about how to solve it. We will therefore give him more time.

**Comment by OmerBenGera** [comment]
@TheMartyCZ Mind reminding him about the issue again?

**Comment by TheMartyCZ** [comment]
Yes, but he still doesn't know how to fix it. :/

**Comment by OmerBenGera** [comment]
Sounds like he hasn't even tried, he hasn't even responded here...

**Comment by TheMartyCZ** [comment]
I sent him a link to this thread and looked here.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to take too much time.
Please continue this conversion with Jet, and if there are any questions, feel free to send them here.
