### ISSUE TITLE
DUPE BLOCKS

### ISSUE THREAD

**Issue by MZhenkM** [BG-Software-LLC/WildStacker#156]
**Minecraft's Version**
(Server 1.12.2) (Client 1.8 - 1.8.9)

This is a rare bug, because this happens only when the client is on 1.8 to 1.8.9
I have the server in 1.12.2 and enabled so that users can enter any version of 1.8

**Plugin's Version**: -
Last dev

**Describe the bug**

It happens that users can duplicate items with the mineral barrels, it happens with any sweep.

If you place blocks with the numbers from the keyboard directly in the inventory of the barrel, it returns them and adds them to the barrel, so that way it is doubled

**To Reproduce**
User video, sorry for the quality.
https://www.youtube.com/watch?v=-_Wkzwd4XHg&feature=youtu.be

**Additional information**

I couldn't get it to work, I removed all plugins and leave only the wildstacker and superiorskyblock for the user to test and it keeps happening.

I try myself and I can't make this happen, but the user does, so I honestly don't understand what happens.

**Comment by MZhenkM** [comment]
Hello,???

**Comment by OmerBenGera** [comment]
Are you sure it's related to WildStacker and not the plugin that lets 1.8 players to join your 1.12 server?

**Comment by OmerBenGera** [comment]
I am not sure if I can actually fix it, but I'll do my best to take a look into this.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build - let me know if it works as it should now

**Comment by MZhenkM** [comment]
Fixed, thank you very much for the incredible work, I apologize for the inconvenience.
