### ISSUE TITLE
Spawner spawned mobs does not stack with each our

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#158]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
purpur1.16.5 #1060

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
WildStacker-b114

**Describe the bug**
When i put a spawner of anytype, i wait for the mob to spawn, after spawned 2 round, the 1st round mob does not stack with second round mobs.
i have tested using simulation tool, it shows the mob can stack, however, they not stacking.
![unknown 1](https://user-images.githubusercontent.com/61608872/115237023-a56f7c00-a14e-11eb-981d-bc77ba8ba83d.png)
![unknown 1](https://user-images.githubusercontent.com/61608872/115237049-ab655d00-a14e-11eb-91e5-f78b642548cd.png)

I have asked this question in discord too, however i found out that there is also some other people encountered same problem 

**To Reproduce**
Steps to reproduce the bug.

put a spawn, wait the spawner to spawn 2 times

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome

config.yml
https://paste.gg/p/anonymous/c4fbccab43ae4e0e848d82a9dd41babb

**Comment by MZhenkM** [comment]
my answer may be ignorant, but I think this is normal, if the mobs are not in the spawn range to stack they will not do it, in your configuration you have minimum range 5. if the mobs are not in that range it will not be stacked.

**Comment by hkkongou** [comment]
> my answer may be ignorant, but I think this is normal, if the mobs are not in the spawn range to stack they will not do it, in your configuration you have minimum range 5. if the mobs are not in that range it will not be stacked.

you taking about the
```
  merge-radius:
    all: 5
``` 
right?

i am assuming this setting stack mobs by checking mob similarity within this radius 🤔 and stack it into one, since the mob is standing with radius less than 5 so it should be stacking 🤔

**Comment by OmerBenGera** [comment]
Try disabling linked entities if you have it enabled, let me know if it helps.
Also upload your config to pastebin please

**Comment by hkkongou** [comment]
not working :(
![image](https://user-images.githubusercontent.com/61608872/115943535-08f90100-a4e3-11eb-8612-6cf48ee0f77a.png)

https://pastebin.com/SUB1cH4h

**Comment by OmerBenGera** [comment]
Enable stack interval, set it to around 200 and it will be fixed :)
Make sure you change the entities stack interval and not the items one.
