### ISSUE TITLE
[Bug] Mob

### ISSUE THREAD

**Issue by Acenox** [BG-Software-LLC/WildStacker#159]
**Minecraft's Version**
GemSpigot-1.8.8 (Fork of TacoSpigot-1.8.8)

**Plugin's Version**: -
WildStacker-b111

**Describe the bug**
Thanks to an arrow then by switching to the sword very quickly you can glitch the mob and therefore kill the mobs extremely quickly.

**To Reproduce**
- Shoot a mob
- Switch between sword and bow

Video: https://www.youtube.com/watch?v=kQ3lOXOteu4

**Additional information**
There is no error in the console.

**Comment by OmerBenGera** [comment]
This is a bug with Minecraft and has nothing to do with the plugin.
