### ISSUE TITLE
Mobs death too fast

### ISSUE THREAD

**Issue by nicolaspujol** [BG-Software-LLC/WildStacker#162]
Minecraft Paper 1.16.5 - 670

WildStacker 3.5.2
WildStacker b119

Mobs stacked are killed too fast.
1st mob is killed at normal speed, following stacked ones are killed too fast.
In action : https://www.youtube.com/watch?v=u6VNW7isQpc

This behaviour is linked to the config.yml following option:
next-stack-knockback: false
with true, mobs die normally, with false, same issue as in the video.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)

**Comment by nicolaspujol** [comment]
Same thing happens with water on blaze, mobs on a cactus, and probably other things

**Comment by nicolaspujol** [comment]
Same thing happens with water on blaze, mobs dying on a cactus, and probably other things

**Comment by OmerBenGera** [comment]
> 
> 
> Same thing happens with water on blaze, mobs dying on a cactus, and probably other things

Mind making a list of causes so I can fix them all?

**Comment by nicolaspujol** [comment]
Fast kill bug :
Arrows (using redstone)
Cactus
Falling blocks / Suffocation
Explosions (light a creeper kill the whole stack at once)
Magma Block
Sweet Berry Bushes
Wither rose
Campfire

Tested and is ok :
Drowning
Falling
Fire
Lava (fixed previously)

Untested :
Lightning (using trident with channeling)
Thorns enchantment
Wither

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by nicolaspujol** [comment]
Same thing happens when mob is killed by player (sword for eg), and is in lava (for eg). 1st is killed by player, followings are killed too fast by lava

**Comment by OmerBenGera** [comment]
> 
> 
> Same thing happens when mob is killed by player (sword for eg), and is in lava (for eg). 1st is killed by player, followings are killed too fast by lava

that's fine. If they are killed by a player, you'll be able to fast-kill them.

**Comment by OmerBenGera** [comment]
I am closing this for now :)

**Comment by nicolaspujol** [comment]
Player should, but lava/cactus... probably not.
Here is what i'm talking about : https://www.youtube.com/watch?v=6oB8_jm3bzs

**Comment by OmerBenGera** [comment]
After you kill an entity with your sword, you or any other damage source can hit it fast when you have next-stack-knockback.
That's the purpose of the next-stack-knockback feature. If you don't want it, just turn it on.
