### ISSUE TITLE
Mobs death too fast

### ISSUE THREAD

**Issue by nicolaspujol** [BG-Software-LLC/WildStacker#163]
Following https://github.com/BG-Software-LLC/WildStacker/issues/162
Same thing happens with water on blaze, mobs dying on a cactus, and probably other things

**Comment by OmerBenGera** [comment]
Reopen the other issue, don't open new issues.

**Comment by nicolaspujol** [comment]
> Reopen the other issue, don't open new issues.

I can't reopen an issue if i'm not the one that closed it

**Comment by OmerBenGera** [comment]
> 
> 
> > Reopen the other issue, don't open new issues.
> 
> I can't reopen an issue if i'm not the one that closed it

Ah I didn't know that. Well, as you did is fine as well :)
We'll move to there.
