### ISSUE TITLE
Slimes and Magmas despawn

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#166]
1.13.2 Paper

Version: B110

When Slimes or Magmas go to stack they just despawn.

Place down spawner and it will happen

I dont know what the issue is. Im sorry. But again when SLimes and Magmas of all sizes go to stack after x amount of time ( 5 seconds) they just despawn. No hidden stacks anywhere near to stack into.

Thank you

**Comment by OmerBenGera** [comment]
Probably because of ypur stack interval, increase it.

**Comment by TenReeez** [comment]
It is currently set to 200 and still same issue

How high should I go without a performance issue?  ty

**Comment by OmerBenGera** [comment]
Take a video of the issue please.

**Comment by TenReeez** [comment]
https://filebin.net/35f23sj5bxk9naxa/My_Video.mp4

Its on 600 interval

Thank you

**Comment by OmerBenGera** [comment]
The video doesn't show much, can you take a new video?

**Comment by OmerBenGera** [comment]
Any news regarding this?
