### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Troaxx** [BG-Software-LLC/WildStacker#167]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
Paper 1.16.5

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
3.5.1

**Describe the bug**
Console spammed me with this error when restarting the server, not sure if it's bad but thought I'd post it here since I can't get Omer's attention via discord (can't @ you in server)

**To Reproduce**
Steps to reproduce the bug.
Restart the server. 

**Additional information**
Additional information that can help understanding the issue.
None, no idea how it happened. 
Config file, clips, etc are more than welcome.
![image](https://user-images.githubusercontent.com/40354680/118478765-d6899f00-b742-11eb-9ccb-7901306571fa.png)

**Comment by OmerBenGera** [comment]
You can ignore it.
