### ISSUE TITLE
Question..

### ISSUE THREAD

**Issue by srrawr11** [BG-Software-LLC/WildStacker#174]
Is it posible to not remove the named animals when the kill-task passes?
I havent found that section in the config.. If not, it is posible to add it?

Thanks!

**Comment by OmerBenGera** [comment]
Entities that were named using name tags will not be removed in kill task.
However, if the "named animals" were named using a custom plugin, you'll have to use the blacklisted-names section instead.

**Comment by srrawr11** [comment]
Alright, so which version is it?
No, just gonna use the classic nametag

**Comment by OmerBenGera** [comment]
If you use vanilla name tags, then they will not get removed.
