### ISSUE TITLE
Stacking Problem

### ISSUE THREAD

**Issue by Sharki0** [BG-Software-LLC/WildStacker#177]
**Minecraft's Version**
![descărcare](https://user-images.githubusercontent.com/44399713/119233842-78d6c780-bb33-11eb-9b77-180849fd3dd3.png)

**Plugin's Version**: -
![descărcare (1)](https://user-images.githubusercontent.com/44399713/119233852-7d9b7b80-bb33-11eb-8973-a7fac3659b90.png)

**Describe the bug**
I downloaded the latest version and the animals or mobs are no longer stacked 
![unknown](https://user-images.githubusercontent.com/44399713/119233795-45943880-bb33-11eb-9270-c6a1ae81b79c.png)
![unknown (1)](https://user-images.githubusercontent.com/44399713/119233778-3614ef80-bb33-11eb-9f1d-246d1b57de15.png)

**To Reproduce**
/

**Additional information**
https://pastebin.com/FbDrjSQv here ist my wd config

**Comment by OmerBenGera** [comment]
It works fine for me.
Mind testing it yourself with cow spawners?

**Comment by Sharki0** [comment]
yes i test with cow spawner
![Screenshot_3](https://user-images.githubusercontent.com/44399713/119234821-82166300-bb38-11eb-97f7-3361e7491b01.png)
w but nothing

**Comment by OmerBenGera** [comment]
> 
> 
> yes i test with cow spawner
> ![Screenshot_3](https://user-images.githubusercontent.com/44399713/119234821-82166300-bb38-11eb-97f7-3361e7491b01.png)
> w but nothing

my bad, you have cows blacklisted from being stacked, of course it will not work

**Comment by Sharki0** [comment]
I really don't go at all, there are problems with stacking and there's still a very big lag

as you can see here, everything comes from the wildstacker
TIMINGS: https://timings.aikar.co/?id=e2671082961249f9bd903bed36d65e0f#timings 
SPARK: https://spark.lucko.me/JaPfmMy6S3

**Comment by Sharki0** [comment]
and?

**Comment by Sharki0** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/44399713/119710092-a2129300-be66-11eb-930d-0eaf5f3bd12a.png)
in general I found the problem, if I put this [entities to false] there is no more lag.
entities:
   # Should entities get stacked on the server?
   enabled: true to false

or if the change in this setting is the same lag

  # Blacklisted entities are entities that won't get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable blacklisted entities, use "blacklist: []"
  blacklist:
  - WITHER
  - IRON_GOLEM
  - PIG_ZOMBIE
  - ZOMBIE
  - SKELETON
  - ENDERMAN

**Comment by OmerBenGera** [comment]
The main issue comes when WildStacker creates a task to be ran on the main thread, and SpigotTimings tries to get the name of the class: https://gyazo.com/89f9135f496723a4823d0516a1b52fb3
So it's technically not an issue with WildStacker, but maybe I can do something in order to fix it.
And yes, it happens when entities stack together, that's why it's fixed when you disable entities stacking.

**Comment by OmerBenGera** [comment]
I pushed version b129, check it out, hopefully it's better

**Comment by OmerBenGera** [comment]
Any news regarding this?
