### ISSUE TITLE
Gold duplication glitch with baby piglins : Wildstacker 3.5.2 on spigot.

### ISSUE THREAD

**Issue by Peeraboon** [BG-Software-LLC/WildStacker#178]
**Minecraft's Version**
This server is running Purpur version git-Purpur-1127 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**: -
Wildstacker 3.5.2
https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-wildstacker-%E2%9A%A1%EF%B8%8F-spawners-entities-drops-blocks-%E2%9A%A1%EF%B8%8F-spawner-upgrades.87404/

**Describe the bug**
able to dupe gold with baby piglins.

**To Reproduce**
1.spawn 5 baby piglins in the nether.
2.Then throw 4 stacks of gold to them.
3.They will pickup some gold
4.After around 1-2 minutes they will dupe the gold.

**Additional information**
default config.

**Comment by OmerBenGera** [comment]
The bug is already fixed in dev builds :)
https://bg-software.com/wildstacker
