### ISSUE TITLE
Piglin Brutes do not keep stack data when zombified?

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#179]
**Minecraft's Version**
1.16.5 Purpur

**Plugin's Version**: -
b123 dev

**Describe the bug**
Piglin brutes lose their stack amount when dealing with zombified piglin

**To Reproduce**
video

**Additional information**
https://www.youtube.com/watch?v=cE9T56uSHkI

**Comment by OmerBenGera** [comment]
I added the ability to configure which transform reasons the plugin should check and copy the data to the transformed entities - so you have the ability to fix it yourself.
Also by default I added the zombified piglin transform so it's fixed without doing any additional work
