### ISSUE TITLE
Villagers stacking and acting as one

### ISSUE THREAD

**Issue by camochameleon56** [BG-Software-LLC/WildStacker#180]
I have an issue with villager farms in which they stack and do not separate. For example, many times baby villagers have stacked together, which is fine. But when they grow up, they do not separate. If i have one composter, both of the villagers may become farmers.

**Comment by OmerBenGera** [comment]
I don't quite sure what you mean.
You're looking so when a stacked baby villager grows, it will be split again?

**Comment by OmerBenGera** [comment]
Any news regarding this?
