### ISSUE TITLE
[Suggestion] Toggle for entities that are spawned by Spawn Eggs to not be stacked 

### ISSUE THREAD

**Issue by WizWazWizard** [BG-Software-LLC/WildStacker#183]
Allow players to spawn mobs with a spawn egg without stacking the mobs. For example, if someone wanted to make a cow farm for aesthetic reasons.

This could be a toggle under Entities:

```
# Do you want entities that are spawned via spawn eggs to be stacked?
EggEntity: true/false
```

**Comment by OmerBenGera** [comment]
Add "SPAWNER_EGG" to the blacklisted section..
Also, don't ask for new features in the issues tracker.
