### ISSUE TITLE
BUG mob xp with mypet plugin

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#184]
VERSION: 1.16.5 lastest tuinity verion

PLUGIN VERSION: 3.5.2- DEV 131

Pet from MYPET plugin dosent get xp for levelling when i kill mob, this problem append only with this plugin

**Comment by OmerBenGera** [comment]
Contact MyPet developer and ask him why can it occur, if the EntityDeathEvent is called normally.
Maybe there's a check that causes MyPet to not give XP anymore.
You can also direct him to this issue so we'll be able to talk directly.

**Comment by kedavlar** [comment]
Mypet have too many conflict with other plugin.. for now i remove it.. so, no worry

**Comment by OmerBenGera** [comment]
I see. So for now, I am closing this.
If you ever want to re-install it, you are more than welcome to reopen the issue :)
