### ISSUE TITLE
Bug: spawner spawning mob more than it should be.

### ISSUE THREAD

**Issue by Peeraboon** [BG-Software-LLC/WildStacker#185]
**Minecraft's Version**
This server is running Purpur version git-Purpur-1151 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**: -
WildStacker-b131

**Describe the bug**
When set spawn-count of spawner to 1
and set limit of entity stack to 20
like this
  limits:
    ALL: 20
When place 21x pig spawner, it should spawn 20x pig and 1 pig
but it spawns 20x pig 2 stacks. (20x pig and 20x pig)

**To Reproduce**
1.set spawn-count of spawner to 1
2.set entity stack limit to 20
  limits:
    ALL: 20
3.place 21 pig spawners.
4.wait for it to spawn. It should spawn 21 pigs because spawn-count is 1.
5.It spawn 40 pigs! ( 20x pig 2 stack )

**Additional information**

**Comment by OmerBenGera** [comment]
Fixed in latest dev build ^^
