### ISSUE TITLE
BUG on mob spawn

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#186]
MINECRAFT 1.16.5 lastest version of tuinity

PLUGIN VERION: 3.5.2- DEV 134

BUG: sometimes the spawn of mob is bugged and spawn only 1 mob instead of 30-40 with a lot
of spawner.

TO REPRODUCE: place a lot of spawner like.. 20-30 or more and go to another location after the
first stack of mob spawn, then come back and wait mob for spawn. Sometimes is bugged, 
sometimes not, u maybe need to do that a few times

**Comment by OmerBenGera** [comment]
Take a video of the issue please

**Comment by kedavlar** [comment]
here the clip, i cant send longer clip but as u can see , sometimes spawn only 1 mob, no matter how many spawner i have.. and every time i have to remove and place again every spawner



https://user-images.githubusercontent.com/85011614/121514096-ef0c7280-c9eb-11eb-8306-ece06aecea32.mp4

**Comment by xsorencoolx** [comment]
same as me
but diffrent

**Comment by OmerBenGera** [comment]
> 
> 
> here the clip, i cant send longer clip but as u can see , sometimes spawn only 1 mob, no matter how many spawner i have.. and every time i have to remove and place again every spawner
> bug1.mp4

Check using /ws inspect for the stack size of the spawner

**Comment by kedavlar** [comment]
stack-amount: 6 as u can see in the clip

**Comment by OmerBenGera** [comment]
Check it out with /ws inspect to make sure it still has the stack size that is shown in the hologram.

**Comment by kedavlar** [comment]
i already test this thing.. nothing change, the spawner are still 6 or more, depend on player..

**Comment by OmerBenGera** [comment]
Weird. Send me your config via pastebin and let me know what java version you use.

**Comment by kedavlar** [comment]
i use java 11 and this is the config https://pastebin.com/nUYaVjVE

**Comment by OmerBenGera** [comment]
Try making it so COW spawners will have no spawn conditions and check if it helps.
About the cave spiders spawning only 1 mob, I am not sure why it occurs at this moment.

**Comment by kedavlar** [comment]
it happend to all player with every spawner..

**Comment by OmerBenGera** [comment]
> 
> 
> it happend to all player with every spawner..

ok? how is it related to anything that I said?
Also, I pushed an update to fix the failure reason showing no nearby players available.

**Comment by kedavlar** [comment]
u mention cow, but this bug happend with all spawner, ill try last update soon

**Comment by OmerBenGera** [comment]
> 
> 
> u mention cow, but this bug happend with all spawner, thats why,.. and.. ill try last update soon

If we find how to fix the cow spawners, we'll find how to fix all the spawners.

**Comment by kedavlar** [comment]
ill do some test with no condition

**Comment by kedavlar** [comment]
ok.. after few test nothing change.. :/

**Comment by kedavlar** [comment]
hmm.. with now option for cow with no spawn condition i found new bug.. when i go away and come back tha spawner keep saying ''there are no nearby player'' and cow dosent spawn

**Comment by OmerBenGera** [comment]
Try replicating the issue on another server with only WildStacker installed

**Comment by kedavlar** [comment]
i found a solution for my server.. i cant test on other server for now. I disable spawn override

**Comment by OmerBenGera** [comment]
> 
> 
> i found a solution for my server.. i cant test on other server for now. I disable spawn override

Ahm ok, well if you can't test it, I can't really do anything regarding this...

**Comment by kedavlar** [comment]
sorry, but i dont have any other server

**Comment by kedavlar** [comment]
with 3.6 , with the same config, mob somatimes stop stacking into old stack and crate a new one

**Comment by OmerBenGera** [comment]
> 
> 
> sorry, but i dont have any other server

Just open one on your own computer, it takes 5 minutes to do so.

**Comment by OmerBenGera** [comment]
> 
> 
> with 3.6 , with the same config, mob somatimes stop stacking into old stack and crate a new one

This has nothing to do with this issue, open a new issue if you believe there's a bug to address

**Comment by kedavlar** [comment]
ok.. for now i dont have time to test this, for now my solution is to not use the lastest version. thanks anyways

**Comment by OmerBenGera** [comment]
I am closing this as you can't test it and I can't replicate it.
If someone else encounters the issue, make sure you reopen the issue so we can get it fixed.
