### ISSUE TITLE
Spawn reason not working

### ISSUE THREAD

**Issue by quimalbert** [BG-Software-LLC/WildStacker#189]
Hi, I'm trying to disable Creepers spawned from Eggs and Commands to be stacked. Followed the guide, but it doesn't work. ItchyDichy told me to come here and make an issue. Here is my config snippet:
https://pastebin.com/FrFzcZnY
Using WildStacker 3.5.2 and Tuinity 1.16.5

**Comment by OmerBenGera** [comment]
Use SPAWNER_EGG and CUSTOM instead.
You can also find the spawn reasons of the mobs using the /ws inspect tool.
Next time, please open an issue using the format.
