### ISSUE TITLE
Spawner Conditions are not working

### ISSUE THREAD

**Issue by ProfLinebeck** [BG-Software-LLC/WildStacker#191]
**Minecraft's Version**
Spigot 1.16.5

**Plugin's Version**: -
Latest

**Describe the bug**
Spawner conditions are not working for me. I've tried setting conditions via both config and "/stacker settings", however none of these ways worked.
I want to disable spawn conditions for all mobs.
Tried to use:
`      ALL: []`
and
```
      ALL: 
       - NOT_PEACEFUL
```
and
`      COW: []`
and
```
      COW: 
       - 'NOT_PEACEFUL'
```
and
```
       COW: NOT_PEACEFUL
```
Tried to set "false" and "true", as well as "NOT_PEACEFUL" inside the settings GUI as well.
Also tried with a normal player(non-admin & non-ranked)
**To Reproduce**
Setting up any conditions and try ingame if they work -> They don't work

**Additional Information**
My plugins list is:
![grafik](https://user-images.githubusercontent.com/85316197/121604138-4c371100-ca4a-11eb-9676-d915cafae3b3.png)

The following is enabled (as it should be):
![grafik](https://user-images.githubusercontent.com/85316197/121604266-80aacd00-ca4a-11eb-9052-fa3c8dce2389.png)

I also noticed that "Time until spawn" inside the Spawner Information window gets stuck at 0.
As for the Cow example, they spawn on grass as usually, no matter what i try :(

I guess none of my plugins are causing this issue, but not too sure.
Edit: Alright i just removed ALL of my plugins while keeping WildStacker. Still doesn't work.
Edit2: Tried latest dev build too.

Is there anything else i could do wrong? Or is that actually a new "bug"?

**Comment by OmerBenGera** [comment]
If you run on Java version above 12, spawners override will not work.

**Comment by ProfLinebeck** [comment]
> 
> 
> If you run on Java version above 12, spawners override will not work.

Oh, good to know! I think this should be added somewhere in the wiki. I just invested a lot of time on this, cause i thought one of my plugins are causing this, or maybe i did something else wrong.
It works now using Java 8 :) 

Cheers!

**Comment by OmerBenGera** [comment]
> > If you run on Java version above 12, spawners override will not work.
> 
> Oh, good to know! I think this should be added somewhere in the wiki. I just invested a lot of time on this, cause i thought one of my plugins are causing this, or maybe i did something else wrong.
> It works now using Java 8 :)
> 
> Cheers!

I am pretty sure there is a debug message in console. I will look into that anyways, so for now I am keeping this opened

**Comment by OmerBenGera** [comment]
I added a debug message regarding this :)
