### ISSUE TITLE
Console spam + Still removing named animals

### ISSUE THREAD

**Issue by srrawr11** [BG-Software-LLC/WildStacker#192]
Version: 3.5.2
Using on: Paper 1.16.5
Edition: Java

Hi, I would like to report this error that spams to the console.. https://pastebin.com/8tns5E7H
And still named animals it removes when the kill systems passes..

**Comment by OmerBenGera** [comment]
Use latest dev build from https://bg-software.com/wildstacker/

**Comment by srrawr11** [comment]
Are these two problems solved in that dev build?

**Comment by OmerBenGera** [comment]
> Are these two problems solved in that dev build?

Yes, they should be
