### ISSUE TITLE
Cant translate upgrade menu

### ISSUE THREAD

**Issue by samcefalo** [BG-Software-LLC/WildStacker#193]
**Minecraft's Version**
1.16.5 paper

**Plugin's Version**: -
3.5.2 

**Describe the bug**
Cant translate 'Current Upgrade' and 'Next Upgrade' in upgrade menu

**To Reproduce**
Open the spawner upgrade menu

**Additional information**
https://prnt.sc/154bmim
https://prnt.sc/154br7e

**Comment by OmerBenGera** [comment]
This is a lack of a feature, not a bug.
