### ISSUE TITLE
[Mc 1.17] Spawners stack but wont get removed.

### ISSUE THREAD

**Issue by Blauwberman** [BG-Software-LLC/WildStacker#196]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)

1.17

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.

WildStacker-1.17-b2.jar

**Describe the bug**

The spawners stack together but the spawner that gets stacked with the other spawner is not removed.

**To Reproduce**
Steps to reproduce the bug.

1. place the spawner you want to stack.
2. place the other spawners you want to get stacked within the spawner.
3. 3 the spawner will not dissapear.
4. Repeat.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

Here is a medal clip of how the bug works.
https://medal.tv/clips/55175626/d1337QVA2jQo

**Comment by OmerBenGera** [comment]
Are there any errors?

**Comment by Blauwberman** [comment]
No, I havn't seen any errors in my console

**Comment by OmerBenGera** [comment]
Upload your config to pastebin please

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
No one has reported a similar issue, and because of lack of response I close this issue for now.
If it occurs again, please let me know here.
