### ISSUE TITLE
Blacklist allowing additions in gui but only receive 1 when removed

### ISSUE THREAD

**Issue by zulater** [BG-Software-LLC/WildStacker#200]
```
# Blacklisted spawners are spawners that won't get stacked.
# EntityType list: https://bg-software.com/entities/
# If you wish to disable blacklisted spawners, use "blacklist: []"
blacklist:
- BLAZE
```

https://youtu.be/NUAJv_hMjGY

When you set a spawner to blacklisted they will not stack (as expected) when you right click to place the spawner block. However, if you use the wildstacker menu, they will remove from your inventory and stack into the same spawner already placed. Then when you try to remove them all you only get one.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
Next time, please use the format.
