### ISSUE TITLE
MOB sometimes dosent despawn

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#201]
MINECRAFT VERSIONE: airplane f74d161 1.16.5

VERSION WILD: 3.5.2 devb137

BUG: Sometimes mob dosent despawn normally, to reproduce just go in gm3 or teleport to another location and go back to the spawner location after a few second

I know my version is not the lastest cause i have a lot of problem with lastest.. like mob spawner create new stack of mob without reach the limit

**Comment by OmerBenGera** [comment]
WildStacker doesn't change behavior of naturally mob spawning

**Comment by kedavlar** [comment]
oh ok.. thanks
