### ISSUE TITLE
Spawners don't stack on Purpur server

### ISSUE THREAD

**Issue by JblackMC** [BG-Software-LLC/WildStacker#203]
**Minecraft's Version**
Purpur version git-Purpur-1191 (MC: 1.17)

**Plugin's Version**: -
3.6.0-DEVb141

**Describe the bug**
Spawners do not stack. Holograms do not show when a stack of spawners are placed. Error is displayed in the console. There is also an error when breaking spawners.

**To Reproduce**
1) Create server with latest purpur jar
2) Install WildStacker
3) Give yourself some spawners
4) Place them, and you will get the error. There is also an error when breaking them.

**Additional information**
Console error: https://pastebin.com/U2eQX6f8

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
