### ISSUE TITLE
WildStacker Console Error

### ISSUE THREAD

**Issue by IPv5** [BG-Software-LLC/WildStacker#206]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
Hyperion Cannon Jar (1.8 TacoSpigot)

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
3.6.0 Dev 142
**Describe the bug**
Error in console
**To Reproduce**
Steps to reproduce the bug.
Not sure
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
https://pastebin.com/1XNEtnnr

**Comment by OmerBenGera** [comment]
Contact the author of: com.massivecraft.factions.proxy.ProxyBoard.getFactionAt(ProxyBoard.kt:11)
Its refarding the hook with FactionsUUID, however its not something to do with WS itself.
