### ISSUE TITLE
WildStacker MySQL error 

### ISSUE THREAD

**Issue by HitsLikeAnOMG** [BG-Software-LLC/WildStacker#207]
**Minecraft's Version**
1.8.8 (Spigot)

**Plugin's Version**: -
Latest 3.6.0 19/06/2021 13:06:21, Dev Builds: #147 26/06/2021 21:12:08,  #138 18/06/2021 21:58:41
**Describe the bug**
WildStacker is marked red when you type /pl and the error code is: 
![image](https://user-images.githubusercontent.com/86609259/123647244-34240780-d828-11eb-894a-1e2e07c65f66.png)

**To Reproduce**
`?

**Additional information**
A problem, which already was found at the beginning of this year lol

**Comment by HitsLikeAnOMG** [comment]
I fixed the bug, your code had to get recoded a bit

**Comment by OmerBenGera** [comment]
The plugin works just fine afaik, however you are more than welcome to make a PR.
I am closing this for now
