### ISSUE TITLE
Strange Server Crash

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildStacker#208]
**Minecraft's Version**
[01.07 22:48:54] [Server] [INFO] --------------------------------
[01.07 22:48:54] [Server] [INFO] This server is running SpaceDeltaSpigot.
[01.07 22:48:54] [Server] [INFO] • Created by StellarDev
[01.07 22:48:54] [Server] [INFO] --------------------------------

**Plugin's Version**: -
WildStacker-b138.jar

**Describe the bug**
Server Crasher, potentially with citizens hook

**To Reproduce**
[crash-2021-06-01_16.48.26-server.txt](https://github.com/BG-Software-LLC/WildStacker/files/6751333/crash-2021-06-01_16.48.26-server.txt)

**Additional information**
Provided Crash Report, also I haven't tried it with the latest dev build. If you want to I can do that.

**Comment by OmerBenGera** [comment]
Upload to pastebin please

**Comment by DJDan21** [comment]
Here it is as a pastebin as you requested https://pastebin.com/9Sd1t7Ki

**Comment by OmerBenGera** [comment]
Do you have Citizens installed?
Also, please try latest dev build, I changed some things with the Citizens hook and it might have been fixed as well

**Comment by DJDan21** [comment]
I'm using 1.8 btw, I didn't mention that :)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Well, if it occurs again, let me know
For now, I am closing this.
