### ISSUE TITLE
Mobs "disappear" on death.

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/WildStacker#209]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
----------------------------------------------------------------------------------------------
Minecraft Version 1.17
Purpur

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
-------------------------------------------------------------------------------------------
b147

**Describe the bug**
--------------------------------------------------------
When killing a mob it completely skips the death animation. They quite literally just pop out of existence like I thanos snapped them. Generally when you kill a mob they turn red and fall over sideways. But not with this issue ongoing, when you kill them, they disappear out of existence but still drop the items. However this affects other things such as the quests for SuperiorSkyblock2 for some reason not counting the mobs.

**To Reproduce**
Steps to reproduce the bug.
-------------------------------
Use the same build, setup a place for mobs to spawn, kill mobs and feel the tremendous power you have with just a snap.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
---------------------------------------------------------------------
I have a couple videos I took when trying to figure out the issue with the quest (before connecting the dots that it was an issue with this plugin), one of them shows me genuinely trying to test it for quest purposes, the other shows me testing it on our dev server then moving on to other servers that haven't been updated yet showing the difference between the deaths. Bear with me they're a little long >~< Feel free to set it at x2 speed, there's no talking or anything.
https://youtu.be/1TrdCkqKczw
https://youtu.be/AvYu9KVSK6o

I also have a screenshot of an error that showed up in console regarding the plugin:
https://i.imgur.com/dBVICcP.png

**Comment by OmerBenGera** [comment]
Please upload your config to pastebin and send it here.

**Comment by Skizzles** [comment]
@OmerBenGera https://pastebin.com/gyzqy67c

This is the config used on there.

**Comment by OmerBenGera** [comment]
```
  # Should corpses be spawned when entity dies ("death animations")?
  spawn-corpses: false
```
Set this to true so corpses will be spawned.

**Comment by Skizzles** [comment]
@OmerBenGera turned on corpses again in the config (idk why that was disabled) but the issue still occurs, tested on 1.17.1 and dev 157

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
