### ISSUE TITLE
Piglin doesn't trade with dropped item

### ISSUE THREAD

**Issue by FauzanAlfansa** [BG-Software-LLC/WildStacker#210]
**Minecraft's Version**
Paper-778 (MC 1.16.5)

**Plugin's Version**
3.6.0-DEVb147

**Describe the bug**
Piglin just picks up the dropped the item without trading anything. Trading with right clicking the piglin works normally.
I also tried disabling WildStacker and both methods works normally.

**To Reproduce**
- Spawn a Piglin
- Drop an Item (i.e. Gold Ingot)

**Additional information**
Video showing the issue: https://www.youtube.com/watch?v=sdUFvuC1yHE

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
