### ISSUE TITLE
spam console

### ISSUE THREAD

**Issue by JessyDrew** [BG-Software-LLC/WildStacker#214]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
The lastet

**Describe the bug**
Spam on console when entity are stacked

**To Reproduce**
Maybe stack mob? :c

**Additional information**
**https://pastebin.com/EQDvjiKf**

**Comment by OmerBenGera** [comment]
Contact EpicSpawners regarding this, it has nothing to so with the plugin.
