### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by Pwouka** [BG-Software-LLC/WildStacker#215]
Hello! 
Version server : Spigot 1.12.2

Wildstacker 3.6.0

Bug :
The bug is simple, when I add the Wildstacker plugin and restart the server, the server can no longer be started, whereas if I remove the WildStacker plugin the server works correctly.

I put the crash report of the server here.
[crash-2021-07-04_18.30.16-server.txt](https://github.com/BG-Software-LLC/WildStacker/files/6760328/crash-2021-07-04_18.30.16-server.txt)

Thank you in advance.

**Comment by Pwouka** [comment]
Hi, I checked everything and I see that the problem comes from the Citizens plugin, I can't remove it, how am I supposed to fix the problem? Can you fix the bug?

**Comment by OmerBenGera** [comment]
Upload the errors you have to pastebin.

**Comment by Pwouka** [comment]
https://pastebin.com/4t0ZMzxL

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
