### ISSUE TITLE
Stacked mobs stay laid down

### ISSUE THREAD

**Issue by Focxer** [BG-Software-LLC/WildStacker#217]
**Minecraft's Version**
Paper version git-Paper-75 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: cc063e1)

**Plugin's Version**: -
WildStacker-b156.jar

**Describe the bug**
When i kill a stacked entity, they stay laid on the floo
![unknown](https://user-images.githubusercontent.com/78274854/124665084-ac22ab00-de82-11eb-95e2-99c3df21e261.png)
r, no matter how much are in the stack, they dont disappear when killed

**To Reproduce**
Just Kill some stacked mob

**Additional information**
i use LevelledMobs on my server and, when i use only WildStacker or only LevelledMobs this dont happens but, when i use them together it brokes, the LM dev asked you to check SpawnReason and he told me:
```that makes it even more hacky
It's something like Lokka said that WildStacker needs to resolve.
Recommend PDC to them lol
What I thiink they need to do is instead of letting it create a new entity it needs to cancel the death event and replace the entities values with expected new value.
But that's just my two cents```

**Comment by OmerBenGera** [comment]
Seems like a visual bug only, you are more than welcome to disable corpses in your config.
