### ISSUE TITLE
Mob and Item Stacking spamming errors

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#218]
**Minecraft's Version**
1.17.1 Purpur

**Plugin's Version**: -
Dev b156

**Describe the bug**
Mob stacking and other features cause massive error spam and do not function.

**To Reproduce**
N/A
Happens regardless of anything

**Additional information**
https://pastebin.com/7CfbP7KB

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
