### ISSUE TITLE
Mob drops being doubled

### ISSUE THREAD

**Issue by 27chandler** [BG-Software-LLC/WildStacker#220]
**Minecraft's Version**
PaperMC
git-paper-68 (MC: 1.17)

**Plugin's Version**: -
Wildstacker Dev Build b158

**Describe the bug**
When a mob is killed, if it is not on the stacking blacklist, it will drop double of whatever items it was supposed to drop

**To Reproduce**
1) Find a mob which is not blacklisted for stacking
2) Grab sword
3) Whack
4) Observe 2X the normal amounts of drops (An easy way to tell is that everything dropped will be an even number no matter what)

**Additional information**
I have tested on Cows, Pigs, Chickens, Squids, Zombies, Skeletons, Blazes and Spiders. If its not added to the stacking blacklist then all items it drops are doubled. Spawn reason seems to not matter as well (Tested with spawn egg spawned, natural spawned and spawner spawned). The doubling also carries over to held items (such as zombies with armour or held items).

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
