### ISSUE TITLE
Dupe Bug (Conflicting with Drop2InventoryPlus)

### ISSUE THREAD

**Issue by KarlPro123** [BG-Software-LLC/WildStacker#222]
### Minecraft's Version

 This server is running Paper version git-Paper-95 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0aa0a1d)

### Plugin's Version

WildStacker, dev build #161
Drop2InventoryPlus 2.3.0

### Describe the bug

It is a dupe bug probably caused by a conflict between WildStacker and the plugin Drop2InventoryPlus.

### To Reproduce

Have at least 2 blocks of a kind. 
Drop one down to the ground and place one. 
Then break the one placed, but make sure that there is one dropped to the ground. 
One block comes to the inventory without dropping on the ground (Drop2InventoryPlus feature) and one stacks up to the other dirt, making it essentially a dupe bug. 
As I know, it works with any item.

### Additional Information

At the testing time, latest versions of both plugins were used and also the latest Paper version.

**Comment by KarlPro123** [comment]
**-- Not related to the issue here --**

Mob Spawners don't really want to spawn any mobs anymore. 
Is there a particular reason to that, can it be caused by WildStacker?
Normal mobs seem to spawn fine however.

![](https://user-images.githubusercontent.com/45460602/125124367-a0441c80-e100-11eb-94d7-953545df3ed8.png)

For example: A Blaze farm like this spawns only 1 Blaze per minute(approx)

**Comment by OmerBenGera** [comment]
Please take a video of that shows how the dupe works.
About the comment you had, I deleted it as it's not related to the issue. You are more than welcome to ask about it on the discord server. From what I've seen, it seems like it's due to spawn restrictions probably

**Comment by KarlPro123** [comment]
Here's the video.

https://www.youtube.com/watch?v=IoDSX7GYmQI

First I showed normal behaviour and then the problem. If you wonder - no, plugman isn't the issue here, I tested with a server restart and the bug was still there.

**Comment by OmerBenGera** [comment]
I opened a ticket for you on the discord server - please send me a copy of the plugin there

**Comment by KarlPro123** [comment]
This should be fixed when the next update comes out for Drop2InventoryPlus.
