### ISSUE TITLE
Spawners Stack

### ISSUE THREAD

**Issue by GodKiko123** [BG-Software-LLC/WildStacker#223]
### Minecraft's Version

Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT

### Plugin's Version

Latest stable version
3.6.0 19/06/2021 13:06:21

### Describe the bug

I setup this:

  # Set a maximum stack for specific spawners.
  # Make sure you follow the "ENTITY-TYPE" format.
  # You can use 'all' as a global limit (all: 20 will set all spawners to be limited to 20 per stack)
  # If you don't want any limits, you can set a random type.
  limits:
  - all: 25
  
  BUT I'm stacking more than 25.

### To Reproduce

I'm stacking more than 25 spawners.

**Comment by OmerBenGera** [comment]
I tried to replicate the issue and it works just fine.
Try changing it from "all" to "ALL", maybe that's the issue

**Comment by GodKiko123** [comment]
Noup, still not working.

**Comment by OmerBenGera** [comment]
Upload your config to pastebin please and send it here.

**Comment by GodKiko123** [comment]
https://pastebin.com/mdwp3pqZ

**Comment by OmerBenGera** [comment]
You wrote the limits wrong.
Remove the `-` at the start of the line of the limits, as the limits section is not a list.
You can always make sure that the changes that you made were applied by using /ws settings.
