### ISSUE TITLE
Ender dragon can't be killed. It instantly respawns after its health reaches 0.

### ISSUE THREAD

**Issue by GerwinVerkerk** [BG-Software-LLC/WildStacker#224]
### Minecraft's Version

[16:18:09 INFO]: This server is running Paper version git-Paper-97 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d985976)
You are running the latest version

### Plugin's Version

Wildstacker 3.6.0, latest stable release

### Describe the bug

When you kill the ender dragon, it instantly respawns with full health. It does not die.

### To Reproduce

Go to the end and kill the ender dragon with the wildstacker plugin installed

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
