### ISSUE TITLE
PinataEvent Integration

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#225]
### Minecraft's Version

1.12.2

### Plugin's Version

b163

### Describe the bug

Hello 

https://hastebin.com/apitufiwuz.properties

### To Reproduce

Spanw pinata with Wildstacker on the same server

### Additional Information

https://hastebin.com/apitufiwuz.properties

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
