### ISSUE TITLE
Potential problem with spawning the right amount of mobs

### ISSUE THREAD

**Issue by KarlPro123** [BG-Software-LLC/WildStacker#226]
### Minecraft's Version

Paper version git-Paper-95 (MC: 1.17.1)

### Plugin's Version

WildStacker #161

### Describe the bug

<img width="555" alt="Screenshot_7" src="https://user-images.githubusercontent.com/45460602/125206162-5ab55a00-e28e-11eb-88b2-6d9874e08698.png">
(Minecraft Fandom Wiki)

It states that a spawner attempts to spawn four mobs around it, then waits from 10 to 39.95 seconds before spawning more.

However, in my server, it doesn't seem to be that way, and what's making it worse, is that these spawners are even stacked, so they should spawn even more. Only 2-3 mobs are spawned each minute. It seems though that they spawn a bit quicker when all mobs near are killed. I also have a short video of that, but I'd prefer to share it privately.

### To Reproduce

-

### Additional Information

I heard someone said maybe spawner upgrades could cause that issue, so I configured my default like this:

        default:
          next-upgrade: coal
          nearby-players: 20
          spawn-count: 4
          spawn-range: 4
          min-spawn-delay: 200
          max-spawn-delay: 800
          max-nearby-entities: 6
          icon:
            type: STONE
            name: '&fBasic'
            lore:
            - '&fThis upgrade is free of charge'
            - '&7 '
            - '&7Spawn Delay Range&f: %min-spawn-delay%-%max-spawn-delay%'
            - '&7Spawn Count&f: %spawn-count%'
            - '&7Max Nearby Entities&f: %max-nearby-entities%'
            - '&7Required Player Range&f: %required-player-range%'
            - '&7Spawn Range&f: %spawn-range%'

Unfortunately, there wasn't any change.

**Comment by OmerBenGera** [comment]
There are 2-3 entities spawned, but each has a stacked size, right?
Because if so, that's intended.

**Comment by KarlPro123** [comment]
I have mob stacking disabled on my server. I expect it to work like vanilla. Also, these mobs don't seem to have any name hovering over (maybe indicating a stack size or something) and also don't give any extra loot like stacked mobs should.

**Comment by KarlPro123** [comment]
#228 seems to be related

**Comment by OmerBenGera** [comment]
> I have mob stacking disabled on my server. I expect it to work like vanilla. Also, these mobs don't seem to have any name hovering over (maybe indicating a stack size or something) and also don't give any extra loot like stacked mobs should.

I understand now, so it doesn't seem to work when stacking entities is disabled. I will take into that.

> #228 seems to be related
Because you have Java 16, the spawners override feature is not supported, however this has nothing to do with the issue. I will check why WildStacker doesn't spawn more entities.

By the way, I don't recommend having stacked spawners enabled while having stacked entities disabled, it will cause a lot of entities to spawn in your world and it will probably cause lag because of all the updates, etc.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
