### ISSUE TITLE
Spawners-override not supported on your java version

### ISSUE THREAD

**Issue by techmonkey1039** [BG-Software-LLC/WildStacker#228]
### Minecraft's Version

1.16.5

### Plugin's Version

All versions from 3.5.0 to b163

### Describe the bug

Prior to 1.17 being released WildStacker worked perfectly! However, since updating to java 16 the error "The 'spawners-override' feature is not supported in your Java version, disabling..." Has occurred and does not allow our spawners to bypass the spawn conditions needed for the mobs to spawn.

### To Reproduce

See above

### Additional Information

![image](https://user-images.githubusercontent.com/5055414/125394243-003ffa80-e36f-11eb-8afa-37ef4a1cc082.png)

**Comment by Focxer** [comment]
And also, should be the same issue that makes mobs quantity from spawners are not increasing

```Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9)

git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a831634)

WildStacker-b163```

**Comment by OmerBenGera** [comment]
This feature it not supported in Java 12 or above, and sadly this cannot be fixed as Java removed features that the plugin uses in these versions.

**Comment by JasonHorkles** [comment]
So does that mean spawner stacking is pointless on 1.17?

**Comment by OmerBenGera** [comment]
> So does that mean spawner stacking is pointless on 1.17?

No, you just can't have WildStacker take over spawners, which technically means that only the spawn conditions override is not working. The rest of the benefits of overriding spawners still work on Paper, even in Java 16.

**Comment by JasonHorkles** [comment]
Interesting, cuz even spawners stacked to 150 act as if only 1 was placed on my server. Should I open a new issue for that?

**Comment by JasonHorkles** [comment]
I suppose the issue I'm having is the same as #226

**Comment by OmerBenGera** [comment]
> I suppose the issue I'm having is the same as #226

Open a new issue please :)
