### ISSUE TITLE
Stacked Mobs not showing Nametags or Stacking properly

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#229]
### Minecraft's Version

1.17.1 Purpur dev 1265

### Plugin's Version

Dev 163

### Describe the bug

No nametags on stacked mobs, also values not correctly updated.

### To Reproduce

Attempt to spawn mobs from spawners with proper stacking settings and nametag values, see no stacked mob tag or correct stacked values.

### Additional Information

Proof:
https://screenshots.skizzles.me/wAnA3/fuzOvOLu42.mp4

Config Section:
https://pastebin.com/a4SqQVhx

**Comment by Lambsy** [comment]
I can confirm I also have this issue after updating our servers to 1.17.1 from 1.16.5. I user latest WildStacker 166 build.

**Comment by brasilcraft54** [comment]
![2021-08-01_22 02 08](https://user-images.githubusercontent.com/67756407/127791606-0fd92fa0-d3ec-49e3-a8c7-d2c5bc8347d5.png)


I have the same problem version  171  build.

**Comment by OmerBenGera** [comment]
Try latest dev build, I think it's fixed.

**Comment by Skizzles** [comment]
Still not seeing nametags on b178

**Comment by OmerBenGera** [comment]
@Skizzles resend your config please

**Comment by Skizzles** [comment]
@OmerBenGera https://pastebin.com/0wGHAs3y

**Comment by OmerBenGera** [comment]
@Skizzles update the following section to this:
```
  # Blacklisted names is a list of names that when an entity has this name, it won't get stacked.
  # Color codes are supported, as well as regex.
  # If you wish to enable stacking of all entities based on their name, use "name-blacklist: []"
  name-blacklist: []
```
This should fix the issue.

**Comment by Skizzles** [comment]
odd was never aware of that option before, this should be resolved with that change.
