### ISSUE TITLE
Many Particle

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#230]
### Minecraft's Version

1.12.2

### Plugin's Version

b63

### Describe the bug

When i place zombie spawner and wait in /day i have many particle arround the spawner : https://pics.revolis.fr/2021-07/14/22-06_u9GB.mp4

### To Reproduce

- Place spawner
- Execute /day
- Wait the spawn

### Additional Information

https://pics.revolis.fr/2021-07/14/22-06_u9GB.mp4

**Comment by OmerBenGera** [comment]
Spawning particles in latest dev build only occurs when the mob was spawned successfully.
Try updating, might be an old bug that was fixed already.
If it still occurs, make sure you reopen the issue, and also test it without WildStacker to confirm that the bug happens only when WS is installed.
