### ISSUE TITLE
Items do not stack properly

### ISSUE THREAD

**Issue by Peeraboon** [BG-Software-LLC/WildStacker#231]
### Minecraft's Version

This server is running Paper version git-Paper-782 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Airplane-9 (MC: 1.16.5)

### Plugin's Version

WildStacker version 3.6.0-DEVb163

### Describe the bug

Item does not stack properly.

### To Reproduce

I use JetMinion plugin (Farmer Minion) and make it to harvest carrot of 25x25 block area.
Video: https://www.youtube.com/watch?v=CLXctNDOUZU

### Additional Information
Wildstacker config: https://pastebin.com/KTcWHuwQ
https://www.youtube.com/watch?v=CLXctNDOUZU

**Comment by Chrustee96** [comment]
Does this mean a stack of 64 will only stack like 40 and 24 items disappear?

**Comment by Peeraboon** [comment]
example I have 20000 carrots. it should be only few Items and the hologram shows x20000 Carrots

**Comment by OmerBenGera** [comment]
It looks fine for me. You can enable items merger task if you want these items to get stacked.
Just be aware that it might lag your server - play with the interval value until you find the best value for your server, I recommend starting at 200.
