### ISSUE TITLE
Villager not turning into Zombie Villager when killed by Zombie

### ISSUE THREAD

**Issue by FauzanAlfansa** [BG-Software-LLC/WildStacker#232]
### Minecraft's Version

Paper-103 (1.17.1)

### Plugin's Version

WildStacker version 3.6.0-DEVb166

### Describe the bug

Villager doesn't turn into Zombie Villager when killed by Zombie. 
I tested it on hard difficulty where the infection chance is 100%.
![2021-07-18_00 22 45](https://user-images.githubusercontent.com/56780574/126044968-71eac96b-9383-4c61-aeaa-a54903725d12.png)

### To Reproduce

- Spawn a Zombie
- Spawn a Villager

### Additional Information

Videos showing the issue
- WildStacker not installed https://youtu.be/QQpmFt7xWso
- WildStacker installed https://youtu.be/Oi4HlIPdDLs

**Comment by DarrienNN** [comment]
What do you mean "Villager will die when zombie attack" ..

**Comment by OmerBenGera** [comment]
> 
> 
> What do you mean "Villager will die when zombie attack" ..

That's only me closing another issue that reported the exact same issue.
I haven't checked it yet - I will look tho soon

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
