### ISSUE TITLE
Stacked spawners not spawning extra mobs

### ISSUE THREAD

**Issue by JasonHorkles** [BG-Software-LLC/WildStacker#233]
### Minecraft's Version

Tuinity version git-Tuinity-21 (MC: 1.17.1)

### Plugin's Version

WildStacker version 3.6.0-DEVb161

### Describe the bug

When stacking spawners, the amount of spawned mobs appears to be as if there was only one spawner there. For example, I stacked 150+ spawners and yet only 3-4 mobs actually spawned.

### To Reproduce

Stack spawners

### Additional Information

Config: https://paste.gg/p/JasonHorkles/d6be28abf947447ebd618778592f0771

**Comment by OmerBenGera** [comment]
Note to myself: only happens when entities are disabled.

**Comment by Billabomb75** [comment]
Try disabling the Listen to Paper option in the Spawners Settings...

**Comment by JasonHorkles** [comment]
Yep that fixes it!

**Comment by OmerBenGera** [comment]
Another note: seems to get fixed when disabling Paper listening

**Comment by OmerBenGera** [comment]
Duplicate of #226
