### ISSUE TITLE
BUG mob with boat

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#234]
### Minecraft's Version

1.16.5 tuinity 9f3435b, is the lastest

### Plugin's Version

DEVb 163

### Describe the bug

Mobs when spawned by spawners who board boats do not despawn

### To Reproduce

Just move the move near the boat, go away and come back

### Additional Information

would there be a way to get these mobs despawn? maybe making them split so that only 1 goes on the boat??

**Comment by OmerBenGera** [comment]
Can you give more details about the issue, as I don't understand what you mean
I am pretty sure entities on boats don't despawn and that's vanilla mechanism.

**Comment by kedavlar** [comment]
I know it's a vanilla mechanic, but I wanted to know if it was possible to get around it by making sure that when the mobs get on the boat it splits so that only 1 remains on the boat .. it's the same mechanism as the name tags

**Comment by OmerBenGera** [comment]
> 
> 
> I know it's a vanilla mechanic, but I wanted to know if it was possible to get around it by making sure that when the mobs get on the boat it splits so that only 1 remains on the boat .. it's the same mechanism as the name tags


I understand now.
Even tho it's more of a feature request than a bug, I'll keep it here and add it when I have the time.

**Comment by kedavlar** [comment]
thanks a lot! sorry if my english is bad

**Comment by OmerBenGera** [comment]
Added in latest dev build
