### ISSUE TITLE
No clue what this is

### ISSUE THREAD

**Issue by JhulyToo** [BG-Software-LLC/WildStacker#238]
### Minecraft's Version

1.17.1 and 1.17.1

### Plugin's Version

Latest from this post

### Describe the bug

23.07 04:57:03 [Server] ERROR Could not pass event ItemSpawnEvent to WildStacker v3.6.0-DEVb141
23.07 04:57:03 [Server] INFO java.lang.NoSuchFieldError: bY
23.07 04:57:03 [Server] INFO at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.getEggLayTime(NMSAdapter_v1_17_R1.java:279) ~[?:?]
23.07 04:57:03 [Server] INFO at com.bgsoftware.wildstacker.listeners.events.EventsListener$EggLay.lambda$onEggLay$0(EventsListener.java:79) ~[?:?]
23.07 04:57:03 [Server] INFO at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.lambda$getNearbyEntities$0(NMSAdapter_v1_17_R1.java:317) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.EntitySection.getEntities(EntitySection.java:50) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.EntitySectionStorage.lambda$getEntities$2(EntitySectionStorage.java:128) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.EntitySectionStorage.forEachAccessibleSection(EntitySectionStorage.java:56) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.EntitySectionStorage.getEntities(EntitySectionStorage.java:126) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.LevelEntityGetterAdapter.get(LevelEntityGetterAdapter.java:46) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.LevelEntityGetterAdapter.get(LevelEntityGetterAdapter.java:42) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.getNearbyEntities(NMSAdapter_v1_17_R1.java:316) ~[?:?]
23.07 04:57:03 [Server] INFO at com.bgsoftware.wildstacker.utils.entity.EntitiesGetter.getNearbyEntities(EntitiesGetter.java:38) ~[?:?]
23.07 04:57:03 [Server] INFO at com.bgsoftware.wildstacker.listeners.events.EventsListener$EggLay.onEggLay(EventsListener.java:78) ~[?:?]
23.07 04:57:03 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:752) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:631) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1177) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1084) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2231) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2199) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2194) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.world.entity.animal.Chicken.aiStep(Chicken.java:103) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2880) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:393) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:903) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:869) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:600) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:581) ~[?:?]
23.07 04:57:03 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-124]
23.07 04:57:03 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

Fix this and tell me whats happening here

**Comment by OmerBenGera** [comment]
Update Wildstacker to latest dev build, it was already fixed :)
