### ISSUE TITLE
Offhand dupe

### ISSUE THREAD

**Issue by Rubenicos** [BG-Software-LLC/WildStacker#239]
### Minecraft's Version

Paper 1.12.2

### Plugin's Version

3.6.0-DEVb166

### Describe the bug

When a player tries to collect a stacked item, with amount greater than 63 (64 or more) and only with space in offhand, the offhand is filled and stacked item amount is not reduced.

### To Reproduce

1. Put in your offhand 1 or more of item you want to duplicate.
2. Fill your inventory with any item.
3. Drop more than 63 of item you want to duplicate.
4. Try to pick up the items.

### Additional Information

https://user-images.githubusercontent.com/44579213/126837135-d8c69014-2d68-4348-a163-ae10dfac3268.mp4

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
