### ISSUE TITLE
Sheep EXP Loot Table Error

### ISSUE THREAD

**Issue by MythricHD** [BG-Software-LLC/WildStacker#240]
### Minecraft's Version

1.12.2

### Plugin's Version

3.6.0-b166

### Describe the bug

Im trying to add the exp option to the sheep loottable but for some reason I get an error. I used it on other mobs like pig and chicken without issues. It applies to both sheep and baby sheep. 

Error: https://paste.helpch.at/nuquwovisu.md

Loottable: https://paste.helpch.at/omoboleyut.json

It works fine if I omit the exp option like so: https://paste.helpch.at/eyaxalezay.json

### To Reproduce

Download the loottable from above and place it in the sheep loottable. I didn't think this was related to the config since other mobs work but If needed i can attach my config

### Additional Information

Not sure if it applies to any other mobs but if it does ill leave a comment below

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
