### ISSUE TITLE
Cauldrons fill with snow/water when weather occurs, which clears the stacked items in there

### ISSUE THREAD

**Issue by spencer-wild** [BG-Software-LLC/WildStacker#241]
### Minecraft's Version

This server is running Purpur version git-Purpur-1288 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 246383a on ver/1.17.1)

[1.17.1]

### Plugin's Version

3.6.0-DEV166

### Describe the bug

Cauldrons which contain stacks of blocks fill with water or snow, and you lose the items in them. Exceptions are generated in the console.

### To Reproduce

1. Start the server.
2. Put down blocks that stack into cauldrons (Iron, gold, diamond etc).
3. Turn on weather.
4. Wait for the cauldrons to fill up. You will no longer be able to remove the blocks. Logging off will result in the block disappearing from the cauldron. (See below) 
**Before the logout:**
![image](https://user-images.githubusercontent.com/65164776/126853913-d3256648-dc05-44d5-a1fe-a49a48fcc5a9.png)
![image](https://user-images.githubusercontent.com/65164776/126853916-66200c86-1293-4057-9a4e-baa3f9bea124.png)
![image](https://user-images.githubusercontent.com/65164776/126853919-d51a82c1-135c-4a85-9b4b-ef5ae6379f57.png)

**After the logout:**
![image](https://user-images.githubusercontent.com/65164776/126853836-dc466974-5d2d-481c-b941-7e1b26b2f6e8.png)
![image](https://user-images.githubusercontent.com/65164776/126853867-3c517fe8-2a38-46e6-ae32-3aff5c03d5c0.png)
![image](https://user-images.githubusercontent.com/65164776/126853869-60b549b1-a704-4a5a-b513-36cc08dc372c.png)

This was taken after the rain stopped, and time passed 
![image](https://user-images.githubusercontent.com/65164776/126853972-9183e10f-7201-4843-bc6b-b3938b835c9b.png)

### Additional Information

Applicable errors:
https://pastebin.com/0Cs5Shyq

Plugins:
AFKPatrol, AnimatedScoreboard, AnnouncerPlus, BanManager, BentoBox, BetterCommandSpy, BuycraftX, ChatInjector, ChestShop, Citizens, CommandPanels, ConsoleSpamFix, CoreProtect, CustomOreGen, DeathMessages, DeluxeTags, DiscordSRV, EconomyShopGUI, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, HolographicDisplays, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PL-Hide, PlaceholderAPI, ProtocolLib, ServerRestart, Spartan, StaffPlus, TAB, TheNewEconomy, TradeSystem, Vault, Watson, WildStacker, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

**Comment by OmerBenGera** [comment]
Is there something that can block cauldrons from filling up with water?
I was AFKing for 30 minutes with storm and yet to get my cauldrons fill with rain (without WS installed, 1.17)

**Comment by LoneDevilX** [comment]
Sometimes it happens after rain and sometimes it just happen after restart server.
Probably is very uncertain, this is the picture tested here.
![2021-09-11_01 14 50](https://user-images.githubusercontent.com/67851836/132892228-104a1a1f-7121-4766-b950-3d8e3dfde1e4.png)

**Comment by LoneDevilX** [comment]
![2021-09-11_01 14 50](https://user-images.githubusercontent.com/67851836/132892318-a7c80c02-8fb0-4f6c-b959-510dea8af52e.png)

**Comment by OmerBenGera** [comment]
> 
> 
> Sometimes it happens after rain and sometimes it just happen after restart server.
> Probably is very uncertain, this is the picture tested here.
> https://cdn.discordapp.com/attachments/884848581884903455/885936867009261568/2021-09-11_01.14.50.png

Read my comments above.

**Comment by LoneDevilX** [comment]
Yep I read and tested, any block can block cauldrons from filling up with water. 
So this is very uncertain, and right now its the only solution... (with WS installed 1.17)

Please do understand I'm here just to tell others/ provide a temporary solution that they can use block to avoid it filling water.

**Comment by Tina-King** [comment]
I am also having this same issue, it started as soon as I upgraded to 1.17 with latest WS.

Not tested on vanilla, but most certainly is an issue on my Skyblock server. Possibly some conflict between WS and BSkyBlock?

Plugins (80): AdvancedBan, AdvancedOreGen, ArmorStandEditor, AuctionHouse, AutoCraft, BanAnnouncer, BentoBox, BetterJails, BetterSlimeChunks, BuildersWand, ChatControlRed, CompatNoCheatPlus, CoreProtect, CraftBook, CraftingStore, CrazyCrates, DailyShop, DeluxeMenus, DiscordSRV, EZLinks, EditableSign, EnjinMinecraftPlugin, EpicSpawners, Essentials, EssentialsChat, EssentialsSpawn, Executor, FeatherBoard, HeadDatabase, HolographicDisplays, HolographicScoreboard, IPWhitelist, InteractiveBooks, InventoryRollbackPlus, ItemFrameShops, LWC, LagAssist, LevelPoints, Lottery, LuckPerms, LuckPermsMVdWHook, MVdWPlaceholderAPI, NashornPlus, NoCheatPlus, OnTime, OpenInv, PlaceholderAPI, PlayerVaults, PlayerVaultsGUI, PlugMan, PremiumVanish, ProtocolLib, QuickShop, Rewards, ServerUtils, ShopGUIPlus, SimplePets, SkinsRestorer, Spicord, SuperLuckyBlock, TAB, TempFly, TigerReports, TradePlus, UltimateKits, UltimateTimber, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, Votifier, VotingPlugin, WildStacker, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags, eZProtector and mcMMO

**Comment by Skizzles** [comment]
@Tina-King @spencer-wild Is this issue still happening? if so, can we confirm this issue is only present with WildStacker installed by itself please?

**Comment by OmerBenGera** [comment]
> Hey, I have the same issue.
> 
> pufferfish 1.18.1 Latest ws build
> 
> Thank you very much

As I mentioned multiple times, WS blocks cauldrons from filling.
If you get the issue, let me know how to replicate it on a server with only WS installed on regular Spigot/Paper.

**Comment by OmerBenGera** [comment]
For no reason, it seems like the CauldronLevelChangeEvent is not fired.
I fixed cauldrons disappearing if they are filled with water, so at least they are not removed.
I will look into why the event is not fired and hopefully fix it as well 

Closing this for now
