### ISSUE TITLE
BUG with recent add of boat unstuck

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#242]
### Minecraft's Version

1.16.5 tuinity

### Plugin's Version

dev 170

### Describe the bug

Little bug when use the new boat unstuck option.. 

https://user-images.githubusercontent.com/85011614/126873738-ea4018e5-a999-48d8-81aa-a80c630cabe1.mp4

### To Reproduce

just move mob near boat

**Comment by OmerBenGera** [comment]
Why is the entity leaving the boat?

**Comment by OmerBenGera** [comment]
Also, you can disable the entity splitting when they join the boat in the config.

**Comment by kedavlar** [comment]
i dont know why they leaving the boat.. i think the try to merge with the stack and i need this option on if there a solution

**Comment by OmerBenGera** [comment]
> i dont know why they leaving the boat.. i think the try to merge with the stack and i need this option on if there a solution

I will look into that

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
