### ISSUE TITLE
Impossible to place Stacked Stew in shulker

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/WildStacker#243]
### Minecraft's Version

Airplane-purpur 1.16.5

### Plugin's Version

Dev-170

### Describe the bug

Using 

stews:
  enabled: true
  max-stack: 64

It can be stacked in chests, but not in shulkerbox

### To Reproduce

Try to put stacked stew in shulker

**Comment by OmerBenGera** [comment]
Thats not a bug, shulker boxes dont support items with larger size than their vanilla max size.
