### ISSUE TITLE
Baby Variant XP Gain Issue

### ISSUE THREAD

**Issue by SilverSeed93** [BG-Software-LLC/WildStacker#245]
### Minecraft's Version

Paper version git-Paper-123 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3801a39)

### Plugin's Version

b170

### Describe the bug

After killing the first Baby Zombies and Baby Drowned in the stack, experience starts to compound almost exponentially. I haven't tested further baby variants. 

### To Reproduce

Stack Baby Zombies or Drowned and start killing them. 

### Additional Information

We have worked around this issue for the moment by deleting Baby Zombies with a command block sitting in the spawn chunk as it can easily disrupt or end the server economy. 

Here is a link to a video of the issue:
https://mega.nz/file/O88GwQqZ#yk2XRqh9G5Tm0ThOJLMzuGTfQvIthViGF7Y0vtB4j7s

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
