### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Askarionn** [BG-Software-LLC/WildStacker#246]
### Minecraft's Version

1.16.5 Yatopia

### Plugin's Version

3.6.0 1.6.6 devbuild 

### Describe the bug

i'm using it on a SMP server
it's 1 instance (1 1.16.5 server) and every player has his own world with worldborder
there's 500+ worlds but the every world it's loaded only if there's 1 player online in that specific world.
i think that might be the problem with the memoryleak

https://www.mediafire.com/file/h7aokvw51ru8q1j/heapdump.20210727.174616.37.0011.phd/file
[crash-2021-07-27_20.17.21-server.txt](https://github.com/BG-Software-LLC/WildStacker/files/6892190/crash-2021-07-27_20.17.21-server.txt)
![23](https://user-images.githubusercontent.com/51824859/127305794-17155906-89d3-4033-95c2-1330d3994b6c.png)
![unknown](https://user-images.githubusercontent.com/51824859/127305808-25f77f8a-72f8-47aa-8316-9ef4aa58910f.png)

### To Reproduce

Not sure how to reproduce it. I'm using PlayerWorldsPro for worlds per player

**Comment by OmerBenGera** [comment]
Note to myself: entities probably dont get removed when a world is unloaded

**Comment by kedavlar** [comment]
I confirm that many times the mobs do not disappear and having 2 different worlds, I too have these lag problems

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
