### ISSUE TITLE
WildStacker Bugs Cocoa_beans.

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#248]
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

WildStacker-b170.jar

### Describe the bug

when pushed by a piston the cocoa does not come correctly it comes much less than it should there are 28 planted and only 9 came wrongly counting the items

Video: https://www.youtube.com/watch?v=OgFeAxdU-Os

### To Reproduce

when farms are done with a piston

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
