### ISSUE TITLE
WildStacker Bug Piglin 

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#249]
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

WildStacker-b170.jar

### Describe the bug

when he throws grouped gold bar to piglin he keeps giving the items endlessly and the gold never runs out.

![2021-07-27_13 59 31](https://user-images.githubusercontent.com/67756407/127693778-91c5be39-d4e4-4382-ad13-2983bc375a09.png)
![2021-07-27_13 59 33](https://user-images.githubusercontent.com/67756407/127693787-8e338f9d-ee0c-4dfe-bbc5-e16e8952ccd3.png)

### To Reproduce

giving pooled gold to piglin

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
