### ISSUE TITLE
wildstacker pulling the cpu a lot

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#250]
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

WildStacker-b171.jar

### Describe the bug

on the 1.17.1 server the wildstacker is pulling a lot the cpu is at 7% consumption this only happens on 1.17.1 on the other 1.12.2 or 1.16.5 servers I don't have that problem I'm just using item grouping nothing else.

see my timings

https://timings.pl3x.net/?id=80c6f8361c894e9eb5a35990f145d67f

### To Reproduce

performance drop on the server

**Comment by brasilcraft54** [comment]
all mobspawners are only spawning 1-2 mobs per mobspawners is this also what is making him so heavy?

**Comment by WarnDangerous** [comment]
Could you provide a spark report please.

Install this plugin :
https://www.spigotmc.org/resources/spark.57242/

Do :
``/spark sampler``
Wait 1 minute
Do
``/spark sampler --stop``
Send the link here

**Comment by OmerBenGera** [comment]
Any news regarding this?
