### ISSUE TITLE
Bucket stack little issue

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/WildStacker#251]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

Dev-b171

### Describe the bug

When you get stacked fill bucket (like lava bucket), and you empty them one by one, at the end you get a stack of your bucket + a single bucket, instead of only 1 stack

### To Reproduce

Take for example 3 lava buckets :
<img width="657" alt="Screenshot_5441" src="https://user-images.githubusercontent.com/31826333/127771628-99a1392e-9ad5-4103-b008-4db5e3e86fb3.png">
If you empty one, you get 2 lava bucket and 1 empty bucket.
<img width="522" alt="Screenshot_5442" src="https://user-images.githubusercontent.com/31826333/127771632-3844961a-87e4-4100-a8e7-ff4764600633.png">
If you empty a second one, you get 1 lava bucket and 2 empty bucket
<img width="596" alt="Screenshot_5443" src="https://user-images.githubusercontent.com/31826333/127771635-9a7a36bd-1be6-4494-a6b6-0487e3c449b0.png">
If you empty the last one, instead of having 3 empty bucket, you get 1 empty bucket + 2 empty buckets
<img width="657" alt="Screenshot_5444" src="https://user-images.githubusercontent.com/31826333/127771636-2794402a-787d-4bdb-a82d-da865fc9cc25.png">

**Comment by OmerBenGera** [comment]
Thats intended, as the last bucket is not stacking because its not stacked anymore.
If I make it stack, it will affect vanilla buckets as well as it will make the buckets move in the inventory when there is no need in them to do so, being more annoying then helpful.
Therefore, I am closing this
