### ISSUE TITLE
IS settings Superiorskyblock

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#254]
### Minecraft's Version

1.12.2

### Plugin's Version

WildStacker-b171.jar

### Describe the bug

Hello, after the server restart the mob stacking settings is reset.

### To Reproduce

Add the stacking settings into superioskyblock and wildstacker and disable it with /is settings, restart the server

**Comment by OmerBenGera** [comment]
Fixed in latest dev build of WildStacker
