### ISSUE TITLE
stacked mob from stacked spawners don't totalise

### ISSUE THREAD

**Issue by WeaZzik** [BG-Software-LLC/WildStacker#256]
### Minecraft's Version

1.12.2

### Plugin's Version

3.6.0

### Describe the bug

Stacked spawners spawn well mobs with the same number, 10x spawners gonna create 10x mobs, but they not gonna stack between them.. I don't know if it's normal but i want to make them all stack in the same stack ^^'

There's no limits of stack applied or some things like that.

### To Reproduce

Didn't do anything, was present with the default config.yml..

**Comment by OmerBenGera** [comment]
Please take a video showcasing the issue and upload it to yt or another videos service.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
