### ISSUE TITLE
Villager being stacked

### ISSUE THREAD

**Issue by miistar** [BG-Software-LLC/WildStacker#258]
### Minecraft's Version

1.17.1

### Plugin's Version

3.6.0

### Describe the bug

I installed the plugin and then i noticed my villagers got stacked and i wasnt able to trade with all of them, cuz it was staked as 1. So i removed the plugin, checked if there was a folder left but the villagers was still stacked. Opened a ticked support on Shockbyte asking for help and they said

"It appears that this plugin may have applied NBT tags to entities within your world, thus permanently modifying them. If the plugin has been removed newly spawned entities should not be affected, however these modified entities will remain unless killed."

Is there a way i can get all the villagers back after removing the plugin? or is there a way i can make them unstack installing the plugin back by messing with the conf file?
![2021-08-12_06 40 45](https://user-images.githubusercontent.com/34053768/129148287-62f7acfb-5ff8-47b2-96cf-47c2e2f555e4.png)

### To Reproduce

Even after removing the plugin the villagers are still stacked

**Comment by OmerBenGera** [comment]
You are more than welcome to blacklist villagers from stacking, or enable the plugin to check their professions in the config of the plugin.
