### ISSUE TITLE
Stacked mob drop item will instantly pickup by mob

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#259]
### Minecraft's Version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)
>

### Plugin's Version

WildStacker-b171

### Describe the bug

use a weapon to kill a stacked mobs, the dropped item will be pickup by the same stack of stacked mob
players cannot pickup item fast enough and most of the loot is taken by the mob. (is still possible for players to pick up loot but not every time

gamerule mobgriefing false may fix this problem but it will cause villagers cannot bread so it would be a very bad solution for survival servers.

### To Reproduce

1. spawn stacked mobs
2. kill a mob

*i am using default config

### Additional Information

is it possible to prevent stacked mobs to pick up items? it should fix the problem 

additional video showing the problem
https://youtu.be/jh-R30eVzxI

**Comment by kedavlar** [comment]
i need this feature too if is possible

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
