### ISSUE TITLE
stacked mobs spawn with armor will keep armor and cause dupe

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#261]
### Minecraft's Version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

### Plugin's Version

WildStacker-b171

### Describe the bug

if a natural spawn stacked mob comes with armor, the armor will keep on the mob even after it die. Since the mob have armor, each time it die, it will keep dropping the armor

### To Reproduce

1. wait for spawners to spawn a stacked mobs that has armor on it, give item to mob pick up does not work
2. kill it

### Additional Information

video showing how it works.
it is very hard to produce, it takes a long time to find stacked mobs comes with armor, mobs may also got stacked by another stacked mobs.

https://youtu.be/qF8C_XDoq50

**Comment by OmerBenGera** [comment]
Look for the following option in the config:
```
  # Should vanilla equipment of entities get cleared after they unstack?
  clear-equipment: false
```
set it to true and it will be fixed.
