### ISSUE TITLE
instant-kill stacked mob does not drop according to stacked numbers

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#262]
### Minecraft's Version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

### Plugin's Version

[11:53:48 INFO]: WildStacker version 3.6.0-DEVb171
[11:53:48 INFO]: Stacking drops, entities, blocks and spawners into one object!
[11:53:48 INFO]: Website: https://bg-software.com/
[11:53:48 INFO]: Author: Ome_R

### Describe the bug

i am using
```
  instant-kill:
  - FALL
  - SUFFOCATION
  - LAVA
  - WATER
  - VOID
  - ENTITY_ATTACK
```

when i kill the stacked mob, with instant kill, it does not drop according to how many stacked mobs.
it only drop like 1 mob.

### To Reproduce

1. wait for mobs to be stacked, alot
2. kill it

### Additional Information

This was asked in #260

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Mind sharing your entire config?

**Comment by hkkongou** [comment]
sure
https://paste.gg/p/anonymous/2bda26ebce3042798db660515941596f

**Comment by OmerBenGera** [comment]
Look for the following section and set it to this:
```
  # Should drops get calculated in relation to the amount of mobs that died?
  multiply-drops: true
```
You must have it enabled in order to get the drops multiplied :)
