### ISSUE TITLE
[BUG] mobs still don't disappear in different world

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#264]
### Minecraft's Version

1.16.5 tuinity

### Plugin's Version

178

### Describe the bug

After all the fix, mobs still don't disappear when teleporting between different worlds

### To Reproduce

just teleport to another world and back to the spawner world

**Comment by OmerBenGera** [comment]
If you teleport to another world, the chunks in the old world might still be loaded.
I tested it with unloading the world and it worked just fine

**Comment by kedavlar** [comment]
i fix it, thanks anyways!! best plugin ever.
