### ISSUE TITLE
mcmmo Rupture skill cause stacked mobs to behave abnormally

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#265]
### Minecraft's Version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

### Plugin's Version

WildStacker version 3.6.0-DEVb181
[22:13:48 INFO]: Stacking drops, entities, blocks and spawners into one object!
[22:13:48 INFO]: Website: https://bg-software.com/
[22:13:48 INFO]: Author: Ome_R

### Describe the bug

when mcmmo is installed and the skill Rupture is enabled for players to use, if a mob have Rupture effect, stacked mobs will keep dying and got knockback and goes forever until stacked to 0

### To Reproduce

1. install mcmmo
2. make sure rupture skill is enabled, is default on
3. hit stacked zombie 

### Additional Information

A video on how it works.
i am very sure this is because of this mcmmo skill,  because when i got mcmmo not installed, cannot reproduce, only with mcmmo can reproduce.

https://youtu.be/OJ6BkS0r4kQ

config
https://paste.gg/p/anonymous/9f12025e2e3046029d1aa72ce65afd80

**Comment by OmerBenGera** [comment]
what does rupture do? just give a lot of damage to the entities?

**Comment by kedavlar** [comment]
it is the ropture ability that causes the mob to snag

**Comment by hkkongou** [comment]
> rupture
according to 
https://mcmmo.fandom.com/wiki/Swords


![image](https://user-images.githubusercontent.com/61608872/129449887-0ad92d67-1401-44c6-b164-ed521ff27583.png)

**Comment by OmerBenGera** [comment]
It says the effect doesn't last for long, however it does in the video, no?

**Comment by hkkongou** [comment]
> It says the effect doesn't last for long, however it does in the video, no?

The effect should end when the mob die
But seems like stacked mobs are many moba behaved like 1 mob and the effect seems carry on and so .. 🤔🤔

**Comment by OmerBenGera** [comment]
> 
> 
> > It says the effect doesn't last for long, however it does in the video, no?
> 
> The effect should end when the mob die
> But seems like stacked mobs are many moba behaved like 1 mob and the effect seems carry on and so .. 🤔🤔

Let me look into their code, hopefully there's something to do regarding this

**Comment by OmerBenGera** [comment]
I took a look in their code, and I might have a solution.
I will start working on it soon and hopefully it will work out :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, it should be fixed

**Comment by hkkongou** [comment]
> Check out latest dev build, it should be fixed

yep
is great now
thank you
