### ISSUE TITLE
hopper does not update after receiving stacked items

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#268]
### Minecraft's Version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

### Plugin's Version

WildStacker version 3.6.0-DEVb184
[17:15:44 INFO]: Stacking drops, entities, blocks and spawners into one object!
[17:15:44 INFO]: Website: https://bg-software.com/
[17:15:44 INFO]: Author: Ome_R

### Describe the bug

hopper does not update when some stacked item were sucked in.
normally , when using hopper as sorter(vanilla redstone), hopper item will need to have placed like this with redstone comparator facing at hopper.
![image](https://user-images.githubusercontent.com/61608872/129473576-daa6bffa-7578-4007-b627-d2d1c36596f7.png)

in  this picture, if there are wither skull > 17, lets say 20, the redstone comparator will deactivate and allow hopper to drop items, until the number become 17, and then the redstone comparator will power up and stop hopper to drop items.

but, in the video below, or in this situation, hoppers have more than 17 items still does not drop items, seems like the redstone contraptions around the hopper does not detect the hopper update, so , even the hopper have more than 17 items, it does not drop..

this problem cannot be reproduced without wildstacker, i have 2 more survival server without wildstacker just for compare, which does not have such problem

### To Reproduce

1. make a redstone sorter 
2. kill some stacked mobs, and have water flow those stacked items to sorter
(is hard to explain, i am not expert in redstone designs but my players are)

### Additional Information

video , important demonstration
https://youtu.be/brNr7z-oXq4

WS config
https://paste.gg/p/anonymous/e631a794590144b9a24e6c56aa5c9b4a

**Comment by hkkongou** [comment]
more info:
players report that items drop from inventory may also trigger this problem, hopper will not update too.

i suspect , since all items are passed to wildstacker for stacking process, no matter what items are dropped to the ground, if is the problem of item detect system, all drp[ item can reproduce this hopper issue.

**Comment by OmerBenGera** [comment]
Seems to work fine for me, maybe I did something wrong?
I set up a simple hoppers sorter, and threw items to the hopper when having stacked items enabled, and it worked fine for me

**Comment by hkkongou** [comment]
> Seems to work fine for me, maybe I did something wrong?
> I set up a simple hoppers sorter, and threw items to the hopper when having stacked items enabled, and it worked fine for me

ok now i figured out what is this problem.
this is due to a misconfiguration of spigot.yml
```
    ticks-per:
      hopper-transfer: 6
      hopper-check: 5
```
if the hopper check is too high or transfer is too low, putting too many things into hopper will cause jamming and no updates.

**Comment by OmerBenGera** [comment]
I am glad you found the cause of the issue :)
