### ISSUE TITLE
superiorskyblock-hook doesn't works

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#270]
### Minecraft's Version

1.12.2

### Plugin's Version

b185.jar

### Describe the bug

Hello, with the latest version the stacking settings not works (i don't have the option into /is settings, maybe the hook not works correctly). it works before the #180 commit

### To Reproduce

Turn superiorskyblock-hook to true and add the settings in /is settings, and look

**Comment by nivcoo** [comment]
I've an error https://hastebin.com/ohizorebey.properties

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by nivcoo** [comment]
Hello : [WildStacker] Couldn't register a custom island-flag into SuperiorSkyblock - open an issue on github.

**Comment by OmerBenGera** [comment]
For no reason, your WildStacker jar seems to not load before SuperiorSkyblock.
Mind sharing with me your full logs file (latest.log)?

**Comment by nivcoo** [comment]
https://hastebin.com/deduruxicu.yaml

**Comment by OmerBenGera** [comment]
Try latest dev build, I think it occurred because of MultiverseCore.

**Comment by nivcoo** [comment]
Same issue with b195

**Comment by OmerBenGera** [comment]
Try this on a server with only SSB and WS, let me know if it still happens

**Comment by nivcoo** [comment]
I haven't the issue with only ws et sb2

**Comment by nivcoo** [comment]
OK, i've the issue with my plugin which have ssb2 in soft depends

**Comment by nivcoo** [comment]
My plugin still loads after so idk why

**Comment by nivcoo** [comment]
Correction, the problem occurs when there are too many plugins which "soft depend: superiorskyblock"

**Comment by nivcoo** [comment]
Ok i've the issue : You have added superior into loadbefore but you have also superior into softdepends, it's the issue

**Comment by nivcoo** [comment]
https://github.com/BG-Software-LLC/WildStacker/pull/293

**Comment by OmerBenGera** [comment]
I pushed a build without SuperiorSkyblock2 being a softdepend, let me know if it works now...

**Comment by nivcoo** [comment]
Not works, it works when i change the condition in my pr

**Comment by OmerBenGera** [comment]
> 
> 
> Not works, it works when i change the condition in my pr

That's the change you wanted me to make, if it doesn't work then it might be something on your end.
The condition that you changed is checking for a specific class path, which is the same as checking if the plugin is enabled.

**Comment by nivcoo** [comment]
Why are you using this condition for Shopguiplus ?

**Comment by nivcoo** [comment]
I will add the setting into my plugin to add that :p

**Comment by nivcoo** [comment]
Because idk why Wildstacker is loaded after ssb2
