### ISSUE TITLE
stacking may cause entitymetadatastore memory leak

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#271]
### Minecraft's Version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

### Plugin's Version

WildStacker version 3.6.0-DEVb184
[17:15:44 INFO]: Stacking drops, entities, blocks and spawners into one object!
[17:15:44 INFO]: Website: https://bg-software.com/
[17:15:44 INFO]: Author: Ome_R

### Describe the bug

since i have installed wildstacker and running, i have some serious memory leak, as i have mention in other tickets.. i have 3 servers, 1 have WS installed, 2 not. The one with WS have this memory leak issue, the G1old will active when server running for more than 12 hours, creating lag spikes.

From the eclipse memory analyzer analysing the heapdump from spark, these are the leak suspects and are relating to entities ... 

![image](https://user-images.githubusercontent.com/61608872/129655803-6d960d34-aba5-4de0-9d98-1e44896933aa.png)
![image](https://user-images.githubusercontent.com/61608872/129655817-34f243e0-232e-4e1c-8327-f53a8750ec53.png)
![image](https://user-images.githubusercontent.com/61608872/129655835-bbe19cea-fbab-4212-8f44-0117b0a9cc6f.png)
![image](https://user-images.githubusercontent.com/61608872/129655850-ddb6b677-df7b-41f9-8094-c148d80d11de.png)

### To Reproduce

1. install WS
2. run server for more than 12 hours with players doing random grinding mob farms

### Additional Information

WS config:
https://paste.gg/p/anonymous/59429a1a37fd4f228c870c6f3ff06bcd

i don't really know how to read heapdump very well as i am not a java developer, i only read some google tutorial on how to find memory leak in basic level.

if you need the heapdump file i can privately send you.

**Comment by OmerBenGera** [comment]
I will look into that.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by hkkongou** [comment]
some of my players reported that picking up stacked drop or attacking stacked mobs caused the entire inventory loss
atm i was upgrading from b184 to b193 , afterwards i convert back to b 184 then
so far i still finding the cause of this problem

**Comment by OmerBenGera** [comment]
> 
> 
> some of my players reported that picking up stacked drop or attacking stacked mobs caused the entire inventory loss
> atm i was upgrading from b184 to b193 , afterwards i convert back to b 184 then
> so far i still finding the cause of this problem

Should be fixed in latest dev build already :)
I am closing this as it seems to be solved.
