### ISSUE TITLE
Pickup sound's pitch is not randomized as in vanilla

### ISSUE THREAD

**Issue by N1ghthauq** [BG-Software-LLC/WildStacker#273]
### Minecraft's Version

Minecraft: 1.17.1
Paper-1.17.1-172

### Plugin's Version

Wildstacker-3.6.0

### Describe the bug

When picking up items, Wildstacker overrides the vanilla pickup sounds, which have a randomized pitch, and allows only one pitch.

### To Reproduce

Fresh install, enable item stacking, ensure item pickup sound is on. Listen to the sounds.
Go to vanilla world, turn volume all the way up, listen to the sounds, drop around 20 different item stacks to thoroughly listen to the pickup sounds.

### Additional Information

A short clip of a world without Wildstacker, using Optifine as the only modification:
https://streamable.com/g401yv

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
