### ISSUE TITLE
Loottables sometimes bug

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/WildStacker#280]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b185

### Describe the bug

I wanted to remove the wither_skeleton dropping cobble sword, so I opened the "loottables" and edit wither_skeleton by removing this loot.

It works but not perfectly, with 30 wither skeleton I still got 3-4 swords (instead of 20 before)

My sword has: 
- looting 3
- sweeping edge
- bane of artropods
- sharpness

maybe it's sweeping edge that bugs and do not apply the custom loots.

### To Reproduce

use my config (see under) for wither_skeleton, spawn some in the same place, and kill them.

### Additional Information

My json file :
 https://pastebin.com/3FyPs3hG
 
 (I also edited WITHER_SKELETON_SKULL)

**Comment by OmerBenGera** [comment]
You must add "dropEquipment: false" so the wither skeletons don't drop their equipment (aka, stone sword).
