### ISSUE TITLE
inventory clear

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/WildStacker#283]
### Minecraft's Version

1.16.5 paper

### Plugin's Version

b191

### Describe the bug

Since your latest release, when I kill mobs, it randomly clear all players inventory, I didn't get the issue on wildstacker b185

(I reproduced the issue on a paper server with only wildstacker, a spawner and killing stacked mobs with netherite sword)

### To Reproduce

(I reproduced the issue on a paper server with only wildstacker, a spawner and killing stacked mobs with netherite sword)

**Comment by OmerBenGera** [comment]
Don't use latest version as of now.

**Comment by OmerBenGera** [comment]
Use latest dev build for now, the changes were reverted.
