### ISSUE TITLE
Strange Piglin Behavior

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/WildStacker#285]
### Minecraft's Version

Purpur 1.17.1-R0.1-SNAPSHOT
Purpur 1.16.5-R0.1-SNAPSHOT
(This happens on 2 different gamemodes so)

### Plugin's Version

1.17: 3.6.0-DEVb184
1.16: 3.6.0-DEVb178

### Describe the bug

Piglins will take items you throw it but just delete them from existence unless they're made of gold. It doesn't do this with tools unless they have no item in their hand. If it has no item in it's hand you can give it a gold tool and it will pick it up and equip it but then it stops trying to pick up tools again. When you kill the piglin it doesn't drop any of the things you gave it.

### To Reproduce

1. Get a piglin
2. Throw it anything but gold armor
3. Cry as it consumes your valuables

### Additional Information

https://imgur.com/gallery/orxZjnX - Armor
https://www.youtube.com/watch?v=_msJ9uH4mV4 - Tools

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
