### ISSUE TITLE
Not correctly working with Towny Advanced

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#288]
### Minecraft's Version

Paper version git-Paper-196 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 59d449d)

### Plugin's Version

Tried with 3.6.0 and #196

### Describe the bug

I'm running the latest version of Paperspigot 1.17.1 with the latest version of Towny Advanced. Normally when mobs enter a claimed area, they despawn. Single mobs still do, but when they are stacked, they don't.

### To Reproduce

Claim a chunk for a town and let stacked mobs walk into it. They should despawn but doesn't.

**Comment by OmerBenGera** [comment]
has it worked before?

**Comment by Sckaletz** [comment]
Well yes, but that was back when we used Paper 1.12.2 a long time ago. I don't remember what version of Wildstacker we used back then.

**Comment by OmerBenGera** [comment]
I checked it using latest of WS and latest of Towny and it seems to work fine.
Are you using a specific version of Towny maybe that conflicts (for example, checks for custom names or something like that)?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Sckaletz** [comment]
Well, it doesn't work here with Towny Advanced 0.97.1.0 and the latest PaperSpigot 1.17.1. I found another stacker system, that worked fine.

**Comment by OmerBenGera** [comment]
I will look into that again I guess...

**Comment by OmerBenGera** [comment]
I found out that my testings were using the exact same version of Towny that you used.
Are you able to replicate it on another server?

**Comment by OmerBenGera** [comment]
Any news regarding this?
