### ISSUE TITLE
Ghast Bug Count

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#289]
### Minecraft's Version

purpur-1.17.1

### Plugin's Version

WildStacker-b194.jar

### Describe the bug

sorry to reopen this ticket but you have a problem with the ghast of 50 mobspawner is born 50 and then over 1k and the maximum was supposed to be 200 and not over 1k.

### To Reproduce

place 50 ghast spawners clustered on the ground.

**Comment by OmerBenGera** [comment]
Send me your config please

**Comment by OmerBenGera** [comment]
I can't replicate the issue, it seems to work fine for me.

**Comment by brasilcraft54** [comment]
I will make a video to show you.

**Comment by brasilcraft54** [comment]
> I can't replicate the issue, it seems to work fine for me.
It happens with the Iron Golem and other mobs as well. This only happens if you let 50 spawns for example, and in the next spawn 3k - 5k are born.

https://youtu.be/A0hSYDnJ-so

**Comment by OmerBenGera** [comment]
how is it jumping from 50 to 5000? it makes no sense.
Why would the spawner spawn 4500 entities? Did you play with the spawn counts in any way?

**Comment by brasilcraft54** [comment]
> how is it jumping from 50 to 5000? it makes no sense.
> Why would the spawner spawn 4500 entities? Did you play with the spawn counts in any way?

I haven't changed anything, it's the normal configuration
and that is why I am reporting it because it never happened started after you fixed that bug where it went from 50 to 51,52,53,54

**Comment by brasilcraft54** [comment]
started after this report that you fixed, it happens with the iron golem too.

https://github.com/BG-Software-LLC/WildStacker/issues/275

**Comment by OmerBenGera** [comment]
Send me your config please

**Comment by brasilcraft54** [comment]
then?

**Comment by brasilcraft54** [comment]
?

**Comment by OmerBenGera** [comment]
I have yet to look into that, there is no need to bump the issue.

**Comment by brasilcraft54** [comment]
> I have yet to look into that, there is no need to bump the issue.

there is even a video showing the problem but you know the players with 10 spawner are born with 1k

**Comment by OmerBenGera** [comment]
> 
> 
> > I have yet to look into that, there is no need to bump the issue.
> 
> there is even a video showing the problem but you know the players with 10 spawner are born with 1k

it doesn't matter unless I can't replicate it.

**Comment by OmerBenGera** [comment]
Any news regarding this?
