### ISSUE TITLE
Stacked entities names ignoring spaces

### ISSUE THREAD

**Issue by iLemon** [BG-Software-LLC/WildStacker#290]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/18317307/130361803-c781bde3-5b6b-4af4-96c4-4704cea34b61.png)

### Plugin's Version

![image](https://user-images.githubusercontent.com/18317307/130361820-10097c6c-7896-44c0-af13-283aa1194a45.png)

### Describe the bug

Stacked entities name is ignoring spaces from the config.
![image](https://user-images.githubusercontent.com/18317307/130361858-4ad6a64b-84b7-4f55-8d6e-fa9ce32e4629.png)
custom-name: '&e&l{0}x {1}'

### To Reproduce

custom-name: '&e&l{0}x {1}'

**Comment by OmerBenGera** [comment]
Weird. I'd recommend testing it with the default config.
If it still occurs, might be due to your custom spigot that you use, even tho I don't think that's the issue.

**Comment by iLemon** [comment]
I managed to resolve this by changing it from
custom-name: '&e&l{0}x {1}'
to
custom-name: '&e&l{0}x&r &e&l{1}'

**Comment by OmerBenGera** [comment]
> 
> 
> I managed to resolve this by changing it from
> custom-name: '&e&l{0}x {1}'
> to
> custom-name: '&e&l{0}x&r &e&l{1}'

Weird, but it works.
I will look into it more on my end, and if I find what causes it I will make an update.
For now, I am closing this :)
