### ISSUE TITLE
Spawn Condition Didnt work

### ISSUE THREAD

**Issue by JessyDrew** [BG-Software-LLC/WildStacker#292]
### Minecraft's Version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 168 version(s) behind
Previous version: git-Paper-786 (MC: 1.16.5)

### Plugin's Version

#198

### Describe the bug

In the config I put:
spawn-conditions:
      COW: 
      - ON_TREE_OR_AIR
      
However in game it does not want to spawn. Only on dirt.

In addition, is it possible to modify the condition of appearance of slime spawns?

### To Reproduce

Put spawn-conditions:
      COW: 
      - ON_TREE_OR_AIR
on the config

**Comment by OmerBenGera** [comment]
The spawning overriding feature doesn't work in 1.17.
If you look in your console, you'd see a warning regarding this.
Therefore, all vanilla spawn conditions must be met in 1.17, as WildStacker cannot override it.

**Comment by JessyDrew** [comment]
My server run on 1.16.5
