### ISSUE TITLE
Loottables Iron Golem & Zombie Drops Not Working

### ISSUE THREAD

**Issue by Proomp** [BG-Software-LLC/WildStacker#299]
### Minecraft's Version

1.8.8

### Plugin's Version

v3.6.0-DEVb203

### Describe the bug

I'm using default loottables settings. Iron golem & Zombie drops not working.

### To Reproduce

latest.log: https://paste.helpch.at/ujadoqibah.sql

**Comment by Ebubekir728** [comment]
> Find what makes drops to not drop, as it's not the first time it happens for you.
> Make sure first tho to test it with only WildStacker installed, so we make sure it's an issue with WildStacker / your spigot jar

I was using Paper on top. latest.log when I use Spigot: https://paste.helpch.at/uhuqoyolan.sql
I don't think this question is related to Spigot jar.

**Comment by OmerBenGera** [comment]
That's weird that only for zombies and iron golems drops are not working.
Are you sure it doesn't happen with other mobs as well?

**Comment by Ebubekir728** [comment]
> That's weird that only for zombies and iron golems drops are not working.
> Are you sure it doesn't happen with other mobs as well?

Creeper working. I don't check other mobs.

**Comment by OmerBenGera** [comment]
It seems to work fine for me, are you sure it's related to WildStacker?
Also, have you tested it with only WildStacker being installed?

**Comment by Proomp** [comment]
> It seems to work fine for me, are you sure it's related to WildStacker?
> Also, have you tested it with only WildStacker being installed?

I just tested it with WildStacker installed and it doesn't work.
latest.log: https://paste.helpch.at/cucofamopa.md

**Comment by OmerBenGera** [comment]
Show me the loot tables of your zombies and iron golems please

**Comment by Proomp** [comment]
I using default loottables.

**Comment by OmerBenGera** [comment]
> 
> 
> I using default loottables.

Default loottables work fine for me.
Are you able to replicate the issue on another server?

**Comment by Proomp** [comment]
I try this another server and not working.

**Comment by OmerBenGera** [comment]
> 
> 
> I try this another server and not working.

What spigot jar are you using? I'll try replicating it again using your exact same setup.

**Comment by Proomp** [comment]
> > I try this another server and not working.
> 
> What spigot jar are you using? I'll try replicating it again using your exact same setup.

I using 1.8.8 Paper (latest). Download link: https://papermc.io/legacy

**Comment by OmerBenGera** [comment]
It works fine for me

**Comment by Proomp** [comment]
I don't know. I will close this issue.
But this issue not solved!

**Comment by OmerBenGera** [comment]
Mind zipping your server and send it to me over?

**Comment by Proomp** [comment]
> Mind zipping your server and send it to me over?

Here https://workupload.com/file/aMje4MRJMAf

**Comment by OmerBenGera** [comment]
I killed an Iron Golem and a Zombie and both dropped items...
Try using the following loot table for the entities:
```
{
  "pairs": [
    {
      "chance": 100,
      "items": [
        {
          "type": "DIAMOND",
          "chance": 100,
          "min": 1,
          "max": 1
        }
      ]
    }
  ]
}
```

It should drop 1 diamond all the time.
Let me know if it works for you.

**Comment by Proomp** [comment]
> I killed an Iron Golem and a Zombie and both dropped items...
> Try using the following loot table for the entities:
> 
> ```
> {
>   "pairs": [
>     {
>       "chance": 100,
>       "items": [
>         {
>           "type": "DIAMOND",
>           "chance": 100,
>           "min": 1,
>           "max": 1
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> It should drop 1 diamond all the time.
> Let me know if it works for you.

This isn't working for Iron Golem but I tried for Skeleton and working for Skeleton.

**Comment by OmerBenGera** [comment]
> 
> 
> > I killed an Iron Golem and a Zombie and both dropped items...
> > Try using the following loot table for the entities:
> > ```
> > {
> >   "pairs": [
> >     {
> >       "chance": 100,
> >       "items": [
> >         {
> >           "type": "DIAMOND",
> >           "chance": 100,
> >           "min": 1,
> >           "max": 1
> >         }
> >       ]
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It should drop 1 diamond all the time.
> > Let me know if it works for you.
> 
> This isn't working for Iron Golem but I tried for Skeleton and working for Skeleton.

I really don't know what to tell you, something is blocking the plugin from dropping items for Iron Golems or something, as it works fine for me using your exact same setup

**Comment by OmerBenGera** [comment]
What's your discord?
I want to give you a jar that prints messages to screen, so we can better understand what happens.

**Comment by Proomp** [comment]
> What's your discord?
> I want to give you a jar that prints messages to screen, so we can better understand what happens.

Ok. 
Proomp#9980

**Comment by Proomp** [comment]
Solved thanks for support!
