### ISSUE TITLE
any mob spawner turns to pig spawner when placed

### ISSUE THREAD

**Issue by BrightTooth3** [BG-Software-LLC/WildStacker#300]
### Minecraft's Version

1.16.5 paper

### Plugin's Version

was using stable version 3.6.0 then tried to fix the error by moving to WildStacker-b203 (this did not fix the issue)

### Describe the bug

everytime i place any spawner it turns into a pig spawner and at the same time i get an error message in server console. (https://pastebin.com/FWq4AZhH)

### To Reproduce

use EconomyShopGUI-3.6.1
use either 3.6.0 or b203 wildstacker
use MineableSpawners 3.1.0
use EssentialsX 2.19.0-dev+256-e4c179f
edit: i forgot to mention you need to use vault - i dont think the version matters
place a spawner, and it should turn into a pig spawner.

### Additional Information

economyshopgui config:
https://pastebin.com/dEwBEYUa

wildstacker config:
https://pastebin.com/4uvEHK1M

mineablespawners config:
https://pastebin.com/7ktP5rXL

EssentialsX config:
https://pastebin.com/JfRWm2d6

**Comment by OmerBenGera** [comment]
For no reason, MineableSpawners return null when trying to retrieve entity type from an item stack.
Try giving yourself spawners using their command and not /ws give - let me know if it works.

**Comment by OmerBenGera** [comment]
Any news regarding this?
