### ISSUE TITLE
WildStacker Guardian Item Drop Issue

### ISSUE THREAD

**Issue by Drevya** [BG-Software-LLC/WildStacker#303]
### Minecraft's Version

1.8.9

### Plugin's Version

3.4.3

### Describe the bug

When I spawn a guardian with a spawner, egg or command, when I kill the guardians, the item does not drop.

### To Reproduce

1) i install wildstacker
2) When I follow the steps I mentioned in "Describe the bug", the item does not drop from the Guardan.
3) after i uninstall the plugin
4) when i kill guardians, the items drop

### Additional Information

1) Just "item" is enabled on config
2) all other features are disabled

+ one-shot is true
  - i disabled and try it but same issue is going on
  
 + i write ENTITY-ATTACK in instant-kill
  - i delete and try it but same issue is going on
  
  loottables -> guardinas is default. I didn't set anything

**Comment by OmerBenGera** [comment]
You use a version that was uploaded months if not years ago, update.

**Comment by OmerBenGera** [comment]
If it still occurs after using latest dev build, reply here.
