### ISSUE TITLE
[bug]baby creatures only drop xp

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#304]
### Minecraft's Version

paper-1.16.5-780

### Plugin's Version

WildStacker-b196

### Describe the bug

baby variant of mobs, such as zombie or piglin, does not drop items , only drop xp.
normal version of mobs drop normally.

video demo:
https://youtu.be/kkpugsW44iM
live server:
https://www.youtube.com/watch?v=g46M_xomV4M

### To Reproduce

1. wait for spawner to spawn baby mob
2. kill them

### Additional Information

config
https://paste.gg/p/anonymous/c771478d13564a09a1b9b7ce1d01b7db

**Comment by OmerBenGera** [comment]
You are more than welcome to change their drop tables to drop items as well :)

**Comment by hkkongou** [comment]
> You are more than welcome to change their drop tables to drop items as well :)

i cannot find baby zombie, baby zombified piglin's drop table, is that normal?

**Comment by OmerBenGera** [comment]
> 
> 
> > You are more than welcome to change their drop tables to drop items as well :)
> 
> i cannot find baby zombie, baby zombified piglin's drop table, is that normal?

They are might not be generated by default - just create them manually by creating the files "zombie_baby.json" and "zombified_piglin_baby.json"

**Comment by hkkongou** [comment]
> zombified_piglin_baby.json
the zombie_baby.json works but zombified_piglin_baby.json is not working... what should i do?

**Comment by OmerBenGera** [comment]
> 
> 
> > zombified_piglin_baby.json
> 
> the zombie_baby.json works but zombified_piglin_baby.json is not working... what should i do?

make sure the name of the loot table is correct.

**Comment by hkkongou** [comment]
> > > zombified_piglin_baby.json
> > 
> > 
> > the zombie_baby.json works but zombified_piglin_baby.json is not working... what should i do?
> 
> make sure the name of the loot table is correct.

is like this

![image](https://user-images.githubusercontent.com/61608872/132019216-382e2f7c-9e79-44c8-ac7d-c4460dd6fc11.png)

**Comment by OmerBenGera** [comment]
try zombie_pigman_baby.json

**Comment by hkkongou** [comment]
> try zombie_pigman_baby.json

this works
thank you so much
