### ISSUE TITLE
WildStacker and ExoticGarden crash server

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#306]
### Minecraft's Version

paper-1.17.1-249

### Plugin's Version

WildStacker-b205.jar

ExoticGarden - DEV 76 (git d148a).jar

### Describe the bug

my server was crashing after checking my timings I found out it was the ExoticGarden and WildStacker after I removed the WildStacker the server did not crash anymore and the tps is fixed at 20.20.20 see below the timings with and without the wildstacker

with WildStacker:  https://timings.aikar.co/?id=1f7466236e304176b112eec7f00baa34

without WildStacker: https://timings.aikar.co/?id=e41060b75aa844dda6cce0e898ce243f

after removing everything everything is back to normal see the ExoticGarden is barely showing ta 0.05.

this is the logs before the server crash: https://pastebin.com/16srD520

### To Reproduce

put the 2 plugins together with about 20 players and let them explore the map after about 10 - 20 minutes the server crashes.

**Comment by brasilcraft54** [comment]
now my server is 2 hours online with no tps dropping or crashing before it was dropping between 10 - 20 minutes after removing wildstacker but I like wildstacker so much I use it in all my servers and this only happens with ExoticGarden

**Comment by OmerBenGera** [comment]
Please provide me with a spark profiler alongside of your config.
From what I can see, the plugin tries to get entities in a new loaded chunk and load their data, and for no reason your server is struggling to handle that easy task.

**Comment by brasilcraft54** [comment]
> Please provide me with a spark profiler alongside of your config.
> From what I can see, the plugin tries to get entities in a new loaded chunk and load their data, and for no reason your server is struggling to handle that easy task.

i don't know how to work with this and i will not add the wildstacker because it will crash the server and it doesn't even last 10m online that it crashes the server isn't there some way it can ignore the exoticgarden and its fruits?

**Comment by OmerBenGera** [comment]
> 
> 
> > Please provide me with a spark profiler alongside of your config.
> > From what I can see, the plugin tries to get entities in a new loaded chunk and load their data, and for no reason your server is struggling to handle that easy task.
> 
> i don't know how to work with this and i will not add the wildstacker because it will crash the server and it doesn't even last 10m online that it crashes the server isn't there some way it can ignore the exoticgarden and its fruits?

You can install both plugins on another server and do the tests there.
If you can't provide me with a spark profiler, I will have to close this ticket.

**Comment by brasilcraft54** [comment]
> > > Please provide me with a spark profiler alongside of your config.
> > > From what I can see, the plugin tries to get entities in a new loaded chunk and load their data, and for no reason your server is struggling to handle that easy task.
> > 
> > 
> > i don't know how to work with this and i will not add the wildstacker because it will crash the server and it doesn't even last 10m online that it crashes the server isn't there some way it can ignore the exoticgarden and its fruits?
> 
> You can install both plugins on another server and do the tests there.
> If you can't provide me with a spark profiler, I will have to close this ticket.

I will do this but what commands should I use and what should I pass you could you tell me?

**Comment by OmerBenGera** [comment]
> 
> 
> > > > Please provide me with a spark profiler alongside of your config.
> > > > From what I can see, the plugin tries to get entities in a new loaded chunk and load their data, and for no reason your server is struggling to handle that easy task.
> > > 
> > > 
> > > i don't know how to work with this and i will not add the wildstacker because it will crash the server and it doesn't even last 10m online that it crashes the server isn't there some way it can ignore the exoticgarden and its fruits?
> > 
> > 
> > You can install both plugins on another server and do the tests there.
> > If you can't provide me with a spark profiler, I will have to close this ticket.
> 
> I will do this but what commands should I use and what should I pass you could you tell me?
> like, do I start the server and run the commands or wait for some time or something?

When the lag occurs, run /spark sampler, wait a few seconds, then /spark sampler --stop
Send me then the link that you get

**Comment by brasilcraft54** [comment]
I made one of 5m and walked around the world and giving /tp to generate new worlds and the exoticgarden went to 8% also on the test server but if I remove the wildstacker it stays at 0.05

https://spark.lucko.me/JIAT1AaDjk

**Comment by brasilcraft54** [comment]
this one I gave /tp 8000 89 - 14000 and it gave a 1 second delay so I ran the command and gave tp somewhere else and gave stop as you asked.

https://spark.lucko.me/4win0sMHov

**Comment by OmerBenGera** [comment]
> 
> 
> I made one of 5m and walked around the world and giving /tp to generate new worlds and the exoticgarden went to 8% also on the test server but if I remove the wildstacker it stays at 0.05
> 
> https://spark.lucko.me/JIAT1AaDjk

I don't see anything from wildstacker in this spark profiler.

**Comment by OmerBenGera** [comment]
> 
> 
> this one I gave /tp 8000 89 -14000 and it gave a 1 second delay so I ran the command and gave tp somewhere else and gave stop as you asked.
> 
> https://spark.lucko.me/4win0sMHov

Neither here, both spark profilers are fine in terms of WildStacker.

**Comment by brasilcraft54** [comment]
> > this one I gave /tp 8000 89 -14000 and it gave a 1 second delay so I ran the command and gave tp somewhere else and gave stop as you asked.
> > https://spark.lucko.me/4win0sMHov
> 
> Neither here, both spark profilers are fine in terms of WildStacker.


this is my timings

https://timings.aikar.co/?id=6f66ea130691432a96d29344bfaadd78

**Comment by OmerBenGera** [comment]
However, ExoticGarden is really lagging your server... nothing to do with WildStacker

**Comment by OmerBenGera** [comment]
> 
> 
> > > this one I gave /tp 8000 89 -14000 and it gave a 1 second delay so I ran the command and gave tp somewhere else and gave stop as you asked.
> > > https://spark.lucko.me/4win0sMHov
> > 
> > 
> > Neither here, both spark profilers are fine in terms of WildStacker.
> 
> this is my timings
> 
> https://timings.aikar.co/?id=6f66ea130691432a96d29344bfaadd78

Timings is not helpful. If spark is fine, then the plugin is fine.
You can check the spark profiler yourself.

**Comment by OmerBenGera** [comment]
> 
> 
> > > this one I gave /tp 8000 89 -14000 and it gave a 1 second delay so I ran the command and gave tp somewhere else and gave stop as you asked.
> > > https://spark.lucko.me/4win0sMHov
> > 
> > 
> > Neither here, both spark profilers are fine in terms of WildStacker.
> 
> this is my timings
> 
> https://timings.aikar.co/?id=6f66ea130691432a96d29344bfaadd78

You know what, even the timings shows that WildStacker is fine...

**Comment by brasilcraft54** [comment]
> > > > this one I gave /tp 8000 89 -14000 and it gave a 1 second delay so I ran the command and gave tp somewhere else and gave stop as you asked.
> > > > https://spark.lucko.me/4win0sMHov
> > > 
> > > 
> > > Neither here, both spark profilers are fine in terms of WildStacker.
> > 
> > 
> > this is my timings
> > https://timings.aikar.co/?id=6f66ea130691432a96d29344bfaadd78
> 
> You know what, even the timings shows that WildStacker is fine...

this is without the wildstacker see how it looks

https://timings.aikar.co/?id=32c0ae98026e49de87c0ef2d97a7096a

**Comment by brasilcraft54** [comment]
exoticgarden is now at 0.11% without wildstacker, that's what's weird

**Comment by brasilcraft54** [comment]
using a wildstacker version of the 166 the problem was much smaller see only 4%

https://timings.aikar.co/?id=a377c98948154a45941b27c67f1a7bbe

**Comment by brasilcraft54** [comment]
another test i did was remove the cluster entities and see they are working perfectly is something related to wildstacker entities. 
                     https://timings.aikar.co/?id=1d865c550cd140e7b686aae10870dbe6

**Comment by OmerBenGera** [comment]
You are again sending me timings...
Use spark profiler.

**Comment by Skizzles** [comment]
Hello @brasilcraft54 

Located in ur timings:
![image](https://user-images.githubusercontent.com/30563757/132121101-58870bc5-8e87-4ce0-9bb0-70d54bddd236.png)

ExoticGarden uses a populator for trees and plants that is well known to cause massive drops in performance. This is unrelated to Wildstacker. I recommend pre generating your world to prevent it from causing lag on ChunkPopulateEvent, or reporting to ExoticGarden for them to fix their issue.

**Comment by OmerBenGera** [comment]
I am closing this, as it doesn't seem to be anything related to WildStacker.

**Comment by brasilcraft54** [comment]
sorry to reopen this conversation but is there any way for wildstacker to ignore the exoticgarden plants or its plugin?

**Comment by OmerBenGera** [comment]
> sorry to reopen this conversation but is there any way for wildstacker to ignore the exoticgarden plants or its plugin?
> 
> or a solution for me to pass on to them?

The solution is that they optimize their plugin, or dont use it.

**Comment by brasilcraft54** [comment]
> > sorry to reopen this conversation but is there any way for wildstacker to ignore the exoticgarden plants or its plugin?
> > or a solution for me to pass on to them?
> 
> The solution is that they optimize their plugin, or dont use it.

solved the problem just add the option "PLAYER" in the blacklist in the configs and solved the problem. i found this out when a player entered minecraft-pe on his cell phone and it showed that the fruits on the trees are NPCs so i decided to test it and it worked.
