### ISSUE TITLE
Wither skeleton spawner to the ceiling/roof it will not spawn...

### ISSUE THREAD

**Issue by GodKiko123** [BG-Software-LLC/WildStacker#310]
### Minecraft's Version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information

### Plugin's Version

Dev builds #206

### Describe the bug

If you touch a wither skeleton spawner to the ceiling it will not spawn...

(I have all the conditions)

### To Reproduce

Just place a Wither Skeleton close to a roof...

**Comment by OmerBenGera** [comment]
It works just fine for me.
Maybe you have a plugin that restricts mobs from spawning on the ceiling of the nether?

**Comment by GodKiko123** [comment]
Okay, OmerBenGera, thank you, I'll see what it can do...
Btw, I've now been waiting for this possibility for months, can you add a command to see the time left to execute the Kill task???
Like  "/kill task time..."
Please I really need this option, if I need it i can even pay.

**Comment by OmerBenGera** [comment]
You are more than welcome to make a PR for the feature you want and I will merge it into the plugin.

**Comment by GodKiko123** [comment]
Ok, I've done it a while ago, I'm waiting :P.
Thanks for everything!
Have a good week.
