### ISSUE TITLE
Stews (Mushroom, Beatroot, Rabbit, etc) Deletes item held and gives you a bowl in whatever slot is available next

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#311]
### Minecraft's Version

1.17.1 Purpur dev 1375

### Plugin's Version

dev b205

### Describe the bug

When you put a stew in ur off hand and eat the stew, it deletes any item ur holding and gives a duplicated bowl into a random slot in ur inventory.

### To Reproduce

https://youtu.be/dkpb9vjmmp4

### Additional Information

Stew stacking is disabled.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
