### ISSUE TITLE
mob dosent despawn airplane

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#312]
### Minecraft's Version

airplane 1.16.5 lastest

### Plugin's Version

dev 205

### Describe the bug

when you teleport to another world and go back, the mobs present do not despawn

### To Reproduce

spawn a spawner [I used an enderman], spawn the mob, teleport to another world and then use the / back command to return

**Comment by OmerBenGera** [comment]
How do you know if they despawn or not?

**Comment by kedavlar** [comment]
when I get back to the mob position, they are still there

**Comment by OmerBenGera** [comment]
> 
> 
> when I get back to the mob position, they are still there

that's how minecraft works...
mobs don't straight away despawn when the chunks are unloaded
Anyways, even if it was an issue, it doesn't sound like it's related to WildStacker.
I am closing this for now
