### ISSUE TITLE
VANISHING SPAWNER GLITCH/BUG [URGENT]

### ISSUE THREAD

**Issue by ClickErrorxD** [BG-Software-LLC/WildStacker#314]
### Minecraft's Version

Minecraft Version: 1.16.5
Server Version: Paper1.16.5.jar

### Plugin's Version

WildStacker-3.6.0.jar

### Describe the bug

Basically, if you LEFT-CLICK, a spawner that is in your inventory while you are in the spawner menu, any menus, and then you EXIT the menu, the spawner(s) disappear. 

### To Reproduce

1. Have spawners from wildstacker inside your inventory.
2. Shift+Right-Click a PLACED spawner.
3. Left-Click a spawner that is in your inventory
4. Instantly close the menu.

### Additional Information

PROOF: https://youtu.be/iMZv-QR9TnI

**Comment by ClickErrorxD** [comment]
Just tested on the newest official version or non official, WildStacker-b207.jar. It's a issue on that version too. Please look into this asap, it's crucial.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
