### ISSUE TITLE
WildStacker removing block manually

### ISSUE THREAD

**Issue by FrankHeijden** [BG-Software-LLC/WildStacker#319]
### Minecraft's Version

x

### Plugin's Version

x

### Describe the bug

WildStacker always cancels the BlockBreakEvent, however, it should only do this when there are stacked spawners. If there’s just one spawner, WildStacker should allow the event to continue to happen, so the blockbreak can be monitored through EventPriority.MONITOR.

link to code:
https://github.com/BG-Software-LLC/WildStacker/blob/d79c4aa4dd2e255eb95ce03113b0cd5a199c44a2/src/main/java/com/bgsoftware/wildstacker/listeners/SpawnersListener.java#L283

### To Reproduce

x

**Comment by amarcais53** [comment]
i can confirm that i have issue with that and plugin to limit the amount of spawners on a oneblock island

**Comment by amarcais53** [comment]
like i can put spawner and its saying i have reached the limit but when i break them its not removing them from the count

**Comment by OmerBenGera** [comment]
No it shouldnt, as WildStacker handles all the spawners.

**Comment by OmerBenGera** [comment]
> i can confirm that i have issue with that and plugin to limit the amount of spawners on a oneblock island

You can ask the developer of that plugin to add support for WildStacker.

**Comment by FrankHeijden** [comment]
> No it shouldnt, as WildStacker handles all the spawners.

Im not sure how this comment solves the issue, the issue is that the MONITOR event will never be fired, even though the spawner is removed. This is because WildStacker artificially removes the spawner. Instead, it should allow the event to pass through when the spawner should be broken.

**Comment by OmerBenGera** [comment]
> > No it shouldnt, as WildStacker handles all the spawners.
> 
> Im not sure how this comment solves the issue, the issue is that the MONITOR event will never be fired, even though the spawner is removed. This is because WildStacker artificially removes the spawner. Instead, it should allow the event to pass through when the spawner should be broken.

Use the events of WildStacker for spawners.

**Comment by OmerBenGera** [comment]
Here is an example of how to use it:
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/hooks/provider/SpawnersProvider_WildStacker.java

**Comment by FrankHeijden** [comment]
It doesn't make much sense to force every plugin in existence which listens to the MONITOR event (which is there for a reason in bukkit) to add support for WildStacker.

**Comment by OmerBenGera** [comment]
> It doesn't make much sense to force every plugin in existence which listens to the MONITOR event (which is there for a reason in bukkit) to add support for WildStacker.

Thats how its done as its not possible to add data to the BlockPlaceEvent.
If you dont like the way its handled, you can make a fork that fits your server - the public version will stay like that, sorry.

**Comment by OmerBenGera** [comment]
Not to mention that you anyways need to add support for the plugin as you need to support stacked blocks with your plugins, so I dont see any problem with that

**Comment by FrankHeijden** [comment]
> > It doesn't make much sense to force every plugin in existence which listens to the MONITOR event (which is there for a reason in bukkit) to add support for WildStacker.
> 
> Thats how its done as its not possible to add data to the BlockPlaceEvent.
> If you dont like the way its handled, you can make a fork that fits your server - the public version will stay like that, sorry.

Above PR fixes it. Its 5 lines ^^

**Comment by FrankHeijden** [comment]
I also noticed you’re manually writing the entry to CoreProtect, because CoreProtect also doesn’t register the BlockBreak if WildStacker cancels the event. If this PR is merged, that can also be removed, as coreprotect would be able to figure out the block has been broken on the MONITOR event priority as well ^^

**Comment by OmerBenGera** [comment]
> I also noticed you’re manually writing the entry to CoreProtect, because CoreProtect also doesn’t register the BlockBreak if WildStacker cancels the event. If this PR is merged, that can also be removed, as coreprotect would be able to figure out the block has been broken on the MONITOR event priority as well ^^

It will not work when placing spawners to be stacked, and therefore it still needs to stay.
Your PR was denied as it causes issues with the current API and the way other plugins may have already used it in order to track spawners.

**Comment by FrankHeijden** [comment]
Its never too late to fix a bad implementation, but fine, this is not my fight anyway.

**Comment by OmerBenGera** [comment]
> 
> 
> Its never too late to fix a bad implementation, but fine, this is not my fight anyway.

I don't see how it's a bad implementation, and even if it was and the fix breaks the API, then it cannot be accepted.

**Comment by FrankHeijden** [comment]
You are "recreating" the effect of allowing the BlockBreakEvent to pass through by setting the block to air. This breaks every plugin monitoring this event for changes, as the result is incorrect (the event is cancelled, while it should not, as the block has been removed from the game). You then proceed to suggest these plugins to use your API, which is really unnecessary if WildStacker did what it is supposed to do.

The correct way to implement this behaviour is to:
1. Cancel every BlockBreakEvent if the stackedspawner container 2 or more stacked spawners.
2. Allow the event to pass through if there's just 1 stackedspawner, such that it will be broken.
3. Monitor the BlockBreakEvent to verify it is actually broken, since plugins in between your event listener and the monitor event may cancel this event as well. If this is not done, it could be that WildStacker thinks there's no spawner anymore, while in fact another plugin saved the spawner from being broken.

These three points will:
1. Not break or alter any API features you have right now (SpawnerPlaceEvent, SpawnerUnstackEvent...)
2. Remove the need for the manual modification in CoreProtect as the MONITOR event will work
3. Fix all compatibility with other plugins regarding the MONITOR event :)

Lastly, you seem to mention block placement as a concern, but this issue and PR aim to resolve an issue in the block break event.

**Comment by OmerBenGera** [comment]
> 
> 
> You are "recreating" the effect of allowing the BlockBreakEvent to pass through by setting the block to air. This breaks every plugin monitoring this event for changes, as the result is incorrect (the event is cancelled, while it should not, as the block has been removed from the game). You then proceed to suggest these plugins to use your API, which is really unnecessary if WildStacker did what it is supposed to do.
> 
> The correct way to implement this behaviour is to:
> 
>     1. Cancel every BlockBreakEvent if the stackedspawner container 2 or more stacked spawners.
> 
>     2. Allow the event to pass through if there's just 1 stackedspawner, such that it will be broken.
> 
>     3. Monitor the BlockBreakEvent to verify it is actually broken, since plugins in between your event listener and the monitor event may cancel this event as well. If this is not done, it could be that WildStacker thinks there's no spawner anymore, while in fact another plugin saved the spawner from being broken.
> 
> 
> These three points will:
> 
>     1. Not break or alter any API features you have right now (SpawnerPlaceEvent, SpawnerUnstackEvent...)
> 
>     2. Remove the need for the manual modification in CoreProtect as the MONITOR event will work
> 
>     3. Fix all compatibility with other plugins regarding the MONITOR event :)
> 
> 
> Lastly, you seem to mention block placement as a concern, but this issue and PR aim to resolve an issue in the block break event.

Let's take the following scenario:
I have a plugin that tracks all blocks placement. Therefore, I listen to BlockPlaceEvent and BlockBreakEvent in MONITOR.
Now, let's see what will happen when WS cancels all the interactions, and when it cancels only part of the interactions:

All Interactions:
You can easily listen to regular BlockPlaceEvent/BlockBreakEvent in MONITOR, while adding support for WS and listen to its events as well. You can get the amount of placed spawners / broken spawners using the event, and you don't have to be worried about counting blocks twice (from BlockPlaceEvent/BlockBreakEvent and WS's events).

Only stacked-spawners interactions:
You'll have to make adjustments to counts when using the WS's events (You must use them anyways, as you need to support stacked-spawners), as both WS's events and the vanilla events will be called. This will make your code messy, unorganized and harder to read. You will have to ignore spawners in vanilla events in order to get the counts correct.

What's easier you think? Not doing anything and just listen to both events, or make adjustments and still listen to both events?

This is my final words and I am locking this issue.
If you want this to be changed for your server, create a fork that fits your server needs.
