### ISSUE TITLE
discord invite expired

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#321]
### Minecraft's Version

n/A

### Plugin's Version

n/A

### Describe the bug

the discord invite on your website and on github seems to doesnt work its saying link expired or you are not allowed to join this discord

### To Reproduce

n/A

**Comment by amarcais53** [comment]
my discord HamtaBot#0001

**Comment by OmerBenGera** [comment]
Try this for now
https://discord.gg/vwzzNHA2a5
