### ISSUE TITLE
Parrots stacking with another although not supposed to

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/WildStacker#323]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev build 209

### Describe the bug

An unnamed cyan parrot and a named parrot that were 1 block apart from each other stacked  although they are not suppoed to. One of the parrots was from a spawnegg, the other one naturally spawned.

https://pastebin.com/AdDpbeiX - Entity config section proving that this shouldnt happen

### To Reproduce

Place 2 parrots of the same color down with spawneggs, and watch them stack after a while.

### Additional Information

https://i.imgur.com/7zsllxw.png

**Comment by OmerBenGera** [comment]
Do not use both whitelist and blacklist of entities.
Choose one of them you want to work with, and stick with it. Dont mix them up, otherwise weird things can happen.
Fix it first, then let me know if it still happens.

**Comment by marvjosh1** [comment]
@OmerBenGera this worked (putting only SPAWNER on the whitelist), however we were wondering how can we get zombified piglins that were transformed by a piglin being in the overworld to stack now as we only see an agrro option for them?

**Comment by marvjosh1** [comment]
Seems to be working as intended now, sorry for the issue!
