### ISSUE TITLE
Zombified Piglins not getting cleared by entity clear

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/WildStacker#324]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev build 209

### Describe the bug

Zombified Piglins are not getting cleared by the stacker, although they are supposed to be so. The zombie piglins in the video are spawned from a spawner, which is whitelisted in the config. Every other mob from spawners is just clearing fine.

https://pastebin.com/ZgBLzuxx - Kill entities config section proving that this shouldnt happen

### To Reproduce

Place down a spawner, have multiple zombified piglins spawn and stack. When an stacked entity clear happens, they dont get cleared

### Additional Information

https://www.youtube.com/watch?v=QisxUlsjPug

**Comment by OmerBenGera** [comment]
You cannot use both whitelist and blacklist. Choose one of them to stick with, and set the other one to be empty.
Let me know if it still happens after the changes.

**Comment by marvjosh1** [comment]
This worked (putting only SPAWNER on the whitelist), however we were wondering how can we get zombified piglins that were transformed by a piglin being in the overworld to stack now as we only see an agrro option for them?

**Comment by OmerBenGera** [comment]
> 
> 
> This worked (putting only SPAWNER on the whitelist), however we were wondering how can we get zombified piglins that were transformed by a piglin being in the overworld to stack now as we only see an agrro option for them?

You can add to the whitelist section the "PIGLIN_ZOMBIFIED", as this is the spawn-cause of all the transformed zombified piglins. You can find it by using `/ws inspect` and right-clicking a transformed zombified-piglin.
