### ISSUE TITLE
Endermites from ender pearls are stacking

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/WildStacker#325]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev build 209

### Describe the bug

When getting multiple endermited from ender pearls, they are stacking although they arent supposed to.

https://pastebin.com/AdDpbeiX - Entity config section proving that this shouldnt happen

### To Reproduce

Throw down some ender pearls until multiple endermites spawn. Wait a short moment, and they stack.

### Additional Information

https://www.youtube.com/watch?v=EiLTPuDqWd0
Note: The pet used here works just like enderpearls without cooldown

**Comment by OmerBenGera** [comment]
Already told you what to do.
