### ISSUE TITLE
When spawner stacking is disabled placed spawners turn into pig spawners.

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/WildStacker#326]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev build 209

### Describe the bug

When placing a spawner with stacked spawners disabled, it will turn into a pig spawner.
Screenshot of config: https://i.imgur.com/1IRSmkz.png

### To Reproduce

Gather yourself a spawner and place it with stacked spawners disabled. It will turn into a pig spawner

### Additional Information

https://www.youtube.com/watch?v=BbKtXwb9hLk
The spawner was collected with a spawner pickaxe (also from wildstacker) and placed down again

**Comment by OmerBenGera** [comment]
You cant use the spawners system if you disable it in your config. Get a plugin that lets you place custom spawners.
This is not a bug.
