### ISSUE TITLE
Hatching turtle eggs

### ISSUE THREAD

**Issue by tncc2k** [BG-Software-LLC/WildStacker#328]
### Minecraft's Version

Spigot 1.16.5

### Plugin's Version

WildStacker v3.6.0-DEVb141

### Describe the bug

When the turtle eggs hatch, the console shows an error

### To Reproduce

https://hastebin.com/lewiyisado.properties

### Additional Information

https://user-images.githubusercontent.com/77291313/133894739-219ef56d-6cfe-4081-9b11-05182486d986.mp4

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
