### ISSUE TITLE
Large Server lag / ram issue

### ISSUE THREAD

**Issue by RhinoCD** [BG-Software-LLC/WildStacker#329]
### Minecraft's Version

1.17.1 - git-Airplane-86 (MC: 1.17.1)

### Plugin's Version

WildStacker-b209.jar

### Describe the bug

Wild Stacker causing huge amounts of lag to server, when I also remove the plugin with plugman, the server ram plummeted to 6 from 8 and has just been causing a huge amount of server lag

### To Reproduce

put wild stacker in plugins folder

https://spark.lucko.me/vNdGNrmq9l

I turned on timings and after a 1 minute I disabled wild stacker and you can see the tps change from 6 to 20 really quickly 
https://timings.aikar.co/?id=e6e558f4ff124d10a3a65fd40f7e320b

**Comment by OmerBenGera** [comment]
Send me a spark profiler, as Timings isnt helpful because I cant know what the issue exactly is.

**Comment by RhinoCD** [comment]
is this not the profiler? https://spark.lucko.me/vNdGNrmq9l

**Comment by OmerBenGera** [comment]
> 
> 
> is this not the profiler? https://spark.lucko.me/vNdGNrmq9l

that's great, I missed it in the first place, that's why I deleted my comment.

**Comment by RhinoCD** [comment]
oh okay! <3

**Comment by OmerBenGera** [comment]
Latest dev build should do be better.
