### ISSUE TITLE
item pickup event works in vanish even if it shouldnt

### ISSUE THREAD

**Issue by TizoCraft** [BG-Software-LLC/WildStacker#333]
### Minecraft's Version

patched_1.17.1.jar:git-Purpur-1374

### Plugin's Version

Dev builds
#211 20/09/2021 12:59:28

### Describe the bug

normally in vanish i cant pick up items but since i use ws i can...

### To Reproduce

install a vanish plugin (i use supervanish) and pick up a item while in vanish

### Additional Information

before i used this plugin i couldnt pick up items if im in vanish now with wildstacker i can pick them up... (using supervanish as vanish plugin) would be cool if u can make it so its not possible to pick up items in vanish

**Comment by OmerBenGera** [comment]
Your vanish plugin needs to cancel AttemptPlayerPickupEvent so it will work.
