### ISSUE TITLE
lava/water bucket stacking still works in chests

### ISSUE THREAD

**Issue by TizoCraft** [BG-Software-LLC/WildStacker#335]
### Minecraft's Version

git-Purpur-1393 (MC: 1.17.1)

### Plugin's Version

Dev build
#211 

### Describe the bug

so i enabled `  fix-stack: true` so players cant stack bukkits etc anymore and it works all fine but in chests buckets are still stackable

### To Reproduce

get a chest and some buckets and try stacking them

### Additional Information

fix thisssssssssssssss

**Comment by OmerBenGera** [comment]
How fix-stack is related to that?
Disable buckets-stacking if you want to disable the ability to stack buckets (only water & lava, regular buckets will always be stackable)
