### ISSUE TITLE
invulnerably villager

### ISSUE THREAD

**Issue by TizoCraft** [BG-Software-LLC/WildStacker#337]
### Minecraft's Version

git-Purpur-1393 (MC: 1.17.1)

### Plugin's Version

Dev builds
#211 

### Describe the bug

you can create a villager which cant be hittet/die

### To Reproduce

use my config spawn 16 villager so they all stack in one and then place a job for them and wait for them to get the job now kill all the last one should survive and is unkillable

**Comment by TizoCraft** [comment]
Config: https://workupload.com/file/HA2jnWgvyAa

**Comment by TizoCraft** [comment]
also had the same problem with a enderman farm

**Comment by OmerBenGera** [comment]
It works fine for me.
Try replicating it on a server with only WildStacker installed.
