### ISSUE TITLE
[WildStacker Issue] Problem with AdvancedEnchantment Enchants

### ISSUE THREAD

**Issue by Starkenz** [BG-Software-LLC/WildStacker#343]
### Minecraft's Version

1.8.8 Latest PaperMC

### Plugin's Version

WildStacker b217

### Describe the bug

In AdvancedEnchantment, there is Inquisitive enchant that gets extra xp from killing mobs.  But when using WildStacker, i am not getting exp or getting extra xp. But strange one is: I used other stacking plugin, it works correctly like getting extra xp and not losing xp. So i thought it was either AE or WildStacker's issue.

### To Reproduce

Here's the video and extra information on description:
https://youtu.be/lhEBL3AEM2g

### Additional Information

This is the different plugin that i tested. Make sure you first watched video that above.
https://youtu.be/1zturIw4YUA

WildStacker config.yml:
https://hastebin.com/liqinubaki.yaml

**Comment by OmerBenGera** [comment]
It depends on how they implement it. If they use EntityDeathEvent and set the EXP there, it will work as it should.
Send GC this issue so he can respond to it.

**Comment by OmerBenGera** [comment]
It seems like GC is not responding, I can't really do anything related to that.
I am keeping this opened so he can reply, hopefully soon.

**Comment by dro1d-89o** [comment]
> It seems like GC is not responding, I can't really do anything related to that. I am keeping this opened so he can reply, hopefully soon.

[GC's Reply](https://github.com/GC-spigot/AdvancedEnchantments/issues/2475#issuecomment-981685280)

**Comment by OmerBenGera** [comment]
I am closing this as GC hasn't responded here and tbh he has just vanished.
If he replies I will reopen it.
