### ISSUE TITLE
Wildstacker doesn't support hexacolor name

### ISSUE THREAD

**Issue by Eliott79** [BG-Software-LLC/WildStacker#353]
### Minecraft's Version

1.16.4

### Plugin's Version

3.6.0-DEVb217

### Describe the bug

WildStacker doesn't support Hexacolor name for item on the floor 

![image](https://user-images.githubusercontent.com/90210037/137534854-a5a87158-43fa-482d-8764-a7419cf0b2b5.png)
![image](https://user-images.githubusercontent.com/90210037/137534878-fb49899e-c9ae-4f8e-8656-dbb034439d26.png)

### To Reproduce

Make an item with an hexacolor name and drop it on the floor

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
