### ISSUE TITLE
virtual item entity cannot be deleted (Reduces TPS)

### ISSUE THREAD

**Issue by tncc2k** [BG-Software-LLC/WildStacker#354]
### Minecraft's Version

PaperMC 1.12.2

### Plugin's Version

WildStacker-b217
tried with: wildtack 3.6.0 06/19/2021 13:06:21
still having this problem

### Describe the bug

Does not completely remove the item stack on the ground, although the image shows it is deleted
Tried with other plugins (stack) not having this problem

### To Reproduce

Default config.yml configuration

### Additional Information

The end of the video mentions the reduction of TPS (alarm) due to too many virtual entities on the ground that cannot be completely removed.
I have tested with other stack plugin which does not have this error at all except wildstack.
Sorry that the video is about 3 minutes long and can't be posted here

Link: https://www.youtube.com/watch?v=2h9_yFvyz4o

**Comment by OmerBenGera** [comment]
I still can't replicate it.
Mind uploading your config to pastebin?

**Comment by tncc2k** [comment]
paper-1.12.2-1618                 (default config)
Plugin:
WildStacker-3.6.1-b232         (default config)
EssentialsX-2.19.0                  (default config)
EssentialsXSpawn-2.19.0       (default config)
[everything runs with a default config]
>>>> Use the command: /killall all (essentials to check)

https://pastebin.com/gvAvpDNY     (default config WildStacker-3.6.1-b232 )

Note that the higher the "fortune" enchantment, the higher the chance of appearing the entity that cannot be erased
low enchant "fortune" still appears but less, if the server runs for a long time, it will cause a drop in tps
>>virtual entity cannot be deleted:
- can be removed by: /stop and turn on the server

**Comment by tncc2k** [comment]
to know the exact virtual entity that cannot be deleted, you should disable mobs spawning to make it easier to check
/gamerule doMobSpawning false
and create a new world
server.properties
level-type=FLAT

**Comment by tncc2k** [comment]
I recorded the most detailed installation video (download paper + plugin) "Paper" + "Plugin" + "test error 1 more time"
The video is about 7 minutes thick, hope you can watch it
Use "Settings (Youtobe Play Speed)" to not lose time
Link: https://www.youtube.com/watch?v=vs-6W5mIIcc

**Comment by OmerBenGera** [comment]
> I recorded the most detailed installation video (download paper + plugin) "Paper" + "Plugin" + "test error 1 more time" The video is about 7 minutes thick, hope you can watch it Use "Settings (Youtobe Play Speed)" to not lose time Link: https://www.youtube.com/watch?v=vs-6W5mIIcc

I will look into it this weekend

**Comment by OmerBenGera** [comment]
I could replicate the issue.

**Comment by OmerBenGera** [comment]
Fixed in latest build
