### ISSUE TITLE
Duplication on cow

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#358]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b222

### Describe the bug

If you shears a stacked mushroom cow, it will spawn a stack of cow, instead of a single cow (or it should convert all the stack into a cow stack)

### To Reproduce

https://youtu.be/TmW_jRJVn0Q?t=47

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
Let me know if it works for you.

**Comment by WarnDa** [comment]
fixed !
