### ISSUE TITLE
java.util.ConcurrentModificationException, Error while calculating drops,  Could not pass event EntityDamageByEntityEvent to other plugins

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#361]
### Minecraft's Version

1.16.5

### Plugin's Version

b224

### Describe the bug

spamming error

these 3 error comes in same time
java.util.ConcurrentModificationException,
 Error while calculating drops 
Could not pass event EntityDamageByEntityEvent to other plugins, including wildstacker, mcmmo, AE

updating from B198 , in version b198 don't have these all problems.

### To Reproduce

seems trigger when player having other plugin's damage skill, damaging mobs

i have advanced enchantment and mcmmo

may related to #269  

### Additional Information

log:
https://paste.gg/p/anonymous/1664de8ea66d4735ba26376f570c5fd3

**Comment by hkkongou** [comment]
now i am testing the build in my live server, not crashing which is good, but still have exception , related to looting seems like 
![image](https://user-images.githubusercontent.com/61608872/139516803-d9adb04c-d4d0-43d3-9d53-7152c69c4965.png)

**Comment by OmerBenGera** [comment]
Latest build should fix the issue.
I am closing this for now :)
