### ISSUE TITLE
[BUG] problem with mypet

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#362]
### Minecraft's Version

1.16.5 tuinity

### Plugin's Version

dev 224

### Describe the bug

when a pet is strong enough to kill mobs spawned by ws spawners with one hit a bug occurs where the mobs become immortal and with a constant death animation

### To Reproduce

set damage of a pet [MYPET plugin] of 50 and let them kill a mob

### Additional Information

BEFORE
![2021-10-24_18 27 50](https://user-images.githubusercontent.com/85011614/138603342-ab5cf140-cef0-4d28-9fc7-293ba905db1d.png)
AFTER
![2021-10-24_18 27 58](https://user-images.githubusercontent.com/85011614/138603352-1fd45441-66d8-4e5e-9dda-f8db86033c1b.png)

**Comment by OmerBenGera** [comment]
this folder doesn't exist.

**Comment by kedavlar** [comment]
![pet](https://user-images.githubusercontent.com/85011614/139519841-89ce0868-2523-426f-a30a-55beaa42e0d8.PNG)

**Comment by OmerBenGera** [comment]
I tested the issue and it seems to work fine for me.
When pets kill mobs, they die as they should.
Try disabling "spawn-corpse", let me know if it helps.

**Comment by kedavlar** [comment]
you need to upgrade pet until they one-shoot the mobs. Disabling spawn-corpe dosent change the problem :/

**Comment by OmerBenGera** [comment]
> 
> 
> you need to upgrade pet until they one-shoot the mobs. Disabling spawn-corpe dosent change the problem :/

How do I upgrade the pet?

**Comment by kedavlar** [comment]
./petadmin exp 93 with my config , if it correct u can see 30 damage in /petinfo command

**Comment by OmerBenGera** [comment]
It only got 4.5 damage
Jesus this plugin is so broken or I am doing something wrong

**Comment by kedavlar** [comment]
do /pcst and select pvp. This pvp is the one i send before in skilltree file: PvP.st.sjon

**Comment by OmerBenGera** [comment]
> 
> 
> do /pcst and select pvp. This pvp is the one i send before in skilltree file: PvP.st.sjon

Already done that.

**Comment by OmerBenGera** [comment]
Nvm, it's called "/pet" and not PvP
My bad.

**Comment by kedavlar** [comment]
sorry, it's just that I have eliminated the other skills and I only have this one to choose from

**Comment by OmerBenGera** [comment]
I could replicate the issue

**Comment by OmerBenGera** [comment]
Fixed in latest build
