### ISSUE TITLE
Disabling stacked entities causes some mobs to have too much health

### ISSUE THREAD

**Issue by JasonHorkles** [BG-Software-LLC/WildStacker#366]
### Minecraft's Version

This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
You are running the latest version
Previous version: git-Paper-279 (MC: 1.17.1)

### Plugin's Version

WildStacker 3.6.0-DEVb227

### Describe the bug

Some mobs (primarily the Husk) will have too much health when spawned when mob stacking is disabled

### To Reproduce

Disable `entities.enabled` in the config, reload the plugin, and try to kill a Husk

### Additional Information

Seems to happen most with the Husk but players have reported it happening with other entities too on occasion (see #359 & https://github.com/SilverstoneMC/Silverstone/issues/67)

**Comment by Skizzles** [comment]
[22:07:43] [Server thread/ERROR]: (net.minecraft.world.entity.EntityLiving:1294) [NAN-HEALTH] 30dd2468-64cd-4f14-80a8-d622498006e2 had NaN health set

Able to confirm this happening regardless of entity stacking enabled or not.

**Comment by OmerBenGera** [comment]
> [22:07:43] [Server thread/ERROR]: (net.minecraft.world.entity.EntityLiving:1294) [NAN-HEALTH] 30dd2468-64cd-4f14-80a8-d622498006e2 had NaN health set
> 
> Able to confirm this happening regardless of entity stacking enabled or not.

Did you just try to kill a husk?

**Comment by Skizzles** [comment]
> > [22:07:43] [Server thread/ERROR]: (net.minecraft.world.entity.EntityLiving:1294) [NAN-HEALTH] 30dd2468-64cd-4f14-80a8-d622498006e2 had NaN health set
> > Able to confirm this happening regardless of entity stacking enabled or not.
> 
> Did you just try to kill a husk?

This was with a zombie in my testing.

**Comment by OmerBenGera** [comment]
> > > [22:07:43] [Server thread/ERROR]: (net.minecraft.world.entity.EntityLiving:1294) [NAN-HEALTH] 30dd2468-64cd-4f14-80a8-d622498006e2 had NaN health set
> > > Able to confirm this happening regardless of entity stacking enabled or not.
> > 
> > 
> > Did you just try to kill a husk?
> 
> This was with a zombie in my testing.

It makes no sense that you get that warning everytime you kill a mob, no matter what the status of stacked-entities is...

**Comment by OmerBenGera** [comment]
I could replicate the issue tho, it takes ages to kill husks, and for no reason

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.

**Comment by JasonHorkles** [comment]
Seems to be fixed, I'll re-open the issue if I come across any further problems

**Comment by brasilcraft54** [comment]
I am having this problem I am using the version, WildStacker-3.6.1-b238.jar and Purpur Last Version, this happened when I disabled some stack mobs.

my config: https://pastebin.com/24ZA7tpe 

console: https://prnt.sc/22yw9g5

**Comment by OmerBenGera** [comment]
> I am having this problem I am using the version, WildStacker-3.6.1-b238.jar and Purpur Last Version, this happened when I disabled some stack mobs.
> 
> my config: https://pastebin.com/24ZA7tpe
> 
> console: https://prnt.sc/22yw9g5

Open a new issue describing the bug you mention.
