### ISSUE TITLE
PreSpawnerSpawnEvent error

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/WildStacker#367]
### Minecraft's Version

Purpur 1.17.1

### Plugin's Version

v3.6.0-DEVb227

### Describe the bug

Error occuring in console occasionally, sometimes its sent multiple times in a short burst sometimes it's only sent here and there:
[PreSpawnerSpawnEvent_Error.txt](https://github.com/BG-Software-LLC/WildStacker/files/7449234/PreSpawnerSpawnEvent_Error.txt)

### To Reproduce

Unsure, Skizz asked me to report it as it was happenning before along with a spawnerspawnevent error. The spawnerspawnevent error is fixed now but now this one still shows up

**Comment by Skizzles** [comment]
Can confirm this bug, effects spawners and also prevents wildtools crowbar from working etc.

https://paste.skizzles.me/qetagewega.properties

Added a pastebin for you Omer.

**Comment by OmerBenGera** [comment]
I can't replicate the issue using latest WildStacker and `git-Purpur-1423 (MC: 1.17.1)`

**Comment by Skizzles** [comment]
some weird issue with Purpur that is fixed now.
