### ISSUE TITLE
"Not enough space to spawn entity" when there's more than enough space

### ISSUE THREAD

**Issue by castiel01x** [BG-Software-LLC/WildStacker#368]
### Minecraft's Version

Purpur 1.16.5

### Plugin's Version

WildStacker-b227

### Describe the bug

spawners don't work when there's more than enough space for them to spawn

https://imgur.com/a/cRyOnWC

### To Reproduce

I'm not quite sure whats causing it but I assume its probably because of purpur since I didn't have this issue when I used paper

**Comment by OmerBenGera** [comment]
Make sure you override the spawning conditions of these mobs, as many mobs cannot spawn in mid-air in latest versions of the game.
Let me know if it helped.

**Comment by castiel01x** [comment]
turned out to be another plugin stopping mobs from spawning, very sorry about this
