### ISSUE TITLE
Lootable issue on baby pigman

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#369]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b227

### Describe the bug

In the lootable "zombie_pigman.json" I set :
> "dropEquipment": false,

To avoid pigman dropping golden sword. It works, except on baby pigman, they still drop their equipement.
There is no file for the baby pigman.

### To Reproduce

Add to zombie_pigman
> "dropEquipment": false

And try to kill baby pigman

**Comment by OmerBenGera** [comment]
Create manually a file for baby pigmans - its name should be `zombie_pigman_baby.json` if I am not wrong, and then set dropEquipment in this file to false.

**Comment by OmerBenGera** [comment]
I am keeping this opened so I remember to patch missing loot tables of baby variants of mobs

**Comment by OmerBenGera** [comment]
I fixed baby loot table variants not generated by default.
