### ISSUE TITLE
Wild Stacker Precious Stones error!

### ISSUE THREAD

**Issue by Areanydd** [BG-Software-LLC/WildStacker#372]
### Minecraft's Version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker version 3.6.0-DEVb227

### Describe the bug

Your plugin it s not compatible with Precious Stones..can i destroy all players spawners without heave allow in their protection.

### To Reproduce

can i destroy all players spawners without heave allow in their protection.

**Comment by OmerBenGera** [comment]
If PreciousStone don't disallow interacting with spawners, for example, players can still open the break menu and break spawners.
I recommend disabling this feature if it doesn't fit to your server.
