### ISSUE TITLE
Error when with plugin when spawners try to spawn

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#374]
### Minecraft's Version

git-Tuinity-17 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2310a94 on HEAD)
Unknown version

### Plugin's Version

wildstacker 3.6.1

### Describe the bug

Spawners wont spawn. COnstant error thrown in console.

I am using Epicspawners, 7.1.2

Not sure if you can tell via errors if its anything to do with these two plugins.

I have not changed config, just replaced .jar

I was previously using devbuild: b217 wildstacker, and didnt have any issues.

### To Reproduce

Place spawner down, mob wont spawn (cow, pig etc)  the only mob that i cna get spawning is a chicken :D

### Additional Information

https://pastebin.com/mc4JNWtX

**Comment by OmerBenGera** [comment]
Use latest version of Tuinity / Paper for 1.17.1.
