### ISSUE TITLE
Dupe glitch with barrels on purpur.

### ISSUE THREAD

**Issue by bpx573** [BG-Software-LLC/WildStacker#376]
### Minecraft's Version

1.17.1 https://gyazo.com/a1305561468f682e50a2a35427261a1b

### Plugin's Version

3.6.1

### Describe the bug

When relogging with a stack already in your inventory, it allows you to place infinite items because it doesnt take the stack away from you. 

### To Reproduce

Logged off for like 4-5 hours. came back and wanted to stack more items for item levels. it will stack but the barrel will not take the block from me, allowing me to "infinitely" add in more blocks

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed.

**Comment by bpx573** [comment]
It worked it happened when placing a solid block that's stacked on top.

**Comment by OmerBenGera** [comment]
> It worked it happened when placing a solid block that's stacked on top.

I don't understand.
Mind taking a video of the issue?

**Comment by OmerBenGera** [comment]
Any news regarding this?
