### ISSUE TITLE
Breeding get issue with +64 animas

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#377]
### Minecraft's Version

1.16.5

### Plugin's Version

b235

### Describe the bug

If you got "smart-breeding:" and more than 64 animals stack, if you try to breed them, it will take only 64 food in your inventory, so reproduce 64 animals, and you can't reproduce the animals left in the stack.

So if you got 128 cow, it takes 64 wheat, and reproduce only 64 cow.

### To Reproduce

- Set smart-breeding: true
- spawn 128 cow
- take 128 wheat
- reproduce them

It will only take 64 wheat and reproduce 64 cow (so spawn 32 baby)

**Comment by OmerBenGera** [comment]
Fixed in latest build
