### ISSUE TITLE
(net.minecraft.world.entity.EntityLiving:1294) [NAN-HEALTH]

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#381]
### Minecraft's Version

git-Paper-336 (MC: 1.17.1

### Plugin's Version

WildStacker-3.6.1-b235.jar

### Describe the bug

when a player tries to place another mobspawner next to another one, it generates this error in the console. 
I forgot to mention that the spawner doesn't group so it generates this error but if I use the plugman and remove the wildstacker and add it again everything works again.
   https://pastebin.com/iJwq3ZJB

### To Reproduce

by placing one mobspawner next to the other.

**Comment by OmerBenGera** [comment]
Are you sure it's because you place spawners next to each other?
Does it start to happen if you do so?
Because this warning is because invalid health is set to entities, and I don't see how it's related to spawners...

**Comment by brasilcraft54** [comment]
> Are you sure it's because you place spawners next to each other? Does it start to happen if you do so? Because this warning is because invalid health is set to entities, and I don't see how it's related to spawners...

yes when I put them they don't group and give this error, but if I get OP I can group and don't get this error, any suggestions on how to fix this?

**Comment by OmerBenGera** [comment]
> > Are you sure it's because you place spawners next to each other? Does it start to happen if you do so? Because this warning is because invalid health is set to entities, and I don't see how it's related to spawners...
> 
> yes when I put them they don't group and give this error, but if I get OP I can group and don't get this error, any suggestions on how to fix this?

Mind taking a video of it?

**Comment by brasilcraft54** [comment]
> > > Are you sure it's because you place spawners next to each other? Does it start to happen if you do so? Because this warning is because invalid health is set to entities, and I don't see how it's related to spawners...
> > 
> > 
> > yes when I put them they don't group and give this error, but if I get OP I can group and don't get this error, any suggestions on how to fix this?
> 
> Mind taking a video of it?

I really did the test and it's not that but something is preventing them from grouping what can it be?

**Comment by brasilcraft54** [comment]
[12:49:32 ERROR]: [STDERR] [net.minecraft.world.entity.EntityLiving] [NAN-HEALTH] ee30483e-cd27-450e-8371-78a9290018e0 had NaN health set

**Comment by brasilcraft54** [comment]
What happens is that it gives this error and no one can group spawners, but I can if I have OP.

**Comment by OmerBenGera** [comment]
It sounds like your players are lacking the permission to stack spawners, and it has nothing to do with that warning.
If you use LuckPerms, you can find which permissions they lack by using their verbose feature, and then give them the permission.

**Comment by brasilcraft54** [comment]
> It sounds like your players are lacking the permission to stack spawners, and it has nothing to do with that warning. If you use LuckPerms, you can find which permissions they lack by using their verbose feature, and then give them the permission.

but I didn't change anything, I've had the server open for 4 months and never had this problem, I just updated the plugin and this happened and yes they have the wildstacker.nextplace permission, it says in luckperms "[LP] default already has wildstacker.nextplace set in context global".

**Comment by brasilcraft54** [comment]
> It sounds like your players are lacking the permission to stack spawners, and it has nothing to do with that warning. If you use LuckPerms, you can find which permissions they lack by using their verbose feature, and then give them the permission.

I made a video I could only group when I put it in creative mode even with OP I couldn't group.  https://youtu.be/plV5o82wZOo

**Comment by OmerBenGera** [comment]
Try replicating it on another server where you only have WildStacker installed, as it works fine for me.

**Comment by brasilcraft54** [comment]
> 

I think this happened when I put in spigotguard

**Comment by OmerBenGera** [comment]
> > 
> 
> I think this happened when I put in spigotguard

What is SpigotGuard?

**Comment by brasilcraft54** [comment]
> > > 
> > 
> > 
> > I think this happened when I put in spigotguard
> 
> What is SpigotGuard?

is a plugin that owns the Aegis fork.

**Comment by brasilcraft54** [comment]
confirmed is spigotguard, if you want you can close this conversation and thank you for answering <3

**Comment by OmerBenGera** [comment]
You welcome :)
