### ISSUE TITLE
[WildStacker] Upgrades do not work, with the correct config

### ISSUE THREAD

**Issue by 0noca** [BG-Software-LLC/WildStacker#386]
### Minecraft's Version

git-Paper-388 ( MC: 1.17.1) (Git: 22aaf91) - latest version of paperz

### Plugin's Version

WildStacker-3.6.1

### Describe the bug

Spawner upgrades do not work, I've completed the config, checked it with YAML, also your discord moderator, but it was correct, also did a server restart, but it didn't apply the changes. I can upgrade the spawners, but it doesn't upgrade the timing, spawn count etc.

WildStacker Config -
https://www.toptal.com/developers/hastebin/jadakogihi.yaml

### To Reproduce

Complete the upgrader config
Restart your server

Check statistics on the spawner/ mobs spawned

Doesn't change/ doesn't spawn more mobs

### Additional Information

![Screenshot_145](https://user-images.githubusercontent.com/71095225/144040834-e1c86cd9-bb96-4744-9c98-a1ce453afcff.png)
![Screenshot_146](https://user-images.githubusercontent.com/71095225/144040837-8865df35-cb88-4dd6-b675-ea5b8df41260.png)

**Comment by 0noca** [comment]
Translation to Upgrades: 
Kiirus - Spawn Delay Range
Tekkimis Kogus - Spawn Count
Mängija kaugus spawnerist - Required Player Range

**Comment by OmerBenGera** [comment]
Fixed in latest build
