### ISSUE TITLE
Random Timeouts 

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildStacker#387]
### Minecraft's Version

BeerSpigot Premium - 1.8.8

### Plugin's Version

WildStacker-3.6.1-b236

### Describe the bug

Random Lag spikes, which according to the spark report I have taken it shows that wildstacker is causing the majority of the lag on my server. 

### To Reproduce

AFK near over 2.3 billion spawners

### Additional Information

Here is my current config I'm using https://pastebin.com/Sn4Ua2Mx
Here is the spark report that i took https://spark.lucko.me/VicEo6HyHG

**Comment by OmerBenGera** [comment]
```  # How much time should be passed between auto-stacking? (in ticks)
  # If you wish to disable the auto-stacking task, set the stack-interval to 0.
  # By default, all items are stacked once, when they spawn.
  stack-interval: 1```
  Increase this value to 200, along side of this one:
  ```  # How much time should be passed between auto-stacking? (in ticks)
  # If you wish to disable the auto-stacking task, set the stack-interval to 0.
  stack-interval: 1```
