### ISSUE TITLE
Unsubscribe from `PlayerAttemptPickupItemEvent`

### ISSUE THREAD

**Issue by SaFiKiK** [BG-Software-LLC/WildStacker#390]
### Minecraft's Version

git-Paper-391 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e73355 on ver/1.17.1)

### Plugin's Version

WildStacker 3.6.1 build 238

### Describe the bug

Most plugins use `EntityPickupItemEvent` to handle players picking up items. This plugin is subscribed to one Paper-only event (`PlayerAttemptPickupItemEvent`) which break most plugins which use only the Bukkit API. For example, this bug can be reproduced with PlotSquared.

### To Reproduce

1. Install PlotSquared latest
2. Install WildStacker latest
3. Create plot world, enable drop-protection flag for plots
4. Try picking up items from plots which belong to other players
5. Item will be picked up as `EntityPickupItemEvent` is never fired

### Additional Information

I don't think that extra checks for [onEntityPickup](https://github.com/BG-Software-LLC/WildStacker/blob/48ef3cfb370211c0ee41d0b1282afead96f61793/src/main/java/com/bgsoftware/wildstacker/listeners/ItemsListener.java#L142) should be made due to the fact that no extra checks are made in `PlayerAttemptPickupItemEvent`. Just unsubscribe and remove [unneeded checks](https://github.com/BG-Software-LLC/WildStacker/blob/48ef3cfb370211c0ee41d0b1282afead96f61793/src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java#L77) will, probably, work?

**Comment by SaFiKiK** [comment]
Oh, well, just found out that new updates are still supporting older versions of Miencraft, so, probably, just check for MC version and do not subscribe if MC Version>= 1.13 (It should be 1.13 when `PlayerPickupItemEvent` became deprecated)

**Comment by OmerBenGera** [comment]
Check out latest build, let me know if it works

**Comment by SaFiKiK** [comment]
Build 241 - still able to pick up

**Comment by SaFiKiK** [comment]
Build 241 - fixed
