### ISSUE TITLE
Can't recover my spawner when i broke it

### ISSUE THREAD

**Issue by WatchesWolf** [BG-Software-LLC/WildStacker#394]
### Minecraft's Version

My server is running Purpur version git-Purpur-1171 (MC:1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

3.6.1

### Describe the bug

When i broke a spawner with my silk touch pickaxe or without silk touch

I don't get it in my inventory or on the ground

PS : Ill try these permissions :

wildstacker.nosilkdrop
wildstacker.silktouch

### To Reproduce

- Place a spawner (Any type)

- Get a pickaxe silk touch or not

- Try to add the permission "wildstacker.nosilkdrop" or "wildstacker.silktouch" if you want

- And finally break the spawner.. you will see you don't get it ^^'

**Comment by OmerBenGera** [comment]
Upload your config please to pastebin and send it here.

**Comment by WatchesWolf** [comment]
> Upload your config please to pastebin and send it here.

https://pastebin.com/L6Uk9zC3

**Comment by OmerBenGera** [comment]
It works fine for me using a silktouch pickaxe - I get it straight into my inventory.

**Comment by WatchesWolf** [comment]
> It works fine for me using a silktouch pickaxe - I get it straight into my inventory.

Is there a plugin that doesn't work well with WildStacker?

**Comment by OmerBenGera** [comment]
> > It works fine for me using a silktouch pickaxe - I get it straight into my inventory.
> 
> Is there a plugin that doesn't work well with WildStacker?

Try it without any plugins but WildStacker so we can understand if the issue comes from WildStacker or not.

**Comment by WatchesWolf** [comment]
> > > It works fine for me using a silktouch pickaxe - I get it straight into my inventory.
> > 
> > 
> > Is there a plugin that doesn't work well with WildStacker?
> 
> Try it without any plugins but WildStacker so we can understand if the issue comes from WildStacker or not.

I have do it, but ws still not works, does a version is recommanded for Java 8 ?

**Comment by OmerBenGera** [comment]
> > > > It works fine for me using a silktouch pickaxe - I get it straight into my inventory.
> > > 
> > > 
> > > Is there a plugin that doesn't work well with WildStacker?
> > 
> > 
> > Try it without any plugins but WildStacker so we can understand if the issue comes from WildStacker or not.
> 
> I have do it, but ws still not works, does a version is recommanded for Java 8 ?

It shouldnt matter.
Are you OP and you break it with a silk touch?
Also, are you using Paper/Spigot?

**Comment by WatchesWolf** [comment]
> > > > > It works fine for me using a silktouch pickaxe - I get it straight into my inventory.
> > > > 
> > > > 
> > > > Is there a plugin that doesn't work well with WildStacker?
> > > 
> > > 
> > > Try it without any plugins but WildStacker so we can understand if the issue comes from WildStacker or not.
> > 
> > 
> > I have do it, but ws still not works, does a version is recommanded for Java 8 ?
> 
> It shouldnt matter. Are you OP and you break it with a silk touch? Also, are you using Paper/Spigot?

Yes i am op and i am on purpur the version is on the top

**Comment by OmerBenGera** [comment]
> > > > > > It works fine for me using a silktouch pickaxe - I get it straight into my inventory.
> > > > > 
> > > > > 
> > > > > Is there a plugin that doesn't work well with WildStacker?
> > > > 
> > > > 
> > > > Try it without any plugins but WildStacker so we can understand if the issue comes from WildStacker or not.
> > > 
> > > 
> > > I have do it, but ws still not works, does a version is recommanded for Java 8 ?
> > 
> > 
> > It shouldnt matter. Are you OP and you break it with a silk touch? Also, are you using Paper/Spigot?
> 
> Yes i am op and i am on purpur the version is on the top

Thats weird..
I will try to test it again

**Comment by WatchesWolf** [comment]
> > > > > > > It works fine for me using a silktouch pickaxe - I get it straight into my inventory.
> > > > > > 
> > > > > > 
> > > > > > Is there a plugin that doesn't work well with WildStacker?
> > > > > 
> > > > > 
> > > > > Try it without any plugins but WildStacker so we can understand if the issue comes from WildStacker or not.
> > > > 
> > > > 
> > > > I have do it, but ws still not works, does a version is recommanded for Java 8 ?
> > > 
> > > 
> > > It shouldnt matter. Are you OP and you break it with a silk touch? Also, are you using Paper/Spigot?
> > 
> > 
> > Yes i am op and i am on purpur the version is on the top
> 
> Thats weird.. I will try to test it again

Ok, thank's ill wait you

**Comment by OmerBenGera** [comment]
I tested it again and it works fine for me :/

**Comment by WatchesWolf** [comment]
> I tested it again and it works fine for me :/

What is your java version 
And
Does wildstacker have unspported plugins ?

**Comment by OmerBenGera** [comment]
> > I tested it again and it works fine for me :/
> 
> What is your java version And Does wildstacker have unspported plugins ?

This has nothing to do with the Java version you use.
Also, I told you to try it without any other plugins installed - what's the matter if there's any unsupported plugins, if you told me you tested it with only WildStacker installed and that it didn't work for you?

**Comment by OmerBenGera** [comment]
Have you tried it?
