### ISSUE TITLE
Stacked Turtles laying an egg cause an error

### ISSUE THREAD

**Issue by 0noca** [BG-Software-LLC/WildStacker#395]
### Minecraft's Version

1.17.1

### Plugin's Version

WildStacker-3.6.1-b238

### Describe the bug

When a stacked turtle lays an egg, the console spams the following error; 

### To Reproduce

Get a stacked turtle
Get it to lay an egg
Error comes

### Additional Information

https://www.toptal.com/developers/hastebin/goxapexeti.properties <-- Error log

https://www.toptal.com/developers/hastebin/yufocekowe.yaml <-- Updated config, after I added turtle to stacking blacklist.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
