### ISSUE TITLE
Issue with Kill

### ISSUE THREAD

**Issue by KibbaXx** [BG-Software-LLC/WildStacker#396]
### Minecraft's Version

1.8.8

### Plugin's Version

3.6.1

### Describe the bug

When other players kill stacked mobs they instant kill the whole stack and drop 3x or 2x of their drop of the stack where the stack is 32 or more but in the config i dont have anything releated to instant killing if i do i can single kill the stack

### To Reproduce

I don't know what it might be

**Comment by OmerBenGera** [comment]
Check if the entities are actually stacked using `/ws inspect` and not by looking at their nametag.

**Comment by OmerBenGera** [comment]
I tested it and it seems to work fine for me.
Have you tested what I wrote above?

**Comment by KibbaXx** [comment]
"Check if the entities are actually stacked using /ws inspect and not by looking at their nametag."
- Says the stack amount its a wildstacker spawner

- It works for me to single kill the stack, at other players it instant kill and drops 2-3 drops not like the whole stack drop, it doesnt have any instant kill option or one shot kill if its needed i can send the config
-

**Comment by KibbaXx** [comment]
Now it stopped spawning mobs
i didnt config anything

**Comment by KibbaXx** [comment]
Not spawning witch,zombie,spiders when the zombie spawner start to spawn it spawn chicken

**Comment by KibbaXx** [comment]
I guess its not syncing with ClearLagg plugin well

**Comment by KibbaXx** [comment]
the only config that is enabled in my clearlagg plugin is this
mobspawner:
  enabled: true
  max-spawn: 1
  remove-mobs-on-chunk-unload: false
  and the auto removal

**Comment by OmerBenGera** [comment]
> "Check if the entities are actually stacked using /ws inspect and not by looking at their nametag."
> 
> * Says the stack amount its a wildstacker spawner
> * It works for me to single kill the stack, at other players it instant kill and drops 2-3 drops not like the whole stack drop, it doesnt have any instant kill option or one shot kill if its needed i can send the config

Check the entities, not spawners. Also, if it works for you and not for your players then it might be another plugin conflicting or they kill the entities using other ways. WildStacker doesnt care which player kills an entity, the same algorithm is ran for everyone equally.

**Comment by OmerBenGera** [comment]
> Not spawning witch,zombie,spiders when the zombie spawner start to spawn it spawn chicken

I dont see how its related to WildStacker, but if you believe its another bug, open a new issue and do not mix different bugs on the same issue.
Also, make sure you test it on a server where only WildStacker installed to make sure there are no other plugins that cause it to happen.

**Comment by KibbaXx** [comment]
Listen, it didnt spawn any mobs went to 0seconds and was stuck on it, then i disabled clear lag plugin they started spawning

the only config that is enabled in my clearlagg plugin is this
mobspawner:
enabled: true
max-spawn: 1
remove-mobs-on-chunk-unload: false
and the auto removal

**Comment by KibbaXx** [comment]
Idk whats wrong when i place blaze spawners in the same chunk other spawners stop spawning

**Comment by OmerBenGera** [comment]
Disable this feature, it seems like it prevents spawners from spawning more than one mob... Check if it fixes itself after disabling it.
And again, do not mix bugs on the same issue page.

**Comment by OmerBenGera** [comment]
Any news regarding this?
