### ISSUE TITLE
Item names display incorrect 

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/WildStacker#398]
### Minecraft's Version

1.8.8 mSpigot

### Plugin's Version

3.6.1.237

### Describe the bug

Item names (Dropped items) aren't displaying correctly in-game, seems like capitalized words aren't working correctly 
![image](https://user-images.githubusercontent.com/61563491/146568155-48b9466b-c46c-4709-914a-f8b3ac7caa29.png)

### To Reproduce

'LOG:0': 'Oak Log'
'LOG:1': 'Spruce Log'
'LOG:2': 'Birch Log'
'LOG:3': 'Jungle Log'
'LEAVES:0': 'Oak Leaves'
'LEAVES:1': 'Spruce Leaves'
'LEAVES:2': 'Birch Leaves'
'LEAVES:3': 'Jungle Leaves'

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
