### ISSUE TITLE
Issue with villager geting nerfed even if they are on blacklist

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#399]
### Minecraft's Version

[15:41:51 INFO]: This server is running Purpur version git-Purpur-"4ff0630" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ff0630 on ver/1.17.1)
[15:41:51 INFO]: You are 1 version(s) behind

### Plugin's Version

DEV 224

### Describe the bug

before the updated villagers was not getting nerfed and after the update of spawners override villagers are getting nerfed even is they are on the black list in config here is my config   

nerfed-entities:
    # A list of entities that will be nerfed.
    # If you want all entities to be nerfed, set this to [].
    whitelist: []
    # A list of entities that won't be nerfed.
    blacklist:
    - WITHER
    - VILLAGER
    - MINECART
    - MINECART_CHEST
    - MINECART_COMMAND
    - MINECART_FURNACE
    - MINECART_HOPPER
    - MINECART_MOB_SPAWNER
    - MINECART_TNT
    - HOPPER_MINECART

### To Reproduce

put a spawner of villager nerf all entity except villager and villagers will not move even if you hit them

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Maybe you have nerf-spawner-mobs enabled in your paper's config?

**Comment by amarcais53** [comment]
oh yeah it is
this is weird it was working before im gonna tell you after the daily restart if its fixed

**Comment by OmerBenGera** [comment]
> oh yeah it is this is weird it was working before im gonna tell you after the daily restart if its fixed

It makes sense that it happened before and now it isnt, this is because the spawners-override feature was disabled in 1.17, however I managed to get it back working in this version again.

**Comment by amarcais53** [comment]
ok the issue is fixed thank you for helping
