### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to WildStacker v3.6.1.244

### ISSUE THREAD

**Issue by nurdism** [BG-Software-LLC/WildStacker#400]
### Minecraft's Version

paper 1.18.1 82

### Plugin's Version

WildStacker 3.6.1 b244

### Describe the bug

This error seems to be triggered when a villager attempts to turn into a zombie villager, the villager will not die but the health will reset and [this error will be thrown](https://pastebin.com/5gSS4wEP)

### To Reproduce

Spawn a zombie, name tag the zombie. Spawn a villager, name tag the villager. Set world difficulty to hard to 100% chance a zombie villager. Let the zombie attack the villager. Error is produced

### Additional Information

[config.yml](https://pastebin.com/P4yXDP39)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
