### ISSUE TITLE
NaN issue on llamas from Pinata Party

### ISSUE THREAD

**Issue by crypticfel** [BG-Software-LLC/WildStacker#404]
### Minecraft's Version

This server is running Paper version git-Paper-85 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: df8d28a)

### Plugin's Version

3.6.1. b-241

### Describe the bug

[19:47:45 ERROR]: [STDERR] [net.minecraft.world.entity.EntityLiving] [NAN-HEALTH] 42b0495a-f78c-4af9-8f93-43204be0b2a6 had NaN health set

### To Reproduce

Run PinataParty, summon a party pinata.  You get this error after a few hits and the pinata despawns.  HexedHero, the creator of the plugin, thinks it's y'all.

### Additional Information

https://pastebin.com/S1H1FKcc

**Comment by OmerBenGera** [comment]
The plugin is premium and I can't test it myself.
What is your discord? I'll make a ticket for you so you can send me a copy of the plugin there.

**Comment by crypticfel** [comment]
CrypticFel

**Comment by OmerBenGera** [comment]
I couldn't replicate the issue.
I summoned a few pinatas and hit them all, no warnings or anything like that.

How did you hit the pinatas?

**Comment by crypticfel** [comment]
you need to have a lot of people or make that health really high

**Comment by crypticfel** [comment]
make the health like 100 or higher

**Comment by crypticfel** [comment]
https://pastebin.com/Efs6eK1Q

**Comment by crypticfel** [comment]
that's the config I use
except I usually set the multiply health by players to true

**Comment by OmerBenGera** [comment]
I changed the health to 50, so in total I had to hit the pinata 100 times.
It still worked as intended and no messages appeared.
Are you able to replicate it yourself on a server with only PinataParty and WildStacker installed?

**Comment by Skizzles** [comment]
@crypticfel 

Do you by chance have McMMO installed? Also please answer Omers question above as well when you get the chance.

**Comment by OmerBenGera** [comment]
Any news regarding this?
