### ISSUE TITLE
Stuck in death animation, stack becomes invincible

### ISSUE THREAD

**Issue by dro1d-89o** [BG-Software-LLC/WildStacker#405]
### Minecraft's Version

1.18.1 Paper

### Plugin's Version

dev #244

### Describe the bug

when killing stacked entities they sometimes glitch out and become stuck between frames in their death animation and become invincible, also making it impossible to hit mobs beside them.

### To Reproduce

cram a bunch of stacked entities into a 1x2x1 and start killing them, should happen soon enough
(seems to happen more often when multiple stacks of stacked entities exist)

### Additional Information

below is an image of it happening, it stays like that and is invulnerable, if the player rejoins they go back to a standing animation but are still invulnerable
![2021-12-23_17 51 24](https://user-images.githubusercontent.com/62203146/147303175-a328b930-dfdf-4d80-85a7-9eb34add297b.png)

**Comment by OmerBenGera** [comment]
How are you killing them?
Are there any errors in console?

**Comment by dro1d-89o** [comment]
killing them with a sword, no errors in console

**Comment by OmerBenGera** [comment]
> killing them with a sword, no errors in console

What do you have on your sword?
Any custom enchantments or other things that manipulate vanilla behavior?
Also, are you able to replicate it on another server where only WildStacker is installed?

**Comment by dro1d-89o** [comment]
Advanced Enchants for custom enchants, see img below for what is on the sword.
No, i don't have access to a server where only wildstacker is installed so I cannot test that.

![image](https://user-images.githubusercontent.com/62203146/147342763-50fdd802-a7d9-4f82-98fd-f4f2d078122c.png)

**Comment by OmerBenGera** [comment]
Try it without the custom modifications on the sword, let me know if it fixes itself.

**Comment by OmerBenGera** [comment]
Are you using AdvancedEnchantments by GC?

**Comment by dro1d-89o** [comment]
I apologize it seems I forgot to reply to the last comment, you made, yes it fixed itself after using a sword without enchants, and taking off all effects. Yes I am using Advanced Enchants by GC, I was thinking about submitting a bug report there if this was their problem instead. I chose here first because I wondered if it had something to do with stacked entities dying faster than expected and glitching out somehow.

**Comment by OmerBenGera** [comment]
There is an already opened issue regarding this:
#343 

We are still waiting for a response from GC.
I am closing this and we'll move to the mentioned issue above.

**Comment by dro1d-89o** [comment]
Got it, the issue you mentioned actually got a reply from GC so I've linked that in a comment on there, even though it doesn't help much. I will create a new issue on Advanced Enchants and see if anything gets fixed.
Thanks for your time.
