### ISSUE TITLE
Event spam in console

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#406]
### Minecraft's Version

1.18.1 paper

### Plugin's Version

3.6.1.242

### Describe the bug

Console spams the following error:  

https://pastebin.com/1b6wFiJW

not sure of cause.

### To Reproduce

run paper 1.18.1 with 3.6.1.242 version

### Additional Information

sorrry I cant provide further info, Im not sure how or why it happening

**Comment by OmerBenGera** [comment]
Duplicate of #403
