### ISSUE TITLE
WildStacker spam console

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#407]
### Minecraft's Version

purpur 1.17.1 last version

### Plugin's Version

WildStacker-3.6.1-b238.jar

### Describe the bug

I am having this problem I am using the version, WildStacker-3.6.1-b238.jar and Purpur Last Version, this happened when I disabled some stack mobs.

my config: https://pastebin.com/24ZA7tpe

console: https://prnt.sc/22yw9g5

### To Reproduce

put the mobs in the list that is not to group

**Comment by OmerBenGera** [comment]
You opened an issue about this already:
<https://github.com/BG-Software-LLC/WildStacker/issues/381>

?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response from @brasilcraft54 

If it happens again, please reply to this issue and answer to why did you open a new issue if it was already addressed out?
