### ISSUE TITLE
Mob's name does noot show stack number

### ISSUE THREAD

**Issue by SenPr** [BG-Software-LLC/WildStacker#409]
### Minecraft's Version

Minecraft 1.17.1
Paper 1.17.1 - Build 403

### Plugin's Version

3.6.2 Stable

### Describe the bug

The name of the mob does not change accordingly to the stack if I use the plugin with ProtocolLib lower than 4.8.0
ProtocolLib 4.8.0 is only for 1.18 and I am using 1.17.1, which may be the cause of the issue.

### To Reproduce

Use 3.6.2 WildStacker with ProtocolLib 4.7.0 on a Paper 1.17.1 server

### Additional Information

I downgraded to an older version (3.6.1) before the 1.18 update and it worked fine.

**Comment by OmerBenGera** [comment]
I tested it using WS 3.6.2 and both ProtocolLib 4.7.0-4.8.0 and it seems to work fine for me.
Are you able to replicate it on a server with only these plugins installed?

**Comment by SenPr** [comment]
Tested it on a separate server. Was unable to replicate

For more details heres a list of my plugins:
AdvancedEnchantments, AdvancedReplay*, AureliumSkills, BeastTokens, BeastWithdraw, Citizens, CloudBoosters, CMI, CMILib, CombatLogX, CrazyEnvoy, DeluxeMenus, DeluxeTags, FeatherBoard, floodgate, HolographicDisplays, JetsMinions, JetsRepairTokens, KGenerators, LiteBans, LuckPerms, MoneyPouch, Multiverse-Core, MythicMobs, OldCombatMechanics, Outpost, PlaceholderAPI, PlayerPoints, PlayerVaults, ProtocolLib, ShopGUIPlus, Shopkeepers, SirBlobmanCore (SirBlobmanAPI, XSeries), SkyblockPerms, SkyblockStuff, SpecializedCrates, SuperiorSkyblock2, TAB, TradeSystem, Vault, VoidGen, VoteParty, Votifier, Vouchers, Vulcan, VulcanReplay, WildChests, WildStacker, WildTools, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3

- Tried without HolographicsDisplay & AdvancedReplay
- SkyblockPerms and SkyblockStuff are my own custom plugins which does not use protocollib or wildstacker

**Comment by OmerBenGera** [comment]
It only happens on your own server?

**Comment by SenPr** [comment]
Only happens on the server with the plugins I listed above.
The separate server I tested did not show the bug.

**Comment by OmerBenGera** [comment]
> Only happens on the server with the plugins I listed above. The separate server I tested did not show the bug.

If you use the exact same plugins on another server with default files, it still occurs?
If so, try removing plugins until you find the problematic one.

**Comment by klaidosHka** [comment]
I looked through his plugins, found the same plugins I have, tested each one and the culprit is `MythicMobs`, the config option about it's custom-name has nothing to do either, false/true leads to the same thing, entities names not showing up.

**Comment by SenPr** [comment]
MythicMobs conflict or maybe just MythicMobs itself I guess?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now.
Seemed to be an issue with custom names provider which may have lead to this issue - because MythicMobs is a names-provider as well, the issue occurred when the plugin was installed.
Hopefully it's fixed in latest dev build :)

**Comment by klaidosHka** [comment]
![seems to work](https://media.discordapp.net/attachments/294846257023811586/928644731062329355/unknown.png)
Yep, it works now, thank you ❤️

**Comment by OmerBenGera** [comment]
Sorry about that, at least it works now :)
