### ISSUE TITLE
Mob count doesnt go down after killing mob in stack

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#410]
### Minecraft's Version

1.18.1 R0.1 snapshot

### Plugin's Version

3.6.2

### Describe the bug

When a stack of mobs spawn. eg: 3x zombies.   when a player kills one of the mobs in the stack, the count stays at 3. But the entity has died and drops exp, items. Leaving only 2 zombies in stack. But count still stays 3 until whole stack is killed

### To Reproduce

As described as above

**Comment by OmerBenGera** [comment]
Try replicating the issue on another server where only WS is installed

**Comment by LurgenAU** [comment]
I'm seeing the same issue on my server. Haven't had a chance to verify on a server with just WS installed, but can confirm that killing the right number of mobs in the stack does result in the stack dying so it looks to me like a visual glitch only.

**Comment by OmerBenGera** [comment]
> I'm seeing the same issue on my server. Haven't had a chance to verify on a server with just WS installed, but can confirm that killing the right number of mobs in the stack does result in the stack dying so it looks to me like a visual glitch only.

I need you to try it on a server with only WS installed

**Comment by OmerBenGera** [comment]
@LurgenAU Try latest dev build, let me know if it works.

**Comment by LurgenAU** [comment]
> 

Gave that a shot, no change unfortunately :(

**Comment by TenReeez** [comment]
Same here. Not fixed as of Dev 3.6.2.261

**Comment by OmerBenGera** [comment]
Does it happen when only WildStacker installed?

**Comment by TenReeez** [comment]
The plugin that conflicts, is MCMMO. :/    Of all the plugins, I dont know why it would be this one. How do I proceed?

**Comment by OmerBenGera** [comment]
> The plugin that conflicts, is MCMMO. :/ Of all the plugins, I dont know why it would be this one. How do I proceed?

Disable mob health

**Comment by LurgenAU** [comment]
Disabling the Mob Health Bar in mcMMO does indeed seem to fix the problem. Thanks for the assistance.
