### ISSUE TITLE
WildStacker causes an infinite loop somehow

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#411]
### Minecraft's Version

paper 1.12.2

### Plugin's Version

WildStacker-3.6.1-b249.jar

### Describe the bug

After a lot of digging I finally found out which plugin makes my server basically to an infinite loop twice a day, a restart solves everything, but it is really annoying...
Somehow WildStacker causes this issue, how did I found out? I used plugman to disable WildStacker and wow! Instantly everything was working as it supposed to. I only have thread dumps to show you, because it is pretty hard to replicate this.

### To Reproduce

https://pastebin.com/3q4wTmAT

**Comment by OmerBenGera** [comment]
Find what causes it, as the stack trace means nothing.

**Comment by Superalex0102** [comment]
> Find what causes it, as the stack trace means nothing.

Any ideas how can I achieve that?

**Comment by OmerBenGera** [comment]
> > Find what causes it, as the stack trace means nothing.
> 
> Any ideas how can I achieve that?

Not really, as there are no even signs of WildStacker being the cause from the stack-trace, therefore I can't think about what could cause it to happen.

**Comment by Superalex0102** [comment]
> > > Find what causes it, as the stack trace means nothing.
> > 
> > 
> > Any ideas how can I achieve that?
> 
> Not really, as there are no even signs of WildStacker being the cause from the stack-trace, therefore I can't think about what could cause it to happen.

As I experienced, I took out WildLoaders from the server and everything is working fine now, no need to restart the server every 6-7 hours or so.
So that's explains when I unloaded WildStacker it solved the issue because the loaders were loading the spawners from WildStacker.

**Comment by OmerBenGera** [comment]
> > > > Find what causes it, as the stack trace means nothing.
> > > 
> > > 
> > > Any ideas how can I achieve that?
> > 
> > 
> > Not really, as there are no even signs of WildStacker being the cause from the stack-trace, therefore I can't think about what could cause it to happen.
> 
> As I experienced, I took out WildLoaders from the server and everything is working fine now, no need to restart the server every 6-7 hours or so. So that's explains when I unloaded WildStacker it solved the issue because the loaders were loading the spawners from WildStacker.

How is WildLoaders related to that again?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Superalex0102** [comment]
I'm still trying to debug this, but still I'm having issues and it is definitely an issue regarding WildStacker as if I don't load WildStacker, the issue is solved.

**Comment by OmerBenGera** [comment]
> I'm still trying to debug this, but still I'm having issues and it is definitely an issue regarding WildStacker as if I don't load WildStacker, the issue is solved.

I believe you, however without more information I can't do anything regarding this.

**Comment by OmerBenGera** [comment]
Try latest dev build, I fixed an infinite event-loop that was caused by the plugin - maybe it fixed the issue for you as well.

**Comment by Superalex0102** [comment]
I’m gonna test it right now, but I can’t give you results until tomorrow

**Comment by Superalex0102** [comment]
Seems like it didn’t fix my issue :(

**Comment by OmerBenGera** [comment]
> Seems like it didn’t fix my issue :(

Mind checking in which version it started to happen?

**Comment by Superalex0102** [comment]
Around b134

**Comment by OmerBenGera** [comment]
> Around b134

Exact version?

**Comment by Superalex0102** [comment]
> > Around b134
> 
> Exact version?

Try with b134, I don't know any specifics other than that

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Superalex0102** [comment]
Still having this issue, but I managed to solved it by having a restart every 6 hours.

**Comment by OmerBenGera** [comment]
> Still having this issue, but I managed to solved it by having a restart every 6 hours.

This is not really a fix you know :(

Mind sharing with me more logs where the issue happens?

**Comment by OmerBenGera** [comment]
Does it still occur?
