### ISSUE TITLE
[BUG] strange bug with MMOitems

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#412]
### Minecraft's Version

1.16.5 tuinity

### Plugin's Version

i try many versione, same thing even with 258

### Describe the bug

The bug is strange.. i think it depend with some hook, maybe myticmob hook. 

When i use wild and custom MI abilities on dynamic folder of MMOitems the plugin MMO dosent load with a error in console. This happend only with wildstacker, when i remove wild all work.

### To Reproduce

use this list of plugin Plugins https://pastebin.com/1fGxeD4P with one ability on dynamic folder of MMOitems and start the server

### Additional Information

Maybe add a way to enable/disable hook can fix this

**Comment by OmerBenGera** [comment]
Upload the error you get please.

**Comment by kedavlar** [comment]
the only error is mmoitems related.. but this happend only with wild in :/ in strange https://pastebin.com/5Atwy618

**Comment by OmerBenGera** [comment]
Upload the entire error to pastebin and send it here.

**Comment by kedavlar** [comment]
it is already the complete error, only 2 lines are missing  https://pastebin.com/puP2zfeT

**Comment by OmerBenGera** [comment]
Did you try to report it to the MMOItems guys?

**Comment by kedavlar** [comment]
yes, no respond for now

**Comment by kedavlar** [comment]
it is strange that removing wild works

**Comment by OmerBenGera** [comment]
I agree with that.
Maybe somehow WildStacker triggers something that affects MMOItems and this error is thrown.
WildStacker is not interacting with MMOItems which makes things much more complicated.

Mind trying to replicate the issue with only WildStacker and MMOItems installed on your server?

**Comment by kedavlar** [comment]
in this case work normally. The thing is that MMOitems work with myticmob thats have hook with wild.. at this point i think the problem is only mmo related..

**Comment by OmerBenGera** [comment]
If you install the 3 of the plugins, do you still get the errors?

**Comment by kedavlar** [comment]
nope

**Comment by OmerBenGera** [comment]
Weird. Try installing the others plugin on that server until you get the error - maybe this way we can find the combination of plugins that make this error to appear.

**Comment by kedavlar** [comment]
yea .. i test a lot of thing and i found another one plugin that cause this. Its multiverse , but when i use only this pl with mmo again work.. its very strange..

I don't want to waste your time, at this point I think it is a mistake which in some cases causes the MMO plugin to be enabled before Myticmob causing all this
