### ISSUE TITLE
Zombie error

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#413]
### Minecraft's Version

1.18.1 R0.1-snapshot 1

### Plugin's Version

3.6.2 Wildstacker

### Describe the bug

https://pastebin.com/QLZsURJh

The above error in console

### To Reproduce

not sure

### Additional Information

Random spam message in console

**Comment by OmerBenGera** [comment]
Update WildStacker to latest dev build, let me know if its better.

**Comment by TenReeez** [comment]
Not fixed as of Dev 3.6.2.261

**Comment by OmerBenGera** [comment]
I am closing this for now
If it happens again, reply here and lmk about it
