### ISSUE TITLE
WildStacker made IridiumSkyblock's disallow pickup not work

### ISSUE THREAD

**Issue by Special70** [BG-Software-LLC/WildStacker#415]
### Minecraft's Version

[10:09:55 INFO]: This server is running Purpur version git-Purpur-1421 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 983ed96 on ver/1.17.1)
[10:09:55 INFO]: You are 7 version(s) behind
Download the new version at: https://purpur.pl3x.net/downloads/
[10:09:55 INFO]: Previous version: git-Paper-353 (MC: 1.17.1)

### Plugin's Version

WildStacker version 3.6.2.261

### Describe the bug

If you have WildStacker installed, even if the owner of the island decided not to allow pickup of items of visitors, visitors still can pickup the items

### To Reproduce

1) Install IridiumSkyblock and WildStacker
2) Go to an island that you do not own
3) Spawn an item entity for reference
4) Pick the item up (Assuming pickup of items of visitors is disabled)

**Comment by OmerBenGera** [comment]
WildStakcer listens to PlayerAttemptPickupItemEvent for picking up items.
However, it also fires EntityPickupItemEvent before it tries to pickup items - therefore, if it doesn't work with IridiumSkyblock, they should check why firing of the event doesn't work.

**Comment by Special70** [comment]
ok time to talk to Iridium Skyblock discord & github

**Comment by PeachesMLG** [comment]
I mean, ill take a look into it, but dont see how this can be caused by us, all we are doing is:
```
    @EventHandler(ignoreCancelled = true)
    public void onEntityPickupItem(EntityPickupItemEvent event) {
        if (!(event.getEntity() instanceof Player)) return;
        Player player = (Player) event.getEntity();
        Optional<Island> island = IridiumSkyblock.getInstance().getIslandManager().getIslandViaLocation(event.getItem().getLocation());
        if (!island.isPresent()) return;

        if (!IridiumSkyblock.getInstance().getIslandManager().getIslandPermission(island.get(), IridiumSkyblock.getInstance().getUserManager().getUser(player), PermissionType.PICKUP_ITEMS)) {
            event.setCancelled(true);
        }
    }
```

**Comment by dlsf** [comment]
Why should whatever you do with the PlayerAttemptPickupItemEvent affect the EntityPickupItemEvent? Or does Spigot do some weird things I'm not aware of?

**Comment by dlsf** [comment]
And even if it does affect it and automatically cancels the other event, I don't see the reason why it should be our fault, we just ignore cancelled PickupEvents so the item should stay on the ground. 

Why do **we** have to check why that event has been cancelled? And how is that even supposed to work, what should we check?

**Comment by OmerBenGera** [comment]
> And even if it does affect it and automatically cancels the other event, I don't see the reason why it should be our fault, we just ignore cancelled PickupEvents so the item should stay on the ground.
> 
> Why do **we** have to check why that event has been cancelled? And how is that even supposed to work, what should we check?

I only wanted to know if your listener is fired when WildStacker is calling the event, nothing else.

**Comment by dlsf** [comment]
> I only wanted to know if your listener is fired when WildStacker is calling the event, nothing else.

Did the code from Peaches answer that question, or do we have to test it?

**Comment by OmerBenGera** [comment]
> > I only wanted to know if your listener is fired when WildStacker is calling the event, nothing else.
> 
> Did the code from Peaches answer that question, or do we have to test it?

I have just noticed the plugin is open source, so I can do the tests myself.
Thanks for answering, appreciated

**Comment by OmerBenGera** [comment]
@Special70 It seems to work fine for me using latest of IridiumSkyblock (3.2.3) and WildStacker (3.6.2.263) on Purpur 1.17 ( git-Purpur-1423).

Check if it works on a server with only WildStacker & IridiumSkyblock installed using the versions I sent above.

**Comment by OmerBenGera** [comment]
Any news regarding this?
