### ISSUE TITLE
Entity Tracking Error

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildStacker#417]
### Minecraft's Version

Minecraft Version: 1.8.8
Server Jar: BeerSpigot Premium  

### Plugin's Version

WildStacker-3.6.2-b261

### Describe the bug

My server console is silently spamming the following message repetitively https://pastebin.com/Ur1nXkYQrepetitively

### To Reproduce

AFK on the server it might not show up.

### Additional Information

Here is my config file I'm using https://pastebin.com/qUuWGGJ6

**Comment by OmerBenGera** [comment]
Pastebin is 404.
Also, check out #419 , is it similar?
If so, this can be closed

**Comment by OmerBenGera** [comment]
Closing this for now.
If it is a new issue, reply here and I will reopen it.
