### ISSUE TITLE
Turtle issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#418]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b261

### Describe the bug

If you set a limit of stacking on a turtle, you can still get more than this mob stack with eggs.

### To Reproduce

- set a limit on turtle (exemple 64)
- spawn a stacked turtle x64
- let them lay an egg
- once the egg hatch, it will spawn a turtle x~80
Once you reproduce theses x70 turtle, you'll have turtle x100, etc.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's fixed.

**Comment by WarnDa** [comment]
Seems fixed for me, I'll create a new issue if my players find a new way to get more turtles than the maximum stack

**Comment by OmerBenGera** [comment]
Perfect :)
