### ISSUE TITLE
Slime Bug Drops

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#423]
### Minecraft's Version

purpur-1.17.1-1428

### Plugin's Version

WildStacker-3.6.1-b242.jar

### Describe the bug

Look, there were 4 large slimes and they were supposed to multiply to make 16, not just 4:

https://www.youtube.com/watch?v=Dhd0arjOHB8&t

my config -> https://pastebin.com/dtEaAD73

### To Reproduce

hoping to group a lot of slimes and killing them with the kill-all option

**Comment by OmerBenGera** [comment]
When it happens again, check if the slime actually has a stack size using `/ws inspect` before killing it.

**Comment by brasilcraft54** [comment]
> 

sim, ele faz

**Comment by OmerBenGera** [comment]
> > 
> 
> sim, ele faz

English?

**Comment by brasilcraft54** [comment]
> > > 
> > 
> > 
> > sim, ele faz
> 
> English?

sorry, yes he does

**Comment by OmerBenGera** [comment]
> > > > 
> > > 
> > > 
> > > sim, ele faz
> > 
> > 
> > English?
> 
> sorry, yes he does

Try replicating the issue on a server with only WS installed.

**Comment by OmerBenGera** [comment]
I managed to replicate the issue myself, I am looking into it right now

**Comment by OmerBenGera** [comment]
If it happens again, let me know by commenting here :)

**Comment by brasilcraft54** [comment]
> Should be fixed in latest dev build Let me know if it works for you as well.

sorry for the delay in answering yes it did work out, thank you.
