### ISSUE TITLE
Plugin Disabled on Startup

### ISSUE THREAD

**Issue by OfficialJrip** [BG-Software-LLC/WildStacker#424]
### Minecraft's Version

Server version 1.8+

### Plugin's Version

3.6.2

### Describe the bug

When I startup my server I get this error line regarding wildstacker https://pastebin.com/SK61XvRB it begins to enable then runs into an error thinking it might be out of date then has an error disabling aswell.

### To Reproduce

Not quite sure how to reproduce besides possibly using my server files

### Additional Information

All Current Installed Plugins https://gyazo.com/0b4a4faf3235e1dae23e5ecfa3ec15e4

**Comment by OmerBenGera** [comment]
Use 1.8.8 paper, let me know if it still occurs.

**Comment by OfficialJrip** [comment]
> Use 1.8.8 paper, let me know if it still occurs.

That did fix my issue makes me wonder why that version of the beerspigot I had wasnt working anymore thank you!

**Comment by OmerBenGera** [comment]
> > Use 1.8.8 paper, let me know if it still occurs.
> 
> That did fix my issue makes me wonder why that version of the beerspigot I had wasnt working anymore thank you!

Its something with the json parser that Beerspigot uses probably.
Anyways, closing this :)
