### ISSUE TITLE
Disables after /uar restart 

### ISSUE THREAD

**Issue by NuggetDesign** [BG-Software-LLC/WildStacker#425]
### Minecraft's Version

Server: Paper("c3d812d") 1.18.1-R0.1-SNAPSHOT

### Plugin's Version

Jar: Dev Build #264

### Describe the bug

When i execute /uar restart or the plugin auto restarts it justs disables the plugin asking if its up to date

### To Reproduce

execute /uar restart or wait for an auto restart

**Comment by OmerBenGera** [comment]
Upload logs and send them here via pastebin

**Comment by NuggetDesign** [comment]
https://paste.helpch.at/adoteziwef.md

**Comment by OmerBenGera** [comment]
Update paper to latest version, let me know if it works.

**Comment by NuggetDesign** [comment]
issue is mythicmobs and all of their plugins dont really support the latest paper version so im in 1.18

**Comment by OmerBenGera** [comment]
Then test it without them for a moment.
The version of Paper that you use has broken configs support which breaks WildStacker.
It should be fixed on latest versions of Paper, so I need to know if it works for you as well or not.

**Comment by OmerBenGera** [comment]
Check out #427
