### ISSUE TITLE
Adding extra lines in config

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#427]
### Minecraft's Version

versionl: git paper-150 1.18.1

### Plugin's Version

3.6.2.261

### Describe the bug

The plugin is adding extra # comments on reboot

### To Reproduce

Im not sure. I know that MCMMO had the same issue ( the dev over there did a fix)
I have only noticed in wildstacker today. I dont know if its related or not. I have only noticed it since I uploaded his new version. 

### Additional Information

![Screenshot (671)](https://user-images.githubusercontent.com/76084803/150070130-8370ce89-6793-405e-92cf-7d218cefb6d1.png)
![Screenshot (672)](https://user-images.githubusercontent.com/76084803/150070133-ae6059ae-9e62-4789-8a51-083d0ab7f4da.png)

**Comment by OmerBenGera** [comment]
Update Paper to latest version, let me know if if fixes the issue.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it works for you as well.
