### ISSUE TITLE
Remove Hologram error

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#434]
### Minecraft's Version

1.18.1

### Plugin's Version

b266

### Describe the bug

Hello i've this error in my console after restart my island (Not really restart due to bug of SS2 : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/873) : https://pastebin.com/DY4RA83y 

I think it's because the block of barrel doesn't exist.

### To Reproduce

Place barrel and restart the server.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
