### ISSUE TITLE
Barrel Bug Fix For Production Server

### ISSUE THREAD

**Issue by ShibaSkyBlock** [BG-Software-LLC/WildStacker#437]
### Minecraft's Version

Minecraft Version 1.8.8
PaperSpigot Latest Version
Java 8

### Plugin's Version

WildStacker version 3.6.2

### Describe the bug

Players & admins can't place blocks in the barrel as defined in the config - see the attached images/gif.

### To Reproduce

Open a barrel with items and try adding them.

### Additional Information

https://gyazo.com/78fd52fb075346f174033d9120565539 
https://gyazo.com/2534b0d77fe7476fc29e938d02cdc0f3

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that :)

**Comment by ShibaSkyBlock** [comment]
Thank you so much @OmerBenGera - you are making so many servers, networks, and player experience so much better
