### ISSUE TITLE
Transformation issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#439]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

WildStacker-3.6.2-b264.jar

### Describe the bug

Transform event doesn't work when a hoglin transform into a zoglin

It should detect the transformation and stack it with the stack of zoglin, but it doesn't.

### To Reproduce

https://youtu.be/slQtBSjaJFI

**Comment by OmerBenGera** [comment]
By adding "UNKNOWN" to the `filtered-transforms` list, it seems to convert the stack amount correctly.

**Comment by OmerBenGera** [comment]
> > By adding "UNKNOWN" to the `filtered-transforms` list, it seems to convert the stack amount correctly.
> 
> If I add UNKNOWN it creates a duplication :
> 
>     * take a stacked hoglin
> 
>     * once it transforms, it will transforms the stack (but not stack it to the actual stack)
> 
>     * and it will also spawn 2 new hoglins from nowhere
>       https://www.youtube.com/watch?v=_LX5ToPDz9I

It works fine for me.
Mind testing it on 1.16 Spigot / Paper?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WarnDa** [comment]
I'll try once I can on paper, but I don't get a lot of free time

**Comment by OmerBenGera** [comment]
They are transforming fine and keep their stack sizes.
They don't stack with nearby entities as it's not a stacking trigger, as you can see here:
https://wiki.bg-software.com/wildstacker/overview/entities-stacker#stacking-triggers

I will make sure they stack tho when a new entity is transformed into another :)

**Comment by WarnDa** [comment]
Doesn't work
![image](https://user-images.githubusercontent.com/31826333/153596015-71f03c43-35df-47fe-b6dc-f67af66c79c3.png)
(using b270)

**Comment by OmerBenGera** [comment]
Should be working on latest one, sorry about that.

**Comment by WarnDa** [comment]
Fixed thanks
