### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/WildStacker#442]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-18 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 15b612e on HEAD)
Received invalid status code (404) from server.
Previous version: git-Airplane-110 (MC: 1.17.1)

### Plugin's Version

WildStacker-3.6.3-b274.jar

### Describe the bug

https://pastebin.com/pkMV3ycy
No errors in the console before the crash

### To Reproduce

I have no idea, I saw that the server stopped working.

**Comment by OmerBenGera** [comment]
Seems like your server got crashed due to a lag.
Take a timings report or spark profiler so we can understand what causes this to happen
