### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by LudnicaKiller** [BG-Software-LLC/WildStacker#444]
### Minecraft's Version

This server is using WineSpigot(3436) or Paper spigot 1.8.8

### Plugin's Version

3.6.3

### Describe the bug

Server crash

### To Reproduce

All of a sudden

### Additional Information

[latest.log](https://github.com/BG-Software-LLC/WildStacker/files/8003348/latest.log)

**Comment by OmerBenGera** [comment]
Sorry about that, fixed on latest dev build
