### ISSUE TITLE
Possible memory leak with shulkers

### ISSUE THREAD

**Issue by airoons** [BG-Software-LLC/WildStacker#446]
### Minecraft's Version

Minecraft 1.17.1 with Purpur 1.17.1 (tested with Paper aswell)

### Plugin's Version

3.6.2.266

### Describe the bug

By unloading chunks, sometimes spawner (or entity?) data (WStackedEntity) seems to be not cleared from memory. I found WildStacker to be the cause from a heapdump.

### To Reproduce

Place 12k Shulker spawners in a player-load distance, each spawner stacked up to 16 (in total 700 tile entities - spawner blocks). Was placed in a SuperiorSkyblock end dimension, in a single chunk with a custom VoidChest plugin that listens to "SpawnerSpawnEvent" (by cancelling it and getting drops with WildStackerAPI.getLootTable -> WildStackerAPI.getStackedEntity).

**This procedure was repeated many times:**
Go to the spawner location, load chunks, then go to a different world to unload chunks. Sometimes ram usage went up (tested by setting allocated memory to a lower value and seeing it allocate more and more). 

### Additional Information

Memory heap dump taken after a half hour.

![a1](https://user-images.githubusercontent.com/16526213/152663322-1c1a3b12-2f27-44b6-b9eb-55f889f137a9.png)
![a2](https://user-images.githubusercontent.com/16526213/152663339-5bc9fd55-0bcb-40f4-86c2-e4bdd549f295.png)

**Comment by OmerBenGera** [comment]
Please upload the hprof file and send it here.

**Comment by airoons** [comment]
Uploaded it to Dropbox, it is compressed with gzip
https://www.dropbox.com/s/i708n8gwpa1dc96/heap-2022-02-06_01.58.51.hprof.gz?dl=0

**Comment by OmerBenGera** [comment]
There seems to be a lot of shulker entities saved in the cached entities.
WildStacker removes this cache when chunks are unloaded. This means that there are probably a lot of shulkers in a loaded chunk in your worlds.
Can you check it out? Let me know if that's the case or not.

**Comment by airoons** [comment]
Hi, there are no signs of actual entities being spawned, checked with /paper entity list and additional plugins. Shouldn't entities be skipped from the cache if SpawnerSpawnEvent (which extends EntitySpawnEvent) is cancelled?

**Comment by OmerBenGera** [comment]
> > > Hi, there are no signs of actual entities being spawned, checked with /paper entity list and additional plugins. Shouldn't entities be skipped from the cache if SpawnerSpawnEvent (which extends EntitySpawnEvent) is cancelled?
> > > We tried the same test with a different spawner (Enderman), problem was the same.
> > 
> > 
> > You think that entities are kept in memory when SpawnerSpawnEvent is cancelled?
> 
> I'll post my code where I am accessing stacked entities via API, but yeah, I think entities might get kept in memory.
> 
> ```java
>     @EventHandler(ignoreCancelled = true)
>     private void onSpawnerEntitySpawn(SpawnerSpawnEvent event) {
>         Chunk chunk = event.getSpawner().getLocation().getChunk();
>         VoidStorage storageFound = VoidChestInstaCollectListener.searchChest(chunk);
>         if (storageFound == null)
>             return;
> 
>         event.setCancelled(true);
> 
>         if (!VoidChestOption.CHUNK_COLLECTOR.isEnabled(storageFound) ||
>                 !storageFound.getVoidStorageAbilities().isChunkCollector())
>             return;
> 
>         Inventory inv = storageFound.getBlockInventory();
>         if (inv == null)
>             return;
> 
>         if (inv.firstEmpty() == -1)
>             return;
> 
>         StackedEntity stackedEntity = WildStackerAPI.getStackedEntity((LivingEntity) event.getEntity());
>         List<ItemStack> drops = WildStackerAPI.getLootTable(stackedEntity.getLivingEntity()).getDrops(stackedEntity, 0, stackedEntity.getStackAmount());
> 
>         for (ItemStack stack : drops) {
>             if (!VoidStorageIgnoreList.getInstance().contains(stack))
>                 continue;
>             inv.addItem(stack);
>         }
>     }
> ```

Ah, so you call the getStackedEntity yourself, which makes a copy in cache.
It's still weird tho, as the plugin should clear the entities after some time by itself.
Do you have spawners stacking enabled?

**Comment by airoons** [comment]
> Ah, so you call the getStackedEntity yourself, which makes a copy in cache. It's still weird tho, as the plugin should clear the entities after some time by itself. Do you have spawners stacking enabled?

Yes, I have, as I mentioned in the beginning of this Github issue, I have spawners stacked to 16

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs.

**Comment by airoons** [comment]
Hi, tried the latest dev build for a few days and it seems as this issue is resolved. In heap dumps Wildstacker wasn't "top problem suspect" anymore. Thank you!
