### ISSUE TITLE
Silktouch

### ISSUE THREAD

**Issue by Ronal1999** [BG-Software-LLC/WildStacker#447]
### Minecraft's Version

1.17

### Plugin's Version

3.6.3

### Describe the bug

I gave the permission to mine spawners with silk touch, but for some reason does not work, this is the permission wildstacker.silktouch

### To Reproduce

just mine and don't give the spawner

**Comment by NuggetDesign** [comment]
If you're using bungee then i guess this wont work. (from my testing)

**Comment by Ronal1999** [comment]
I am not using bungee mode, just normal, even being op cant get spawner

**Comment by OmerBenGera** [comment]
> I am not using bungee mode, just normal, even being op cant get spawner

Do you get any messages?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by NuggetDesign** [comment]
still doesnt work for me. I have no other silk touching plugin except an autopickup plugin

**Comment by OmerBenGera** [comment]
The auto pickup plugin interfaces with the plugin. Uninstall it and you'll see that it works.

**Comment by NuggetDesign** [comment]
@OmerBenGera i uninstalled it and it still didnt work :/

**Comment by NuggetDesign** [comment]
@OmerBenGera it still doesnt work after uninstalling it

**Comment by OmerBenGera** [comment]
> @OmerBenGera it still doesnt work after uninstalling it

Try it on a server with only WildStacker installed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If it still occurs, lmk
