### ISSUE TITLE
Killing stacked mobs

### ISSUE THREAD

**Issue by NuggetDesign** [BG-Software-LLC/WildStacker#449]
### Minecraft's Version

1.18.1-R0.1-Snapshoot Paper(115)

### Plugin's Version

Dev build 274

### Describe the bug

Mobs are instantly killed for each stack and for some reason it divides its with only having mobs be x2 or x3

### To Reproduce

Get spawners and let them spawn.

### Additional Information

![2022-02-07_05 05 30](https://user-images.githubusercontent.com/75328554/152703734-d279c0ae-92e6-4cb9-9be2-755e57404180.png)
![2022-02-07_05 05 21](https://user-images.githubusercontent.com/75328554/152703737-68ef9913-2ff1-487c-ae62-7a32c6490559.png)

**Comment by OmerBenGera** [comment]
Do you have custom enchantments on your sword?

**Comment by NuggetDesign** [comment]
I tried with custom enchants and without.

**Comment by OmerBenGera** [comment]
> I tried with custom enchants and without.

Try it on a server with only WildStacker installed.
I dont quite understand what the issue exactly is, however I know custom enchants can interface with it.

**Comment by NuggetDesign** [comment]
Im unable to do that as i dont have another server to test on.

**Comment by NuggetDesign** [comment]
are there any other option?

**Comment by OmerBenGera** [comment]
> Im unable to do that as i dont have another server to test on.

Test it on localhost

**Comment by NuggetDesign** [comment]
Ill test this by today.

**Comment by NuggetDesign** [comment]
The jar is unable to open the jar in local server as it wont load the plugins. 
![image](https://user-images.githubusercontent.com/75328554/153533104-27dc2ef1-54e1-4f8b-9209-2b55a280fc6b.png)

**Comment by OmerBenGera** [comment]
> The jar is unable to open the jar in local server as it wont load the plugins. ![image](https://user-images.githubusercontent.com/75328554/153533104-27dc2ef1-54e1-4f8b-9209-2b55a280fc6b.png) ![image](https://user-images.githubusercontent.com/75328554/153533182-f2f977a3-f4a2-4d4c-879c-efe6e88abda4.png)

What?

**Comment by NuggetDesign** [comment]
i cant seem to be able to test the plugin in local

**Comment by OmerBenGera** [comment]
> i cant seem to be able to test the plugin in local

Why not?
Just put the plugin inside your plugins folder.
Also, update to latest dev build.

**Comment by NuggetDesign** [comment]
i tried both it for some reason it wont load. Imma try again later.

**Comment by NuggetDesign** [comment]
No, no errors. Imma try with another server and see if it works.

**Comment by OmerBenGera** [comment]
> I tested this out and it works perfectly fine in the other server. Do you know if maybe its because of other plugins

Custom enchantments may interface with it.

**Comment by NuggetDesign** [comment]
im currently using AdvancedEnchantments. Do I have to report to you or the dev for CE

**Comment by NuggetDesign** [comment]
cause it looks like its an issue for here i believe

**Comment by OmerBenGera** [comment]
> cause it looks like its an issue for here i believe

Check out latest version of AE.
If it still occurs, open an issue on their github.
