### ISSUE TITLE
Battlepass entitydeathevent

### ISSUE THREAD

**Issue by NuggetDesign** [BG-Software-LLC/WildStacker#453]
### Minecraft's Version

Paper 1.18.1

### Plugin's Version

Dev Build #278

### Describe the bug

11.02 07:43:03 [Server] ERROR Could not pass event EntityDeathEvent to BattlePass v3.6.9
11.02 07:43:03 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildstacker.api.WildStacker.getSystemManager()" because "com.bgsoftware.wildstacker.api.WildStackerAPI.instance" is null
11.02 07:43:03 [Server] INFO at com.bgsoftware.wildstacker.api.WildStackerAPI.getStackedEntity(WildStackerAPI.java:45) ~[SaberFactions.jar:?]
11.02 07:43:03 [Server] INFO at com.bgsoftware.wildstacker.api.WildStackerAPI.getEntityAmount(WildStackerAPI.java:54) ~[SaberFactions.jar:?]
11.02 07:43:03 [Server] INFO at io.github.battlepass.quests.quests.internal.KillMobQuest.onEntityKill(KillMobQuest.java:29) ~[battle-pass-3.6.10.jar:?]
11.02 07:43:03 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1420.execute(Unknown Source) ~[?:?]
11.02 07:43:03 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
11.02 07:43:03 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
11.02 07:43:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
11.02 07:43:03 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:868) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1715) ~[?:?]
11.02 07:43:03 [Server] INFO at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1622) ~[?:?]
11.02 07:43:03 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:122) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at com.bgsoftware.wildstacker.handlers.SystemHandler.lambda$spawnCorpse$11(SystemHandler.java:507) ~[WildStacker-3.6.3-b278.jar:?]
11.02 07:43:03 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:03 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
11.02 07:43:04 [Server] ERROR Could not pass event EntityDeathEvent to BattlePass v3.6.9
11.02 07:43:04 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildstacker.api.WildStacker.getSystemManager()" because "com.bgsoftware.wildstacker.api.WildStackerAPI.instance" is null
11.02 07:43:04 [Server] INFO at com.bgsoftware.wildstacker.api.WildStackerAPI.getStackedEntity(WildStackerAPI.java:45) ~[SaberFactions.jar:?]
11.02 07:43:04 [Server] INFO at com.bgsoftware.wildstacker.api.WildStackerAPI.getEntityAmount(WildStackerAPI.java:54) ~[SaberFactions.jar:?]
11.02 07:43:04 [Server] INFO at io.github.battlepass.quests.quests.internal.KillMobQuest.onEntityKill(KillMobQuest.java:29) ~[battle-pass-3.6.10.jar:?]
11.02 07:43:04 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1420.execute(Unknown Source) ~[?:?]
11.02 07:43:04 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
11.02 07:43:04 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
11.02 07:43:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
11.02 07:43:04 [Server] INFO at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:161) ~[WildStacker-3.6.3-b278.jar:?]
11.02 07:43:04 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-155]
11.02 07:43:04 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-155]

### To Reproduce

Use the battlepass and wildstacker

**Comment by OmerBenGera** [comment]
The plugin was not enabled and therefore other plugins that try to hook into it throw errors.
Send me entire logs file so I can check why it is not enabled.

**Comment by NuggetDesign** [comment]
https://paste.helpch.at/xaxunezabo.md

**Comment by OmerBenGera** [comment]
What java version are you using?
The plugin seems to load fine, however the API's plugin instance isn't initialized correctly.

**Comment by NuggetDesign** [comment]
Its using java 17. What should we do going forward

**Comment by OmerBenGera** [comment]
Let me know if it happens using latest dev build as well.

**Comment by NuggetDesign** [comment]
Ill try with the latest one #285

**Comment by NuggetDesign** [comment]
It fixed the issue. however, you closed a ticket sayings its a duplicate of this. 

[16:04:17] [Server thread/ERROR]: [MythicMobs] [31m[SCHEDULER] Exception thrown whilst executing task[37m
[16:04:17] [Server thread/WARN]: java.lang.NullPointerException: Cannot read field "f" because "this.tracked" is null
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.nms.v1_18_R1.packet.entity.RangeManager.getPlayerInRange(RangeManager.java:32)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.api.model.AbstractModeledEntity.getPlayerInRange(AbstractModeledEntity.java:259)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.nms.v1_18_R1.packet.entity.PacketArmorStandB.sendPackets(PacketArmorStandB.java:171)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.nms.v1_18_R1.packet.entity.PacketArmorStandB.setMeta(PacketArmorStandB.java:126)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.model.part.MEPartEntity.initialize(MEPartEntity.java:41)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.model.MEActiveModel.generatePartEntities(MEActiveModel.java:135)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.api.model.AbstractModeledEntity.addActiveModel(AbstractModeledEntity.java:225)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.model.MEModeledEntity.addActiveModel(MEModeledEntity.java:95)
[16:04:17] [Server thread/WARN]: 	at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.mythicmobs.mechanics.MechanicModel.castAtEntity(MechanicModel.java:69)
[16:04:17] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeTargetedEntitySkill$5(SkillMechanic.java:453)
[16:04:17] [Server thread/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[16:04:17] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:449)
[16:04:17] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeSkills$1(SkillMechanic.java:406)
[16:04:17] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[16:04:17] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[16:04:17] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[16:04:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:04:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[16:04:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[16:04:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[16:04:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[16:04:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[16:04:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:04:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

This is being spammed in my console when

**Comment by OmerBenGera** [comment]
> It fixed the issue. however, you closed a ticket sayings its a duplicate of this.
> 
> [16:04:17] [Server thread/ERROR]: [MythicMobs] �[31m[SCHEDULER] Exception thrown whilst executing task�[37m [16:04:17] [Server thread/WARN]: java.lang.NullPointerException: Cannot read field "f" because "this.tracked" is null [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.nms.v1_18_R1.packet.entity.RangeManager.getPlayerInRange(RangeManager.java:32) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.api.model.AbstractModeledEntity.getPlayerInRange(AbstractModeledEntity.java:259) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.nms.v1_18_R1.packet.entity.PacketArmorStandB.sendPackets(PacketArmorStandB.java:171) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.nms.v1_18_R1.packet.entity.PacketArmorStandB.setMeta(PacketArmorStandB.java:126) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.model.part.MEPartEntity.initialize(MEPartEntity.java:41) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.model.MEActiveModel.generatePartEntities(MEActiveModel.java:135) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.api.model.AbstractModeledEntity.addActiveModel(AbstractModeledEntity.java:225) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.model.MEModeledEntity.addActiveModel(MEModeledEntity.java:95) [16:04:17] [Server thread/WARN]: at Model-Engine-r2.4.0.jar//com.ticxo.modelengine.mythicmobs.mechanics.MechanicModel.castAtEntity(MechanicModel.java:69) [16:04:17] [Server thread/WARN]: at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeTargetedEntitySkill$5(SkillMechanic.java:453) [16:04:17] [Server thread/WARN]: at java.base/java.lang.Iterable.forEach(Iterable.java:75) [16:04:17] [Server thread/WARN]: at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:449) [16:04:17] [Server thread/WARN]: at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeSkills$1(SkillMechanic.java:406) [16:04:17] [Server thread/WARN]: at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToSupplier.get(Delegates.java:121) [16:04:17] [Server thread/WARN]: at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654) [16:04:17] [Server thread/WARN]: at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70) [16:04:17] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) [16:04:17] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) [16:04:17] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547) [16:04:17] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) [16:04:17] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470) [16:04:17] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264) [16:04:17] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) [16:04:17] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
> 
> This is being spammed in my console when

This error is not related to the plugin. It's an error from MythicMobs.

I am closing this issue :)

**Comment by NuggetDesign** [comment]
1 second this happens when i enable the kill tasks

**Comment by OmerBenGera** [comment]
> 1 second this happens when i enable the kill tasks

You said it's fixed. Does it still occur?

**Comment by NuggetDesign** [comment]
The one is fixed is for battlepass entitydeathevent. this error i sent is not. Its spammming in my chat and it only happens when i enabled killtask

**Comment by OmerBenGera** [comment]
> The one is fixed is for battlepass entitydeathevent. this error i sent is not. Its spammming in my chat and it only happens when I have wildstacker in the server
> 
> I also have killtasks on but even if its off it still spams the error. I need to remove wildstacker for it to not show up

The error you sent has nothing to do with the original issue. Let's move to the issue you have already opened.

**Comment by NuggetDesign** [comment]
correct i opened this issue in another ticket but you closed it saying that its a duplicate of this issue.

**Comment by OmerBenGera** [comment]
> correct i opened this issue in another ticket but you closed it saying that its a duplicate of this issue.

You can still comment there.
