### ISSUE TITLE
Kill tasks killing blacklisted mobs

### ISSUE THREAD

**Issue by NuggetDesign** [BG-Software-LLC/WildStacker#454]
### Minecraft's Version

Paper 1.18.1

### Plugin's Version

Dev Build #285

### Describe the bug

I set blacklists on the killtasks for a specific mob and its still being cleared.

### To Reproduce

put PIG:EGG in killtasks

### Additional Information

https://gyazo.com/fd0060f763e2beb837b4913faae8c326

**Comment by NuggetDesign** [comment]
i tried with normal egg ones and they still get killed

**Comment by NuggetDesign** [comment]
okay.

**Comment by NuggetDesign** [comment]
It works for normal spawned eggs but it doesnt work for spawn eggs with custom textures. i used CUSTOM as a spawn reason but it still clears it

**Comment by NuggetDesign** [comment]
it works thank you!

**Comment by OmerBenGera** [comment]
What was the spawn cause?

**Comment by NuggetDesign** [comment]
MYTHIC_MOBS

**Comment by OmerBenGera** [comment]
> MYTHIC_MOBS

Ah, makes sense :)
Mobs from mythic mobs have a custom spawn cause `MYTHIC_MOBS`.
Closing this for now.

**Comment by NuggetDesign** [comment]
yeah, thank you.
