### ISSUE TITLE
Stacked drowned issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#458]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b286

### Describe the bug

When drowned are stacked, they don't drop trident at all.
(we tried on 1500 stacked drowned)

But when they are not stacked, they can drop trident.

### To Reproduce

Spawn stacked drowned, try to kill them 1 by 1 (even with looting 100) you'll never get trident

**Comment by OmerBenGera** [comment]
I can't replicate it.
I get a trident when I kill a drowned.

Do you have `dropEquipment` set to false for the loot table?

**Comment by WarnDa** [comment]
> I can't replicate it. I get a trident when I kill a drowned.
> 
> Do you have `dropEquipment` set to false for the loot table?

I got default config of loottable of drowned. So might be TRUE
(or it wouldn't drop trident without stacking)

On my config I got : 
>   # Should vanilla equipment of entities get cleared after they unstack?
  clear-equipment: true

Maybe it changes something (I don't think)
I'll retry again to be sure

**Comment by WarnDa** [comment]
But if a drowned spawn without trident in his hand, then there are 1000 drowned that stack on it, the 1000 won't drop trident at all

**Comment by OmerBenGera** [comment]
> But if a drowned spawn without trident in his hand, then there are 1000 drowned that stack on it, the 1000 won't drop trident at all

It doesn't work like that with equipment.
If the drowned doesn't have a trident in his hand and you have instant-kill for entity attack, it doesn't matter how many entities there are in the stack, as the equipment is only counted once (prevent duplicates, etc).
If you don't have instant-kill for entity attack, but you have clear-equipment, the equipment of the next drowneds in the stack will get cleared - including the trident.
A fix for this would be to add the trident as an item and disable equipement drops for drowned.
