### ISSUE TITLE
Server crashing with Error

### ISSUE THREAD

**Issue by paint2005** [BG-Software-LLC/WildStacker#459]
### Minecraft's Version

Paper 1.18.1

### Plugin's Version

latest dev build #286

### Describe the bug

server crashes randomly spamming panel with this error 
`[12:36:14 ERROR]: Nag author: 'Ome_R' of 'WildStacker' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

### To Reproduce

it happiness randomly so i cant help you Reproduce

**Comment by OmerBenGera** [comment]
You can ignore the warning.
Your server crashes due to something else.
