### ISSUE TITLE
Console spam erro

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#460]
### Minecraft's Version

paper 1.18.1 last version

### Plugin's Version

WildStacker-3.6.3-b286

### Describe the bug

this keeps showing up in the console. 
1° https://prnt.sc/26wijya

### To Reproduce

just using it or using the plugman to update the 2 way does it.

**Comment by OmerBenGera** [comment]
Look for the entire stack trace of the error and upload it to pastebin.

**Comment by brasilcraft54** [comment]
> 

https://pastebin.com/FvMpv2J2

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue.

**Comment by brasilcraft54** [comment]
> Check out latest dev build, let me know if it fixes the issue.

I believe you have solved it. thanks <3
