### ISSUE TITLE
[FEATURE] Remove nametag or change it

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#461]
### Minecraft's Version

1.16.5 tuinity

### Plugin's Version

3.6.3.286

### Describe the bug

Actually the nametag are a big problem for mob despawning.. i mean.. if you use a nametag on a mob, the mob dosent disappear if i go away and turn back. I dont know how, but its possible to add a way to block nametag or just change how they work?

### To Reproduce

.

**Comment by OmerBenGera** [comment]
This is not a bug report.
