### ISSUE TITLE
Spark of the plugin

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#463]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b288

### Describe the bug

The plugin start to take a lot of server %, and it impacts the mspt,
So maybe you have a solution (if the dev of the spawner plugin I use could do something to improve this, or if directly you could improve the used method in wildstacker) except "reduce number of spawner"

- I'm using "UpgradeableSpawners" as spawner provider
- It uses prespawnerevent to directly add mobs to the current stack instead of spawning a new one
- I got 600 mob spawners currently enabled.
- My config : https://pastebin.com/dPdtK84k

The spark : 
https://spark.lucko.me/Kn0QtZ81SZ
![image](https://user-images.githubusercontent.com/31826333/154803727-bfe7c353-6d2c-4eec-8d66-698581d19d03.png)

### To Reproduce

Use a lot of spawners in mob farms

**Comment by OmerBenGera** [comment]
I will look into optimizing it if possible.
I haven't seen anything there that is really can cause issues - some simple tasks are reported as taking a lot of time, which indicates an overall lag on the server, which causes every task to take more time than usual.

**Comment by WarnDa** [comment]
But it's permanent : https://spark.lucko.me/wy6h8Xb4Rs
![image](https://user-images.githubusercontent.com/31826333/155592264-e13a848c-a7e8-4142-8c98-f19b3fc25ac0.png)

I'm sure there is a way to fix that, maybe the issue could be in upgradeablespawners that could do a better hook into wildstacker, but I don't know

**Comment by OmerBenGera** [comment]
As I said before, I will look into optimizing it.

**Comment by WarnDa** [comment]
Hello,

thanks for the update !
Here is a spark after the update : 
https://spark.lucko.me/1SiHwhty0g

The onPreSpawnSpawner() is way better, but it's not possible to apply the same fix for "onItemSpawn()" ?

**Comment by OmerBenGera** [comment]
> Hello,
> 
> thanks for the update, it helped a lot ! Here is a spark after the update : https://spark.lucko.me/1SiHwhty0g ![image](https://user-images.githubusercontent.com/31826333/155769648-00a27e3f-9160-4345-bf3a-93ec7d4ad9ea.png)
> 
> The onPreSpawnSpawner() is way better, but it's not possible to apply the same fix for "onItemSpawn()" ?

I haven't done anything.

**Comment by WarnDa** [comment]
Your NMS changes didn't optimize this task ?

**Comment by OmerBenGera** [comment]
> Your NMS changes didn't optimize this task ?

No. I didn't change anything related to that
