### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by NuggetDesign** [BG-Software-LLC/WildStacker#464]
### Minecraft's Version

1.18.1 - Paper

### Plugin's Version

Dev Build 285

### Describe the bug

Ftop cant count the stacked spawners.

### To Reproduce

install ftop and addon ftopgui

### Additional Information

<img width="676" alt="image" src="https://user-images.githubusercontent.com/75328554/154806117-23818f4a-9bf9-48a6-ad7b-4fc7c561c212.png">

**Comment by OmerBenGera** [comment]
I am talking with CustomEnchants privately.
