### ISSUE TITLE
Huge performance impact

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#468]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

dev 261

### Describe the bug

since now a few weeks wildstacker is taking a lot of percentage on my timings you can see that on the spark report here its taking 16% of the server thread which is A LOT https://spark.lucko.me/sqOy96WUga

### To Reproduce

i dont know how to reproduce it

**Comment by OmerBenGera** [comment]
The lag comes from BentoBox's entity limits
![Uploading Screenshot_20220221-195620_Chrome.jpg…]()

**Comment by amarcais53** [comment]
oh , so how can i fix it ?

**Comment by amarcais53** [comment]
i did openned an bug report on their github https://github.com/BentoBoxWorld/Limits/issues/158

**Comment by OmerBenGera** [comment]
I recommend including the spark as well there.
Closing this one :)

**Comment by amarcais53** [comment]
yeah i did
