### ISSUE TITLE
conflict with modelengine

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#469]
### Minecraft's Version

1.18.1 Paper

https://pastebin.com/iQuy8kpN

### Plugin's Version

Wildstacker: 3.6.2.265
ModelEngine: R2.3.2

### Describe the bug

As per error:
https://pastebin.com/iQuy8kpN

but also this is getting spammed every few seconds:

[02:31:35 WARN]: [WildStacker] Plugin WildStacker v3.6.2.265 generated an exception while executing task 531
java.lang.ClassCastException: null

### To Reproduce

Add model engine, Wildstacker into a bowl, mix well and wallah!

Not sure of the reason tbh. 

### Additional Information

The initial error is on start up. While the generated exception is a constant spam

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
