### ISSUE TITLE
cant pick up custom named items B290

### ISSUE THREAD

**Issue by eghbalTG** [BG-Software-LLC/WildStacker#470]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

3.6.3 b290

### Describe the bug

cant be pick up custom name items

### To Reproduce

set name for item then drop it

**Comment by OmerBenGera** [comment]
Are there any errors?

**Comment by OmerBenGera** [comment]
Are there any errors?

**Comment by OmerBenGera** [comment]
Are there any errors?

**Comment by eghbalTG** [comment]
console dont show any error

OS: linux ubuntu 20
Java: 16.0.1
fork: Purpur 1.16.5

در تاریخ سه‌شنبه ۱ مارس ۲۰۲۲،‏ ۱۹:۴۶ Ome_R ***@***.***> نوشت:

**Comment by eghbalTG** [comment]
And Api dont work on my linux ubuntu 20 os but its work on windows OS

در تاریخ سه‌شنبه ۱ مارس ۲۰۲۲،‏ ۲۳:۱۴ Mr Eghbal ***@***.***>
نوشت:

**Comment by OmerBenGera** [comment]
Does it still occur?

**Comment by eghbalTG** [comment]
Works on Windows server 
but does not work on Ubuntu 20 Linux!

**Comment by OmerBenGera** [comment]
Have you tried latest dev build?

**Comment by eghbalTG** [comment]
Yes version 3.7.0

**Comment by eghbalTG** [comment]
Previously worked properly around Build 290 this happened

**Comment by OmerBenGera** [comment]
This cannot happen in latest dev build anymore, as reflections is not used to set the API's instance.

**Comment by eghbalTG** [comment]
![image](https://user-images.githubusercontent.com/22130034/160147571-e27e4d90-8626-400f-8e75-3efff1a90bbd.png)
```

 if(label.equalsIgnoreCase("jcheck") && sender instanceof Player ){
            Player p = (Player) sender;
            for(Entity ent :p.getNearbyEntities(3,3,3)){
               if(ent instanceof Item){
                   try{
                     Item IT = (Item) ent;
                       boolean HasPerm = false;
                       String ISNAME = IT.getCustomName();
                     p.sendMessage(Rang("TYPE: "+IT.getType().getName()+" NAME: "+ISNAME+" Amount:"+IT.getItemStack().getAmount() + " Trust:"+HasPerm));
                       int stack = WildStackerAPI.getItemAmount(IT);
                   p.sendMessage(Rang("WAPI: "+ stack));
               }catch (Exception ex){
                   p.sendMessage(Rang("&c&lERROR: &e"+ex.getMessage()));
               }
               }
           }
        }
```

**Comment by eghbalTG** [comment]
Top screen for version 1.18.2
Java 17
--------
Screen bottom 1.16.5
Java 16
![image](https://user-images.githubusercontent.com/22130034/160149859-5d799ad0-5cf5-42be-aec5-92f9d2ce2785.png)

**Comment by OmerBenGera** [comment]
Send me your logs file (upload to pastebin and send it here).

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If the issue still occurs, lmk by replying here
