### ISSUE TITLE
spawners not stacking

### ISSUE THREAD

**Issue by CptKildor** [BG-Software-LLC/WildStacker#471]
### Minecraft's Version

1.17.1

### Plugin's Version

3.6.3

### Describe the bug

i have edited Set a maximum stack for specific spawners. to what i want on my server but now they aint stacking.

  # Set a maximum stack for specific spawners.
  # Make sure you follow the "ENTITY-TYPE" format.
  # You can use 'all' as a global limit (all: 20 will set all spawners to be limited to 20 per stack)
  # If you don't want any limits, you can set a random type.
  limits:
    all: 20 (also tried ALL: 20)
    EXAMPLE_ENTITY: 10

### To Reproduce

placing spawners down dont stack.

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send it here.

**Comment by CptKildor** [comment]
https://pastebin.com/Ubex0tAW

**Comment by OmerBenGera** [comment]
> any news on the two issues? was it the config?

Be patient, I havent looked into it.
I only have time on the weekends - I will update you here once I have looked into it.

**Comment by OmerBenGera** [comment]
Your config has formatting issues with caused the plugin to not even get enabled.
Check out line 521 and correct that line to follow yaml's formatting.

After you fix it, it will work for you.
