### ISSUE TITLE
can you limit the enitities that spawn from spawner?

### ISSUE THREAD

**Issue by CptKildor** [BG-Software-LLC/WildStacker#472]
### Minecraft's Version

1.17.1

### Plugin's Version

3.6.3

### Describe the bug

can you limit the enitities that spawn from spawner? for example cow spawner has x20 stack limit but spawns 10+ stacks of 20 i just want stacks of 20 but say 2-3 cows spawning max.

### To Reproduce

edited config

**Comment by OmerBenGera** [comment]
Yes. Use "COW:SPAWNER" as the mob type under the limits section.
Next time you have a question, ask on discord and not here.
