### ISSUE TITLE
Stacked Mobs not dying after first mob is killed

### ISSUE THREAD

**Issue by samidont0817** [BG-Software-LLC/WildStacker#474]
### Minecraft's Version

Purpur 1.18.2 Build 1566

### Plugin's Version

Version: 3.6.3.291

### Describe the bug

You can kill the first Mob that is part of the Stacked Mobs. But once you kill the first mob, the stack becomes invincible.

### To Reproduce

Spawn mobs using a stacked spawner.
Try to kill stacked mobs. First mob will die. You will notice the rest wont.

### Additional Information

https://youtu.be/PRbYskF2YdQ
https://pastebin.com/KkgZP2XM

**Comment by Skizzles** [comment]
This is fixed when using the latest dev build.
