### ISSUE TITLE
Cannot pickup spawners

### ISSUE THREAD

**Issue by joshua-philip** [BG-Software-LLC/WildStacker#475]
### Minecraft's Version

1.18.2 Paper (paper-1.18.2-234)

### Plugin's Version

Wild Stacker 3.6.3 Dev Build 292 (1.18.2 Support)

### Describe the bug

Players are unable to pick up a spawner via the GUI or silk touch. Console posts "Could not pass event BlockBreakEvent to WildStacker v3.6.3.292"

### To Reproduce

Pick up a spawner via silk touch or the GUI.

**Comment by OmerBenGera** [comment]
Send the entire stack trace here. Upload to pastebin and send it here

**Comment by joshua-philip** [comment]
This is the only stack trace I'm seeing [https://pastebin.com/kLAt49hY](https://pastebin.com/kLAt49hY)

**Comment by OmerBenGera** [comment]
This error is not related to WildStacker.
You said you get "Could not pass event BlockBreakEvent to WildStacker v3.6.3.292" - then just send me the entire stack trace of the error.

**Comment by joshua-philip** [comment]
The newest stable released fixed it
