### ISSUE TITLE
Issues when using Wildstacker with Boss plugin

### ISSUE THREAD

**Issue by bipedd** [BG-Software-LLC/WildStacker#477]
### Minecraft's Version

1.18.1 paper

### Plugin's Version

WildStacker 3.6.3

### Describe the bug

The issue I encounter is bosses stack to each other and there's no way to disable this.
Plugin link: https://www.mc-market.org/resources/21619/

### To Reproduce

Spawn two of the same boss next to each other, they will then stack to each other. Keep in mind mob stacking for that mob must be enabled.

### Additional Information

https://user-images.githubusercontent.com/77213949/157754105-ed859cfe-011e-48e0-be05-bb5fded62990.mp4

**Comment by OmerBenGera** [comment]
You can prevent your bosses from stacking by adding them to the blacklist section.
They have a custom "spawn reason" so you can differ them from other mobs. You can find their custom spawn reason using the /ws inspect tool.
