### ISSUE TITLE
CoreProtect API v9 is not supported

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#480]
### Minecraft's Version

1.17.1

### Plugin's Version

261

### Describe the bug

getting that error 
![image](https://user-images.githubusercontent.com/62488520/158006416-dfefd45d-d542-4658-8985-b1db72a9dc3e.png)

### To Reproduce

N/A

**Comment by OmerBenGera** [comment]
Version of CoreProtect?

**Comment by amarcais53** [comment]
ops sorry im using Coreprotect 21.1

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
