### ISSUE TITLE
striking lightning on stacked pigs to transform them into zombified piglins gets killed on one kill

### ISSUE THREAD

**Issue by Special70** [BG-Software-LLC/WildStacker#481]
### Minecraft's Version

1.17.1 Purpur-1421

### Plugin's Version

3.7.0

### Describe the bug

the transformed pigs behaved like the plugin didn't exist when killed

### To Reproduce

1) put stacked pigs
2) strike lightning on them
3) kill it

**Comment by Special70** [comment]
got an answer in discord. this issue can be closed ty

**Comment by Special70** [comment]
after talking at the discord, their suggestions seem to not work

**Comment by OmerBenGera** [comment]
Look at the config for the transform-reasons list and try adding LIGHTNING - let me know if it works

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
