### ISSUE TITLE
SpawnerSpawnEvent Listener Priority

### ISSUE THREAD

**Issue by Angeschossen** [BG-Software-LLC/WildStacker#482]
### Minecraft's Version

git-Paper-187 (MC: 1.18.1)

### Plugin's Version

3.6.3

### Describe the bug

I'm not sure if this fits into the discussion section, so I'm opening a issue instead. I just wanted to ask if it would be possible for you to change the listener priority of the SpawnerSpawnEvent to LOW, instead of LOWEST. I got a request to add stacking compatibility with WildStacker with one of my plugins. However, since WildStacker listens on LOWEST, it's not guaranteed that I can modify the stacked entity amount on spawner spawn before WildStacker does. I would like to listen on LOWEST and then cancel the event, to prevent both plugins doing different actions which might lead to too many entities spawned. I can also open a PR. Just wanted to ask if WildStacker must run on LOWEST for any reason before opening a PR with the potential of breaking something.

[Link to source](https://github.com/BG-Software-LLC/WildStacker/blob/139d1136c25b0e40f752dafa6e52627534f628a0/src/main/java/com/bgsoftware/wildstacker/listeners/SpawnersListener.java#L423)

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Why do you need to change the entity's amount before WildStacker run its logic?

**Comment by OmerBenGera** [comment]
They can disable WS's spawners from functioning and letting your plugin do the job instead... it sounds like you have a plugin with similar functionalities to WS's spawners  and you want both of them to work - correct me if I am wrong.

Also, you can make a PR for such event and I will just accept it. I do not have a lot of time to do that on my own...

**Comment by Angeschossen** [comment]
Thanks, I may have found an alternative solution, though. I want to retrieve nearby stacked entities, but encounter a problem.

Do you have any idea why this returns randomly null, even if at least one stacked entity is in range?
````
            Optional<StackedEntity> ee = EntitiesGetter.getNearbyEntities(location,
                            4, e -> e.getType() == entityType)
                    .map(WStackedEntity::of)
                    .findFirst();
````

**Comment by Angeschossen** [comment]
Apparently setting the range to 6 instead of 4 seems to fix it. Even though the max possible range in the enclosure would be 4 (if the entity would stand inside the fence).

**Comment by Angeschossen** [comment]
I'm now using Bukkits getNearbyEntities instead. That seems to work. Thank you for your fast replies! This issue can be closed from my side.
