### ISSUE TITLE
Wildstacker not working with NachoSpigot

### ISSUE THREAD

**Issue by Redwolf223** [BG-Software-LLC/WildStacker#484]
### Minecraft's Version

1.8.8

### Plugin's Version

3.7.0

### Describe the bug

Mobspawner won't spawn any mob if Wildstacker is running with NachoSpigot.

### To Reproduce

By  running wildstacker with nachospigot.

**Comment by OmerBenGera** [comment]
What is NachoSpigot?

**Comment by OmerBenGera** [comment]
> Yes.

It sounds like an issue with NachoSpigot then?

**Comment by Redwolf223** [comment]
Yes. I've also opened a ticket on their github, but i wanted also to ask here as maybe you could try and fix it by updating your plugin.

If it's not possible, than still thank you for your time.

**Comment by OmerBenGera** [comment]
> Yes. I've opened a ticket on their github, but i wanted to also ask here as maybe you could try and fix it by updating your plugin.
> 
> If it's not possible, than still thank you for your time.

I don't know exactly what causing it to not work.
You can send them a link to this issue if there's something I need to change in order for it to work with their fork

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Redwolf223** [comment]
They won't answer, so i will have to wait on their side.

If you want you could try and see if you find the problem, but i don't want to waste your time so you can close the ticket.

Thank you.

**Comment by Elierrr** [comment]
Can confirm

It seems to be that it cannot, for some reason, find nearby players on NachoSpigot while on Paper it can and works properly.

Relevant Nacho issue: https://github.com/CobbleSword/NachoSpigot/issues/378

**Comment by OmerBenGera** [comment]
The issue (from my investigation at least) is that spawners are only ticked once per second, instead of once per tick, causing the spawners to spawn mobs in a really slow delay (20 times slower). I tried changing the setting `tile-entity-ticking-time` to 1 and it doesn't seem to do anything - spawners still tick in intervals of seconds.

This can be fixed by changing the delays of WS to work with seconds instead of ticks (in the upgrades section) - let me know if it helps!

**Comment by Redwolf223** [comment]
Hi thank you for all your help! 

I still can't seem to find the "seconds instead of ticks option" inside the config.yml of wildstacker.

How is it called?

**Comment by OmerBenGera** [comment]
> Hi thank you for all your help!
> 
> I still can't seem to find the "seconds instead of ticks option" inside the config.yml of wildstacker.
> 
> How is it called?

It's inside Nacho's config file, not WS.

**Comment by Redwolf223** [comment]
Thank you, i've changed tile-entity-ticking-time to 1 and the spawners seems to be working fine now.

I still can't find the settings for delays to work with seconds instead of ticks option inside the nacho.yml file.

Could you be more specific? Thank you

**Comment by OmerBenGera** [comment]
> Thank you, i've changed tile-entity-ticking-time to 1 and the spawners seems to be working fine now.
> 
> I still can't find the settings for delays to work with seconds instead of ticks option inside the nacho.yml file.
> 
> Could you be more specific?

You can make the delays to work with seconds in WS's config file, under the upgrades section.
I am closing this for now :)
