### ISSUE TITLE
Stacked mobs droped items like one mob

### ISSUE THREAD

**Issue by Yankata777** [BG-Software-LLC/WildStacker#486]
### Minecraft's Version

I have 2 servers that use this plugin. One is at 1.18.1 and the other at 1.16.5

### Plugin's Version

WildStacker version is 3.6.3 

### Describe the bug

When many mobs get stаck and are killed (by anything) items are dropped as for 1 mob.

### To Reproduce

1. When stacking mobs, everything is fine.
2. When killing mobs (from anything), things like 1 mob are dropped.

Expectation: When you kill the stack mob to give things as they should be.

**Comment by OmerBenGera** [comment]
Great :)
