### ISSUE TITLE
Stacked drowned mobs don't drop any nautilus shells when holding them

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/WildStacker#487]
### Minecraft's Version

Purpur 1.18.1 b1566

### Plugin's Version

3.7.0 b297

### Describe the bug

Whenever killing mobs from a stack of drowneds, sometimes you will see a drowned holding a nautilus shell falling to the side. Whenever this happens, no nautilus shell will be dropped, although the drop chance of getting it from a drowned holding it should be 100%.

### To Reproduce

Let some drowneds stack up, and start killing them one by one. Sometimes, a drowned holding a nautilus shell will fall dead to the side, and the nautilus shell will not be dropped.

### Additional Information

https://www.youtube.com/watch?v=69p256Pda5Q

**Comment by OmerBenGera** [comment]
Make sure you have "dropEquipment" set to true to the loot table of drowneds.

**Comment by OmerBenGera** [comment]
I understand what you meant.
You meant that the corpse itself has a nautilus shell and it doesn't drop it, which means sense.
The corpse is only visually there, and it is not actually a mob. Therefore, even if it is equipped with any item or armor, they will never get dropped.

If you want a drowned to drop its nautilus shell, you need one to be spawned with one and kill it.

This is not a bug :)
