### ISSUE TITLE
Durability dont go down when one shooting an entity

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#493]
### Minecraft's Version

1.17.1 puffrefish

### Plugin's Version

dev 300

### Describe the bug

for some reason the durabilty of some tools is not going down when we one shot them , i tested with an iron shovel and the bug hapen it also happen with some other tools 

### To Reproduce

here is the step to reproduce https://www.youtube.com/watch?v=RSHjpfMeMwM

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
Mind testing it on a Paper server instead of Pufferfish?

**Comment by amarcais53** [comment]
https://user-images.githubusercontent.com/62488520/163566087-19ed4420-4121-40b9-b954-dbcf91745e11.mp4

just tried on paper 1.17.1 with only wildstacker installed

**Comment by amarcais53** [comment]
here is my config https://pastebin.com/PUx4d6QE

**Comment by OmerBenGera** [comment]
Fixed in latest dev build - the issue only occurred when `fast-kill` was enabled :)

**Comment by amarcais53** [comment]
ty
