### ISSUE TITLE
Synchronization with clearlag does not work

### ISSUE THREAD

**Issue by D3BoxOfficiel** [BG-Software-LLC/WildStacker#494]
### Minecraft's Version

1.16.5 Purpur.jar

### Plugin's Version

3.7.0

### Describe the bug

Synchronization with clearlag does not work, mobs and items (stack) do not clear

### To Reproduce

Just try

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
Mind uploading your config file of WildStacker to pastebin and send it here?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
