### ISSUE TITLE
Enderman Are Still Teleporting with Nerf Teleport feature disabled

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildStacker#495]
### Minecraft's Version

1.8.8 and BeerSpigot Premium

### Plugin's Version

WildStacker-3.7.0-b300

### Describe the bug

Enderman still being able to teleport even when the nerf teleport setting in the config is set to false.

### To Reproduce

Change the nerf entities section of the config to all mobs, place an enderman spawner and punch an enderman, the enderman will still teleport when it's in an aggressive state.

### Additional Information

Here is my current config: https://pastebin.com/767up4XB

**Comment by OmerBenGera** [comment]
This might be because the EntityTeleportEvent is not called for this teleportation type. Not something that can be fixed on the plugin's side, sorry.
