### ISSUE TITLE
Entity Chunk Limit Not Working

### ISSUE THREAD

**Issue by EcoSMP** [BG-Software-LLC/WildStacker#496]
### Minecraft's Version

Purpur_Latest_1.18.2.jar

### Plugin's Version

3.7.0

### Describe the bug

  We use the jobs plugin and it is important that we limit the number of stacks of mobs per plot so players cannot be killing mobs from 10+ stacks at a time. This makes the job payout way too high. We want to limit the number of stacks per chunk to 2 stacks. We use LagAssist and it will allow us to set an entity limit for each type of mob which we have done and it works for normal mobs but breeding stacked mobs with WildStacker will still create another entity and LagAssist will not remove a stack. We have tried using the setting below from the config but it doesn't seem to change anything one way or another. Could you help us determine whats going wrong and find a solution to this problem? Thanks!
  
  # Set a maximum amount of entity objects in a chunk.
  # If you want to disable the feature, set it to 0.
  chunk-limit: 2

### To Reproduce

1. Breed animals until you have many stacks
2. Turn on chunk limit to limit entity objects to 2 per chunk
3. The existing stacks of entities remain above 2 per chunk and can still be bred to continue making even more entities in the chunk.

### Additional Information

We have well balanced Job payouts on our server but this has made the Hunter job almost unusable since it can be easily abused by killing 10+ mobs per swing of a sword with sweeping edge on many different stacks. We want to limit the number of stacks to 1-2 per chunk so the job payouts remain balanced and to decrease lag on the server. Thanks again for your time!

**Comment by OmerBenGera** [comment]
Are you using WildStacker's chunk limits or LagAssist's chunk limits?

**Comment by EcoSMP** [comment]
We have tried both. Wildstackers did not seem to do anything whatsoever. We did turn off lagassist when testing this.

As of now we are using Lagassist until we can figure out how to get Wildstacker working.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better now

**Comment by OmerBenGera** [comment]
I am closing this.
If the issue still persists, lmk
