### ISSUE TITLE
Stacked mobs get food from inventory instead of hand

### ISSUE THREAD

**Issue by Lemrigue** [BG-Software-LLC/WildStacker#498]
### Minecraft's Version

paper-287 1.18.2

### Plugin's Version

3.7.0

### Describe the bug

When you give food to stacked animals, it removes items from inventory instead of removing the items in the held hand

### To Reproduce

take seeds in your slots, give food to stacked chickens, it will takes seeds from the 1st slot, then the 2nd slots, until it reaches the slot you are currently on

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
