### ISSUE TITLE
My villager cannot breed

### ISSUE THREAD

**Issue by Chrqmated** [BG-Software-LLC/WildStacker#499]
### Minecraft's Version

Minecraft version: 1.16.5
Spigot: 1.16.5 PURPUR
Plugin: 3.7.0

### Plugin's Version

3.7.0 

### Describe the bug

My villager cannot breed when the SuperiorskyBlock2 and Wildstacker plugin are together on the server. After disabling Wildstacker, my villagers have miraculously managed to have baby

### To Reproduce

Created a server with Purpur 1.16.5, Superior, and Wildstacker, tries to reproduce villagers on your island and they will not appear

**Comment by OmerBenGera** [comment]
Did you nerf villagers by any chance?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
