### ISSUE TITLE
1.8.8 version based issue i believe

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/WildStacker#500]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Build #305

### Describe the bug

The entities do not stack i've reset the config many times and redid it and the same issue happens

### To Reproduce

use my config https://pastebin.com/t5VKxVHX

**Comment by OmerBenGera** [comment]
Try replicating the issue on another server with only WS installed running on Paper/Taco.

**Comment by DebuffPvP** [comment]
can you check here if my config is right? https://www.toptal.com/developers/hastebin/aficarugoc.yaml

**Comment by DebuffPvP** [comment]
> Try replicating the issue on another server with only WS installed running on Paper/Taco.

i just tried and still doesn't stack with that same config i have given you and that's the only thing i've edited. The main reason i'm using wildstacker is to stack mobs and nothing else. I seen it says to allow wildstacker to handle spawners for better performance and i don't want it to mess with any of the explosion/silktouch that i want silkspawners to handle. Also would that mean i'd need to give spawners through the wildstacker command instead if that were enabled instead of through silkspawners /ss?

**Comment by DebuffPvP** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
> @OmerBenGera

No need to tag me or bump the issue.
I will look into the issue when I have the time.

**Comment by OmerBenGera** [comment]
Do you have at least 8 mobs around so they stack together?

**Comment by DebuffPvP** [comment]
yes i do and i can give you my server jar if you'd like so you can also test it too

**Comment by OmerBenGera** [comment]
Use `/ws simulate` and try clicking two entities that don't stack together - what does it show?

**Comment by DebuffPvP** [comment]
what do i enter for the arguments cause it requires it https://gyazo.com/4cab958d5b88afe3b8358f8cb80e3db9

**Comment by OmerBenGera** [comment]
> what do i enter for the arguments cause it requires it https://gyazo.com/4cab958d5b88afe3b8358f8cb80e3db9

Your name...

**Comment by DebuffPvP** [comment]
https://gyazo.com/ee910f469db8a508c50a9aa8fbd5bef0

**Comment by DebuffPvP** [comment]
I didn't know about the simulate tool feature sorry

**Comment by OmerBenGera** [comment]
> https://gyazo.com/ee910f469db8a508c50a9aa8fbd5bef0

As I told you, there arent enough entities nearby.
You must have at least 8 pigs in a 5-block range so they get stacked together.

Try it with default config file, you'll see that they get stacked.

**Comment by DebuffPvP** [comment]
So after some major testing i found out the main issue is
  stack-interval: 0 it's set to 0 by default when the plugin generates all the files and changing this to 20 ticks which is 1 second fixed the issue i've been trying to fix for weeks lol

**Comment by DebuffPvP** [comment]
Also since you're here. I've been trying to use linked-entities and when i place 2 spawners of which require 5 entities to merge with a radius of 10 to check for linked entities they all merge into one mob. If i have If you have spawner stacking disabled will this stop linked entities from working?

**Comment by OmerBenGera** [comment]
> Also since you're here. I've been trying to use linked-entities and when i place 2 spawners of which require 5 entities to merge with a radius of 10 to check for linked entities they all merge into one mob. If i have If you have spawner stacking disabled will this stop linked entities from working?

It should still work

**Comment by OmerBenGera** [comment]
> So after some major testing i found out the main issue is stack-interval: 0 it's set to 0 by default when the plugin generates all the files and changing this to 20 ticks which is 1 second fixed the issue i've been trying to fix for weeks lol

The issue was that at the time the mobs spawn, there werent enough entities nearby, which I explained to you dozens of times already but you just refuse to listen. By enabling the stack interval, the plugin tries to stack each second all the mobs again, so evwntually they get stacked again.
This is gonna lag your server probably, you should not put a value lower than 200.

Anyways, closing this one.

**Comment by DebuffPvP** [comment]
@OmerBenGera Well i put barriers around the spawner to which mob spawner the mobs were stacking from at the stack radius and they didn't stack and only stacked when i enabled the ticks. I never refused to listen.
