### ISSUE TITLE
MythicMobs conflicting with WildStacker

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#502]
### Minecraft's Version

Spigot 1.8.9

### Plugin's Version

WildStacker: WildStacker-3.7.0-b305.jar
MythicMobs: MythicMobs-2.3.0 (Latest 1.8 version of MythicMobs)

### Describe the bug

Not sure why it happens, it just spams console. 

https://paste.helpch.at/erefipovom.bash

### To Reproduce

It just starts spamming when you start the server with MythicMobs and Wildstacker

**Comment by OmerBenGera** [comment]
Try updating to MythicMobs v4.6.5; it should work for 1.8.8

**Comment by Rhys00** [comment]
> Try updating to MythicMobs v4.6.5; it should work for 1.8.8

Seems to be working fine now, thank you!
