### ISSUE TITLE
Mobs AI with custom integration

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#504]
### Minecraft's Version

paper 1.17.1

### Plugin's Version

b305

### Describe the bug

I use a plugin called "UpgradeableSpawners" and the dev added a hook into wildstacker to directly spawn stacked mobs. But we can't spawn stacked mobs without AI.
We want to spawn stacked mobs without AI but with water pushing (like the "nerf-spawner-mobs: true" in spigot.yml)

UpgradeableSpawners' dev will maybe have to show his hook, so you can see what method he used.

### To Reproduce

- Use upgradeablespawners/Wildstacker
- Disable wildstacker spawner stacking, but let mob stacking
- Set "no-ai: true" in upgradeablespawners
- Set "listen-paper-pre-spawn-event: false" in Wildstacker*
- Try to spawn mobs

**Comment by OmerBenGera** [comment]
Make sure you have `nerfed-entities` enabled for your mobs inside WildStacker's config.
I am not sure what the bug report here tbh..

**Comment by WarnDa** [comment]
It seems to fix the issue, thanks !
