### ISSUE TITLE
chunkload event lag

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#505]
### Minecraft's Version

1.18.2 purpur 

### Plugin's Version

dev build #300 

### Describe the bug

timings showing that a chunk load event from wildstacker is causing some mspt loss at any time
https://timings.aikar.co/?id=89e49e35d42545c49ea0562dcecb162a#plugins

### To Reproduce

no steps

### Additional Information

![image](https://user-images.githubusercontent.com/61608872/166131931-3e259a1e-81e4-467b-98be-f960c9e50fe4.png)

**Comment by OmerBenGera** [comment]
Take a spark profiler and send it here, timings mean nothing.
If you dont know what it is, google "spark plugin"

**Comment by hkkongou** [comment]
maybe is a  one time thing, i cannot take spark and timings found this
