### ISSUE TITLE
Random Error In Console

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#506]
### Minecraft's Version

Spigot 1.8.9

### Plugin's Version

WildStacker-3.7.0-b305.jar

### Describe the bug

I am not sure what is causing the error, it just sometimes randomly shows in console. https://paste.helpch.at/letidajara.bash

### To Reproduce

I am unsure, and have tried to find out why but cant.

**Comment by OmerBenGera** [comment]
Thanks for reporting, will look into that.

**Comment by OmerBenGera** [comment]
Does it still happen?

**Comment by Rhys00** [comment]
> Does it still happen?

Yeah it does, https://paste.helpch.at/osefuxuzat.bash

**Comment by OmerBenGera** [comment]
Try it on Paper, let me know if it still occurs

**Comment by Rhys00** [comment]
> Try it on Paper, let me know if it still occurs

Happens on paper too, it just does it randomly and I have no clue why. It doesnt seem to effect anything its strange!

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build, sorry about the long waiting time

**Comment by Rhys00** [comment]
This error was said to be fixed in a previous update but it sill isnt.

https://paste.helpch.at/nofuveqavi.bash

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's fixed now

**Comment by OmerBenGera** [comment]
Any news regarding this
