### ISSUE TITLE
Drop 64 Enderpearl > Pickup and its a 64 stack :)

### ISSUE THREAD

**Issue by AabegR** [BG-Software-LLC/WildStacker#507]
### Minecraft's Version

1.18.1 Purpur

### Plugin's Version

WildStacker-3.7.0-b300.jar

### Describe the bug

- Player gets a 64 stack of e pearl rather than 16.
- MAJIK HAHA idk if it's a bad bug but I find it cool!

### To Reproduce

- So the max stack for ender pearl is 16, right?
- So drop 4 stacks = 64 e pearls
- Wildstacker will auto stack them to 64 right?

- Pick it up
- Check your inventory, and you have a stack of 64!

### Additional Information

Lemme know if you need more details or a vid. This should be easy to reproduce! Thankss

**Comment by OmerBenGera** [comment]
Look for the `fix-stack` option in the config file and enable it :)

**Comment by AabegR** [comment]
Ahh, yess I see smart guy thank you very much :)

Also, do you know why a single item doesn't have a name on it? Not sure if this is a config one too!
But pretty much let's say I drop a stick while chopping trees. I don't see the nametag and only see the stick vibing by itself.

Not sure if this is WildStacker but lemme know if you have any ideas! Thanks, mate :)

**Comment by OmerBenGera** [comment]
> Ahh, yess I see smart guy thank you very much :)
> 
> Also, do you know why a single item doesn't have a name on it? Not sure if this is a config one too! But pretty much let's say I drop a stick while chopping trees. I don't see the nametag and only see the stick vibing by itself.
> 
> Not sure if this is WildStacker but lemme know if you have any ideas! Thanks, mate :)

You can make unstacked items to have a display name as well in the config

**Comment by OmerBenGera** [comment]
> Ahh, yess I see smart guy thank you very much :)
> 
> Also, do you know why a single item doesn't have a name on it? Not sure if this is a config one too! But pretty much let's say I drop a stick while chopping trees. I don't see the nametag and only see the stick vibing by itself.
> 
> Not sure if this is WildStacker but lemme know if you have any ideas! Thanks, mate :)

You can make unstacked items to have a display name as well in the config

**Comment by AabegR** [comment]
Ayoo, thanks fam it works! Appreciate it.
The plugin is very fresh I rate that :)
