### ISSUE TITLE
Dupe glitch.

### ISSUE THREAD

**Issue by Zepollonetwork** [BG-Software-LLC/WildStacker#509]
### Minecraft's Version

1.17.1

### Plugin's Version

3.7.0

### Describe the bug

Dupe glitch when throwing an item, please see the video attached!

### To Reproduce

Throw an item on the ground when an item is already placed the item will stack and dupe the item.

### Additional Information

https://user-images.githubusercontent.com/102814432/168439192-b53169b4-a6b2-450e-9802-840f2325651f.mp4

**Comment by OmerBenGera** [comment]
I can't replicate the issue on my server.
