### ISSUE TITLE
Stack Limit Per Chunks Not Working

### ISSUE THREAD

**Issue by EcoSMP** [BG-Software-LLC/WildStacker#511]
### Minecraft's Version

1.18.2 PurPur

### Plugin's Version

Version 3.7.0

### Describe the bug

The plugin can successfully limit the number of stacks per chunk if the mobs are spawning in that same chunk. However, if the mobs spawn in a different chunk and then get moved to the chunk next door with water for example, there can be as many stacks as you want and it never removes them. 

We need to limit the total number of stacks per chunk at all times regardless of whether the mobs spawned in that chunk or not.

### To Reproduce

To reproduce the issue one would simply need to spawn the mobs in one chunk and have them move into a different chunk with water. They will far surpass the chunk-limit setting. Ours is 4 and the max mobs per stack is 64 meaning the max amount of mobs in any chunk should be 4 stacks of 64 mobs. However, if the mobs spawn in one chunk and move into another they still only stack up to 64 per chunk but there can be endless stacks, not limited to 4 how it is supposed to be.

**Comment by OmerBenGera** [comment]
This is the intended behavior and not a bug.
It will not let newly spawned mobs spawn and exceed the limit, however mobs movement isnt checked.

**Comment by OmerBenGera** [comment]
> That means the limit can easily be easy bypassed. Meaning the feature of having a limit is essentially useless. Wouldn't call that intended behavior.

Thats intended behavior.
