### ISSUE TITLE
Glitched Unbreakable

### ISSUE THREAD

**Issue by Aarpn** [BG-Software-LLC/WildStacker#512]
### Minecraft's Version

1.8.8

### Plugin's Version

3.7.0 b306

### Describe the bug

in stable 3.7.0 wildstacker is the issue with unbreakable swords fixed, but then the beta versions after its broken again and the swords when klling mobs turn into pink/black block

### To Reproduce

just have unbreakable on your sword then kill mobs

**Comment by OmerBenGera** [comment]
I dont understand the issue.
Mind uploading a short video to YT?

**Comment by Aarpn** [comment]
I will see if one of my staff can do it

**Comment by OmerBenGera** [comment]
As shown in the video, it works fine if you dont use the custom sword. Therefore, the plugin of the custom sword interrupts with WS and causes this behavior.
Contact their developer for a fix.
