### ISSUE TITLE
BarrelsListener.onPistonRetract() event

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#513]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b306

### Describe the bug

I got 
> barrels:
  # Should blocks get stacked into barrels on the server?
  enabled: false

But in spark wildstacker still check for pistons
![image](https://user-images.githubusercontent.com/31826333/170956172-330af857-7507-4d91-ae29-418a1b9323da.png)

### To Reproduce

X

### Additional Information

(I just want to disable all pistons interaction with plugin that don't need to, so I check for every plugin, even if it's 0.00%)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
