### ISSUE TITLE
Stacks Not Taking Food When Breeding

### ISSUE THREAD

**Issue by EcoSMP** [BG-Software-LLC/WildStacker#515]
### Minecraft's Version

1.18.2 PurPur

### Plugin's Version

3.7.0

### Describe the bug

We have the smart breeding setting turned on so when clicking a stack of mobs with food to breed them it should be taking the same number of food items out of inventory as there are number of mobs stacked. However, instead it breeds them properly but takes zero food from the players inventory so they can use one piece of wheat to breed as many cows as they want for example.

### To Reproduce

1. Have mob stacking and smart breeding turned on.
2. Right click mob stack to breed with food.
3. Animals will breed but don't actually take any food from inventory.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
