### ISSUE TITLE
Hex Color Code Items

### ISSUE THREAD

**Issue by ItchyDitchy** [BG-Software-LLC/WildStacker#516]
### Minecraft's Version

Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)

### Plugin's Version

3.7.0.305

### Describe the bug

Dropping a hex colored item shows the wrong colors.
Example: [https://imgur.com/a/brHgJRJ](url)

### To Reproduce

Rename an item with hex color code -> drop 2 or more of it -> see wrong colors of the item

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
