### ISSUE TITLE
smart-breeding consume only 1 stack.

### ISSUE THREAD

**Issue by IncludivicS** [BG-Software-LLC/WildStacker#523]
### Minecraft's Version

CraftBukkit version 3523-Spigot-1dffefb-effea36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker version 3.7.0.1

### Describe the bug

smart-breeding consume only 1 stack it should consume 900 if the cows are 900.

### To Reproduce

feed the animals.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
Make sure you enable it in the config, under the smart breeding section.

**Comment by IncludivicS** [comment]
Can I use in 1.19?

**Comment by OmerBenGera** [comment]
> Can I use these fix in 1.19? @OmerBenGera

Published a new build with the patch for 1.19 as well.
