### ISSUE TITLE
How to use custom-names

### ISSUE THREAD

**Issue by axin0452** [BG-Software-LLC/WildStacker#525]
### Minecraft's Version

1.18.2

### Plugin's Version

3.7.0

### Describe the bug

How to use custom-names,To distinguish between entity chicken and item chicken,because they have the same ID

### To Reproduce

PIG: '猪'
CHICKEN: '鸡'

**Comment by OmerBenGera** [comment]
I dont know what chicken item is, but entities and items do not share the same name.
Anyways, ask for help on the discord server, not here

**Comment by axin0452** [comment]
I asked for help on discord and no one helped me,The ID of chicken and raw chicken is the same, I can't customize the name of the chicken, if I add chicken in the config file, it will only change the name of the raw chicken

@OmerBenGera

**Comment by OmerBenGera** [comment]
> I asked for help on discord and no one helped me,The ID of chicken and raw chicken is the same, I can't customize the name of the chicken, if I add chicken in the config file, it will only change the name of the raw chicken
> 
> @OmerBenGera

There is no solution for that.
