### ISSUE TITLE
Server Lag Spike Issue

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#526]
### Minecraft's Version

1.8.8

### Plugin's Version

3.7.0.312

### Describe the bug

WildStacker seems to be making my server have a lag spike every 5 minutes or so. 

Report: https://spark.lucko.me/GPE2zDk3vZ

Outlined: 
1. https://spark.lucko.me/GPE2zDk3vZ?hl=95,16906
2. https://spark.lucko.me/GPE2zDk3vZ?hl=126

### To Reproduce

N/A - Just happens randomly every 4-6 minutes.

**Comment by OmerBenGera** [comment]
Disable items merger, let me know if it helps.

**Comment by Rhys00** [comment]
> 

There is no item merge setting?

**Comment by OmerBenGera** [comment]
> > 
> 
> There is no item merge setting?

in the config it's called "stack-interval" under the items section.
Let me also know what was the value you set there.

**Comment by Rhys00** [comment]
> > > 
> > 
> > 
> > There is no item merge setting?
> 
> in the config it's called "stack-interval" under the items section. Let me also know what was the value you set there.

Hey! After further testing it was another plugin causing it to act up, after fixing the other plugins issue it then was fine. Thank you and sorry about this!
