### ISSUE TITLE
JSON Object Error

### ISSUE THREAD

**Issue by bobhenl** [BG-Software-LLC/WildStacker#528]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/18662086/174606720-10926daf-3cab-4453-ae2f-47b499057212.png)

### Plugin's Version

WildStacker-3.8.0-b315.jar

### Describe the bug

There's error spamming in console
https://pastebin.com/YxyYFsm1

### To Reproduce

Sorry, I don't know.

**Comment by OmerBenGera** [comment]
What's the error..?

**Comment by bobhenl** [comment]
https://pastebin.com/YxyYFsm1 Oh sorry

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
