### ISSUE TITLE
stacked spawner spawning mob as 1 spawner

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#529]
### Minecraft's Version

[19:55:54 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1628 (MC: 1.18.2)
* You are running the latest version

### Plugin's Version

WildStacker-3.7.0-b313

### Describe the bug

Stacked spawner are not spawning correct number of mobs. spawners with 100+ stacked is spawning only 2-3 mobs.

After each server restart, players need to break the stacked spawner and place it to "fix" the stacked mob spawning number.

### To Reproduce

restart server

### Additional Information

video demo
https://www.youtube.com/watch?v=zgY14PO15fc&ab_channel=Poyu

**Comment by amarcais53** [comment]
i got simillar issue , and if you wait and dont restart the server they will spawn something like 1000 from 1000
its increasing with time

**Comment by OmerBenGera** [comment]
It works fine for me.
Please upload your config file to pastebin and send it here

**Comment by hkkongou** [comment]
> It works fine for me. Please upload your config file to pastebin and send it here

ok
here it isss 
https://paste.denizenscript.com/View/99262

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue using your config neither.
Try replicating it yourself on another server with only WildStacker installed and using your own config file.
Let me know whether it happens or not.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by amarcais53** [comment]
Seems to be related to #489

**Comment by OmerBenGera** [comment]
> Seems to be related to #489

Might be.
If your issue is fixed, we'll see if this one is fixed as well

**Comment by amarcais53** [comment]
Yeah I’m home in 1 day so expect me to come in 1 week with more infos

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by amarcais53** [comment]
oh yeah comming back from the feedback i've got , bug is fixed for sure and the stacker is also more performant but since the update my Garbage collection seems to be way more slower than before 
![image](https://user-images.githubusercontent.com/62488520/190629220-32c79e8b-485c-4bf8-ab66-dc08618769f5.png)
i was at 55ms average before updating

**Comment by amarcais53** [comment]
not sure if you need a flare report or spark

**Comment by OmerBenGera** [comment]
> oh yeah comming back from the feedback i've got , bug is fixed for sure and the stacker is also more performant but since the update my Garbage collection seems to be way more slower than before ![image](https://user-images.githubusercontent.com/62488520/190629220-32c79e8b-485c-4bf8-ab66-dc08618769f5.png) i was at 55ms average before updating

No clue what was changed.
Anyways, I am closing this for now
If it turns to actually be an issue, open a new issue and I'll see what can be done
