### ISSUE TITLE
Spawners dont spawn after server restart

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#534]
### Minecraft's Version

1.8.8

### Plugin's Version

3.8.0.317

### Describe the bug

When I stop and start the servers, peoples spawners seem to not spawn, the spawn countdown is just stuck. Sometimes it happens for players and sometimes it will be fine.

### To Reproduce

Place spawners down, stop and start and see if they stop spawning. Maybe will need to try a couple times.

**Comment by Rhys00** [comment]
Here is a video of it, this is when I stopped my server, then started it and went to check the spawners and they are glitched. https://streamable.com/ljjyjj

**Comment by Rhys00** [comment]
I did further testing and its being causes by a plugin that uses wildstacker as its dependency. Sorry!

**Comment by Rhys00** [comment]
I am still confused though, as when we remove wildstacker dependency on our custom chunk collector plugin the spawners work fine. But when we have the wildstacker dependency in, it just makes the spawners freeze on restart.

**Comment by OmerBenGera** [comment]
> I am still confused though, as when we remove wildstacker dependency on our custom chunk collector plugin the spawners work fine. But when we have the wildstacker dependency in, it just makes the spawners freeze on restart.

I have no clue what they do that causes this to occur.
Have you tried contacting their developer?

**Comment by OmerBenGera** [comment]
I am closing this for now
If you have any more questions, feel free to ask on the discord server for help :)
