### ISSUE TITLE
Spawner upgrade dupe!

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#535]
### Minecraft's Version

1.12.2 paper

### Plugin's Version

WildStacker-3.7.0-b313

### Describe the bug

You can turn a low tier into a high tier

### To Reproduce

https://imgur.com/a/nGTTCWm

### Additional Information

```
  # How many blocks from the spawner should be checked for other spawners to stack into?
  # EntityType list: https://bg-software.com/entities/
  merge-radius:
    all: 1
```

**Comment by Superalex0102** [comment]
Also works with WildStacker-3.8.0-b317.jar

**Comment by Superalex0102** [comment]
So I found another information for the bug. The server is 1.12.2, it doesn't work if you connect with the 1.12.2 version, but if you connect with 1.8 it works.

**Comment by Superalex0102** [comment]
What I forgot to write is you at least need to upgrade it to 1 tier above, so you can't do this with a normal non tiered spawner.

**Comment by Superalex0102** [comment]
This is a huge dupe, please fix it ASAP.

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Mind sending me your config file?

**Comment by OmerBenGera** [comment]
Please send me your config file

**Comment by Superalex0102** [comment]
> Please send me your config file

https://pastebin.com/fQ3XxmwY

**Comment by Superalex0102** [comment]
> Please send me your config file

https://pastebin.com/7CauGT30

**Comment by Superalex0102** [comment]
I can’t open my server because of this dupe, have you found anything?

**Comment by OmerBenGera** [comment]
I havent looked at your config, might have time tomorrow - if not, it will be done next week.

The project is open source, PRs are more than welcome.

**Comment by OmerBenGera** [comment]
Your config's pastebin was expired.
Re-upload it and send it again.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
