### ISSUE TITLE
Lil type error in lang.yml

### ISSUE THREAD

**Issue by s3babyy** [BG-Software-LLC/WildStacker#540]
### Minecraft's Version

1.8.8 & 1.8.8

### Plugin's Version

latest as of 10/07/2022

### Describe the bug

Just a little typo in the lang.yml file that's automatically generated
https://imgur.com/a/chhGbIw
Line 39 of lang.yml file within \plugins\WildStacker

### To Reproduce

Install the latest WildStacker and check out the lang.yml file

### Additional Information

https://imgur.com/a/chhGbIw
Line 39 of lang.yml file within \plugins\WildStacker

**Comment by OmerBenGera** [comment]
Fixed :)
