### ISSUE TITLE
Slime size stack

### ISSUE THREAD

**Issue by DarkOakHD** [BG-Software-LLC/WildStacker#541]
### Minecraft's Version

PaperSpigot 1.8.8

### Plugin's Version

WildStacker 3.8.0-b317

### Describe the bug

When you try to kill a BIG slime, the smaller Slimes don't stack leading to TPS drops.

### To Reproduce

Place a slime spawner, and kill a big Slime

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
