### ISSUE TITLE
Some performance issues

### ISSUE THREAD

**Issue by Hyronymos1337** [BG-Software-LLC/WildStacker#544]
### Minecraft's Version

1.19 purpur

### Plugin's Version

latest dev build

### Describe the bug

https://spark.lucko.me/iofxSUxNxQ

https://spark.lucko.me/YKXBYloh8y

### To Reproduce

https://spark.lucko.me/iofxSUxNxQ

https://spark.lucko.me/YKXBYloh8y

**Comment by amarcais53** [comment]
your issue most likely come from supreme essentials 
![image](https://user-images.githubusercontent.com/62488520/180269179-5d4502f3-dc21-4fb3-8474-4c0cf1ada869.png)

**Comment by OmerBenGera** [comment]
As you've seen, that's not related to WildStacker.
WildStacker calls the EntityDeathEvent, therefore if another plugin is the source of the lag, it will show under WildStacker even tho it isn't.

Closing this for now :)
