### ISSUE TITLE
Spawners Override 

### ISSUE THREAD

**Issue by RandomUser4510** [BG-Software-LLC/WildStacker#545]
### Minecraft's Version

1.17.1

### Plugin's Version

Lattest

### Describe the bug

Before going into more details, "spawners-override" works on +1.17?

### To Reproduce

Before going into more details, "spawners-override" works on +1.17?

### Additional Information

Before going into more details, "spawners-override" works on +1.17?

**Comment by OmerBenGera** [comment]
Yes.
For further questions, ask for help on the discord server
This is not the place to do so
