### ISSUE TITLE
"fix-stack" pretty much breaks the 'bucket stack' setting.

### ISSUE THREAD

**Issue by ClickErrorxD** [BG-Software-LLC/WildStacker#546]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/87890013/179382211-54ec61e5-9941-4b9e-9117-0db17ba16dab.png)

### Plugin's Version

WildStacker-3.8.0.jar

### Describe the bug

Dropping stacked water/lava buckets instantly turns the stacked item into 1x item... upon picking them up, you only get one, not the stack you originally dropped.

### To Reproduce

Stack your buckets via a chest.
Drop the stack on the ground.
Pick the "stack' up.

### Additional Information
https://gyazo.com/64d025f34da4ca847237e1802f03a95a

**Comment by OmerBenGera** [comment]
I can't replicate the issue - it seems like something is changing the buckets amount to not be 16.
Are you able to replicate the issue yourself on a server with only WildStacker installed?

**Comment by ClickErrorxD** [comment]
> I can't replicate the issue - it seems like something is changing the buckets amount to not be 16. Are you able to replicate the issue yourself on a server with only WildStacker installed?

I can go ahead and give this a try now.

**Comment by ClickErrorxD** [comment]
> I can't replicate the issue - it seems like something is changing the buckets amount to not be 16. Are you able to replicate the issue yourself on a server with only WildStacker installed?

Yea, on a server with JUST wildstacker, the bucket's drop as 16 and pickup as 16. Even with FIx-stack enabled or disabled. Do you got any ideas of what might stop the buckets from stacking? Spawner's and item's still stack on our server,

**Comment by OmerBenGera** [comment]
> > I can't replicate the issue - it seems like something is changing the buckets amount to not be 16. Are you able to replicate the issue yourself on a server with only WildStacker installed?
> 
> Yea, on a server with JUST wildstacker, the bucket's drop as 16 and pickup as 16. Even with FIx-stack enabled or disabled. Do you got any ideas of what might stop the buckets from stacking? Spawner's and item's still stack on our server,

Sorry for the long waiting time.
No, sadly not - I do not have an idea of what may cause it to happen.
Try adding plugins one by one until the issue happens again.
Also, make sure you use the same configuration as you have on your public server, maybe it's something in your configuration file that causes this weird behavior

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know by replying to this issue
