### ISSUE TITLE
Non-stacked mob can't be nerfed

### ISSUE THREAD

**Issue by Ammorack** [BG-Software-LLC/WildStacker#550]
### Minecraft's Version

1.17
NFT-Worlds-1.17.1.jar

### Plugin's Version

WildStacker version 3.8.0.317

### Describe the bug

Mob who is not stacked - single mob, he bypasses config and can't be nerfed.

### To Reproduce

Config setup:

1. Creeper will not stack if spawn reason is spawn egg
2. Nerf Creeper in config

### Additional Information

We tested and it somehow do not work with single mob stack, because if stack have 1+ mobs, those nerf parameter's work.

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send it here

**Comment by OmerBenGera** [comment]
I cna't replicate the issue. 
Also, according to your config, creepers cannot have stack sizes at all (they are limited to 1 only)

**Comment by Ammorack** [comment]
https://pastebin.com/D9Yc211e
Big sorry, wrong config, try with this config. This is right one.

**Comment by OmerBenGera** [comment]
If CREEPER is blacklisted, it cannot be nerfed - that's an intended behavior.

**Comment by OmerBenGera** [comment]
Closing this as it doesn't seem like a bug.
If you have further questions, let me know
