### ISSUE TITLE
Experience Not Dropping

### ISSUE THREAD

**Issue by noulalu** [BG-Software-LLC/WildStacker#552]
### Minecraft's Version

1.8.8

### Plugin's Version

Latest Release

### Describe the bug

Experience From Everything Is Not Dropping, Including Bottle'o Enchanting

### To Reproduce

Use a bottle'o enchanting or kill a mob

**Comment by OmerBenGera** [comment]
How is it related to the plugin..?

**Comment by OmerBenGera** [comment]
I tried to replicate the issue and xp is dropping just fine for me, which makes me believe another plugin disabling xp from being dropped.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
