### ISSUE TITLE
Piglins Not Stacking

### ISSUE THREAD

**Issue by noulalu** [BG-Software-LLC/WildStacker#553]
### Minecraft's Version

1.8.8

### Plugin's Version

Latest Release

### Describe the bug

Piglins Arent Stacking, I Have Removed Them From The Filtered Transformations But They Still Arent Stacking. Natural Spawned Piglins Wont Stack, But Piglins From Spawn Eggs Stack.

### To Reproduce

Spawn A Piglin From Spawn Egg, And Find Piglins In The Nether.

**Comment by OmerBenGera** [comment]
In newer versions of the game, mobs that spawn naturally will not always stack do to how entities are loaded into the game.
The solution is to enable stack-interval
