### ISSUE TITLE
Scoreboard.dat too big

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/WildStacker#554]
### Minecraft's Version

1.8.8 - Paper

### Plugin's Version

Dev build "WildStacker-3.8.0-b319.jar"

### Describe the bug

Scoreboard getting too big due to wildstacker (scoreboard.dat is only 2 days old and it has 750k entities saved) I've to remove the scoreboard.dat every 2 days or it'll being start doing crashes randomly

### To Reproduce

I think having a high amount of spawners in the entire server (I'm running a superiorskyblock skyblock gamemode)

### Additional Information

![image](https://user-images.githubusercontent.com/60794574/179467194-326c1e78-9590-46b2-9af6-721a9ae5fecf.png)

**Comment by OmerBenGera** [comment]
In 1.8.8 data of entities and items are saved into the scoreboard. You can change this by installing NBTInjectoe

**Comment by ArefyNetwork** [comment]
> In 1.8.8 data of entities and items are saved into the scoreboard. You can change this by installing NBTInjector

I installed (NBT API 2.10.0) enabling nbtinjector on config.yml, but doesn't print that wildstacker is using nbtinjector on console log
