### ISSUE TITLE
Visual glitch when breaking spawners - they show up as pigs

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/WildStacker#556]
### Minecraft's Version

paper 1.19 latest build

### Plugin's Version

3.8.0.316

### Describe the bug

Whe I give a spawner, example wolf (x5) and I place this stacked spawner and I break this, the wolf spawner was replace with a pig spawner.

### To Reproduce

- /ws give PSEUDO spawner wolf 5
- Break the stacked spawner
- And you can see pig spawner instead of the wolf spawner

### Additional Information

Vidéo:

https://cdn.discordapp.com/attachments/808881071298707456/999243463113580626/Minecraft_1.19_-_Multiplayer_3rd-party_Server_2022-07-20_11-12-28.mp4

**Comment by OmerBenGera** [comment]
Check if it happens if you only have WildStacker installed on your server

**Comment by Teyir** [comment]
I have the same issue with the same server jar file et and with only wildstacker 
![image](https://user-images.githubusercontent.com/60007549/179968176-c1700343-e55c-4077-9616-10ca427ec3d8.png)

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
I didn't watch the video as it requires me to download it. If you want me to look at it, please upload it to an online streaming service and send a link to it here.

**Comment by Teyir** [comment]
This is the video → https://youtu.be/KAqkyW0wh6s

**Comment by Teyir** [comment]
This is the video → https://youtu.be/KAqkyW0wh6s

@OmerBenGera

**Comment by OmerBenGera** [comment]
This is only a visual glitch.
If you relog, does it fix itself?

**Comment by Teyir** [comment]
> This is only a visual glitch (you can see in the messages they are all detected as "wolf" spawners) If you relog, does it fix itself?

Relog ?

**Comment by OmerBenGera** [comment]
> > This is only a visual glitch (you can see in the messages they are all detected as "wolf" spawners) If you relog, does it fix itself?
> 
> Relog ?

Leave and join the server, or leave the chunk and come back

**Comment by OmerBenGera** [comment]
This looks like an issue with Spigot. When cancelling the break event, the spawner is shown as pig even tho it isn't.
This is a visual glitch only as I stated before, and I will report it to Spigot so they can fix it.

Closing this for now

**Comment by OmerBenGera** [comment]
For reference, here's the issue I opened:
https://hub.spigotmc.org/jira/browse/SPIGOT-7129

**Comment by OmerBenGera** [comment]
@Teyir 
After some testings, it looks like an issue with ViaVersion.
I removed completely WildStacker and it still happens, however once I removed ViaVersion it fixed itself.

I'll report it over them.

**Comment by Teyir** [comment]
> @Teyir 
> After some testings, it looks like an issue with ViaVersion.
> I removed completely WildStacker and it still happens, however once I removed ViaVersion it fixed itself.
> 
> I'll report it over them.

I don't have ViaVersion on my servers

**Comment by OmerBenGera** [comment]
> > @Teyir
> > After some testings, it looks like an issue with ViaVersion.
> > I removed completely WildStacker and it still happens, however once I removed ViaVersion it fixed itself.
> > I'll report it over them.
> 
> I don't have ViaVersion on my servers

It still happens for me without WildStacker and it only got fixed by removing ViaVersion.
You might have something else that causes it then.
This is not an issue with WildStacker anyways.

**Comment by Teyir** [comment]
> > > @Teyir
> > > After some testings, it looks like an issue with ViaVersion.
> > > I removed completely WildStacker and it still happens, however once I removed ViaVersion it fixed itself.
> > > I'll report it over them.
> > 
> > I don't have ViaVersion on my servers
> 
> It still happens for me without WildStacker and it only got fixed by removing ViaVersion.
> You might have something else that causes it then.
> This is not an issue with WildStacker anyways.

I have try with a paper server 1.19 with only wildstacker 

( I have try with 2 servers)
