### ISSUE TITLE
Problem with feature limiting entities per chunk

### ISSUE THREAD

**Issue by Fredh1000** [BG-Software-LLC/WildStacker#557]
### Minecraft's Version

GuardSpigot 1.8.8

### Plugin's Version

Stable build 3.8.0

### Describe the bug

When you move an existing stack to another chunk with a FULL entity stack inside (which for example has a limit of 2000 and has 2000 mobs) the stack you moved will not despawn and by doing so you can even get to 10 stacks in a single chunk.

### To Reproduce

Create a full entity stack in one chunk, create another stack in another chunk, and finally move the created stack to the chunk where the other full stack is. 
P.S. I PUT THE ENTITY LIMIT FOR CHUNK AT 1.

### Additional Information

I can send a screenshot. However I recommend setting the entity chunk limiter by entity, just like you did for spawners.
![screen](https://user-images.githubusercontent.com/82319919/179974644-56797c4e-b6f1-46d8-8d01-33bd68fb0b06.jpg)

**Comment by OmerBenGera** [comment]
Not a bug.
Chunk limit will only limit newly spawned entities.
