### ISSUE TITLE
Thread dump error

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/WildStacker#558]
### Minecraft's Version

paper 1.19 #65

### Plugin's Version

3.8.0.316

### Describe the bug

I have this error on my console → https://paste.gg/p/anonymous/f36bc47ba4ec4a1aafa3dff8f9e90172

### To Reproduce

I just kill some stacked mobs (x15 zombie, wolf, chickens)

**Comment by OmerBenGera** [comment]
Duplicate of #536
