### ISSUE TITLE
Entities show stacked names even when the stack amount is 0

### ISSUE THREAD

**Issue by Maroon28** [BG-Software-LLC/WildStacker#559]
### Minecraft's Version

 git-Purpur-1612 (MC: 1.18.2)*

### Plugin's Version

3.8.0, not a dev build

### Describe the bug

Title. When you kill an entity that isn't stacked, their name briefly shows up as `x0 <name>`. This is more easily seeable with the ender dragon or a wither, since their names are on bossbars. Furthermore, the behaviour of unstacked entities is changed, I.E they don't play the crit sound when killed with a 1 shot. 

### To Reproduce

- Install the plugin, disable stacking of all non-spawner entities
- Spawn the ender dragon, or kill any normal entity
- They don't play the crit sound on the final hit, and they display their names as x0 <entity>

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
