### ISSUE TITLE
Enderman taking water damage even with nerfed entities!

### ISSUE THREAD

**Issue by RandomUser4510** [BG-Software-LLC/WildStacker#562]
### Minecraft's Version

1.17

### Plugin's Version

Lattest

### Describe the bug

Enderman taking water damage even with nerfed entities!

### To Reproduce

Enderman taking water damage even with nerfed entities!

### Additional Information

Enderman taking water damage even with nerfed entities!

**Comment by OmerBenGera** [comment]
WildStacker uses spigot nerfing system and cannot change its behavior. Therefore, if endermans take damage from water, nothing can be done regarding this

**Comment by RandomUser4510** [comment]
After this message you can close the issue... 
Is it possible through a separate plugin? Or is there no such possibility.

**Comment by OmerBenGera** [comment]
> After this message you can close the issue... Is it possible through a separate plugin? Or is there no such possibility.

If you make a separate plugin that changes the way nerfing works, then sure it should work
