### ISSUE TITLE
Piglins wont barter with dropped gold

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#565]
### Minecraft's Version

1.19 paper build 81

### Plugin's Version

dev b323

### Describe the bug

Piglins do not pickup dropped gold and successfully barter

### To Reproduce

Drop gold ingots on the ground with a non stacked piglin and watch them not barter, you can even drop entire stacks without a barter happening.

### Additional Information

Happens with just wildstacker installed, tested after this video below. I removed wildstacker and the issue is resolved.

https://www.youtube.com/watch?v=wI0HSggLcwQ

**Comment by OmerBenGera** [comment]
Are they nerfed?

**Comment by Skizzles** [comment]
> Are they nerfed?

They are not nerfed.

**Comment by Skizzles** [comment]
nerfed-entities:
    # A list of entities that will be nerfed.
    # If you want all entities to be nerfed, set this to [].
    whitelist:
    - TEST
    # A list of entities that won't be nerfed.
    blacklist: []
    # A list of worlds that entities can be nerfed in.
    # If you want entities to be nerfed inside all worlds, set this to [].
    worlds: []
    # Should nerfed entities be able to teleport?
    teleport: false

**Comment by OmerBenGera** [comment]
> > Are they nerfed?
> 
> They are not nerfed.

I will look into if

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
