### ISSUE TITLE
Wither Skeleton Sword drops are always full durability

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#566]
### Minecraft's Version

1.19 paper dev 81

### Plugin's Version

dev 323

### Describe the bug

All stone swords dropped from wither skeletons are full durability

### To Reproduce

Spawn a wither skeleton
Kill it for a sword drop
See full durability

### Additional Information

This has broken in the past so seems to be a reoccurring issue. Removing wildstacker resolves the issue and I also tested with just wildstacker installed.
https://youtu.be/dyeConvsx1U

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
