### ISSUE TITLE
Spawner issue in 1.19

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#567]
### Minecraft's Version

1.19

### Plugin's Version

b323

### Describe the bug

Hello when i place spawner it became pig spawner like my video https://pics.revolis.fr/2022/07/31/14-18_QOjA.mp4 .

### To Reproduce

Place spawner and try to stack them.

**Comment by OmerBenGera** [comment]
Duplicate of #556
