### ISSUE TITLE
NMS update 1.19.1

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#570]
### Minecraft's Version

pufferfish 1.19.1

### Plugin's Version

b322

### Describe the bug

Error in console due to nms not updated, hope it will help you to update (or not at all, lol, but I prefer reporting)
https://pastebin.com/7nTkXqna

### To Reproduce

use 1.19.1

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
