### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Ignius14** [BG-Software-LLC/WildStacker#571]
### Minecraft's Version

1.19 paper

### Plugin's Version

Latest

### Describe the bug

Just giving errors in perfect written upgrades section

### To Reproduce

Just watch the photo

### Additional Information

![90DDBAEF-DA2C-412B-A7AD-94E51E6E5A0B](https://user-images.githubusercontent.com/105884828/182407955-7517dbaf-812a-4530-b913-37008aaa927e.png)

**Comment by Ignius14** [comment]
Config: paste.helpch.at/xoduyaveqe.bash

**Comment by OmerBenGera** [comment]
Do not open issues for other things than bug reports.

For your question, you have an misconfigured menu - reset it and it will work again.
Closing this
