### ISSUE TITLE
WildStacker bug Holograms

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#575]
### Minecraft's Version

paper-1.19.1-105

### Plugin's Version

WildStacker-3.8.0-b328

### Describe the bug

the holograms don't appear and the items don't group correctly, I broke a chest and the items stayed on the floor, but the hologram didn't appear, but when I got my inventory it was full and the hologram updated.

1° https://prnt.sc/GaH2x-pFNRYl
2° https://prnt.sc/_S5KjbjNYZFp
3° https://prnt.sc/m0QKZe7p0V86

I tested it on the server with only wildstacker, and the problem continues.

1° https://prnt.sc/hB9PCCr1x2nQ

### To Reproduce

fill a chest with items and break it, the holograms do not appear.

**Comment by OmerBenGera** [comment]
It works fine for me, I can't replicate the issue.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
