### ISSUE TITLE
WildStacker Item Dupe !!

### ISSUE THREAD

**Issue by poyu39** [BG-Software-LLC/WildStacker#576]
### Minecraft's Version

![版本](https://user-images.githubusercontent.com/42506064/183009590-11b8abfd-21f5-41f8-9811-23277b5571ab.PNG)

### Plugin's Version

![版本2](https://user-images.githubusercontent.com/42506064/183009685-6f2cf89b-50a7-4468-9112-a5486e783682.PNG)

### Describe the bug

When item on ground from Vanilla type to WildStacker type, can take out more items from it by some trick.

In this video is auto redstone machine to check item count and use dropper to take item.(also can use hand)

like a auto dupe machine.

### To Reproduce

https://www.youtube.com/watch?v=e2hiqaqXrd4&ab_channel=Poyu

### Additional Information

I think this horrible bug have a long time. (maybe since 1.16.5?)

Duplication is a big blow to game balance, so hope can fix it soon.

It's hard to find records by CoreProtect, if player don't have a lot of thing.

**Comment by OmerBenGera** [comment]
I don't understand in what direction blocks are facing, what block types you use there, etc.
Take the video again without any texture pack on, or at least explain (even in text) how to build this machine.

**Comment by poyu39** [comment]
Sorry, my english is poor QQ 

![2022-08-05_20 39 57](https://user-images.githubusercontent.com/42506064/183081082-3e2d46c7-e041-42f3-855b-993ada2c7897.png)

open the switch can keep throwing item out

this is litematica file
[https://drive.google.com/file/d/1m3m436OXS-EuH0PBru3DH6FdGfFngxt2/view?usp=sharing](url)

**Comment by OmerBenGera** [comment]
> https://drive.google.com/file/d/1m3m436OXS-EuH0PBru3DH6FdGfFngxt2/view?usp=sharing

Are these droppers?
Also, to which direction does the observer point?

**Comment by poyu39** [comment]
Yes there are two dropper.
And Observer is looking right in that screenshot.

**Comment by poyu39** [comment]
There are some link broken, so i edit to a new versoin.(youtube and google drive)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
