### ISSUE TITLE
Plugin fails with "does not support your version mappings" (MC1.19 Paper e4f21e3)

### ISSUE THREAD

**Issue by Beanzilla** [BG-Software-LLC/WildStacker#577]
### Minecraft's Version

This server is running Paper version git-Paper-60 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e4f21e3)

paper.jar

### Plugin's Version

Loading WildStacker v3.8.1.331 (Yes dev release)

### Describe the bug

WildStacker does not support your version mappings... Please contact @Ome_R

### To Reproduce

N/A (I just grabbed the plugin and dropped it into an existing setup)

### Additional Information

I've also tried WildStacker 3.8.1 (non-dev) and got this issue, was thinking the dev version might be a bit newer and thus not have this issue. (but appears I still get it, :disappointed:)

I also get this same issue with:
- WildTools (v2.13.1.78)
- WildChests (v2.4.1.69)
- WildLoaders (v1.2.1.56)

> I'll be making a issue mentioning this into the other repos (just so each one has a copy of this information filled in).

**Comment by Beanzilla** [comment]
I've made an issue in WildTools too, but I'll stop there since each issue probably is pinging you (which I didn't want to do, I'm not that kind of person).

**Comment by Beanzilla** [comment]
Trying `This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)`

**Comment by OmerBenGera** [comment]
1.19 is not supported, update to 1.19.1
