### ISSUE TITLE
Thread dumps: - 381 - WildStacker

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#579]
### Minecraft's Version

paper-1.19.2-114

### Plugin's Version

WildStacker-3.8.1-b333.jar

### Describe the bug

https://mclo.gs/yrgdDfo

### To Reproduce

no erros console

**Comment by OmerBenGera** [comment]
Update to latest versions, already been fixed

**Comment by SrMonsterYT** [comment]
> Atualização para as versões mais recentes, já corrigidas

I don't see another build, only WildStacker-3.8.1-b333 on the site, is it going to be updated or is it that version there? that one I'm already using.

**Comment by OmerBenGera** [comment]
My bad, I misread the issue.
I will look into ig

**Comment by SrMonsterYT** [comment]
https://mclo.gs/JxGWk7M

**Comment by SrMonsterYT** [comment]
> My bad, I misread the issue. I will look into it

https://mclo.gs/yvHOfHe

**Comment by OmerBenGera** [comment]
> > My bad, I misread the issue. I will look into it
> 
> https://mclo.gs/yvHOfHe
> 
> my server crashed after a few hours. https://mclo.gs/SqglMG2
> 
> is the only mistake I have

There is no need to keep posting the same error over and over again.
I will look into it once I am at home, be patient.
You can disable exp using another plugin for now as a temporary fix
Also, the plugin is open source, you can try and fix it yourself.

**Comment by SrMonsterYT** [comment]
> > > My bad, I misread the issue. I will look into it
> > 
> > 
> > https://mclo.gs/yvHOfHe
> > my server crashed after a few hours. https://mclo.gs/SqglMG2
> > is the only mistake I have
> 
> There is no need to keep posting the same error over and over again. I will look into it once I am at home, be patient. You can disable exp using another plugin for now as a temporary fix Also, the plugin is open source, you can try and fix it yourself.

what is exp? in the settings? in which part? my server has crashed 5 times, which option should I disable

**Comment by OmerBenGera** [comment]
> > > > My bad, I misread the issue. I will look into it
> > > 
> > > 
> > > https://mclo.gs/yvHOfHe
> > > my server crashed after a few hours. https://mclo.gs/SqglMG2
> > > is the only mistake I have
> > 
> > 
> > There is no need to keep posting the same error over and over again. I will look into it once I am at home, be patient. You can disable exp using another plugin for now as a temporary fix Also, the plugin is open source, you can try and fix it yourself.
> 
> what is exp? in the settings? in which part? my server has crashed 5 times, which option should I disable

exp from mobs.
You can install an external plugin that disables it and it will temporary fix the issue.

**Comment by SrMonsterYT** [comment]
> 

Can you tell me some please, and sorry to send so many messages but my server has already crashed 6, and I tried to go back to previous versions but it disables the plugin, can you tell me some plugin to do this?

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it's fixed.

**Comment by SrMonsterYT** [comment]
I'll check it out and let you know

**Comment by SrMonsterYT** [comment]
new error: https://mclo.gs/WMuoL92

**Comment by OmerBenGera** [comment]
> new error: https://mclo.gs/WMuoL92

Fixed in latest dev build.
I am closing this one for now.
If the issue still occurs, let me know
