### ISSUE TITLE
Spawned mobs do not correctly update nametag when dying

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#580]
### Minecraft's Version

1.19.1

### Plugin's Version

3.8.1

### Describe the bug

When killing a stacked mob, their nametag does not update correctly to represent the size of the stack

### To Reproduce

Kill stacked mobs and watch the nametag not go down (I did it with blazes)

**Comment by ArmonicPvP** [comment]
Yep, I just tested this again on some Chickens that I was able to one-shot and the issue seems to no longer occur. It still doesn't seem to update that fast, but as long as it updates!

**Comment by OmerBenGera** [comment]
Healthbar plugins are not supported
Disable the healthbar and it will work again
