### ISSUE TITLE
Plugins no longer work in 1.19

### ISSUE THREAD

**Issue by GekoOff** [BG-Software-LLC/WildStacker#581]
### Minecraft's Version

1.19 Paper

### Plugin's Version

WildTools => 2.13.1
WildStacker => 3.8.1

### Describe the bug

The plugins is displayed in red in the list of plugins, and moreover, when I type a command, it tells me that there is an internal error!

### To Reproduce

I put the plugins file in the plugins files of the server, I launch it, I do /pl to see the plugins (it is displayed in red) then I do some command of the two plugins with the message that there is an internal error...

### Additional Information

Please fix that x) Thx

**Comment by Beanzilla** [comment]
Yeah see #577

> If you can just upgrade to 1.19.1

**Comment by OmerBenGera** [comment]
1.19 is not supportrd anymore
