### ISSUE TITLE
Holographics bug

### ISSUE THREAD

**Issue by wbejgli** [BG-Software-LLC/WildStacker#582]
### Minecraft's Version

1.16.5 / Spigot

### Plugin's Version

Wild stacker version: 3.8.1-b333

### Describe the bug

if I place a spawner, **I don't see the hologram**, or **sometimes it is visible**, but even then with **max 3-4 spawners in 1 chunk**. I've already thought about **Spigot**'s fault, **that I configured it incorrectly**.

### To Reproduce

**Even if I put the spawner in another chunk**, its **hologram is not visible**.
![image](https://user-images.githubusercontent.com/111155888/184452003-ee172b9d-2ce1-4340-8c56-7d5f9497d881.png)

### Additional Information

![image](https://user-images.githubusercontent.com/111155888/184451462-0c99440e-88f5-4390-b86c-8c8d7ab106aa.png)
Here is a picture of the error, **which can be found inside the red circle**, **they are also stacked spawners**, but their **hologram is not visible**.

**Comment by OmerBenGera** [comment]
Can you replicate the issue on a server with only WildStacker installed on your server?

**Comment by wbejgli** [comment]
![image](https://user-images.githubusercontent.com/111155888/184481211-22184b8d-260f-461c-922f-588a49303205.png)

**Comment by wbejgli** [comment]
now im replaced with ws ver: 3.8.1
![image](https://user-images.githubusercontent.com/111155888/184492169-c95c8d3d-89f8-490e-8ef7-9005600ea26d.png)

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/111155888/184481211-22184b8d-260f-461c-922f-588a49303205.png)

This looks good to me, no?

**Comment by wbejgli** [comment]
yeah, its an another server, with only wildstacker
I think im going to re-config the ws

**Comment by OmerBenGera** [comment]
> yeah, its an another server, with only wildstacker I think im going to re-config the ws

Try coping your config from the server with the issue to the one that works, check if you can replicate the issue again.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
