### ISSUE TITLE
Disable certain loot table from mobs

### ISSUE THREAD

**Issue by WildCooding** [BG-Software-LLC/WildStacker#583]
### Minecraft's Version

This server is running Paper version git-Paper-79 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 22ac7d6)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-81 (MC: 1.19)

### Plugin's Version

WildStacker-3.8.0-b323

### Describe the bug

I wanted to disable the loot table of a mob by replacing everything in e.g the iron_golem.json with {}. But that did not work. I tried on different ways to disable the loot table from the plugin to not overwrite the loottables from other plugins or datapacks with custom drops.

### To Reproduce

1. Install WildStacker
2. Add a Custom mob drop via. loot-table (like a datapack) 
3. Kill the mob

Than you can see that, WildStacker overrides all other loot tabels

**Comment by OmerBenGera** [comment]
You cant disable loot tables.
Plugins can easily modify drops by changing them in EntityDeathEvent. Drops from datapacks are not supported but you can use other plugins / edit loot tables of the plugin for that.
