### ISSUE TITLE
NMS issue in 1.19.2

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#585]
### Minecraft's Version

1.19.2

### Plugin's Version

b337

### Describe the bug

Hello, when i place slime spawner i've this issue : https://hastebin.com/ricatomuvi.properties

After that spawner will be replace by pig spawner (After restart or chunk unload/load). but sometimes i do not have any error.

### To Reproduce

Place spawner/slime spawner and look console

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
