### ISSUE TITLE
API set stacked entity health

### ISSUE THREAD

**Issue by Crazzyguyy** [BG-Software-LLC/WildStacker#587]
### Minecraft's Version

using git-Purpur-1757 (MC: 1.19.2)

### Plugin's Version

3.8.1.337
dev build

### Describe the bug

Unable to set health of a stacked entity with getEntity().getLivingEntity().setHealth(new_health); or getEntity().setHealth(new_health); in teh API.

### To Reproduce

below is a pastebin of my listener, everything works perfectly except teh set health, added the delayed 20 tick part after recommened by Ome_R, preferable would work with just "event.getEntity().getLivingEntity().setHealth(new_health);"
(This plugin is made to kill a certain number of entities in a stack based on how much damage teh player does)

https://pastebin.com/Gmtu1W0s

**Comment by OmerBenGera** [comment]
> 

I am not sure if you know, but the feature you try to implement already exists in the plugin; look for "spread-damage" in the config file.
Also, I tested your code and it works flawlessly fine for me:
https://gyazo.com/43cd202e881b58baa4953f9652991cc8
It probably means another plugin interfaces with this.

**Comment by Crazzyguyy** [comment]
lmao, haven't used the plugin for a while, that used to not be there thanks!
is there a way too add a configurable damage multiplier?

**Comment by OmerBenGera** [comment]
> lmao, haven't used the plugin for a while, that used to not be there thanks! is there a way too add a configurable damage multiplier?

No, the plugin does not change damage from players.

**Comment by OmerBenGera** [comment]
I am closing this as there doesn't seem to be an issue.
If you need further help, you may ask on the discord server
