### ISSUE TITLE
WildStacker bug iron golem.

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#59]
when I reach this amount the server crashed I thought that this did not cause a problem because it is only 1 item but all this item crashes the server
and not to mention that the slimefun BASIC_CIRCUIT_BOARD item that drops from the iron golem because of slimefun dropped all that much of an item with only a few iron golem
another question because this amount of items brings down the server? so if i save 1kk of chicken and kill and drop many items can i bring down servers?
this only happened after I updated the wildstacker everything was normal I didn't put any new plugin or anything

proof: https://youtu.be/Ncc7YiECIuY 
proof 2: https://prnt.sc/1037lea

server version: 1.12.2
plugin version: WildStacker-b70.jar
my plugins: https://prnt.sc/1037ijh

it only happens with iron golem

**Comment by brasilcraft54** [comment]
just kill one iron golem and this happens see

1° https://prnt.sc/10382al
2° https://prnt.sc/10382rx

problem looks like wildstacker and slimefun and as I said nothing has been modified apart from wildstacker

**Comment by OmerBenGera** [comment]
So I understand: Slimefun adds a custom item to Iron Golems, and it causes the server to crash because of WildStacker?

**Comment by OmerBenGera** [comment]
??

**Comment by brasilcraft54** [comment]
> Então eu entendo: o Slimefun adiciona um item personalizado ao Iron Golems e faz com que o servidor trave por causa do WildStacker?

the wildstacker is sending too many rails and this is causing lag

**Comment by OmerBenGera** [comment]
> 
> 
> > Então eu entendo: o Slimefun adiciona um item personalizado ao Iron Golems e faz com que o servidor trave por causa do WildStacker?
> 
> the wildstacker is sending too many rails and this is causing lag

That's not what I asked. I asked if Slimefun adds the rails to Iron Golems or not.

**Comment by OmerBenGera** [comment]
How to make Slimefun to add the rails to Iron Golems so I can try and replicate it myself?

**Comment by brasilcraft54** [comment]
https://youtu.be/SuitfhdW49I  the slimefun track still has problems is the wildstacker because as I said nothing has been modified

**Comment by brasilcraft54** [comment]
> How to make Slimefun to add the rails to Iron Golems so I can try and replicate it myself?

just kill the iron golem and the rail will come in the drop

**Comment by OmerBenGera** [comment]
Any news regarding this?
When I tried to replicate it, I couldn't from what I remember. I received the correct amount of rails
