### ISSUE TITLE
Restarting the server breaks Jobs and mcMMO checks

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#590]
### Minecraft's Version

1.19.2

### Plugin's Version

WildStacker-3.8.1

### Describe the bug

When restarting the server, players are able to grind mcMMO and Jobs off of stacked mobs left after the restart. Possibly adding a kill existing stacks on restart could fix this?

### To Reproduce

Restart the server with an existing stack (mine was blazes) and watch as you now gain mcMMO from the existing stack

**Comment by OmerBenGera** [comment]
Why wouldnt you be able to do so?

**Comment by ArmonicPvP** [comment]
I thought there was a part of the config that disabled earning mcMMO from spawner/stacked mobs, but I can't find it anymore. Maybe when the mobs were nerfed it was disabled for earning mcMMO from them, I can't remember. I know the Jobs disabling one is in the Jobs config, so it probably cannot be fixed there. I found a workaround of just killing the stacks periodically, which fixes the issue.
