### ISSUE TITLE
Many spawners default as pig on placement

### ISSUE THREAD

**Issue by Rockin21** [BG-Software-LLC/WildStacker#591]
### Minecraft's Version

git-PufferfishPlus-24 (MC: 1.19)

### Plugin's Version

3.8.1

### Describe the bug

Various mob spawners do not work and turn to pig on placement, though they worked just fine before the addition of WildStacker.

### To Reproduce

Placing a mobspawner with the following item data does **NOT** work
![Capture](https://user-images.githubusercontent.com/110613392/186137451-f9bfbd2d-38b2-4824-b2ad-60f3658145c2.PNG)
:

**Comment by OmerBenGera** [comment]
"essentials:convert" is a hint to your issue.
Essentials interfacing with spawners and making them pigs instead of the actual spawner due to lack of permissions.
Not a bug with the plugin
