### ISSUE TITLE
NBTInjector not working on 1.8.8

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/WildStacker#592]
### Minecraft's Version

1.8.8 Paper

### Plugin's Version

Latest dev build

### Describe the bug

Scoreboard getting too big due to wildstacker (scoreboard.dat is only 2 days old and it has 750k entities saved) I've to remove the scoreboard.dat every 2 days or it'll being start doing crashes randomly

Already opened an issue before (https://github.com/BG-Software-LLC/WildStacker/issues/554) but I installed (NBT API 2.10.0) enabling nbtinjector on config.yml, but doesn't print that wildstacker is using nbtinjector on console log

Thanks again

### To Reproduce

![179467194-326c1e78-9590-46b2-9af6-721a9ae5fecf](https://user-images.githubusercontent.com/60794574/186620088-63cf0e77-3034-42f2-8b5f-4a08bf1be530.png)

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Seems to be fixed
If the issue still occurs, let me know
