### ISSUE TITLE
Big lag on mushrooms

### ISSUE THREAD

**Issue by MisterGranti67** [BG-Software-LLC/WildStacker#593]
### Minecraft's Version

pufferfish-paperclip-1.18.2-R0.1-SNAPSHOT-reobf.jar

### Plugin's Version

(always) WildStacker-3.8.1-b341

### Describe the bug

When the mushrooms are stacked (about 15,000, or even from 2500) the mspt begin to increase very well, even reaching 80 MSPT.
With very big lag in play.

### To Reproduce

- Activate the mushroom stack
- Wait until they are stacked at +15,000
- And you update the stack, such as harvesting mushrooms with an enchanted scissor to the maximum.

### Additional Information

![freeze-serveur-preuve](https://user-images.githubusercontent.com/43696669/187022066-2d4b712d-739e-4170-83bc-9448075dfdb7.png)

**Comment by MisterGranti67** [comment]
My config : https://hastebin.com/ukabiwoveg.yaml

**Comment by OmerBenGera** [comment]
mushroom stacking?
What are you talking about?

**Comment by OmerBenGera** [comment]
Send me the spark profiler please.

**Comment by MisterGranti67** [comment]
Here is the spark made earlier: https://spark.lucko.me/nOhDHaAOAV

**Comment by OmerBenGera** [comment]
Seems like your server struggles with loading data of a new entity when shearing the mushroom cow.
My suggestion would be to disable stack split upon shearing mushrooms, which will not trigger this behavior.
