### ISSUE TITLE
Plugin WildStacker v3.8.1.341 generated an exception while executing task 29860882

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#597]
### Minecraft's Version

Pufferfish git-Pufferfish-34 (MC: 1.19.2)

### Plugin's Version

WildStacker #341

### Describe the bug

error -> https://mclo.gs/E2ZmLmN

### To Reproduce

I still don't know what is causing this

**Comment by SrMonsterYT** [comment]
https://mclo.gs/ObJxyfc

**Comment by OmerBenGera** [comment]
> https://mclo.gs/ObJxyfc

There is no need to report the same error over and over again.
Be patient, I will look into it when I can.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, let me know
