### ISSUE TITLE
EntityBreedEvent not being called

### ISSUE THREAD

**Issue by airoons** [BG-Software-LLC/WildStacker#599]
### Minecraft's Version

1.17.1, paper (but affects all versions with EntityBreedEvent)

### Plugin's Version

dev341

### Describe the bug

With smart breeding, EntityBreedEvent is not being called at all, should be called the same amount as babies are being spawned.
https://github.com/BG-Software-LLC/WildStacker/blob/dev/src/main/java/com/bgsoftware/wildstacker/listeners/EntitiesListener.java#L494

### To Reproduce

1. Breed a stack of mobs with smart-breeding enabled
2. Test with another plugin that uses EntityBreedEvent to see whether event is being called

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.
Btw, the event is only called once with the father and the mother being the same entity.
The stack size of the child is already set.
Calling the same event multiple times will cause lag, therefore not recommended.

**Comment by airoons** [comment]
Thank you, I can agree on lag but that would depend on the server setup (how large can mob stacks get, etc.). I'm using this for a "Breed" mission type I made (SuperiorSkyblock), so I implemented this fix similarly.
