### ISSUE TITLE
custom mob loot not working

### ISSUE THREAD

**Issue by Tzmo** [BG-Software-LLC/WildStacker#600]
### Minecraft's Version

1.19

### Plugin's Version

WildStacker-3.8.1-b341.jar

### Describe the bug

custom mob loot doesnt seem to work at all for me after running "/wstacker reload" or restarting the server. i've tried killing the iron golem myself and letting it burn in lava, still only drops iron and poppy. 

config.yml: https://pastebin.com/fAfNaTKL
iron_golem.json: https://pastebin.com/6tWSDUYU

### To Reproduce

.

**Comment by Tzmo** [comment]
i think i figured it out, if "entities" is turned off in the "config.yml", then the custom mob drops dont work

**Comment by OmerBenGera** [comment]
> i think i figured it out, if "entities" is turned off in the "config.yml", then the custom mob drops dont work

Right, intended :)
May I close this issue?

**Comment by Tzmo** [comment]
ah didnt realise it was intended, my bad
