### ISSUE TITLE
/wildstacker setting UI not responding

### ISSUE THREAD

**Issue by V0nCleef** [BG-Software-LLC/WildStacker#603]
### Minecraft's Version

git-Paper-135  MineCraft version: 1.19.2

### Plugin's Version

WildStacker-3.8.1-b349

### Describe the bug

When using /wildstacker:stacker settings you can only use the menu once.. before the button icons are moved to the top.
And then its very hard to use the setting UI

Also added an video file to show you an error in the console.
red line in console at time 2:28, dont know if this is related to the bug i experience.

And a video added to show you what i mean with above explanation.

### To Reproduce

When the server is freshly booted and i do /wildstacker:stacker settings i see a menu with buttons.
I can click a button and it will work fine.

Once i exit that menu and i return to the main menu the buttons will all be moved to the top, and pressing on the wont work.
The "buttons" are still on their supposed spot.. but its hard to know where.. since the icons all moved to a different spot.

This can be fixed restarting the server.. but then it will work only once before getting messed up again.

### Additional Information

https://user-images.githubusercontent.com/112802245/188503892-f6682675-7908-4beb-bb10-44e286fcdddd.mp4

https://user-images.githubusercontent.com/112802245/188504531-cd95e41c-c8c6-419f-abb5-705a903c26c5.mp4

**Comment by OmerBenGera** [comment]
Send me the error here via pastebin

**Comment by V0nCleef** [comment]
> Send me the error here via pastebin

It is one line, hopefully its OK if not done via pastebin.

`[19:57:21 ERROR] [WilldStacker] Plugin WildStacker v3.8.1.349 has failed to register events for class com.bgsoftware.wildstacker.hooks.SilkSpawnersHook$SilkSpawnersListener because de/dustplanet/silkspawners/events/SilkSpawnersSpawnerChangeEvent does not exist.`

**Comment by OmerBenGera** [comment]
Send me your entire logs.
Upload them to padtebin

**Comment by V0nCleef** [comment]
> 

https://pastebin.com/6gKsJBz0

now that i look at the log my self... i see that perhaps chestcleaner plugin is responsible for this?
since it will try to "order" the chest.. one i close the screen.
Actually i am 99% positive.... sorry for having wasted your time sir.

**Comment by OmerBenGera** [comment]
> > 
> 
> https://pastebin.com/6gKsJBz0
> 
> now that i look at the log my self... i see that perhaps chestcleaner plugin is responsible for this? since it will try to "order" the chest.. once i close the screen. Actually i am 99% positive.... sorry for having wasted your time sir.

Probably it cant handle the settings menu 
Contact their support for help :)
