### ISSUE TITLE
Guardian can't be nerfed

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#605]
### Minecraft's Version

Pufferfish 1.19.2-34

### Plugin's Version

b345

### Describe the bug

Guardian (and all water mobs) can't be nerfed.
It's a bug from mojang, but maybe you got a solution for this ?

### To Reproduce

- Put this config :
![image](https://user-images.githubusercontent.com/31826333/188729188-d1371fab-5102-47b5-b350-e9ae6a4c0a8c.png)
- Spawn guardians
- it moves

**Comment by OmerBenGera** [comment]
The nerfing system depends on spigot's. Therefore, if this is a bug in spigot, then I cant do anything regarding this

**Comment by WarnDa** [comment]
> You did when you requested Guardians don't move bounce up and down client side.
I will make the change, but Guardians will still move (note: this is a client side action, so you shouldn't be worried about it affecting server performance).

Can't do nothing, as it's client side (pretty weird for players, but no solution)
