### ISSUE TITLE
Residence Bug

### ISSUE THREAD

**Issue by bgprotobg2** [BG-Software-LLC/WildStacker#606]
### Minecraft's Version

1.8

### Plugin's Version

3.8.1

### Describe the bug

When the Spawner menu is enable players can enter in other people's residences and shift right click the spawners and remove it. Please add residence support or fix this issue

### To Reproduce

i explained above

### Additional Information

No

**Comment by OmerBenGera** [comment]
Disable the menu then.
If Residence not cnacelling the interaction with spawners, players will be able to open the menu.
