### ISSUE TITLE
Disabling Entity Stacking Doesn't work

### ISSUE THREAD

**Issue by HzDeimos** [BG-Software-LLC/WildStacker#607]
### Minecraft's Version

Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### Plugin's Version

3.8.0 and 3.8.1

### Describe the bug

I have disabled entity stacking, spawner stacking and spawner override, But entities from spawners keeps getting stacked.

### To Reproduce

Get a mob spawner and place it.

### Additional Information

![image](https://user-images.githubusercontent.com/86536884/189486204-b677d79d-9d23-4221-b36c-5b62359c59e4.png)
![image](https://user-images.githubusercontent.com/86536884/189486212-95f70ad9-3f18-4fde-9004-5270d595f71a.png)
![image](https://user-images.githubusercontent.com/86536884/189486337-dbd2fddb-db51-47c6-b1e2-e56c8fc17095.png)
![image](https://user-images.githubusercontent.com/86536884/189486346-bc13f9b9-ca39-4848-a1c2-1360e3f76b1d.png)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed.
If it still occurs, let me know by replying here
