### ISSUE TITLE
Mobs with same upgrade not stacking with others

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#608]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

WildStacker-3.8.1-b349

### Describe the bug

i'm currently having an issue where mobs are not being stacked somehow even after checking the upgrade and the spawn reason as i mentionned here on discord https://discordapp.com/channels/554276823010246687/554282642980470785/1018157769154637925

### To Reproduce

instal latest WS and add a lot of spawners , with time some of them will not stack and create another stack

### Additional Information
my config https://pastebin.com/DrH7UBps

_No response_

**Comment by amarcais53** [comment]
fixed it by remove the stack check name     UPGRADE: false

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
