### ISSUE TITLE
wildstacker stacked Executable items dropped can dupe 

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#609]
### Minecraft's Version

1.18.2

### Plugin's Version

WildStacker-3.8.1-b351

### Describe the bug

A dupe method can be used when Executable items is installed with wildstacker

### To Reproduce

1. get entire inventory full with 1 free slot
2. drop Executable items on the ground more than 64(128 is in video)
3. put into the chest
4. you can see item pick up does not reduce number of stacked item

https://youtu.be/12o8JhYqcJk

### Additional Information

ExecutableItems_Prem-5.3.1 (latest)
SCore-3.3.1 (core plugin for EI )
WildStacker-3.8.1-b351 (latest)

in case you want to contact the EI author:
his DC: https://discord.com/invite/TRmSwJaYNv
or Ssomar#2000

**Comment by OmerBenGera** [comment]
If they have a custom algorithm to pick up items, they will have to add support directly to WildStacker.

**Comment by OmerBenGera** [comment]
I understood from Ssomar that it was fixed on his end, therefore I am closing this :)
