### ISSUE TITLE
Spawn conditions do not work

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#611]
### Minecraft's Version

1.18.2 pufferfish

### Plugin's Version

dev-359

### Describe the bug

on lastest build the feature that can ovverride ''spawn-condition'' dosent work.. here the config i alway use https://pastebin.com/7KcWv5FG

Ex: cow dosent spawn on stone or creeper dosent spawn during the day

### To Reproduce

place spawner and see if it spawn with light during the day

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works
