### ISSUE TITLE
Mob loot tables from datapacks not dropping gear with Wildstacker

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#612]
### Minecraft's Version

1.19.2 purpur dev 1779

### Plugin's Version

Wildstacker dev 359

### Describe the bug

This is quite similar to https://github.com/BG-Software-LLC/WildStacker/issues/596 except the mobs dont drop the loot table at all. I am unsure if related, however unloading wildstacker from my server solves the issue (also with just wildstacker installed the issue is present).

### To Reproduce

- Use a data pack with loot tables: https://www.planetminecraft.com/data-pack/incendium-nether-expansion/
- Spawn the Hovering inferno with /function incendium:_admin_menu, clicking hovering inferno, clicking Spawn
- Kill the hovering inferno by clicking "End"

Nothing from the loot table gets dropped, this is the same with loot tables with other data packs.

### Additional Information

You can see in the video here:
https://screenshots.skizzles.me/wAnA3/ZEYAHaKU32.mp4

**Comment by OmerBenGera** [comment]
WS overrides the loot tables of the game.
Not a bug.

**Comment by Skizzles** [comment]
@OmerBenGera is there a way to disable wildstacker overriding loot tables for a specific mob type or just overriding handling of loot tables in general?

**Comment by Skizzles** [comment]
I don't really have a use case for custom loot tables through wildstacker and would prefer its handling just disabled so I could use data packs and such.

**Comment by OmerBenGera** [comment]
> @OmerBenGera is there a way to disable wildstacker overriding loot tables for a specific mob type or just overriding handling of loot tables in general?

Sadly not. The loot tables are used for better calculation of drops for large stack sizes.
You can customize the loot inside WildStacker instead of the datapack.

**Comment by Skizzles** [comment]
> > @OmerBenGera is there a way to disable wildstacker overriding loot tables for a specific mob type or just overriding handling of loot tables in general?
> 
> Sadly not. The loot tables are used for better calculation of drops for large stack sizes. You can customize the loot inside WildStacker instead of the datapack.

Sadly the datapack spawns and handles loot among other things like worldgen and such. I guess I will have to find a way around it.
