### ISSUE TITLE
Some sort of bug

### ISSUE THREAD

**Issue by RandomUser4510** [BG-Software-LLC/WildStacker#616]
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

lattest

### Describe the bug

console error https://pastebin.com/SCgUPdGW

### To Reproduce

use lattest version , should be enought https://pastebin.com/SCgUPdGW

### Additional Information

Having this mensage spamming on console 

https://pastebin.com/SCgUPdGW

**Comment by ItzFabb-uwu** [comment]
This issue was a known issue on:
https://github.com/BG-Software-LLC/WildStacker/issues/473

**Comment by ItzFabb-uwu** [comment]
For anyone having issues with mobs being invincible/not dying , in config.yml set https://prnt.sc/ID6_TOqpHtGK and restart.

Credits to:  
![image](https://user-images.githubusercontent.com/58950562/191518881-83b31a29-b8c1-447f-9726-da5edd99d6cb.png)

**Comment by OmerBenGera** [comment]
Duplicate of #473 

The temp-solution above will work.
