### ISSUE TITLE
Singel item doesn't show their tags

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/WildStacker#617]
### Minecraft's Version

1.8.8 Winespigot (v3913)
![image](https://user-images.githubusercontent.com/58950562/191517581-c906fd46-cfee-4475-83d2-c5679a70c7ce.png)

### Plugin's Version

![Uploading image.png…]()

### Describe the bug

Single item when get dropped their tag won't showed.

### To Reproduce

Drop 1x items it should show (x1 Grass Block)

### Additional Information

https://youtu.be/dumDfitxP0Y

**Comment by ItzFabb-uwu** [comment]
![image](https://user-images.githubusercontent.com/58950562/191518179-bdeb9f91-ce79-4d09-9b47-33f627364f3a.png)

**Comment by OmerBenGera** [comment]
You need to enable it in the config file so it will work, as it is not enabled by default.
