### ISSUE TITLE
Custom-Items Issue

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/WildStacker#618]
### Minecraft's Version

1.8.8 Winespigot (v3913)

### Plugin's Version

![Uploading image.png…]()

### Describe the bug

There's an issue with
```
LOG2:0: 'Acacia Log'
LOG2:1: 'Dark Oak Log'
```
Custom Items Name it's not working on 1.8.8 for some reason.

### To Reproduce

Use 1.8.8 winespigot v3913 and try to put this config
```
###############################################
##                                           ##
##          WildStacker Custom Names         ##
##            Developed by Ome_R             ##
##                                           ##
###############################################

# Should this feature be enabled?
enabled: true

# Here you can specify custom types for entities & items.
# Please follow the "ITEM_TYPE: CUSTOM_NAME", "'ITEM_TYPE:ITEM_DATA': CUSTOM_NAME" and "ENTITY_TYPE: CUSTOM_NAME" formats.
# {0} represents item's name, if found

INK_SACK:15: 'Bone Meal'
STONE:1: 'Granite'
STONE:2: 'Polished Granite'
STONE:3: 'Diorite'
STONE:4: 'Polished Diorite'
STONE:5: 'Andesite'
STONE:6: 'Polished Andesite'
DIRT:1: 'Coarse Dirt'
DIRT:2: 'Podzol'
GRASS: 'Grass Block'
WOOD:0: 'Oak Planks'
WOOD:1: 'Spruce Planks'
WOOD:2: 'Birch Planks'
WOOD:3: 'Jungle Planks'
WOOD:4: 'Acacia Planks'
WOOD:5: 'Dark Oak Planks'
LOG:0: 'Oak Log'
LOG:1: 'Spruce Log'
LOG:2: 'Birch Log'
LOG:3: 'Jungle Log'
LOG2:0: 'Acacia Log'
LOG2:1: 'Dark Oak Log'
SULPHUR: 'Gunpowder'
MOB_SPAWNER: '{0}'

```

### Additional Information

https://youtu.be/Fx_pqptpG50

**Comment by ItzFabb-uwu** [comment]
![image](https://user-images.githubusercontent.com/58950562/191520509-94597303-8fa5-49fd-8a00-82691dccd7c5.png)

**Comment by ItzFabb-uwu** [comment]
Also it seems to happend to all the others

LOG2
LEAVES2

**Comment by ItzFabb-uwu** [comment]
> Did you enable this feature in the config file?

Ome_R i got this issue fixed.

**Comment by ItzFabb-uwu** [comment]
> Did you enable this feature in the config file?

Turns out i have to follow the wildstacker's id instead of the real minecraft vanilla id.

**Comment by ItzFabb-uwu** [comment]
Because it's kinda confusing when it comes to wildstacker's id item

**Comment by ItzFabb-uwu** [comment]
If someone running onto the same issue here's a tutorial:
![image](https://user-images.githubusercontent.com/58950562/191558979-4db81ae0-0075-4c91-b280-f304688f99f5.png)

x64 Log 2 

Instead using the id:meta from minecraft's website you have to just follow the wildstacker id to
```
LOG_2:1: 'Dark Oak Log'
```
![image](https://user-images.githubusercontent.com/58950562/191559252-f572eeff-787e-4f3d-b4df-ce87376bd650.png)


And then do /ws reload
![image](https://user-images.githubusercontent.com/58950562/191559342-8df70cae-9111-4c65-9f45-3e356dbc3b96.png)


And Walla...
![image](https://user-images.githubusercontent.com/58950562/191559401-187774f1-1d24-46f1-9cd2-bd29ef1feaa1.png)

**Comment by OmerBenGera** [comment]
> If someone running onto the same issue here's a tutorial: ![image](https://user-images.githubusercontent.com/58950562/191558979-4db81ae0-0075-4c91-b280-f304688f99f5.png)
> 
> x64 Log 2
> 
> Instead using the id:meta from minecraft's website you have to just follow the wildstacker id to
> 
> ```
> LOG_2:1: 'Dark Oak Log'
> ```
> 
> ![image](https://user-images.githubusercontent.com/58950562/191559252-f572eeff-787e-4f3d-b4df-ce87376bd650.png)
> 
> And then do /ws reload ![image](https://user-images.githubusercontent.com/58950562/191559342-8df70cae-9111-4c65-9f45-3e356dbc3b96.png)
> 
> And Walla... ![image](https://user-images.githubusercontent.com/58950562/191559401-187774f1-1d24-46f1-9cd2-bd29ef1feaa1.png)

This is not WildStacker Id but Bukkit Ids.
In 1.8.8 they have a weird naming not matching vanilla. Use https://bg-software.com/material/ to find the correct names.
