### ISSUE TITLE
Entity Custom Tag Count not updating after changes (death)

### ISSUE THREAD

**Issue by Aeyos** [BG-Software-LLC/WildStacker#619]
### Minecraft's Version

Client: 1.19.2
Server: git-Paper-142
JRE: Java 17 (OpenJDK 64-Bit Server VM 17.0.4.1+1)
Host: Mac OS X 12.6 (x86_64)

### Plugin's Version

Latest dev version, 2022.5-b362

### Describe the bug

After killing some cows from a stack that were spawed from eggs, the custom name tag shows the correct amount and quickly reverts to the old number.

See this for more context:
  - Spawned 10x Cows from spawn eggs
  - Killed 5x Cows
  - Entity Custom Tag shows "10x Cows"
  - Inspector shows correct entity amount
  - Upon killing all cows, the stack dies but still showing 10x

<img width="596" alt="image" src="https://user-images.githubusercontent.com/4277681/192099975-8833636e-03a9-40d4-9853-d1d1f03d4714.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/4277681/192099987-29d887b0-b2bd-4476-80a8-6b83fd96ae9b.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4277681/192100017-cf55992d-e095-4f14-b059-34508009ef1f.png">

### To Reproduce

  - Spawn 10x Cows from spawn eggs
  - Kill 5x Cows with any tool
  - Use Inspector tool
  - Stack entity should show 10x Cows
  - Inspector tool should show 5x Cows
  - Spawn another cow from an egg
  - Stack entity shows correct number (6x Cows)
  - Inspector tool shows count == 6

![image](https://user-images.githubusercontent.com/4277681/192100120-4578485a-1986-4f6e-bb4f-61cf7308cef6.png)

### Additional Information

<img width="773" alt="image" src="https://user-images.githubusercontent.com/4277681/192100360-f48c6e7d-05c9-4e2c-9252-58f5d2d6e6bc.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/4277681/192100339-2c063268-b1c8-49b1-bd69-0b194c826abb.png">

**Comment by OmerBenGera** [comment]
Do you have mcmmo or another healthbar plugin?

**Comment by Aeyos** [comment]
@OmerBenGera yes, I do have mcmmo. Just a quick update: after spawning another egg the count is fixed

**Comment by OmerBenGera** [comment]
Healthbars are not supported and may break the custom names of entities (mcmmo has a healthbar)
disable it and it will work.
