### ISSUE TITLE
Cannot stack entities

### ISSUE THREAD

**Issue by TimeWasted13** [BG-Software-LLC/WildStacker#623]
### Minecraft's Version

1.19.2 Paper

### Plugin's Version

WildStacker v2022.5-b363

### Describe the bug

26.09 22:17:33 [Server] [ERROR] Could not pass event BlockPlaceEvent to WildStacker v2022.5-b363
26.09 22:17:33 [Server] [INFO] java.lang.NoSuchFieldError: P
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1192.spawner.StackedBaseSpawner.updateDemoEntity(StackedBaseSpawner.java:438) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1192.spawner.StackedBaseSpawner.<init>(StackedBaseSpawner.java:80) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1192.NMSSpawners.updateStackedSpawner(NMSSpawners.java:55) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:52) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:46) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:252) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:241) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:63) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:58) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:140) ~[WildStacker-2022.5-b363.jar:?]
26.09 22:17:33 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor922.execute(Unknown Source) ~[?:?]
26.09 22:17:33 [Server] [INFO] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
26.09 22:17:33 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
26.09 22:17:33 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
26.09 22:17:33 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:395) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:584) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1968) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-"b58c0cf"]
26.09 22:17:33 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]

### To Reproduce

Placing spawners, cannot use the GUI to increase the amount, entities cram and die

**Comment by OmerBenGera** [comment]
Try updating Paper to latest version, let me know if it works.

**Comment by TimeWasted13** [comment]
Didn't work, running paper-1.19.2-177. Also, noticed this error on startup

27.09 17:00:11 [Server] [ERROR] [WildStacker] Plugin WildStacker v2022.5-b363 has failed to register events for class com.bgsoftware.wildstacker.hooks.SilkSpawnersHook$SilkSpawnersListener because de/dustplanet/silkspawners/events/SilkSpawnersSpawnerChangeEvent does not exist.

**Comment by OmerBenGera** [comment]
How do you download Paper?
For me it works just fine.

**Comment by TimeWasted13** [comment]
I download it from https://papermc.io/downloads

- Stop the server
- Delete the old .jar
- Add the new one
- Change the .jar version in the startup
- Start server

**Comment by saffue** [comment]
i also have this issue, the plugin errors everytime i collect exp, load/ placing a spawner, and starting the server. i am running paper 182 

**loading the plugin**
https://paste.helpch.at/iyafubimoq.rb

**loading a spawner**
https://paste.helpch.at/ikeqehodic.rb

**placing/ a spawner**
https://paste.helpch.at/ofajibajar.rb

**collecting exp**
https://paste.helpch.at/taqilukapa.php

**Comment by l3igKev** [comment]
Can confirm this exact behaviour on my server instance.  

WildStacker v2022.5-b363
paper #182

errors every startup, every time a spawner is placed, but collect exp can be resolved with configuration change (as per discord sticky).

Disabled all other plugins, generated new world, same issue.
Downgraded to paper #173 and no more errors in logs. 

Issue possibly related to chunk system change in paper #174?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
