### ISSUE TITLE
Wilderstacker Causes Dupe With AutoShulker Plugin

### ISSUE THREAD

**Issue by EcoSMP** [BG-Software-LLC/WildStacker#626]
### Minecraft's Version

Pufferfish 1.18.2

### Plugin's Version

WildStacker-2022.5-b363

### Describe the bug

We use a plugin called AutoShulker which allows players to create shulkers that automatically collect certain items into the shulker instead of going into their inventory and then having to manually move them to the shulker. For example, a player can craft one that collects stone/deepslate as they mine so only the ores go into their regular inventory as the shulkers auto collect the mass amounts of regular stone/deepslate. 

There is a dupe where if the players inventory is full of other items and they attempt to pick up the item the autoshulker is set to collect, it wont actually pick up the items but dupes them into the shulker as if they are being picked up. The default function of the shulker is to simply not pick up any more items at all if the players inventory is full. However, with wildstacker on the shulker will still attempt to pick up the items and it does store them, but it never picks them up off the ground meaning you can dupe a full shulker of netherite blocks within 30-60 seconds for example.

We have removed all plugins and added them back one by one to find which one is causing an issue and it turns out its Wilderstacker. With Wildstacker disabled the issue stops and when its enabled the issue starts again. I want to make it clear that we are not saying this is a problem with Wildstacker itself necessarily, we are just asking for help potentially finding which option we could turn off/on in the Wildstacker config to stop this from happening. 

Any help you may be able to offer will be greatly appreciated!

### To Reproduce

1. Enable both Wildstacker & AutoShulker plugins

2. Create an auto shulker

3. Fill your inv all the way up

4. Drop the item the shulker is set onto the ground and walk over it and it will start duping the item into the shulker without ever actually picking it up off the ground.

### Additional Information

https://streamable.com/enlab6

**Comment by OmerBenGera** [comment]
Seems like the AutoShulker plugin conflicts with WildStacker's item stacking.
Mind giving me a link to that plugin so I can look at it and see why it occurs?

**Comment by OmerBenGera** [comment]
> Yes but unfortunately this is a premium plugin. Also, we do not use Wildstackers item stacking features. We only use entity stacking. Thanks again for your help!
> 
> https://www.spigotmc.org/resources/autoshulker.89807/

sadly because it's a premium plugin I can't take a look at it.
Contact their developer for help regarding this.

(Btw, even if you have stacked items disabled, WS will still handle items pickup)

**Comment by OmerBenGera** [comment]
@EcoSMP I rewrote the items pickup system in latest dev build.
Try it out, let me know if it's better.

**Comment by OmerBenGera** [comment]
> > @EcoSMP I rewrote the items pickup system in latest dev build. Try it out, let me know if it's better.
> 
> That is great news! We will try it out today

For reference, check out #632

**Comment by OmerBenGera** [comment]
> This does seem to have resolved the issue. We greatly appreciate this!

Awesome :)
