### ISSUE TITLE
Droping stacked item that are disabled from stacking make them disapear

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#627]
### Minecraft's Version

1.17.1 puffrerfish

### Plugin's Version

WildStacker-2022.5-b363.jar

### Describe the bug

I disabled item stacking for shulker boxes , but when people break a storage unit with shulker on it they get stacker shulkers on the inventory and if they drop them on the ground it delete all of them and keep only one since stacking is disabled

### To Reproduce

i explained up

**Comment by OmerBenGera** [comment]
Please upload the config file of WildStacker to pastebin and send it here.

**Comment by amarcais53** [comment]
> Please upload the config file of WildStacker to pastebin and send it here.

https://pastebin.com/xKUFhmpZ

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
