### ISSUE TITLE
Not shown MobSpawners' holograms.

### ISSUE THREAD

**Issue by Fredh1000** [BG-Software-LLC/WildStacker#628]
### Minecraft's Version

GuardSpigot 1.8.8

### Plugin's Version

WildStacker 2022.5 dev build #364

### Describe the bug

Spawners' holograms are not shown.
Mobs' holograms are shown!!!

### To Reproduce

Use the plugin with the spawner feature active, obviously with the hologram and see that it doesn't show it.

### Additional Information

![2022-10-01_12 28 22](https://user-images.githubusercontent.com/82319919/193405385-bb66f181-517f-445c-8ffa-07ca15984f1d.png)

**Comment by Fredh1000** [comment]
My WildStacker config:
https://pastebin.com/LVjaByxc

**Comment by OmerBenGera** [comment]
> My WildStacker config: https://pastebin.com/LVjaByxc

Try using default config file, let me know if it works.

**Comment by Fredh1000** [comment]
I tried and you can't see the holograms anyway.

**Comment by OmerBenGera** [comment]
> I tried and you can't see the holograms anyway.

Have you tried using PaperSpigot for 1.8.8?
I think the issue is an incompatibility with GuardSpigot

**Comment by Fredh1000** [comment]
The problem started when I updated the plugin to the latest dev build, previously I was using the stable build 3.8.1 and had no problems.

**Comment by OmerBenGera** [comment]
> The problem started when I updated the plugin to the latest dev build, previously I was using the stable build 3.8.1 and had no problems.

Try it on Paper, let me know if it still occurs.

**Comment by Fredh1000** [comment]
Ehmmmm, I am very stupid. I set the maximum number of armorstand to 0... ahahah. Sorry for the lost time and thanks for support!

**Comment by OmerBenGera** [comment]
huh I see
At least it is fixed :)
