### ISSUE TITLE
Blazes

### ISSUE THREAD

**Issue by bgprotobg2** [BG-Software-LLC/WildStacker#629]
### Minecraft's Version

1.8

### Plugin's Version

v2022.5 and the latest dev

### Describe the bug

When merge radius is enable the blazes are very bugged. They are spawning from the spawners for 5/10 mins and then they just disappear. They are not spawning anymore. If i kill the mobs they are spawning again. Every player in my server has this problem. Only the blazes have this issue.

### To Reproduce

I described it above

### Additional Information

No

**Comment by OmerBenGera** [comment]
What version of spigot do you use?
The exact output of /version please.
Also, upload your config to pastebin and send it here

**Comment by bgprotobg2** [comment]
![Screenshot 2022-10-01 230715](https://user-images.githubusercontent.com/51120459/193426534-b0a3dccd-9f9a-4194-b601-40b76b9bfa6b.png)
this is the spigot
[config.txt](https://github.com/BG-Software-LLC/WildStacker/files/9691129/config.txt)
this is the config

**Comment by OmerBenGera** [comment]
Please upload the config to pastebin and send it here.

**Comment by bgprotobg2** [comment]
https://pastebin.com/RExqsmLH

**Comment by OmerBenGera** [comment]
> https://pastebin.com/RExqsmLH

hey, thanks for the information.
I meant the config of WildStacker, mind uploading it as well and sending it here?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
@bgprotobg2

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know by replying here
