### ISSUE TITLE
spawner item stacking bug

### ISSUE THREAD

**Issue by Tzmo** [BG-Software-LLC/WildStacker#630]
### Minecraft's Version

1.19

### Plugin's Version

2022.5 #364

### Describe the bug

when `shift-place-stack` is set to `true` and you shift-place spawner stacks, it will merge the remaining spawner stacks into one spawner.

(max spawner stack size is set to 10 in the config aswell)

example: 

10 `x10 Enderman Spawner`
will turn into
1 `x90 Enderman Spawner`

### To Reproduce

https://www.youtube.com/watch?v=F2fXHkXOjok

**Comment by OmerBenGera** [comment]
This is not a bug.
You receive 90 spawners as you had 100 in your hand, 10 you placed down.
If you place these 90 again, you'll receive 80 back and so on.
