### ISSUE TITLE
Fox picks up item and deletes any other item in their mouth

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#632]
### Minecraft's Version

Purpur 1758 1.19.2

### Plugin's Version

Dev 366

### Describe the bug

When a fox picks up an item in their mouth and then picks up another item they are supposed to drop the current item they have. With WildStacker installed the item just gets deleted.

### To Reproduce

Drop an item to a tamed fox
Wait for the fox to pick it up
Drop another item to the same tamed fox
Watch the item get deleted

### Additional Information

Tested with just wildstacker installed, issue fixes when removing wildstacker.

**Comment by OmerBenGera** [comment]
Check out latest dev build, I rewrote the entire item pickup system.
It should hopefully work better for all mobs, and always.

Let me know if you face any issues with it

**Comment by Skizzles** [comment]
Seems to be working great! Fox now drop the item from their mouth :)
