### ISSUE TITLE
MMOitems bug with new damage system

### ISSUE THREAD

**Issue by kedavlar** [BG-Software-LLC/WildStacker#633]
### Minecraft's Version

1.18.2 pufferfish

### Plugin's Version

b366

### Describe the bug

With the new system of damage of mmoitems/mythiclib of the new version (6.8.2 mmoitems and 1.14.2 for the lib) , the stacked mob have some problem..

Ill explain as better as i can.. 

When I hit the mobs in the stack very quickly .. for example with 7-8 cps .. the mobs get bugged and do not give the xp to level up with mcmmo ..
and in addition it does not suffer any backlash, remaining stationary and immobile .. only when it does, however, do you receive the xp ..

Another important thing to consider is that everything works correctly if you don't one shove the mob, instead, having an increased damage on fist / Sword / ax and one shoting the mob in stack, you have this problem

### To Reproduce

To reproduce, just try the latest version of mmoitems and myticlib and try to do what I explained above

### Additional Information

I did not know if to put it in the bug or feature section because it is a problem that only mobs in the stack have, all other things work correctly

**Comment by OmerBenGera** [comment]
WildStacker is known to have issues when other plugins handle damage differently, including custom enchants plugins and such.
No solution for that unfortunately.
