### ISSUE TITLE
Severe server lag with WildStacker

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#636]
### Minecraft's Version

PaperSpigot 1.19.2 #196

### Plugin's Version

2022.5-b368

### Describe the bug

Server is getting extreme lag from WildStacker

https://timings.aikar.co/dev/?id=2fd47a6f2d8146418d526e85f2fb8698

### To Reproduce

https://pastebin.com/aBNAeurb

### Additional Information

This started when I updated the plugin the other day along with updating my server PaperSpigot. The server lasts for a few hours before crashing and then restarting. I've been going through my logs and WildStacker constantly pops up in thread dumps. I ran a Timings report and I see WildStacker is at the top.

**Comment by OmerBenGera** [comment]
Don't set your stack interval to 1.
