### ISSUE TITLE
fix-stack is not functioning after a recent update

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#637]
### Minecraft's Version

1.19.2 purpur 1783

### Plugin's Version

2022.5-b368

### Describe the bug

Fix-stack should make non stackable items go into the inventory as such, instead they are being added as stacks.

### To Reproduce

Toss down something like shears and seem them stack, then pick them up and see the stack size remain uncorrected.

### Additional Information

# When fix-stack is disabled, items with a max-stack of 1 will be added to inventories
  # with a max-stack size of 64. If a player picks up 80 picks, he will get 64 + 16, instead
  # of 80 different items.
  fix-stack: true
  
  https://www.youtube.com/watch?v=zs8fC2_ZfMs

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
