### ISSUE TITLE
Entity Death Event

### ISSUE THREAD

**Issue by xanthacreator** [BG-Software-LLC/WildStacker#640]
### Minecraft's Version

1.19

### Plugin's Version

WildStacker v2022.5-b374

### Describe the bug

whenever i kill a stacked entity with a weapon from the crackshot plugin an error occurs in console and the mob glitches out

### To Reproduce

12.10 23:32:59 [Server] ERROR Could not pass event EntityDeathEvent to WildStacker v2022.5-b374
12.10 23:32:59 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation$Result.isCancelEvent()" because "this.monitorEntityDamageEventResult" is null
12.10 23:32:59 [Server] INFO at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamageMonitor(EntitiesListener.java:292) ~[WildStacker-2022.5-b374.jar:?]
12.10 23:32:59 [Server] INFO at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:287) ~[WildStacker-2022.5-b374.jar:?]
12.10 23:32:59 [Server] INFO at com.bgsoftware.wildstacker.listeners.EntitiesListener.onCustomEntityDeath(EntitiesListener.java:172) ~[WildStacker-2022.5-b374.jar:?]
12.10 23:32:59 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor637.execute(Unknown Source) ~[?:?]
12.10 23:32:59 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
12.10 23:32:59 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
12.10 23:32:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
12.10 23:32:59 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.projectile.ThrownEgg.onHitEntity(ThrownEgg.java:49) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:181) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.projectile.ThrownEgg.onHit(ThrownEgg.java:54) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:79) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
12.10 23:32:59 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
12.10 23:32:59 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xanthacreator** [comment]
I have a video but it's too big to send I could send it on discord tho

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
