### ISSUE TITLE
Invicible Blazez

### ISSUE THREAD

**Issue by Gholox** [BG-Software-LLC/WildStacker#642]
### Minecraft's Version

1.16.5

### Plugin's Version

2022.5 17/09/2022 20:04:19

### Describe the bug

When i want to kill stacked blaze they are invicible i have sword with sharpness 10 and i can kill only one per stack

### To Reproduce

.

### Additional Information

https://user-images.githubusercontent.com/112893594/195977354-8e88c256-8c1f-4bb4-b385-95f6548a803f.mp4

**Comment by Gholox** [comment]
https://pastebin.com/WkRuu4b1 the config

**Comment by OmerBenGera** [comment]
Update the plugin to latest dev build

**Comment by Gholox** [comment]
from where?

**Comment by OmerBenGera** [comment]
> from where?

From our website, under the stable builds tab.
