### ISSUE TITLE
Some of named mobs are still cleared with the clearlag

### ISSUE THREAD

**Issue by Keidenn** [BG-Software-LLC/WildStacker#645]
### Minecraft's Version

 git-Purpur-1632 (MC: 1.18.2)** 

### Plugin's Version

v2022.5

### Describe the bug

Hello ! 

Some of the mobs are getting cleared even if they are renamed with a name tag, not all of them but little by little they all ends up getting cleared

### To Reproduce

Just name a mob with a name tags and wait

**Comment by OmerBenGera** [comment]
WildStacker tracks named-tag entities only if they were vanilla renamed with a nametag.
If a plugin changes this behavior then WildStacker will not know about it, and therefore will not consider these mobs as having a name tag.
Check it on a server with only WildStacker and ClearLagg installed, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Keidenn** [comment]
Hello, sorry for the time of response

I'm having trouble recreating the issues. I tried just downloading a back-up of the serv and launch it in local, i didnt touch anything but the delay for the clear lagg (i put 1 per seconds) but nothing happens, so i'm kind of stuck, idk why it happens on the server

**Comment by OmerBenGera** [comment]
> Hello, sorry for the time of response
> 
> I'm having trouble recreating the issues. I tried just downloading a back-up of the serv and launch it in local, i didnt touch anything but the delay for the clear lagg (i put 1 per seconds) but nothing happens, so i'm kind of stuck, idk why it happens on the server

Weird. Continue to investigate the issue and try to find the cause.
It might occur if the entity is renamed not with vanilla nametag, I can tell that.

**Comment by Keidenn** [comment]
Hello ! i'm here giving an update

So, i assume i succeeded to make the bug occure again in local. But i had to restart for my mobs to despawn, and i don't need to restart when i'm on the online server to make the mobs disappear, its just random

BUT : Maybe you may have an idea; the plugins i have left are MyWorlds, BKCommonLib and obviously WildStacker, only them
https://www.spigotmc.org/resources/myworlds.39594/
https://www.spigotmc.org/resources/bkcommonlib.39590/

if by chance you may have knowledge of bugs cause by this plugin, i don't know, i'm kindda hopping for a miracle xD

**Comment by OmerBenGera** [comment]
@Keidenn Does it still occur?

**Comment by OmerBenGera** [comment]
I fixed a similar issue in latest dev build. Update and let me know if it still occurs.

**Comment by Keidenn** [comment]
I ran some test and yes it stills occurs :/

**Comment by OmerBenGera** [comment]
> I ran some test and yes it stills occurs :/

Take a video of the issue please

**Comment by Keidenn** [comment]
I'll try and post will post it as soon as i can have it occure again, but i don't know if it will help because it always happen when the mobs are out of sight

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Keidenn** [comment]
I can't really record it. It happen most of the time when  the mob is out of sight

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
