### ISSUE TITLE
Bentobox compatibility

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#648]
### Minecraft's Version

The server is running Paper version git-Paper-215 (MC: 1.19.2)

### Plugin's Version

WildStacker v2022.5-b368

### Describe the bug

When I enable "manage-menu" and "amounts-menu", all players are able to steal everyone elses spawners.  Even if they are not added to that specific island (Bentobox Skyblock). 

### To Reproduce

When rightclicking a spawner you pick "amounts menu" to add or withdraw spawners from a stack. 
All players can do this on someone elses island and without being trusted to that island. That way everyone can open the menu on someone elses spawner stack and steal their spawners.

**Comment by OmerBenGera** [comment]
There are dozens of different claiming plugins, WildStacker can't add support for all of them.
They need to make it so you can't interact with blocks, or at least give you the ability to configure which blocks you can't interact with (similar to how it's done within SuperiorSkyblock)
If there's no such feature, then it seems like the spawner menus feature cannot work for you.
