### ISSUE TITLE
Spawner method is used even when OFF

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#649]
### Minecraft's Version

pufferfish-40 1.19.2

### Plugin's Version

b883

### Describe the bug

> spawners:
  # Should spawners get stacked on the server?
  enabled: false
  spawners-override:
    # Should spawners behavior be overridden by WildStacker?
    # When enabled, you should see better performance from spawners.
    enabled: false

My config in WildStacker (b376)
but in spark there are events related to spawners.
I use another spawner plugin that hooks into wildstacker to support spawning stacked mobs, might be this, but not sure

![image](https://user-images.githubusercontent.com/31826333/197290470-0026924d-9d48-4967-ac29-af5a8c5fe748.png)
spark : https://spark.lucko.me/HxUnpiSV82

### To Reproduce

- install wildstacker
- user another spawner plugin
- disable spawner system in wildstacker
- check spark

**Comment by OmerBenGera** [comment]
That's intended. It doesn't cache this object tho, only creates it and the object is not used anymore.
