### ISSUE TITLE
Issue: Collecting items with more than 64 stack size after death will only give 64

### ISSUE THREAD

**Issue by tenten4846g** [BG-Software-LLC/WildStacker#650]
### Minecraft's Version

Minecraft Version: 1.19.2
Server jar: Paper (Version: git-Paper-220)

### Plugin's Version

WildStacker version: 2022.5 dev build 363

### Describe the bug

Collecting items with more than 64 stack size as the first item after your last death will only give 64

### To Reproduce

1. Fill your inventory with a fuck ton of stone
2. Get killed by something, mobs, fall, /kill, you name it
3. Collect the stone **The stone item must be the first item you pick up**

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
I filled my inventory entirely with stone, `/kill` myself, then I went back and picked up the items, and I received all the items correctly.
Are you able to replicate the issue on a server with only WildStacker installed?

**Comment by tenten4846g** [comment]
For the issue, It seems like the issue is not present in the server with only EssentialsX and WildStacker, I'll look into finding the cause of the issue and fix it, thank you.

**Comment by OmerBenGera** [comment]
> For the issue, It seems like the issue is not present in the server with only EssentialsX and WildStacker, I'll look into finding the cause of the issue and fix it, thank you.

You welcome.
I am closing this issue for now; if it turns to be an issue with the plugin, reply and let me know
