### ISSUE TITLE
Scute in loottables

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#651]
### Minecraft's Version

Version git-Paper-215 (MC: 1.19.2)

### Plugin's Version

WildStacker v2022.5-b368

### Describe the bug

Adding "Scute" to loottables doesn't drop Scutes.
https://pastebin.com/i3PAf20C

### To Reproduce

Adding Scute to ex. Turtles.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
