### ISSUE TITLE
Spawners cannot be placed together when placing the spawner on itself

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#652]
### Minecraft's Version

1.19.2 paper

### Plugin's Version

dev build 379

### Describe the bug

Spawner merging works if you place a spawner down on the ground then right click another spawner on the ground next to the spawner. However, if you right click the spawner on to the already placed spawner, it cancels the place event and doesn't merge them.

### To Reproduce

Place spawner down
Right click with a spawner onto the placed spawner

**Comment by ArmonicPvP** [comment]
Not sure if it matters, I have these settings for merging

  # Should there be the ability to place spawners next to each other?
  next-spawner-placement: true

  # Should there be only one spawner in the merge radius?
  only-one-spawner: false

**Comment by OmerBenGera** [comment]
Take a video showcasing the video, as I can't replicate it myself.
Upload it to an online streaming service (youtube for example) and send a link to it here.

**Comment by ArmonicPvP** [comment]
> Take a video showcasing the video, as I can't replicate it myself. Upload it to an online streaming service (youtube for example) and send a link to it here.

https://youtu.be/rAktb6EQJYQ

**Comment by ArmonicPvP** [comment]
Turns out that I can't place anything next to the spawners when clicking directly on its face. No other blocks work

**Comment by ArmonicPvP** [comment]
Found the issue was related to another plugin that was cancelling the changing of spawners by preventing you from placing anything near them
