### ISSUE TITLE
Spawners only dropping 64 items when stacks have 500 mobs

### ISSUE THREAD

**Issue by Devs52** [BG-Software-LLC/WildStacker#653]
### Minecraft's Version

1.12.2 Paper

### Plugin's Version

Latest dev build

### Describe the bug

Players on my server have stacked spawners of 500+ and when they die, they only get 64 items.

### To Reproduce

I don't know what's causing this, the config is basically default (Has changed the die in stack, and chunk merge from false to true)

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed, let me know if it still occurs.

**Comment by Devs52** [comment]
Just tried this on a server with the following plugins:

EssentialsX
Vault
SilkSpawners (Found the plugin bugs without it)
WildStacker

Still getting the same issue

**Comment by OmerBenGera** [comment]
Get rid of SilkSpawners as well as Essentials.
Also, does it work only with spawners or any item that is larger than 64 items?
Furthermore, upload your config to pastebin and send it here please

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If the issue still occurs, let me know by replying.
