### ISSUE TITLE
Certain regions from other plugins gets removed on server restart

### ISSUE THREAD

**Issue by R3voolt** [BG-Software-LLC/WildStacker#654]
### Minecraft's Version

latest paper

### Plugin's Version

tried latest dev and latest stable

### Describe the bug

Using cosmetics core plugin froom Lone Dev, and i must create a wardrobe so players can equip cosmetics. 
All works fine till server restart, when my wardrobe region gets removed.
After removing all plugins 1 by 1 , i found out that wild stacker made this happen. 
When i remove wild stacker from server, coosmetics core wardrobe is saved and works fine after restart. If i add wild stacker i get the  problem. 

### To Reproduce

Using cosmetics core plugin froom Lone Dev, and i must create a wardrobe so players can equip cosmetics. 
All works fine till server restart, when my wardrobe region gets removed.
After removing all plugins 1 by 1 , i found out that wild stacker made this happen. 
When i remove wild stacker from server, coosmetics core wardrobe is saved and works fine after restart. If i add wild stacker i get the  problem.

**Comment by OmerBenGera** [comment]
Contact them regarding this.
WildStacker doesnt interact with that plugin, so it might be a compatability issue on their side.
