### ISSUE TITLE
GUI not opening

### ISSUE THREAD

**Issue by saffue** [BG-Software-LLC/WildStacker#655]
### Minecraft's Version

1.19.2

### Plugin's Version

WildStacker-2022.5-b379.jar

### Describe the bug

the spawner gui opens when you first place the spawner but then just doesn't open past that, no errors, just doesn't open, spanner's still stack 

### To Reproduce

honestly no idea, everything is enabled in the config files, just nothing happens

### Additional Information

_had to put it on yt coz it wouldnt let me upload_
https://youtu.be/T71qbF9_8Yo
[WildStacker.zip](https://github.com/BG-Software-LLC/WildStacker/files/9874609/WildStacker.zip)

**Comment by OmerBenGera** [comment]
You need to sneak in order to open the menu (configurable).
I don't see anything wrong in the video.

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed using default config files of the plugin, let me know if it still occurs.

**Comment by saffue** [comment]
completely new server, not even essentials, using a newly downloaded dev build #380 
https://user-images.githubusercontent.com/67953277/198703860-76a391a1-1a99-4804-a7e3-c35092d868ec.mp4

**Comment by OmerBenGera** [comment]
Upload your config file to pastebin and send it here

**Comment by saffue** [comment]
https://pastebin.com/ujSyppZv

**Comment by PhoenixGre** [comment]
Any update on this?

**Comment by saffue** [comment]
same thing happens on the new 381 version

**Comment by OmerBenGera** [comment]
Does it still occur?
I tried replicating it with your config file and your server version and it works just fine.

**Comment by saffue** [comment]
yea this still happens

**Comment by OmerBenGera** [comment]
Have you tried using default config files?
It makes no sense.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know by replying here
