### ISSUE TITLE
Stacked entities not dropping correct amount of items.

### ISSUE THREAD

**Issue by ItzSave** [BG-Software-LLC/WildStacker#658]
### Minecraft's Version

1.19.2 - Pufferfish-40

### Plugin's Version

2022.5-b380

### Describe the bug

When having a stack of more than 1 entity there's a chance that the entire stack will die and only drop 1 item instead of the stack total.

https://www.youtube.com/watch?v=y1RSz2PLerE

### To Reproduce

Have a stack of spawners with more than 1 and kill a stack of entities after they spawn.

**Comment by OmerBenGera** [comment]
Please upload your config file to pastebin and send it here.

**Comment by ItzSave** [comment]
> Please upload your config file to pastebin and send it here.

https://pastebin.com/KDKDXjaE

**Comment by OmerBenGera** [comment]
I killed over 200 entities without any issues, which makes me believe it might be a conflict with another plugin
Try it on a server with only WildStacker installed, let me know if it still occurs.

**Comment by ItzSave** [comment]
I can't recreate this on a server with only wildstacker. Not entirely sure what plugin could be interfering with them but will dig deeper.

**Comment by OmerBenGera** [comment]
> I can't recreate this on a server with only wildstacker. Not entirely sure what plugin could be interfering with them but will dig deeper.

Let me know once you find it
I recommend adding plugins one by one until you get the issue again

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ItzSave** [comment]
Have not had the chance to verify this will start testing this week to confirm if the issue still persist

**Comment by ItzSave** [comment]
Going to go ahead and close this for now. Will reopen with more information when/if I have it.
