### ISSUE TITLE
Corpses are left on the ground after recent update

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#660]
### Minecraft's Version

1.19.2 Purpur dev 1831

### Plugin's Version

Dev 381

### Describe the bug

Corpses from mobs are left on the ground and don't go away, this happened recently after updating the plugin.

### To Reproduce

Kill mobs from spawners using things like campfires/wither roses.

### Additional Information

https://screenshots.skizzles.me/wAnA3/TANOgigO28.mp4

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
Please upload your config to pastebin and send it here

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
Will update when I can, sorry for the delay.
