### ISSUE TITLE
Unbreakable Weapon / Tool texture bug

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#661]
### Minecraft's Version

1.8.8

### Plugin's Version

2022.6-b381

### Describe the bug

if your weapon / tool has an unbreakable tag on 1.8,8, if u hit a mob with it and with **fast-kill** option enabled on config, the texture of that item will be messed up.

### To Reproduce

EX:
1. Enable fast-kill option in config
2. Use an unbreakable weapon/tool, attack a mob from spawner, see your unbreakable weapon/tool texture get bugged.

NOTE:
This does not happen if fast-kill option is disabled, but it sucks as fast-kill is really essential.

### Additional Information

![image](https://user-images.githubusercontent.com/89855789/199789075-e5dfe582-34ac-42d8-95c2-4b6575959ff0.png)

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Are you able to replicate the issue on a server with only WildStacker installed?
If so, please let me know your exact version of `/version`

**Comment by SisaNyza** [comment]
I've tested this on multiple 1.8.8 spigot forks with only WildStacker installed, issue happens only when fast-kill: is enabled & player is in survival mode & has a item that is unbreakable, DeathSimulation class line 86 sets **result.cancelEvent = true** & line 126 
then triggers the reduceKillerToolDurability method on line 127 which reduces the durability of them item's texture causing the texture to glitch out

**Comment by illudota** [comment]
Yes its weird  cuz it only happens when fast-kill is enabled, hang on let me try with only WS installed

**Comment by illudota** [comment]
> It seems to work fine for me. Are you able to replicate the issue on a server with only WildStacker installed? If so, please let me know your exact version of `/version`

https://github.com/BG-Software-LLC/WildStacker/issues/661#issuecomment-1303049528

make sure fast-kill option is enabled in config.

**Comment by illudota** [comment]
any update?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs

**Comment by illudota** [comment]
> Check out latest dev build, let me know if it still occurs

Fixed thanks, but i had this small error that kept showing up for a while but it disappeared overtime, dont know the cause though.
https://mcpaste.io/83474a441820d92e

**Comment by OmerBenGera** [comment]
@illudota Should be fixed as well with latest dev build :)
I am closing this for now
