### ISSUE TITLE
Break spawners in protected regions

### ISSUE THREAD

**Issue by LeVraiTheGO** [BG-Software-LLC/WildStacker#665]
### Minecraft's Version

Paper 1.18.2

### Plugin's Version

WildStacker 3.8.1

### Describe the bug

If you use a script using the skript plugin to protect regions (see script in the reproduce section), even if you aren't allowed to break the block it will break the spawner for you, but not other blocks because it is protected.
So Wildstacker let you break spawners even if you're not allowed to break blocks.

### To Reproduce

1. Install Skript.
2. Use the script below and put this script in **plugins/Skript/scripts**:
```
on break:
 cancel event
```
3. Reload the script using /sk reload <script name>
4. Place a spawner
5. Break it and you will see that you can break the spawner but not the blocks.

### Additional Information
None

**Comment by OmerBenGera** [comment]
Make sure you cancel the event before WS tries to break the spawner (before HIGHEST priority)
It's a bug on your end.

If you can't do it with Skript, then don't use Skript.

**Comment by LeVraiTheGO** [comment]
Are you making so when you break a spawner it sets the spawner to air. Bacause I made something that tells you if you break a block but when I break a block it says which block I'm breaking but when I break a spawner is says nothing.

**Comment by OmerBenGera** [comment]
> Are you making so when you break a spawner it sets the spawner to air. Bacause I made something that tells you if you break a block but when I break a block it says which block I'm breaking but when I break a spawner is says nothing.

Yes, it does.
