### ISSUE TITLE
Invulrable Mobs

### ISSUE THREAD

**Issue by battery3996** [BG-Software-LLC/WildStacker#666]
### Minecraft's Version

Minecraft 1.19.2
Purpur 1.19.2-1825

### Plugin's Version

WildStacker-2022.6-b381

### Describe the bug

Stacked Mobs will sometimes become invulnerable when killed and decrease in stacks.

### To Reproduce

Kill a mob that is stacked and it will sometimes trigger. Unsure how exactly it is triggered.

### Additional Information

https://i.imgur.com/H2DOnvN.gifv

**Comment by OmerBenGera** [comment]
Replicate the issue on a server with only WS installed.

**Comment by battery3996** [comment]
it's very inconsistent. it happens rarely. Also I am unable to replicate this on a server with only WS as I have an active player base on the server and don't have another server to do it on. PC is not powerful enough to run the game and server simultaneously. So far it has mainly happened with pillagers and shuckers.

**Comment by OmerBenGera** [comment]
I can't replicate the issue myself.
Look for a free hosting online and open a server there, otherwise I won't be able to fix it.

**Comment by mistermaster38** [comment]
i also have this issue with 60 plugins installed in our active server

**Comment by OmerBenGera** [comment]
> i also have this issue with 60 plugins installed in our active server ive installed stable version 2022.6 and tried dev 2022.6 -b390 only solution is when clearlagg goes through and kills stacked entities issue was replicated 2x after about 3 stacks each of 10x zombies only happens after all 10 are killed
As I said above as well as on the discord server, try it on a server with only WS installed.
Let me know if it still occurs

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by mistermaster38** [comment]
i have no way to test it myself without paying for a new server 
ive tried using that free site but i cant add the plugin for it

**Comment by battery3996** [comment]
Im in the same boat as mistermaster

**Comment by battery3996** [comment]
As stated above, I don't have a powerful enough rig to host a server and client at the same time. Running on 8gb max of ram for system, client, and local server. 

Windows already wants to eat 2-4gb just to function. My clients eats up 4-6gb. As you see with the limitations, there is no way for me to run a server with minimum 6gb just to launch a local server and client to get the results.

**Comment by OmerBenGera** [comment]
@battery3996 @mistermaster38 @Skizzles Check out latest dev build, let me know if it's fixed.

**Comment by cynikhavoc** [comment]
This was fixed with dev build 400 for me.

**Comment by OmerBenGera** [comment]
Awesome
If it occurs again lmk
