### ISSUE TITLE
WildStacker causing problems with another plugin

### ISSUE THREAD

**Issue by ZadeFear** [BG-Software-LLC/WildStacker#667]
### Minecraft's Version

Server Version: 1.8
JAR: ReliableSpigot (https://builtbybit.com/resources/reliablespigot-log4j-patched-affordable-cannon-optimized-jar.15892/)

### Plugin's Version

Currently Using 3.8.0.316
Was using 2022.6 before finding the bug

### Describe the bug

Im using a chunk collector plugin (https://www.spigotmc.org/resources/customschunkcollectors-1-8-1-18.91542/)

The issue is that when I place 1000x iron golem spawners for example in the same chunk as the chunk collector, on the latest version of stacker, only about 10 mobs get added to the collector.  When I break the chunk collector, there is 1000+ iron golems. Heres a video example: https://gyazo.com/93d1872afa8a404edadbfd06b6d3e290

The video shows that the amount of iron golems being added to the chunk collector is only about 10-20 each second. Even though I placed 1k iron golems.

When I break ther chunk collector, 1k+ golems spawn.

I spoke to the dev of the collector plugin and he said its possibly a problem with the WildStackerAPI

I am currently using version 3.8.0.316 and the bug is fixed. Video: https://gyazo.com/55a7395d84d26e028cd11ca516e059bf

### To Reproduce

Not really able to reproduce unless you have the ChunkCollector plugin which is premium.

**Comment by ZadeFear** [comment]
I forgot to mention that the chunk collector collects the same amount of drops from 1 spawner as 1000 spawners, or 100 spawers, or 50, or anything

**Comment by ZadeFear** [comment]
Yes. https://gyazo.com/93d1872afa8a404edadbfd06b6d3e290

**Comment by OmerBenGera** [comment]
Are you sure this plugin supports WildStacker..?

**Comment by OmerBenGera** [comment]
Also, have you tried contacting their developer?
It seems like it doesnt support WildStacker, that's it - not something I can do anything about.

**Comment by ZadeFear** [comment]
Plugin has wildstacker support. This is what the dev told me.
https://gyazo.com/414c57660188d47bf79d6f28d296a017

**Comment by ZadeFear** [comment]
It used to work like normal before I updated to 2022.6

**Comment by OmerBenGera** [comment]
Weird, I will look into it.
What is your discord? I will need a copy of that plugin.

**Comment by ZadeFear** [comment]
likewtf#8461

**Comment by ZadeFear** [comment]
would i be able to show this to the dev without getting causing any problems?

**Comment by OmerBenGera** [comment]
> would i be able to show this to the dev without getting causing any problems?

I sent him a link to this issue.
We'll wait for his respond.
