### ISSUE TITLE
Entities spawned by spawner will stack directly

### ISSUE THREAD

**Issue by ChrissW-R1** [BG-Software-LLC/WildStacker#670]
### Minecraft's Version

1.19.2

### Plugin's Version

2022.6

### Describe the bug

Any entities, which will spawned by a spawner will instantly stack to existing entities near the spawner.
We have set, that only 50 or more entities on the same location will be stacked. This works perfectly, but with a spawner this limit will not be used.

### To Reproduce

1. Set porperty entities.minimum-required.all to 50
2. Create a normal pig spawner (default)
3. Wait until two pigs were spawned

### Additional Information

We also set the property entities.linked-entities.enabled to false, but nothing changed.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by Testic19** [comment]
Its still happening for me with latest dev build

**Comment by OmerBenGera** [comment]
> Its still happening for me with latest dev build

I don't know why tbh, it doesn't happen for me and the plugin makes sure to not reduce durability for items with the unbreakable tag.

**Comment by OmerBenGera** [comment]
> Reference in

Take a video of the issue.
Also, upload your config to pastebin and send it here

**Comment by ChrissW-R1** [comment]
We tested it, too. We used the version 2022.6-b386.
The issue still exist without any visible changes.

Configuration: https://pastebin.com/G7NJEfzG
Video with a simple default spawner: https://user-images.githubusercontent.com/1086210/202915331-527afd85-c373-4a93-9b0c-e1f9b3aa514d.mp4

**Comment by OmerBenGera** [comment]
Do you run Paper?

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully now it's fixed.

**Comment by ChrissW-R1** [comment]
Yes, works fine now. Thank you very much.
