### ISSUE TITLE
Barrel hologram issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#674]
### Minecraft's Version

This server is running Pufferfish+ version git-PufferfishPlus-32 (MC: 1.19.2) (Implementing API version 1.19.2-R0.

### Plugin's Version

WildStacker version 2022.6-b384

### Describe the bug

I'm using superiorskyblock and limiting armorstand per island, and as each barrel is two armorstands, it makes issues on limit, and barrel do not get the bloc inside them after reaching limit.
 
First barrels : 
![image](https://user-images.githubusercontent.com/31826333/203167598-d9e4862d-9c4b-4a9f-a876-63893872f195.png)

After I reached armorstand limit :/
![image](https://user-images.githubusercontent.com/31826333/203167067-c1d2f548-06b6-4fdb-a6b5-8641eae7333c.png)

It would be possible to change the hologram system to be packets instead of holograms ?
Or make barrels bypassing armorstand limit (not counting for it).

### To Reproduce

- set an armorstand limit in superior
- place barrels
- after reaching limit, barrel won't get the bloc inside them

**Comment by WarnDa** [comment]
( Are barrels correctly deleted if I delete my island ? How are they saved, I hope I won't get issue in the future with a lot of invisible armorstand that kill performances )

**Comment by OmerBenGera** [comment]
> ( Are barrels correctly deleted if I delete my island ? How are they saved, I hope I won't get issue in the future with a lot of invisible armorstand that kill performances )

Don't worry about it, SSB deletes all entities and blocks (including the barrels).
Then later, WS will also delete them from cache automatically.

**Comment by OmerBenGera** [comment]
Check out latest dev build of both WS and SSB, let me know

**Comment by WarnDa** [comment]
It works perfectly thanks !
![image](https://user-images.githubusercontent.com/31826333/203852075-209a1ecd-7f5a-4928-9bd1-cec880ed2269.png)

**Comment by OmerBenGera** [comment]
> It works perfectly thanks ! ![image](https://user-images.githubusercontent.com/31826333/203852075-209a1ecd-7f5a-4928-9bd1-cec880ed2269.png)

Amazing :D
