### ISSUE TITLE
Error keep appearing in console

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#677]
### Minecraft's Version

Paperspigot fork 1.8.8 (Cannon Jar)

### Plugin's Version

Dev build #b386

### Describe the bug

Idk it just keeps showing up in my console idk the cause, and the thing is, I'm alone in my server(server maintenance), and this error just shows up. it will disappear then will re-appear again some time. i dont think its fatal but who knows?

### To Reproduce

No idea.

### Additional Information

https://mcpaste.io/8e0efcecf3134c08

**Comment by OmerBenGera** [comment]
> Same error on newer version - Pufferfish version git-Pufferfish-38 (MC: 1.19.2) https://pastebin.com/raw/XVP4KG08 looks like it happens when a mob dies from fall damage

Thats not the same error, however it was reported already.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know by replying.
