### ISSUE TITLE
NoSilk Touch Permissions Bug

### ISSUE THREAD

**Issue by Zsomi** [BG-Software-LLC/WildStacker#679]
### Minecraft's Version

Purpur-1632 1.18.2

### Plugin's Version

WildStacker-2022.6-b387

### Describe the bug

My problem would be that when I don't add the nosilk permission, the player still gets the spawners if he hits with a normal pickaxe.

### To Reproduce

You knock out a spawn with a any pickaxe.

### Additional Information

https://pastebin.com/vzaueFyK

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, it works fine for me
Does it happen for you if you only have WildStacker installed?

**Comment by Zsomi** [comment]
Unfortunately, I haven't tried it yet, I'll test it soon anyway.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still exists, let me know
