### ISSUE TITLE
WildStacker does not work with NachoSpigot

### ISSUE THREAD

**Issue by imBuzz** [BG-Software-LLC/WildStacker#681]
### Minecraft's Version

1.8.8 NachoSpigot

### Plugin's Version

2022.6

### Describe the bug

HI! This bug happens with Mob Spawners and there are times that spawners do not spawn any entities, and others in which the entities spawn, but are not merged with the others .

### To Reproduce

Just download NachoSpigot, place a spawner and see what happens

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by imBuzz** [comment]
Same

**Comment by OmerBenGera** [comment]
> Same

Does it work with regular Paper/Spigot or is it only affecting NachoSpigot?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
