### ISSUE TITLE
Item dupe

### ISSUE THREAD

**Issue by kamilleon** [BG-Software-LLC/WildStacker#682]
### Minecraft's Version

1.19 Purpur

### Plugin's Version

2022.6-b390

### Describe the bug

When a chest or any block that can store items gets exploded by a TNT, and item stacking is enabled in the config, one or multiple items from inside the block get duped when standing close to it.

### To Reproduce

- Place down a button/lever, TNT, and a chest next to each other
- Power the TNT
- Stand near the chest, max ~1 block away
- Open the Chest, and put any item inside, preferably something that is stackable
- Item gets duped with a ~50% chance

Video: 

https://user-images.githubusercontent.com/25117301/203857453-c95fbc21-7062-4526-b0ae-e80a0e204d78.mp4

### Additional Information

Something I want to say, the dupe is pretty weird, it does not double the items but rather gives like +44 from a 64 stack.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
