### ISSUE TITLE
Barrel issue with axe

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#685]
### Minecraft's Version

1.19.2 pufferfish

### Plugin's Version

b390

### Describe the bug

If you activate barrel stacking on copper block and place a oxidized copper block, and turn it into a copper block with right clicking on it, your axe disappear

### To Reproduce

- activate barrel on copper block
- place an oxidized copper block
- take an axe
- right click on the oxidized copper until it turns on a normal copper block
- the block will stack and you'll lose your axe
- 

### Additional Information

Video : 
https://youtu.be/_ZccnnJ3lT8
(my custom command to activate stacking it /stack)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
