### ISSUE TITLE
WildStacker x FTOP by CustomEnchants bug

### ISSUE THREAD

**Issue by realgamerk** [BG-Software-LLC/WildStacker#686]
### Minecraft's Version

Version: 1.8.8
Jar: SpaceDeltaSpigot

### Plugin's Version

WildStacker version 2022.6

### Describe the bug

~FTOP plugin by CustomEnchants~
the plugin can't detect the spawners stacking up
ex: I placed 100 stacked spawners but the FTOP plugin only detects 1. 

### To Reproduce

The wildstacker plugin is not supporting FTOP plugin

### Additional Information

![image](https://user-images.githubusercontent.com/112314692/205431783-f119d6d2-f050-4e51-91a3-e755a24fd5ee.png)
![image](https://user-images.githubusercontent.com/112314692/205431802-6eace960-1865-46f5-86f2-ff001d4a4334.png)

**Comment by OmerBenGera** [comment]
Contact CustomEnchants regarding this, not an issue with WildStacker.
I know he loves to blame WildStacker on this, however this is not an issue with the plugin and he really isn't trying to fix it neither.
I recommend either trying to convince him to fix the compatibility with the plugin or switch to another plugin that supports WildStacker.
