### ISSUE TITLE
1.8.8 Picking up fired arrows error

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#689]
### Minecraft's Version

1.8.8 Paperfork

### Plugin's Version

2022.6 b381

### Describe the bug

error when picking up fired arrows

### To Reproduce

fire an arrow, pick it up

### Additional Information

https://mcpaste.io/fce5b60f0b4fd6c9

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it still occurs.

**Comment by illudota** [comment]
It still occurs.

**Comment by OmerBenGera** [comment]
It's fixed with latest dev build
I know you can't download it from the website, Paper broke something and the plugin can't be compiled correctly
Hopefully will be fixed soon

**Comment by OmerBenGera** [comment]
Fixed in latest dev build (b395)
