### ISSUE TITLE
Stacked Spawners losing the ability to spawn stacked mobs

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#692]
### Minecraft's Version

Purpur 1.19.2 dev 1856

### Plugin's Version

Wildstacker 392
SuperiorSkyblock 925

### Describe the bug

There was a bug where SSB had spawners turn into pigs, after that build had changes modified I now notice the spawners losing their data somehow. Unsure if this is SSB or Wildstacker.

### To Reproduce

Honestly not sure.

On restart / chunk unload the spawner loses its data. I check with /ws debug and nothing shows up.

Mobs then only spawn without any stack data.

### Additional Information

![image](https://user-images.githubusercontent.com/30563757/206591416-c8142dbb-2f67-4af8-b877-6901000fde94.png)

**Comment by OmerBenGera** [comment]
I don't understand what the issue is.
If the actual spawner no longer has its mob type, then it's not an issue with neither SuperiorSkyblock or WildStacker, as neither of the plugins track this type of data.
Check if using `/ws inspect` WildStacker can detect the mob type.

**Comment by Skizzles** [comment]
> I don't understand what the issue is. If the actual spawner no longer has its mob type, then it's not an issue with neither SuperiorSkyblock or WildStacker, as neither of the plugins track this type of data. Check if using `/ws inspect` WildStacker can detect the mob type.

Its not the mob type, the spawner will not spawn stacked mobs any further. Its basically lost its stack count until its placed back down. As I said, this is similar to how SSB had an issue where it was turning spawners to pig, you fixed that recently.

**Comment by OmerBenGera** [comment]
> > I don't understand what the issue is. If the actual spawner no longer has its mob type, then it's not an issue with neither SuperiorSkyblock or WildStacker, as neither of the plugins track this type of data. Check if using `/ws inspect` WildStacker can detect the mob type.
> 
> Its not the mob type, the spawner will not spawn stacked mobs any further. Its basically lost its stack count until its placed back down. As I said, this is similar to how SSB had an issue where it was turning spawners to pig, you fixed that recently.

I fixed an issue with WS incorrectly calculating mobs to spawn, causing mobs to spawn with an incorrect stack count.
Try updating, might fix this issue as well. Report back if it still occurs / fixed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
