### ISSUE TITLE
Mob-Amount glitching

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#694]
### Minecraft's Version

Paperfork 1.8.8

### Plugin's Version

393

### Describe the bug

Idk but suddenly the mob amount goes down.

(b381 this bug does not happen, im stuck between two versions, either the unbreakable texture bug, or mob amount bug, they're both annoying)

b381 - No mob amount bug, but have texture bug
b393 - No texture bug, but have mob amount bug

### To Reproduce

No idea, it just happens that way, its so annoying. here is video below.

### Additional Information

https://streamable.com/p7eykc

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send it here

**Comment by illudota** [comment]
> Upload your config to pastebin and send it here

https://pastebin.com/Wc19z3te
if u want u can test with my cannon jar as well, might be a good help

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by illudota** [comment]
Fixed, thank you so much Omer.
