### ISSUE TITLE
HUGE ITEM DUPE

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#695]
### Minecraft's Version

paper 1.12.2

### Plugin's Version

b395

### Describe the bug

You can dupe any items that stack via WildStacker, I tested paper as a blacklist item and it was fixed, so it is definitely something to do with WildStacker.

### To Reproduce

https://imgur.com/a/knqmk69

Use a hacked client that has fastbreak and it should dupe the items shown in the video.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
