### ISSUE TITLE
New error code spamming console with devbuild 400

### ISSUE THREAD

**Issue by cynikhavoc** [BG-Software-LLC/WildStacker#697]
### Minecraft's Version

mcmmo: 2.1.218-snapshot
spigot: 3553-spigot-14a2382-ef09464 MC1.19
API version 1.19-RO.1-SNAPSHOT
Wildstacker: Dev400

### Plugin's Version

Dev build #400

### Describe the bug

https://pastebin.com/vyKASP5K new error log
also the wolves give you mcmmo exp for whatever you're holding, fist, sword, axe
https://prnt.sc/IWkmjZWRuePk

### To Reproduce

wolves are taming level 150, im just afk wolves are attacking a silkspawner spawned skeleton with wildstacker, leveling my unarmed/swords/axes while holding that specific one.
spamming my console thousands of times with the above pastebin.

### Additional Information

N/A

**Comment by cynikhavoc** [comment]
Update: After hitting taming level 700, I no longer gain taming levels, only unarmer/sword/axe depending on what im holding.

**Comment by cynikhavoc** [comment]
Now happens with devbuild 399, and whenever anyone hits any mobs
https://pastebin.com/SgqkTNPb
15,000lines of error codes

**Comment by cynikhavoc** [comment]
Console doesn't get spammed on the latest stable version. All the dev version I have tested gives you like 100x MCMMO EXP for using the abilities (serrated strikes etc)
The latest stabled version however does NOT do that.

**Comment by cynikhavoc** [comment]
Redownloaded 400 after your most recent update, console is still spammed and serrated strikes still gets me 1000x the amount of levels its supposed to.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by cynikhavoc** [comment]
Console spamming is fixed, however dogs still level your mcmmo skill for other things than taming, and there is still a dupe, and mcmmo combat skills still apply 1000x the amount they're supposed to ONLY with this plugin.

**Comment by OmerBenGera** [comment]
> Console spamming is fixed, however dogs still level your mcmmo skill for other things than taming, and there is still a dupe, and mcmmo combat skills still apply 1000x the amount they're supposed to ONLY with this plugin.

I dont know which dupe you talk about, but I cant replicate the issues you mentioned - neither the taming nor the levels.
Take a video of the issues please.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know by replying here

**Comment by WarnDa** [comment]
> Console spamming is fixed, however dogs still level your mcmmo skill for other things than taming, and there is still a dupe, and mcmmo combat skills still apply 1000x the amount they're supposed to ONLY with this plugin.

I get this issue on jobsreborn, when player kill entities, it sometimes count 30-40 mobs instead of 1.

This DO NOT happen on dev build b400, but it happens since b406 (even happen on b411)

**Comment by OmerBenGera** [comment]
> > Console spamming is fixed, however dogs still level your mcmmo skill for other things than taming, and there is still a dupe, and mcmmo combat skills still apply 1000x the amount they're supposed to ONLY with this plugin.
> 
> I get this issue on jobsreborn and questcreator, when player kill entities, it sometimes count 30-40 mobs instead of 1.
> 
> This DO NOT happen on dev build b400, but it happens since b406 (even happen on b411) no error in console, and idk how to really reproduce it, but my players reported me the issue multiple times so I stick on b400

Open a new issue regarding this please.
