### ISSUE TITLE
didn't add support for 'all' on charge

### ISSUE THREAD

**Issue by restubilal** [BG-Software-LLC/WildStacker#698]
### Minecraft's Version

1.19.2 paper

### Plugin's Version

latest

### Describe the bug

no support on all variable 
break-charge:
    ALL:
      price: 1000
      multiply-stack-amount: true

  # All settings related to break charge.
  # place-charge:
  #   EXAMPLE_MOB:                     The name of the mob.
  #     price: 0                       The price to charge upon placing.
  #     multiply-stack-amount: false   Should the price get multiplied by the amount that were placed?
  place-charge:
    ALL:
      price: 1000
      multiply-stack-amount: true

### To Reproduce

break-charge:
    ALL:
      price: 1000
      multiply-stack-amount: true

  # All settings related to break charge.
  # place-charge:
  #   EXAMPLE_MOB:                     The name of the mob.
  #     price: 0                       The price to charge upon placing.
  #     multiply-stack-amount: false   Should the price get multiplied by the amount that were placed?
  place-charge:
    ALL:
      price: 1000
      multiply-stack-amount: true

**Comment by OmerBenGera** [comment]
Added in latest dev build
