### ISSUE TITLE
[issue] Can't hit or kill mobs

### ISSUE THREAD

**Issue by Starkenz** [BG-Software-LLC/WildStacker#699]
### Minecraft's Version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
Previous version: git-Paper-295 (MC: 1.18.2)

### Plugin's Version

WildStacker-2022.6-b400.jar

### Describe the bug

Can't hit or kill mobs.

### To Reproduce

Put the jar into the server.

### Additional Information

Here's my config
https://hastebin.com/ohivokafay.yaml

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it still occurs

**Comment by Starkenz** [comment]
Still can't hit. Here's the video:
https://youtu.be/GuviUBtIWNE

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Starkenz** [comment]
Sorry for the long reply. I think it's working without plugins.

**Comment by OmerBenGera** [comment]
> Sorry for the long reply. I think it's working without plugins. One of my plugins causing this. But I don't know which one is it out of 100 plugins.

Try adding them in groups until it happens again.
Make sure you update me here what caused it. It might be a conflict with WildStacker that I can fix on my end.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know by replying here
