### ISSUE TITLE
Duping with stacked items

### ISSUE THREAD

**Issue by cynikhavoc** [BG-Software-LLC/WildStacker#700]
### Minecraft's Version

mcmmo: 2.1.218-snapshot
spigot: 3553-spigot-14a2382-ef09464 MC1.19
API version 1.19-RO.1-SNAPSHOT
Wildstacker: Dev 399/400/401

### Plugin's Version

Dev 399/400/401

### Describe the bug

Dupe any stackable item

### To Reproduce

You just spam q into hoppers and they dupe. this works with any stackable item and has to have stacked items on for it to work.

### Additional Information

N/A

**Comment by cynikhavoc** [comment]
update still works on stable version, and with stacked items disabled.

**Comment by cynikhavoc** [comment]
Enabled and disabled every option possible and still works on every version by simply dropping items into hoppers at different speeds

**Comment by OmerBenGera** [comment]
You said you disabled items stacker and it still occurred?
Are you sure its related to WS?
Try replicating it on a server with only WS installed.

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
Please upload your config to pastebin and send a link to it here.

**Comment by cynikhavoc** [comment]
100% sure its WS, i removed it and the dupe no longer works.
https://pastebin.com/07rGgwrE

**Comment by OmerBenGera** [comment]
Take a video of the issue as well
Upload it to an online streaming service and send a link to it here

**Comment by cynikhavoc** [comment]
Yes i removed everything except for essential plugins and there is still a hopper dupe. when throwing items with q you have to do different speeds like fast 5 slow 3 fast 20 slow 1 slow 2 fast etc.
removing WS on both of my servers stopped the dupe

**Comment by OmerBenGera** [comment]
> Yes i removed everything except for essential plugins and there is still a hopper dupe. when throwing items with q you have to do different speeds like fast 5 slow 3 fast 20 slow 1 slow 2 fast etc. removing WS on both of my servers stopped the dupe

As I said, take a video of the issue

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by tantan2121** [comment]
There's a potential that WildStacker also cause ores dupe on my server :/, sadly I haven't find what cause WildStacker to dupe yet.

**Comment by OmerBenGera** [comment]
> There's a potential that WildStacker also cause ores dupe on my server :/, sadly I haven't find what cause WildStacker to dupe yet.
> 
> What I do know is our players heavily using high fortune and lots of hopper

Open a new issue regarding this, this is not related to this issue.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.

**Comment by WarnDa** [comment]
I get the issue, it's related to upgradeablehoppers and their instant suction
https://www.youtube.com/watch?v=gH0Gg7pvkNg
![image](https://user-images.githubusercontent.com/31826333/214152535-fea8f2de-0fef-4698-aa49-4acb64bb3ed7.png)


I just opened a ticket on their discord, and dev told me : 
![image](https://user-images.githubusercontent.com/31826333/214152584-7389c96b-82b5-48b8-9efa-bf0405169ba3.png)

**Comment by OmerBenGera** [comment]
> I get the issue, it's related to upgradeablehoppers and their instant suction https://www.youtube.com/watch?v=gH0Gg7pvkNg ![image](https://user-images.githubusercontent.com/31826333/214152535-fea8f2de-0fef-4698-aa49-4acb64bb3ed7.png)
> 
> I just opened a ticket on their discord, and dev told me : ![image](https://user-images.githubusercontent.com/31826333/214152584-7389c96b-82b5-48b8-9efa-bf0405169ba3.png)

Please open a new issue regarding this

**Comment by cynikhavoc** [comment]
> I get the issue, it's related to upgradeablehoppers and their instant suction https://www.youtube.com/watch?v=gH0Gg7pvkNg ![image](https://user-images.githubusercontent.com/31826333/214152535-fea8f2de-0fef-4698-aa49-4acb64bb3ed7.png)
> 
> I just opened a ticket on their discord, and dev told me : ![image](https://user-images.githubusercontent.com/31826333/214152584-7389c96b-82b5-48b8-9efa-bf0405169ba3.png)

this is the same exact issue i had

**Comment by OmerBenGera** [comment]
> > I get the issue, it's related to upgradeablehoppers and their instant suction https://www.youtube.com/watch?v=gH0Gg7pvkNg ![image](https://user-images.githubusercontent.com/31826333/214152535-fea8f2de-0fef-4698-aa49-4acb64bb3ed7.png)
> > I just opened a ticket on their discord, and dev told me : ![image](https://user-images.githubusercontent.com/31826333/214152584-7389c96b-82b5-48b8-9efa-bf0405169ba3.png)
> 
> this is the same exact issue i had

You have never mentioned that you use UpgradableHoppers.
Even when I told you to remove all plugins except WildStacker and you told me that you did and it still occurs, turns to be a lie.
Dont use my plugins please. You are a liar, then you spread false info about my plugins and submit false reviews.
