### ISSUE TITLE
Only x1 mob per mob spawner

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#701]
### Minecraft's Version

1.8.8 PaperSpigot

### Plugin's Version

b395

### Describe the bug

It only spawns x1 per spawner despite default spawner count is 4

### To Reproduce

B395 on Paper 1.8.8
I only have B395 Wildstacker and Essentials on my server

### Additional Information

https://streamable.com/eh4lg3

**Comment by illudota** [comment]
Tested with latest dev version, issue also persists.

**Comment by OmerBenGera** [comment]
The spawner will attempt to spawn the amount of mobs specified with spawn count, however it's not guaranteed to occur.
In your case, the spawner will spawn between 1 and 4 mobs, with an average of 2-3.
