### ISSUE TITLE
Bloodmoon Advanced and WildStacker imcopability

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#702]
### Minecraft's Version

1.19.2 pufferfish

### Plugin's Version

WildStacker-2022.6-b402.jar

### Describe the bug

The bosses in the blood moon plugin group together even with modified names on top of their heads, is there a way for them not to group with the other mobs?

### To Reproduce

put the Bloodmoon Advanced and WildStacker plugin on the server when 1 boss is born and another mob appears next to it they group together, if there are 2 skeletons

### Additional Information

you could add bloodmoon to the blacklist of mobs so it doesn't group

**Comment by mrgeneralq** [comment]
(Developer of Bloodmoon here) Adding some additional details to @SrMonsterYT 

- It's not just bosses but any mob in general. The plugin is spawning mobs, the mobs have custom names, armor etc. Is there an option to not make the mobs stack?

**Comment by OmerBenGera** [comment]
They can add support by listening to EntityStackEvent of WildStacker and cancel the event if its one of their entities.

**Comment by mrgeneralq** [comment]
We tried your solution but it doesn't work. After doubting about the logic I removed every possible condition and just register the listener.

Still no luck. It keeps stacking everything.

the maven settings provided in the readme.md say's to use "latest" as the version value which maven will mention it doesn't exist. Therefore I used one of the versions I found by manually going in the repo: "2022.6"

Code:

    @EventHandler
    public void onMobSpawn(EntityStackEvent e){
/*
        StackedEntity entity = e.getEntity();
        if(entity.getLivingEntity() == null)
            return;

        World world = entity.getWorld();

        if(this.bloodmoonService.bloodmoonIsRunning(world))

 */
        e.setCancelled(true);
    }

**Comment by mrgeneralq** [comment]
So the only thing left on the code is e.setCancelled(true)

**Comment by SrMonsterYT** [comment]
I performed the tests and all are stacking still, and if I put in the configuration the name of the mobs in the configuration: name-blacklist: , would it work?

**Comment by mrgeneralq** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
> I performed the tests and all are stacking still, and if I put in the configuration the name of the mobs in the configuration: name-blacklist: , would it work?

Yes.

**Comment by SrMonsterYT** [comment]
there is another conflict with the blood moon, so I decided to continue here so as not to open another ticket

after several tests removing the wildstacker and leaving only the blood moon the bug did not happen

bug: when killing a Blood Moon boss the items are doubled

with wildstacker: https://prnt.sc/cspYo0YrbXv2, https://prnt.sc/PZla_KGGr878

without wikdstacker:  https://prnt.sc/fVPp8A4O6m6A, https://prnt.sc/yMkiza-Zx11G

**Comment by mrgeneralq** [comment]
As requested by @SrMonsterYT adding some additional details:

Our plugin controls the drops when a mob is killed. Drops are being cleared before the mob dies. When wildstacker is being used, it makes a copy of the drops.

**Comment by OmerBenGera** [comment]
The drops are multiplied only if the entity that was killed has a stack size that is not 1 and multiply drops is enabled.
Might be because the entities of that plugin are stacked.

**Comment by OmerBenGera** [comment]
@mrgeneralq Do you mind giving me access to your plugin so I can add support to it on my end?
My spigot username is Ome_R

**Comment by mrgeneralq** [comment]
Hello @OmerBenGera 

No problem, I will grant you access as we speak. Although there are some things you need to know.
Can you please add me on discord? MrGeneralQ#0001. This information has to remain confidential for now.

**Comment by OmerBenGera** [comment]
> Hello @OmerBenGera
> 
> No problem, I will grant you access as we speak. Although there are some things you need to know. Can you please add me on discord? MrGeneralQ#0001. This information has to remain confidential for now.

Mind joining my discord server and tag me there?
I'll create a private ticket for us both.

**Comment by OmerBenGera** [comment]
> Hello @OmerBenGera
> 
> No problem, I will grant you access as we speak. Although there are some things you need to know. Can you please add me on discord? MrGeneralQ#0001. This information has to remain confidential for now.

I joined your discord server.

**Comment by OmerBenGera** [comment]
The dupe is fixed in latest dev build :)
