### ISSUE TITLE
McMMO and WildStacker conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#703]
### Minecraft's Version

pufferfish 1.19.2

### Plugin's Version

WildStacker-2022.6-b402.jar

### Describe the bug

logs erro: https://pastebin.com/rxKs6CZG

the server crashes and gives this error

### To Reproduce

I have not yet found out what causes this

### Additional Information

I don't know if the problem is in mcMMO or in WildStacker

**Comment by SrMonsterYT** [comment]
can you tell me if it is wildstacker? sorry to bother you, I just wanted to know, because this has never happened before

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by SrMonsterYT** [comment]
ok I will test it as soon as I have an answer I will comment here

**Comment by SrMonsterYT** [comment]
another problem happened, I don't know if it is the same but it seems, the error was this 

https://pastebin.com/Um6jNPn9

**Comment by SrMonsterYT** [comment]
I think it was solved, I haven't had any more problems so far, thank you very much

**Comment by SrMonsterYT** [comment]
I think the problem is back yet error: 

https://pastebin.com/GnyHWXEP

**Comment by OmerBenGera** [comment]
This is not related to WildStacker in any way:
```[01:39:27] [Paper Watchdog Thread/ERROR]: During the run of the server, a plugin set an excessive velocity on an entity
[01:39:27] [Paper Watchdog Thread/ERROR]: This may be the cause of the issue, or it may be entirely unrelated```
This warning has happened due to BarbedWire.
