### ISSUE TITLE
Double Events

### ISSUE THREAD

**Issue by SisaNyza** [BG-Software-LLC/WildStacker#704]
### Minecraft's Version

1.19.2 

### Plugin's Version

2022.6 & latest Dev

### Describe the bug

The EntityDamageByEntityEvent is being called 2 times, wasn't happening in older versions of WildStacker

### To Reproduce

Listen to EntityDamageByEntityEvent and it will be called 2 times, don't know if it matters but the item the mob was hit with is unbreakable & the event is cancelled

**Comment by OmerBenGera** [comment]
WildStacker cancels the first event in LOWEST priority and fires it again.
Make sure you ignore canceled events.
