### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by Yoloman0013** [BG-Software-LLC/WildStacker#705]
### Minecraft's Version

Paper 1.19.3 

### Plugin's Version

WildStacker-2022.6-b404

### Describe the bug

Stacking doesnt work and players are placing empty spawners

### To Reproduce

Place a spawner without op and with all permissions for plugin

for op stacking doesnt work either 

### Additional Information

https://pastebin.com/ifRbQ1Qj

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
