### ISSUE TITLE
Retrieving less stacked blocks than what you died with

### ISSUE THREAD

**Issue by Hero-Gate** [BG-Software-LLC/WildStacker#709]
### Minecraft's Version

1.19.2 Paper version 210

### Plugin's Version

v2022.6

### Describe the bug

Players are retrieving less than what they lost when they die, upon picking up their dropped loot.

### To Reproduce

1. Die with say, 3 stacks of dirt.
2. Before picking up your lost dirt, add any item to your inventory.
3. Pick up the 3 stacks of dirt (shown as 192 dirt on the ground)
4. You will only get 1 stack

### Additional Information

Config: [https://pastebin.com/Cfud6eAJ](https://pastebin.com/Cfud6eAJ)

**Comment by OmerBenGera** [comment]
This happened before and turned to be an issue with another plugin.
Try it with only WildStacker installed on your server, let me know if it still occurs.

**Comment by Elgorond** [comment]
> This happened before and turned to be an issue with another plugin. Try it with only WildStacker installed on your server, let me know if it still occurs.

The conflict is with SuperiorSkyblock. It only happens on the Island world, and doesn't happen anymore when I remove the plugin.

**Comment by OmerBenGera** [comment]
Also try updating to latest version of WS

**Comment by Elgorond** [comment]
> Also try updating to latest version of WS

Still happens. Though I've tested with just these plugins...
![2022-12-25_10 13 11](https://user-images.githubusercontent.com/8552780/209658823-973d60a7-af16-4481-8e7d-6d4c1d90ed4f.png)

**Comment by OmerBenGera** [comment]
It works fine for me with SSB and WS installed.

**Comment by Elgorond** [comment]
> It works fine for me with SSB and WS installed. Do you mind taking a video of the issue? Upload it to YT or any other online streaming service and send a link to it here.

[https://www.youtube.com/watch?v=4l8ZlLItDOQ&ab_channel=HeroGateNetwork](https://www.youtube.com/watch?v=4l8ZlLItDOQ&ab_channel=HeroGateNetwork)

You'll notice i respawned with a few items in my inventory. You can ignore that. When I tested earlier without those plugins the issue still happened. But the main issue is that 3 stacks of dirt only let me pickup 1 stack for some reason. Only happens from items you died with. If I drop that amount (from inventory without dying) I can pick it back up again.

**Comment by OmerBenGera** [comment]
> > It works fine for me with SSB and WS installed. Do you mind taking a video of the issue? Upload it to YT or any other online streaming service and send a link to it here.
> 
> https://www.youtube.com/watch?v=4l8ZlLItDOQ&ab_channel=HeroGateNetwork
> 
> You'll notice i respawned with a few items in my inventory. You can ignore that. When I tested earlier without those plugins the issue still happened. But the main issue is that 3 stacks of dirt only let me pickup 1 stack for some reason. Only happens from items you died with. If I drop that amount (from inventory without dying) I can pick it back up again.

Try it on a server with only WS installed.
I can't replicate the issue myself.

**Comment by Elgorond** [comment]
> > > It works fine for me with SSB and WS installed. Do you mind taking a video of the issue? Upload it to YT or any other online streaming service and send a link to it here.
> > 
> > 
> > https://www.youtube.com/watch?v=4l8ZlLItDOQ&ab_channel=HeroGateNetwork
> > You'll notice i respawned with a few items in my inventory. You can ignore that. When I tested earlier without those plugins the issue still happened. But the main issue is that 3 stacks of dirt only let me pickup 1 stack for some reason. Only happens from items you died with. If I drop that amount (from inventory without dying) I can pick it back up again.
> 
> Try it on a server with only WS installed. I can't replicate the issue myself.

2 plugins installed (so it's not related to SuperiorSkyblock, my bad):
- BungeeGuard (ignore this)
- WildStacker

Better (more precise) replication method:

1. Give yourself 3 stacks of dirt
2. Go to chunks that will unload when leaving/dying (so outside of spawn chunks)
3. Die
4. Respawn and go back to where you died (which will reload the unloaded chunks)
5. You will only pick up 1 stack of dirt

So I suspect it has to do when the chunk unloads, not saving the proper stack amount? Because this bug does not happen in spawn chunks that are always loaded

**Comment by Elgorond** [comment]
You get a chance to confirm this?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Elgorond** [comment]
> Check out latest dev build, let me know if it works

Still has the bug

**Comment by OmerBenGera** [comment]
The issue is caused because when the ChunkLoadEvent and ChunkUnloadEvent are called with the new chunks system of Paper, it does not contain the entities anymore. I added support for their new events: EntitiesLoadEvent and EntitiesUnloadEvent so when they are called they save and load the data for the entities. 
Do you have these events in your Paper version? They might not be included in it and you'll need to update.

**Comment by OmerBenGera** [comment]
@Elgorond What version of Paper do you use? I will try to replicate it with your exact same version.

**Comment by Elgorond** [comment]
> @Elgorond What version of Paper do you use? I will try to replicate it with your exact same version.

1.19.2 Paper version 210

**Comment by OmerBenGera** [comment]
@Elgorond Let me know if it works now

**Comment by Elgorond** [comment]
> @Elgorond Let me know if it works now

Fixed!
