### ISSUE TITLE
Second hand unusable on Minecraft due to WildStacker

### ISSUE THREAD

**Issue by L064NTv** [BG-Software-LLC/WildStacker#710]
### Minecraft's Version

Server 1.17.1 (Paper)

### Plugin's Version

WildStacker.2022.6

### Describe the bug

Hello ! I have an problem with second hand. When WidlStacker is on in my server, i cant put a bloc with my seconde hand and when is off, i can. Have you ever had the problem?
thx

### To Reproduce

Take a block in the second hand then try to put it on the ground

### Additional Information

![image](https://user-images.githubusercontent.com/121443905/209558423-833bafe6-54a3-43a1-98c9-3c7c0d906126.png)

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it's fixed.

**Comment by L064NTv** [comment]
Oh yes ! Thank you very much is good !
