### ISSUE TITLE
Loot tables not working fully (DEV b406)

### ISSUE THREAD

**Issue by introvertism** [BG-Software-LLC/WildStacker#713]
### Minecraft's Version

Purpur 1.19.3-1879

### Plugin's Version

WildStacker-2022.6-b406

### Describe the bug

Up until now I had poppy removed from iron golem drops and snowballs removed from snowman drop but now after upgrading to 1.19.3 and the latest dev they are dropping again even though they are not in the loot table file. I do have a drop added to snowmen and that is working fine though.

### To Reproduce

Use latest dev version and purpur version and edit the loot table of iron golems to not include poppy as a drop. Put down an iron golem spawner and kill it, it will drop a poppy.

### Additional Information

https://pastebin.com/raw/VfbxWWzK

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
I removed poppies from the iron golem loot table and I don't have any of them dropped.
Try replicating it on a server with only WS installed, let me know if it still occurs.

**Comment by introvertism** [comment]
Ah, looks like one of my plugins which detects a damage cause and then insta kills a mob by doing ent.damage(999); is somehow causing this. Thanks for the quick reply, if you have any tips on how I can avoid this I would appreciate it! :)
