### ISSUE TITLE
Bad mob spawner when a player places it

### ISSUE THREAD

**Issue by DEV-Velris** [BG-Software-LLC/WildStacker#720]
### Minecraft's Version

Version 1.18.2
paper-1.18.2-388.jar

### Plugin's Version

I tried with the version:
2022.6
Dev #407

### Describe the bug

When a player places a spawner in Zombie for example, it turns into a pig directly. When the player is OP it works fine.

Even with the permission: wildstacker.place.* it does not work.

### To Reproduce

Place a spawner as a player.

**Comment by OmerBenGera** [comment]
This is due to another plugin, not related to WildStacker.
I know EssentialsX requires you a permission to place spawner blocks - `essentials.spawnerconvert` or something like that
