### ISSUE TITLE
Re open 720

### ISSUE THREAD

**Issue by DEV-Velris** [BG-Software-LLC/WildStacker#721]
### Minecraft's Version

All details in https://github.com/BG-Software-LLC/WildStacker/issues/720

### Plugin's Version

All details in https://github.com/BG-Software-LLC/WildStacker/issues/720

### Describe the bug

All details in https://github.com/BG-Software-LLC/WildStacker/issues/720

### To Reproduce

All details in https://github.com/BG-Software-LLC/WildStacker/issues/720

### Additional Information

You close the issue #720 but it still doesn't work with your permission !
It doesn't work with only wildstacker on the server !

**Comment by TadaClip** [comment]
I have the same problem, this is serious!
When a non-op player puts up a spawner, it becomes a pig spawner and just says this on the console:
[20:20:03 WARN]: Skipped entity with id

**Comment by DEV-Velris** [comment]
> 

I have nothing in console, it just spawn a pig instead of a cow when i'm not op

**Comment by OmerBenGera** [comment]
Find the plugin that caused it to occur.
As I told you, it is not WildStacker.
