### ISSUE TITLE
Only stack mobs from spawners

### ISSUE THREAD

**Issue by Xenonhead** [BG-Software-LLC/WildStacker#722]
### Minecraft's Version

1.19.3

### Plugin's Version

2022.6

### Describe the bug

Hi can I stack only from Spawners?
I cant find the option in the config file

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Do not open issues for support - they are meant to be opened only for bug reports.
You can add "SPAWNER" to the whitelist section under the entities section.
