### ISSUE TITLE
Mobs from spawner have AI when the option on spigot is Nerf spawner mobs

### ISSUE THREAD

**Issue by antibitcoin** [BG-Software-LLC/WildStacker#723]
### Minecraft's Version

after mobs get stacked they gain their AI back.

### Plugin's Version

2022.6

### Describe the bug

My mobs had no ai so players made farms according to this, but now that mobs gain AI after getting merged people started dying, and its just taking a hit on the server. I want them to stay dump like before.

### To Reproduce

set nerf spawner mobs to true on spigot settings and restart

**Comment by OmerBenGera** [comment]
WildStacker overrides the nerfing system.
Instead of setting it to true in Spigot's files, add "SPAWNER" to the nerfing-entities whitelist in the config file of WildStacker and you'll get the same effect.
