### ISSUE TITLE
Bugged spawner placement

### ISSUE THREAD

**Issue by DEV-Velris** [BG-Software-LLC/WildStacker#724]
### Minecraft's Version

Version: 1.18.2
Paper Build 388

paper-1.18.2-388

### Plugin's Version

2022.6

### Describe the bug

When a player places a spawner it automatically turns into a pig even if this spawner is a cow spawner.

### To Reproduce

To reproduce this bug, just put :

//Should spawners get stacked on the server ?
enabled : false

in the spawners configuration. When this value is set to true, it works but once set to false, it does not work anymore. **The tests have been done with WildStacker only.**

**Comment by OmerBenGera** [comment]
If you disable spawners, WildStacker will not handle spawners anymore - aka, your spawners will not work anymore.
Use a different plugin to handle your spawners or enable spawners in WS's config file.
