### ISSUE TITLE
Dev builds overriding MythicMobs mob drops

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/WildStacker#726]
### Minecraft's Version

Paper 1.19.2-210

### Plugin's Version

Tested with 399, 407, 408 dev builds

### Describe the bug

Previously on the latest stable (2022.6) WildStacker wasn't overriding MythicMob mob drops. But ever since updating to 399+ it breaks it, and overrides the mob drops. So sometime after 2022.6 this issue started.

So instead of getting gold ingots and a custom command when you kill a custom zombie (spawned with MythicMobs), it will drop vanilla zombie loot and not run the command.

### To Reproduce

See above

**Comment by OmerBenGera** [comment]
I am using the default mobs of MythicMobs and latest version of WildStacker and it seems to work fine.
I spawned a SkeletalKnight and I receive a gold nugget when it dies.

**Comment by Elgorond** [comment]
> I am using the default mobs of MythicMobs and latest version of WildStacker and it seems to work fine. I spawned a SkeletalKnight and I receive a gold nugget when it dies.

That's very odd... Just tried it myself and I got bones.

**Comment by Elgorond** [comment]
> I am using the default mobs of MythicMobs and latest version of WildStacker and it seems to work fine. I spawned a SkeletalKnight and I receive a gold nugget when it dies.

Add Despawn: false to the options in the SkeletalKnight. This is what seems to break the drops now.

**Comment by OmerBenGera** [comment]
I managed to replicate the issue, however I am not sure what Despawn does or why it works without it.
I tried to look at MythicMobs but their code is huge and I can't seem to find where they listen to the EntityDeathEvent and what they do there.
I'd suggest to contact them and ask for help as well, they might have answers or a solution to this.

**Comment by Elgorond** [comment]
> I managed to replicate the issue, however I am not sure what Despawn does or why it works without it. I tried to look at MythicMobs but their code is huge and I can't seem to find where they listen to the EntityDeathEvent and what they do there. I'd suggest to contact them and ask for help as well, they might have answers or a solution to this.

Despawn: false makes it so the mobs don't despawn when chunk unloads or despawn naturally over time. They need to be killed or server needs to restart

**Comment by OmerBenGera** [comment]
> > I managed to replicate the issue, however I am not sure what Despawn does or why it works without it. I tried to look at MythicMobs but their code is huge and I can't seem to find where they listen to the EntityDeathEvent and what they do there. I'd suggest to contact them and ask for help as well, they might have answers or a solution to this.
> 
> Despawn: false makes it so the mobs don't despawn when chunk unloads or despawn naturally over time. They need to be killed or server needs to restart. I've asked for some help in their discord. Hopefully a dev can assist you

Hmm weird why it affects the drops.
Hopefully they will be able to respond here and give us some help with this.

**Comment by Elgorond** [comment]
> > > I managed to replicate the issue, however I am not sure what Despawn does or why it works without it. I tried to look at MythicMobs but their code is huge and I can't seem to find where they listen to the EntityDeathEvent and what they do there. I'd suggest to contact them and ask for help as well, they might have answers or a solution to this.
> > 
> > 
> > Despawn: false makes it so the mobs don't despawn when chunk unloads or despawn naturally over time. They need to be killed or server needs to restart. I've asked for some help in their discord. Hopefully a dev can assist you
> 
> Hmm weird why it affects the drops. Hopefully they will be able to respond here and give us some help with this.

Ash — 01/15/2023 1:39 PM
that issue doesn't really make any sense, despawn should have no effect on drops

So uh, that's the response I got

**Comment by OmerBenGera** [comment]
> > > > I managed to replicate the issue, however I am not sure what Despawn does or why it works without it. I tried to look at MythicMobs but their code is huge and I can't seem to find where they listen to the EntityDeathEvent and what they do there. I'd suggest to contact them and ask for help as well, they might have answers or a solution to this.
> > > 
> > > 
> > > Despawn: false makes it so the mobs don't despawn when chunk unloads or despawn naturally over time. They need to be killed or server needs to restart. I've asked for some help in their discord. Hopefully a dev can assist you
> > 
> > 
> > Hmm weird why it affects the drops. Hopefully they will be able to respond here and give us some help with this.
> 
> Ash — 01/15/2023 1:39 PM that issue doesn't really make any sense, despawn should have no effect on drops
> 
> So uh, that's the response I got. Any idea why previous WildStacker versions don't have this bug?

I changed the way the EntityDamageEvent for the last entity damage is called.
Instead of being called by Bukkit, it is called by WildStacker - that might somehow affect it.

However, it works without the despawn, therefore I suspect it's not a direct issue of WildStacker.
Check what else affects this besides despawn, it might be something else that causes this to occur.

**Comment by Elgorond** [comment]
> > > > > I managed to replicate the issue, however I am not sure what Despawn does or why it works without it. I tried to look at MythicMobs but their code is huge and I can't seem to find where they listen to the EntityDeathEvent and what they do there. I'd suggest to contact them and ask for help as well, they might have answers or a solution to this.
> > > > 
> > > > 
> > > > Despawn: false makes it so the mobs don't despawn when chunk unloads or despawn naturally over time. They need to be killed or server needs to restart. I've asked for some help in their discord. Hopefully a dev can assist you
> > > 
> > > 
> > > Hmm weird why it affects the drops. Hopefully they will be able to respond here and give us some help with this.
> > 
> > 
> > Ash — 01/15/2023 1:39 PM that issue doesn't really make any sense, despawn should have no effect on drops
> > So uh, that's the response I got. Any idea why previous WildStacker versions don't have this bug?
> 
> I changed the way the EntityDamageEvent for the last entity damage is called. Instead of being called by Bukkit, it is called by WildStacker - that might somehow affect it.
> 
> However, it works without the despawn, therefore I suspect it's not a direct issue of WildStacker. Check what else affects this besides despawn, it might be something else that causes this to occur. I can tell you that when it occurred, the drops of MythicMobs were not added to the drops list in EntityDeathEvent.

I've relayed this message to the MythicMobs dev. But from more testing I think it has to do with mobs when they don't despawn from chunk unloads (somehow they function differently?). Setting despawn to "false" or "chunk" there is no issue. The issue happens when using "true" or "persistent".
[https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Mobs/Options#despawn](https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Mobs/Options#despawn)

**Comment by Elgorond** [comment]
[https://discordapp.com/channels/213109157983813633/1063905958012665986](https://discordapp.com/channels/213109157983813633/1063905958012665986)

Here's the link to the discord thread if you're interested. Could talk to the dev there.

**Comment by OmerBenGera** [comment]
I have no clue. I also don't know where they listen to EntityDeathEvent and where they add their custom drops.
They need to somehow help us debug it on their end.

**Comment by Elgorond** [comment]
> I have no clue. I also don't know where they listen to EntityDeathEvent and where they add their custom drops. They need to somehow help us debug it on their end.

If you ask him these questions I'm sure he will answer. Would probably be resolved quick if you join their [discord](https://discord.com/invite/K3tqXfT) and click on the previous link I sent to get to the thread. Hard to be a middleman here

And personally can't update until this is fixed :/

**Comment by Elgorond** [comment]
Any update on this?

**Comment by OmerBenGera** [comment]
@Elgorond Can you test if it still occurs with latest dev build?
Ash doesn't really respond in our ticket, so let's try to fix it ourselves.

**Comment by Elgorond** [comment]
> @Elgorond Can you test if it still occurs with latest dev build? Ash doesn't really respond in our ticket, so let's try to fix it ourselves.

Issue still occurs

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, let me know if it works

**Comment by Elgorond** [comment]
> Hey, check out latest dev build, let me know if it works

Seems to be fixed!
