### ISSUE TITLE
Mobs don't stack 

### ISSUE THREAD

**Issue by LPXZIsGod** [BG-Software-LLC/WildStacker#728]
### Minecraft's Version

paper latest build #375

### Plugin's Version

Latest dev build #408 07/01/2023 15:10:04

### Describe the bug

Whenever mobs spawn, they do not stack it looks to me like the plugin is not able to somehow keep up with the spawn, perhaps a database issue. i have tried many things but i'm unable to change the bahavior of the plugin. I'm happy to supply any information needed to solve the issue

### To Reproduce

Just use wildstacker on 1.19.3, i have spawner stacks of 25 and mobstacking turned on.

**Comment by OmerBenGera** [comment]
Run `/ws simulate` and click the two entities, make sure they can stack together.
Also, send me your config file by uploading it to pastebin and send a link to it here.

**Comment by LPXZIsGod** [comment]
I have tried a couple of things and i saw that the stack interval was set to 0, i have changed that value to a bigger number (400) which seems to have fixed the issue.  
https://pastebin.com/30UxXXNP here is the config file, i ended up removing the plugin and readding it later on.

**Comment by OmerBenGera** [comment]
> I have tried a couple of things and i saw that the stack interval was set to 0, i have changed that value to a bigger number (400) which seems to have fixed the issue. https://pastebin.com/30UxXXNP here is the config file, i ended up removing the plugin and readding it later on.

If stack-interval fixed the issue, it means the mobs were far away from each other and thats why they didnt stack together.
I am closing this for now, keep the stack interval :)
