### ISSUE TITLE
Lootables not working on 1.7.10

### ISSUE THREAD

**Issue by iwentafk** [BG-Software-LLC/WildStacker#729]
### Minecraft's Version

1.7.10 KCauldron

### Plugin's Version

2022.6-b408 - Dev Build 408

### Describe the bug

Using custom loot tables do not work on any of the dev builds from 2022.6 since the plugin was patched for 1.7.10. I've configured everything correctly and mobs just drop default drops and the console just spams with errors. Also the wildstacker command itself does not do anything I have to restart the server to reload the configs.

### To Reproduce

Put a custom drop in loot tables on a 1.7.10 server and kill the mob. It just drops default loot.

### Additional Information

Console Errors:

https://hastebin.com/omikigeqat.properties

**Comment by OmerBenGera** [comment]
Only spigot and its forks are supported.
