### ISSUE TITLE
Stacked mobs giving no XP for mcmmo

### ISSUE THREAD

**Issue by Noobymen** [BG-Software-LLC/WildStacker#732]
### Minecraft's Version

This server is running Paper version git-Paper-376 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1719345)

### Plugin's Version

WildStacker-2022.6-b409

### Describe the bug

when killing stacked mobs there are no mcmmo xp given

### To Reproduce

mcmmo and wildstacker and slimefun on one server 
spawn a mob spawner in using /sf cheat click top right to search and typ in chat spawner then you choose the reinforced spawner place it down by default it will be pig spanwer but i wood change it to be a skeleton or a blaze for testing by using a spawn egg on the spanwer when you place it down
use sword when killing mobs 
do /swords keep to track if you get xp
and then just kill the stacked mobs

### Additional Information

Am talking about mobs that spawn using mob spawners from Slimefun

**Comment by OmerBenGera** [comment]
By default, mcMMO does not give experience for mobs that spawned unnaturally - make sure it is enabled.
If it still occurs after you enable it let me know here and I will reopen the issue.
