### ISSUE TITLE
Entity Stacker not stacking, all spawns individually. 

### ISSUE THREAD

**Issue by BishopFranklin** [BG-Software-LLC/WildStacker#734]
### Minecraft's Version

git-Purpur-1632 (MC: 1.18.2)

### Plugin's Version

Version 2022.6

### Describe the bug

spawner stacks are not spawning mobs in stacks. They spawn all of the mobs individually. I had this plugin working 9 hours ago, I went to bed and woke up and mobs no longer stack. 

### To Reproduce

I'm not too sure, 
One of our players said that they were they only one on and it was already happening when he logged on...
So I guess try to have everyone leave the server and log back on and see if that breaks it. 

### Additional Information

I was told to make a ticket here after Ome_R suggested me too.  
Here is my .config file 
https://pastebin.com/Y6weG9St

**Comment by LPXZIsGod** [comment]
I have the same problem, i've figured out that when placing the spawners as an OP it does work so maybe it has something to do with a permission?

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue myself.
Try replicating it on a server with only WS installed

**Comment by iSeitan** [comment]
I have the same issue when using Upgradablespawners

**Comment by OmerBenGera** [comment]
> I have the same issue when using Upgradablespawners Also wildstacker is removing the option from upgradablespawner that makes mobs from spawners with no AI

WildStacker overrides the spigot's nerfing system. Any plugin (including Spigot itself) that use this will not work and you should use WildStacker's config to enable it instead.
Not related to the issue anyways.
@LPXZIsGod Any news regarding this?

**Comment by LPXZIsGod** [comment]
This happend to me aswell, i've found out that using the ingame settings sometimes breaks the config somehow. That did it for me at least

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue persists, let me know
