### ISSUE TITLE
Auto-stacking edge case

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/WildStacker#735]
### Minecraft's Version

Paper 1.19.2-210

### Plugin's Version

2022.6

### Describe the bug

Auto-stacking seems to stop working for certain stacks if a mob in the stack dies right before the stack stops moving? You'll see what I mean if you watch the vid: [https://www.youtube.com/watch?v=j7m2P8pnvZk&ab_channel=HeroGateNetwork](https://www.youtube.com/watch?v=j7m2P8pnvZk&ab_channel=HeroGateNetwork) The iron golems are nerfed so I think it requires that for the bug to happen as well

I'm guessing that as a quick-fix for me, lowering the stack interval might reduce this edge case? Because the stack might be able to re-stack just before the stack stops moving. I currently use stack-interval: 100

### To Reproduce

See above vid

**Comment by OmerBenGera** [comment]
I don't quite understand what the issue is to be honest...

**Comment by Elgorond** [comment]
> I don't quite understand what the issue is to be honest...

Don't you see how some of them stop auto-stacking? Is that intended?

**Comment by OmerBenGera** [comment]
Use the simulate tool on these mobs, check if they can stack together.

**Comment by Elgorond** [comment]
> Use the simulate tool on these mobs, check if they can stack together.

Yea my stacking interval was just too low I think. You can close this
