### ISSUE TITLE
EliteBosses mobs regen health when trying to kill them and go god mode

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#736]
### Minecraft's Version

1.8.8

### Plugin's Version

Dev Build #408

### Describe the bug

With EliteBosses, when you place a boss down it either has god mode, or it will take damage and instantly regen and then go into god mode. This has only happened since I updated WildStacker. No error in console. 

### To Reproduce

Place down a boss from EliteBosses and you can see it will regen health and become a god, or it will spawn with god mode.

**Comment by OmerBenGera** [comment]
I contacted Splodgebox and hopefully we will be able to sort it out.
Keeping this opened for the time being. I will report back once I have some news

**Comment by OmerBenGera** [comment]
Hey, what do you mean by "god mode"? It does not take damage?

**Comment by Rhys00** [comment]
> Hey, what do you mean by "god mode"? It does not take damage?

Yeah that is correct, the boss goes into a mode where it does not take damage. You can hit it, it’s just the hearts don’t go down and you can’t kill it.

**Comment by OmerBenGera** [comment]
You are right, it takes much more time to deal damage to EliteBosses when WildStacker is installed.
I will contact Splodgebox  regarding this, hopefully it will be fixed soon

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, let me know if it works

**Comment by Rhys00** [comment]
> Hey, check out latest dev build, let me know if it works

Nah doesnt work, to note it also lets you 2 hit bosses with like 2k health and custom mobs etc.

**Comment by OmerBenGera** [comment]
> > Hey, check out latest dev build, let me know if it works
> 
> Nah doesnt work, to note it also lets you 2 hit bosses with like 2k health and custom mobs etc.

What does not work exactly?
Now you report the opposite...

**Comment by OmerBenGera** [comment]
@Rhys00 I fixed an issue with killing any mob with just 2 hits.
I am closing this for now; If any of the issues pop up again, let me know.
