### ISSUE TITLE
WildStacker -> Named entity EntityCow['x172 Vaca'/678781

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#737]
### Minecraft's Version

Pufferfish git-Pufferfish-47 (MC: 1.19.2)

### Plugin's Version

WildStacker-2022.6-b408.jar

### Describe the bug

this keeps happening in the console non-stop, it only started when I upgraded to the latest versions of wildstacker, is this wildstacker? 

-> https://prnt.sc/EIWAK_Z0BhKT
-> https://pastebin.com/AZhXQ88b

### To Reproduce

it seems that this happens when 1 mob is killed

**Comment by OmerBenGera** [comment]
Pufferfish for no reason prints these messages when a named entity dies.
Because WildStacker gives custom names to all entities, it will show for each dead entity.
Contact them for support, nothing to do on my end.

**Comment by kev626** [comment]
`log-named-deaths: false` in spigot.yml. This is not a bug.
