### ISSUE TITLE
Sweeping edge enchant [BUG]

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/WildStacker#738]
### Minecraft's Version

paper-1.19.3-379

### Plugin's Version

WildStacker-2022.6-b411

### Describe the bug

Theres a bug where sweaping edge damage deletes complete stack of mobs instead of killing them normally
Like I got a stack of 100 mobs, if i have sweeping edge enchant, it would kill one, but delete the whole stack without giving exp or items
and sometime the sweeping edge damage to other mobs around the target will die glitched the same

So theres a bug that delete stacks, without giving item or exp

### To Reproduce

Use a sword with sweeping edge, makes multiple stack of monsters in the same spot
Kill a mobs and you'll see stacks get deleted

**Comment by OmerBenGera** [comment]
Do you mind taking a short video of the issue?

**Comment by iSeitan** [comment]
https://www.youtube.com/watch?v=dIFteh9Njcw

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by iSeitan** [comment]
After some testing, it seems to have fixed the issue!! :D
