### ISSUE TITLE
Make StackTask.run() not creating lag spike

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#741]
### Minecraft's Version

1.19.2

### Plugin's Version

b400

### Describe the bug

the StackTask.run() that happen every 5mn make some lag spike
It wouldn't be possible to make it in two times, or transform less mobs per tick, so it doesn't create lag spike
That's not really important currently, but with more mobs it would get higher and make higher lag

https://spark.lucko.me/HnH61pCyH0
![image](https://user-images.githubusercontent.com/31826333/213941128-15c1ef4e-5e6a-47a2-b059-151ba911f71d.png)

### To Reproduce

- set an auto stacking delay
- wait for entities to stack
- do a spark --only-tick-over 100

### Additional Information

Config :

  merge-radius:
    all: 6
  stack-interval: 2400

**Comment by OmerBenGera** [comment]
The stack task is laggy in its roots.
It goes through all the entities and look for nearby entities, then tries to stack them up.
Don't use it if you don't want lag.
