### ISSUE TITLE
Mobs sometimes count false when killed

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#742]
### Minecraft's Version

pufferfish 1.19.2

### Plugin's Version

working great : b400

getting issue : b406 -> b414

### Describe the bug

Using plugin version b406 or newer, sometimes when player kill a stacked mob, it will increase a lot his statistic in JobsReborn/QuestCreator, so he kill 1 mobs, and it can count like if he killed 50 mobs

I don't get the issue at all on b400, but if I upgrade on a newer version than b406 I get the issue

I still don't know how to reproduce, but I open the ticket because maybe other people get the issue, or maybe you see a broken patch between b400 and b406, maybe : 
> Potential fix for issues with mcmmo and other plugins when entities die (#697)
> Fixed infinite recursive calls when other plugins call custom EntityDamageEvent events (#703)
> Potential fix for issues with mcmmo and other plugins when entities die (#697)

Hope we'll find the issue, there are important issues I need to fix by ugrading wildstacker.

### To Reproduce

to be determinated

### Additional Information

if someone get the issue, please help :)

**Comment by WarnDa** [comment]
I still got the issue, it's very random, can't  really find the reason or a way to 100% reproduce it, but I'm sure the bug is still there on b414, and wasn't before b406 !

The sword I used to to test, maybe it can help : 
![image](https://user-images.githubusercontent.com/31826333/214644445-5847c89f-7595-4947-a5ee-fa248f854134.png)

**Comment by OmerBenGera** [comment]
Check out in latest dev build.

**Comment by WarnDa** [comment]
Player tell me it's still happening for him

**Comment by WarnDa** [comment]
Possible to add debug or other things to find the issue ?
I need to update as it fixes some issues for me, but I can't

**Comment by OmerBenGera** [comment]
> Possible to add debug or other things to find the issue ? I need to update as it fixes some issues for me, but I can't due to this

You can use `/is admin debug entity_spawn` and `/is admin debug entity_despawn` to get informed when the plugin tracks new/killed entities

**Comment by WarnDa** [comment]
> > Possible to add debug or other things to find the issue ? I need to update as it fixes some issues for me, but I can't due to this
> 
> You can use `/is admin debug entity_spawn` and `/is admin debug entity_despawn` to get informed when the plugin tracks new/killed entities

It won't track if the killed mob counted as x1 or x5, so we won't know

**Comment by OmerBenGera** [comment]
> > > Possible to add debug or other things to find the issue ? I need to update as it fixes some issues for me, but I can't due to this
> > 
> > 
> > You can use `/is admin debug entity_spawn` and `/is admin debug entity_despawn` to get informed when the plugin tracks new/killed entities
> 
> It won't track if the killed mob counted as x1 or x5, so we won't know

It prints the amount of mobs that spawned/despawned.

**Comment by WarnDa** [comment]
I just tried and it prints nothing in console or in my chat :/
> superior b977
> Wildstacker b400

**Comment by OmerBenGera** [comment]
> I just tried and it prints nothing in console or in my chat :/
> 
> > superior b977
> > Wildstacker b400

How can I replicate it?
You said it happens randomly, right?

**Comment by WarnDa** [comment]
> > I just tried and it prints nothing in console or in my chat :/
> > > superior b977
> > > Wildstacker b400
> 
> How can I replicate it? You said it happens randomly, right?

Yes, but doesn’t happen on b400, and happen since b404, randomly when player kill the mobs it will count like the whole stack amount/the amount left in the stack, as it increase 2-3 levels in 1 kill in jobs reborn

**Comment by OmerBenGera** [comment]
> > > I just tried and it prints nothing in console or in my chat :/
> > > > superior b977
> > > > Wildstacker b400
> > 
> > 
> > How can I replicate it? You said it happens randomly, right?
> 
> Yes, but doesn’t happen on b400, and happen since b404, randomly when player kill the mobs it will count like the whole stack amount/the amount left in the stack, as it increase 2-3 levels in 1 kill in jobs reborn

Let me know how to replicate the issue.
I need exact steps so I can look into it.

**Comment by WarnDa** [comment]
I updated to latest dev build and seems fixed, the fix was maybe this : https://github.com/BG-Software-LLC/WildStacker/commit/448b30e3b77a85f293fdf6117a3c6839eed2eeb5
WIll reopen it if the issue persist

**Comment by OmerBenGera** [comment]
Okay, good.
Let me know if it happens again :)
