### ISSUE TITLE
mythic mobs warmup timer anulled by wildstacker

### ISSUE THREAD

**Issue by R3voolt** [BG-Software-LLC/WildStacker#743]
### Minecraft's Version

[19:54:11 INFO]: This server is running Paper version git-Paper-384 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18fabc0)
You are running the latest version
Previous version: git-Paper-381 (MC: 1.19.3)

### Plugin's Version

DEV   WildStacker-2022.6-b415

### Describe the bug

Create a mythic mob spawner, add warmup timer to xx, and u will see it works just fine
Add wildstacker plugin, and created mm spawner wont follow aany warmup rule anymore, and will just spawn mobs ignoring all warmup timer!

### To Reproduce

Create a mythic mob spawner, add warmup timer to xx, and u will see it works just fine
Add wildstacker plugin, and created mm spawner wont follow aany warmup rule anymore, and will just spawn mobs ignoring all warmup timer!

### Additional Information

tested on a fresh server, just with necesarly plugins!
Hope on a fix when u can ! Thanks a lot !

**Comment by OmerBenGera** [comment]
WildStacker handles spawners by itself and will override any other plugin.
You can disable it in the config if you wish.
