### ISSUE TITLE
Dropped items from stacked mobs

### ISSUE THREAD

**Issue by Swoochy** [BG-Software-LLC/WildStacker#748]
### Minecraft's Version

1.8 

### Plugin's Version

Latest Stable Version

### Describe the bug

When the mob dies and drops the items. it can say there 35k. but when player picks it up. it fills the inventory and the other amount disappears. 

### To Reproduce

happens every time a mob gets killed and drops the items

**Comment by OmerBenGera** [comment]
What version of Spigot are you using?
What version of the plugin are you using?
Please upload your config to pastebin and send a link to it here

**Comment by Swoochy** [comment]
SpigotPaper-445 (1.8.8)
Wildstacker-2022.6

Config: https://pastebin.com/Xtuk8bnw

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Swoochy** [comment]
Latest dev has glitch when instant kill and nerfed. The mod just shows the fealty animation even when off. But it’s stays. Even if another mob in the stack.

**Comment by OmerBenGera** [comment]
> Latest dev has glitch, when instant kill and nerfed is on. The mob just shows the death animation even when off. But it’s stays, so killing a stack of mobs to death animation would glitch underground but the mob is still technically there.

Send me the config that causes this issue and I will look into it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
