### ISSUE TITLE
Villager ai somehow nog being disabled

### ISSUE THREAD

**Issue by LPXZIsGod** [BG-Software-LLC/WildStacker#750]
### Minecraft's Version

Paper version #380 (1.19.3) 

### Plugin's Version

WildStacker-2022.6-b411.jar (dev build i believe)

### Describe the bug

Villager don't seem to have their ai disabled when nerfed, it's a combination of unloading /reloading the chunks aswell as placing down workbenches. There are no errors in the console. 

### To Reproduce

Wildstacker + paper, all entities on "nerfd" that should reproduce this bug. 

### Additional Information

Unfortnately i'm unable to supply further evidence since i run quitte a large server, so leaving this bug for any longer results in an economy crash, since mending is worth a lot.

**Comment by OmerBenGera** [comment]
Upload your config to pastebim and send a link to it here.
In general, I dont think nerfing villagers will make them untradeable, so if thats what you want to achieve, you should use a 3rd party plugin to do that.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
