### ISSUE TITLE
Custom Drop with jetsminions

### ISSUE THREAD

**Issue by TardyC** [BG-Software-LLC/WildStacker#751]
### Minecraft's Version

1.8 labymod client
Server.jar Ver
![image](https://user-images.githubusercontent.com/82113954/218146768-7c12b562-604b-4121-845d-25a4708aa0e1.png)
JetsMinions Ver
![image](https://user-images.githubusercontent.com/82113954/218146895-820ae1c5-0cf2-4988-bc1d-5aaea5391ae7.png)
Wildstacker Version
![image](https://user-images.githubusercontent.com/82113954/218146949-af22811a-47fa-47b9-ba9a-d75a7a94f8ee.png)

Video of my problem
https://medal.tv/games/minecraft/clips/UzCtAJCOFSS2B/d13372lLVKJN?invite=cr-MSxSSGYsNTIzNjQ5OCw

### Plugin's Version

Server.jar Ver
![image](https://user-images.githubusercontent.com/82113954/218146768-7c12b562-604b-4121-845d-25a4708aa0e1.png)
JetsMinions Ver
![image](https://user-images.githubusercontent.com/82113954/218146895-820ae1c5-0cf2-4988-bc1d-5aaea5391ae7.png)
Wildstacker Version
![image](https://user-images.githubusercontent.com/82113954/218146949-af22811a-47fa-47b9-ba9a-d75a7a94f8ee.png)

### Describe the bug

I dont get drops by the slayer custom drops

But then i killed them by my own sword there is no problem i get the drop but why dont then JetsMinions slayes it
It need to be on upgradede spawner so i can get more upgrades

### To Reproduce

Standart config on both plugins
Tried everything 
Pastebins to lootables: https://pastebin.com/BKqLcVpb
PasteBin for config: https://pastebin.com/7w2UmwKU

**Comment by OmerBenGera** [comment]
Do you mind testing it on 1.19.3? Check if it still occurs

**Comment by TardyC** [comment]
I only play in 1.8

**Comment by TardyC** [comment]
And i only work in 1.19.3
dont work in 1.8 can you do so i work in 1.8

**Comment by TardyC** [comment]
Ohh sry i dont work in 1.19

**Comment by OmerBenGera** [comment]
> Ohh sry i dont work in 1.19

It works fine in 1.19, however it is bugged in 1.8
I am looking into it.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by TardyC** [comment]
Dont work

**Comment by TardyC** [comment]
Now do custom drops not work even if i kill them

**Comment by TardyC** [comment]
No error in console or anything

**Comment by OmerBenGera** [comment]
Try checking it again, as it works fine for me.

**Comment by OmerBenGera** [comment]
Check out dev build 418, let me know if it works now
@TardyC

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue persists, let me know

**Comment by TardyC** [comment]
Dev 418 dont work maybe try debug?

I cant getting it to work

**Comment by OmerBenGera** [comment]
I managed to replicate the issue again, I will talk with Jet regarding this.

**Comment by OmerBenGera** [comment]
Check out latest version of JetsMinions, let me know if it works.

**Comment by TardyC** [comment]
works now
