### ISSUE TITLE
Guardian AI

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#754]
### Minecraft's Version

Paper version git-Paper-270 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker-2022.6-b416.jar

### Describe the bug

You can't nerf Guardians. They still have AI no matter what I write. All other mobs work fine and without AI when added here.

  nerfed-entities:
    # A list of entities that will be nerfed.
    # If you want all entities to be nerfed, set this to [].
    whitelist:
    - BLAZE:SPAWNER
    - CHICKEN:SPAWNER
    - SPIDER:SPAWNER
    - ENDERMAN:SPAWNER
    - SKELETON:SPAWNER
    - GUARDIAN:SPAWNER
    - ENDERMITE:SPAWNER

### To Reproduce

Add "Guardian:Spawner" to nerfed entities and have them spawn.

**Comment by OmerBenGera** [comment]
If you nerfed them by WildStacker, then WildStacker sets them the nerf status of Spigot
If they still have AI and are not actually nerfed, it is a bug in Spigot as WildStacker uses Spigot's system to nerf entities.
