### ISSUE TITLE
Mob stack size hit with fire aspect

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#756]
### Minecraft's Version

Paper version git-Paper-270 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker-2022.6-b416.jar

### Describe the bug

When a stack of mobs is hit with a sword with fire aspect the stack keeps adding mobs to the stack by itself. Even without spawners nearby.

https://medal.tv/games/minecraft/clips/VNZmlRjpSjKJa/d1337HINphpd?invite=cr-MSxBUVYsNzM1MDU0Myw
https://medal.tv/games/minecraft/clips/UitedJLmdc_Ev/d1337odOqeKv?invite=cr-MSxDUnosNzM1MDU0Myw

Clips are from two different servers.

### To Reproduce

Hit a stack of mobs with a fire aspect sword.

### Additional Information

Wildstacker config file:

https://pastebin.com/Aiq3xYX4

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue on latest dev build?
I can't seem to do so

**Comment by Sckaletz** [comment]
This happens now with Wildstacker 2022.6 B423. It doesn't add to the stack, but it keeps killing from the stack after I've stopped hitting them. And I'm hitting really really slow.

https://medal.tv/games/minecraft/clips/10jzKTUMv9JtrI/d1337MwX8mv5?invite=cr-MSxLc3UsNzM1MDU0Myw

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue on a server with only WildStacker installed?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
