### ISSUE TITLE
WildStacker disabling Villager's AI after restarting.

### ISSUE THREAD

**Issue by NerdTryingToCode** [BG-Software-LLC/WildStacker#757]
### Minecraft's Version

Purpur 1.19.2

### Plugin's Version

Stable Version 2022.6

### Describe the bug

Villagers AI get disabled completely, you can still trade but they won't move / leave beds.
External force will move it but won't reactive its AI.
I blacklisted Villagers in the linking-nerfed thing.

### To Reproduce

Summon a villager, give it a job, restart.

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send a link to it herr

**Comment by NerdTryingToCode** [comment]
https://pastebin.com/2qHuJmFn

**Comment by OmerBenGera** [comment]
If you use the inspect tool (/ws inspect) and click on a villager, do you see it nerfed?

**Comment by NerdTryingToCode** [comment]
Let me try

**Comment by NerdTryingToCode** [comment]
> If you use the inspect tool (/ws inspect) and click on a villager, do you see it nerfed?

Is the commad for dev builds? It says /stacker inspect

**Comment by NerdTryingToCode** [comment]
> If you use the inspect tool (/ws inspect) and click on a villager, do you see it nerfed?

It is 
![image](https://user-images.githubusercontent.com/85940129/220038200-d9ec7452-bade-42f8-9293-9fca5dff3885.png)

**Comment by NerdTryingToCode** [comment]
Also is there a way to unnerf villagers, i still need to fix the nerfed one for players

**Comment by OmerBenGera** [comment]
> > If you use the inspect tool (/ws inspect) and click on a villager, do you see it nerfed?
> 
> It is ![image](https://user-images.githubusercontent.com/85940129/220038200-d9ec7452-bade-42f8-9293-9fca5dff3885.png)

Try removing villagers from blacklist, check if it helps

**Comment by NerdTryingToCode** [comment]
> > > If you use the inspect tool (/ws inspect) and click on a villager, do you see it nerfed?
> > 
> > 
> > It is ![image](https://user-images.githubusercontent.com/85940129/220038200-d9ec7452-bade-42f8-9293-9fca5dff3885.png)
> 
> Try removing villagers from blacklist, check if it helps

It happened before i even blacklist it but i'm gonna do it now

**Comment by NerdTryingToCode** [comment]
Can i just disable the nerf feature

**Comment by NerdTryingToCode** [comment]
![image](https://user-images.githubusercontent.com/85940129/220112774-ba2cc46c-d385-4a33-a04b-e0f9816763a4.png)
Still same issue after removing it from blacklist, imma try disabling nerf, however can i unnerf previously nerfed ones?

**Comment by OmerBenGera** [comment]
You should use "VILLAGER", all in upper case instead.
However, this will make all entities nerfed besides villagers - if you don't want any mobs to be nerfed, just keep the blacklist empty.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
