### ISSUE TITLE
Empty Spawners

### ISSUE THREAD

**Issue by Refunded** [BG-Software-LLC/WildStacker#758]
### Minecraft's Version

paper-1.19.3.jar
(couldn't upload jar, says unsupported file type)

Java 1.19.3

### Plugin's Version

Dev Build #416

### Describe the bug

When placing a spawner nothing ends up inside. They are empty.

### To Reproduce

On many occasion I've tried updating, reverting etc. Spawners are always empty when placed, but when broken say "piggy" spawner broken.

### Additional Information

This is a copy and paste of my Error/Console log of when trying to place a spawner.

19.02 01:03:21 [Server] WARN Skipping Entity with id 
19.02 01:03:21 [Multicraft] Skipped 6 lines due to rate limit (30/s)
19.02 01:03:20 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1963) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:587) ~[?:?]
19.02 01:03:20 [Server] INFO at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:403) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:396) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
19.02 01:03:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
19.02 01:03:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
19.02 01:03:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor586.execute(Unknown Source) ~[?:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:150) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:59) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:64) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:246) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:257) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:47) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:54) ~[WildStacker-2022.6-b416.jar:?]
19.02 01:03:20 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.block.CraftCreatureSpawner.getSpawnedType(CraftCreatureSpawner.java:18) ~[paper-1.19.3.jar:git-Paper-312]
19.02 01:03:20 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.MobSpawnerData.a()" because "net.minecraft.world.level.block.entity.TileEntityMobSpawner.d().f" is null
19.02 01:03:20 [Server] ERROR Could not pass event BlockPlaceEvent to WildStacker v2022.6-b416
19.02 01:03:20 [Server] WARN Skipping Entity with id

**Comment by OmerBenGera** [comment]
Does it happen if you only have WS installed?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
