### ISSUE TITLE
Circular plugin loading Error

### ISSUE THREAD

**Issue by Dragonaere** [BG-Software-LLC/WildStacker#759]
### Minecraft's Version

Paper 1.19.3

### Plugin's Version

2022.6 Dev build 416

### Describe the bug

Circular plugin loading. Wild Stackers loads Citizens which loads Superior Skyblock which loads Wild stackers

### To Reproduce

Have Wild stackers, citizens and superior skyblock and start the server.

### Additional Information

![image](https://user-images.githubusercontent.com/43673678/220806632-97d12951-ffdc-425d-8dc7-ede212dfd517.png)

**Comment by OmerBenGera** [comment]
For now, add `-Dpaper.useLegacyPluginLoading=true` to your server arguments.
I will fix it in the future - this requires the superiorskyblock hook feature to be separated into another 3rd-party plugin/module.

**Comment by Dragonaere** [comment]
Sounds good, thanks

**Comment by OmerBenGera** [comment]
```
Starting with Paper build 425, the server no longer stops or logs any errors on cyclic dependencies of Spigot plugins. Sorry for the small chaos this caused to some of you.
```
From PaperMC's discord.
