### ISSUE TITLE
Breaking a spawner block after server startup causes a massive lag

### ISSUE THREAD

**Issue by Lecer69** [BG-Software-LLC/WildStacker#760]
### Minecraft's Version

git-Purpur-1912 (MC: 1.19.3), from https://purpurmc.org

### Plugin's Version

#416 10/02/2023 15:50:55
on PlugMan info: 2022.6-b416

### Describe the bug

Just break a spawner block after server startup, the server freezes for 10~20 seconds.
It's just for first time after startup, I haven't tested it with other players. (I haven't made my server public yet)

### To Reproduce

Fix the performance issue

### Additional Information

Config: https://pastebin.com/chetd3d8
And Spark profiler: upload it on https://spark.lucko.me
[profile-2023-02-23_10.03.41.zip](https://github.com/BG-Software-LLC/WildStacker/files/10815409/profile-2023-02-23_10.03.41.zip)

**Comment by OmerBenGera** [comment]
Take a spark sampler using `/spark sampler` (to stop the sampler, run `/spark sampler --stop`) and send me a link to it here.

**Comment by Lecer69** [comment]
[profile-2023-03-06_03.44.37.zip](https://github.com/BG-Software-LLC/WildStacker/files/10896032/profile-2023-03-06_03.44.37.zip)
Spark Sampler:

**Comment by OmerBenGera** [comment]
> [profile-2023-03-06_03.44.37.zip](https://github.com/BG-Software-LLC/WildStacker/files/10896032/profile-2023-03-06_03.44.37.zip) Spark Sampler:

Why isnt it an online one?
I prefer it to be online and you just send me a link instead of requiring me to download an untrusted file.

**Comment by Lecer69** [comment]
Spark can't generate online link because of some connection issues in my region.
It generates a file instead of online link.
Unzip the file then upload it in spark website

**Comment by OmerBenGera** [comment]
The only lag I see is from breaking a stacked block, which I pushed an update that might fix it.

**Comment by Lecer69** [comment]
I don't know but somehow this issue is fixed without touching anything.
