### ISSUE TITLE
Weird bug when killing mobs.

### ISSUE THREAD

**Issue by Kanataaa** [BG-Software-LLC/WildStacker#761]
### Minecraft's Version

Running 1.18.2 spigot on my server.

### Plugin's Version

WildStacker-2022.6

### Describe the bug

I don't really know how to describe the bug other then that every time an mob is killed, there's a large error message with something related to modifiers "protected"
![f31043297d35cd0b94fce77bf31b00c6](https://user-images.githubusercontent.com/78446260/221344317-645f9cea-c999-4850-bf9b-b518404e2b69.png)

### To Reproduce

Kill a mob.

### Additional Information

[config.zip](https://github.com/BG-Software-LLC/WildStacker/files/10830497/config.zip)

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it works.

**Comment by Kanataaa** [comment]
Updated to latest, no issues now. Tysm!

**Comment by OmerBenGera** [comment]
> Updated to latest, no issues now. Tysm!

Glad it worked!
