### ISSUE TITLE
WildStacker killing all entites 

### ISSUE THREAD

**Issue by jefflima1** [BG-Software-LLC/WildStacker#762]
### Minecraft's Version

PaperMC latest version 1.19.3

### Plugin's Version

WildStacker-2022.6-b408

### Describe the bug

I started the plugin, without any changes to the config file, and unfortunately it killed all mobs already on the server, how can I solve this? I have a backup so I managed to recover the players' tamed animals, is it possible to prevent this from happening?

### To Reproduce

I just started the server, without any changes made to the config.

**Comment by OmerBenGera** [comment]
Check out the kill task in the config file, make sure it is disabled.
If it is, then it wasn't WildStacker that killed your entities

**Comment by jefflima1** [comment]
Thanks for the help, I disabled it in the config, a question, I use slimefun but when I use the spawner provider like WildStacker, once I break it with the slimefun pickaxe, the spawner does not come broken, it has some specific configuration so that it can be used together with slimefun?

**Comment by OmerBenGera** [comment]
> Thanks for the help, I disabled it in the config, a question, I use slimefun but when I use the spawner provider like WildStacker, once I break it with the slimefun pickaxe, the spawner does not come broken, it has some specific configuration so that it can be used together with slimefun?

They do not work together unfortunately.
A PR to support Slimefun is more than welcomed :)

Closing this issue
