### ISSUE TITLE
Missing Mobs not showing inside mob spawners

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildStacker#763]
### Minecraft's Version

1.16.5 and Paper-794 1.16.5

### Plugin's Version

WildStacker-2022.6-b418.jar

### Describe the bug

When placing down the following spawners it's not showing the models inside spawners for certain mobs which are Enderman, Zombified Piglin and Iron Golem are the only ones that I've discovered so far. The only temporary fix i know of is to use a resource pack and edit the mob spawner texture and it will show the missing entity for some reason.

### To Reproduce

Place down either Enderman, Zombified Piglin or Iron Golem it will show just a mob spawner block

### Additional Information

https://i.gyazo.com/d51767367966f329bc542561b0b7be4d.png < Zombified Piglin
https://i.gyazo.com/3fd81a8671dbccfcb679e036c3c89624.png < Enderman
https://i.gyazo.com/1d9f3b6085da703abc437db7ab1989a5.png < Iron Golem

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed

**Comment by DJDan21** [comment]
alright will do

**Comment by DJDan21** [comment]
Just loaded a server with 1.16.5 with only wildstacker installed and it still doesn't work as shown here https://i.gyazo.com/a64250428522beb2ad8c8ddb182485a1.png

**Comment by OmerBenGera** [comment]
> Just loaded a server with 1.16.5 with only wildstacker installed and it still doesn't work as shown here https://i.gyazo.com/a64250428522beb2ad8c8ddb182485a1.png

Which plugins do you have installed?
Also, try newer game versions.

**Comment by DJDan21** [comment]
It still works in 1.8.8 but for some reason it's not 1.16.5, i will say it never used to be an issue but idk what has caused it

**Comment by OmerBenGera** [comment]
Works fine on my 1.16.5 server:
https://gyazo.com/b57c84e87b4c5e2b60d4d9f2509bf281

Try it yourself on a server with only WildStacker installed.

**Comment by DJDan21** [comment]
@OmerBenGera I've just updated my wild stacker to WildStacker-2022.6-b423 and I don't know if it's a client-side issue on my end or a server issue, on the test server is using and its using java 11. I would like to resolve my issue so it looks the same as your 1.16.5 server, do you have suggestions in how i can resolve it?
![image](https://user-images.githubusercontent.com/19984107/226147213-c45cce2b-b38c-421d-8a25-2da2ace5aa8a.png)

**Comment by OmerBenGera** [comment]
> @OmerBenGera I've just updated my wild stacker to WildStacker-2022.6-b423 and I don't know if it's a client-side issue on my end or a server issue, on the test server is using and its using java 11 with only wild stacker installed. I would like to resolve my issue so it looks the same as your 1.16.5 server, do you have suggestions on how I can resolve it? ![image](https://user-images.githubusercontent.com/19984107/226147213-c45cce2b-b38c-421d-8a25-2da2ace5aa8a.png)

Use another version that its not 1.16.5

**Comment by DJDan21** [comment]
Updated my server now 1.19.3 and its fixed the issue ty for trying to help
