### ISSUE TITLE
Who's the Pillager Now? Advancement not working

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#765]
### Minecraft's Version

1.18.2

### Plugin's Version

WildStacker-2022.6-b418

### Describe the bug

With WildStacker installed, Who's the Pillager now? advancement is not working. Without WildStacker it works perfectly.

### To Reproduce

-

**Comment by Superalex0102** [comment]
or if I disable 
```
entities:
  # Should entities get stacked on the server?
  enabled: true
```

**Comment by Superalex0102** [comment]
I tested furthermore
if I disable this
```
  # Should entities can be killed fast by players (No damage-cooldown)?
  fast-kill: false
```
it works fine.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
