### ISSUE TITLE
Zombified piglins not stacked

### ISSUE THREAD

**Issue by Ammutadori075** [BG-Software-LLC/WildStacker#766]
### Minecraft's Version

1.18.2

### Plugin's Version

*

### Describe the bug

Hi, I have a problem with wildstacker, I can't figure out why zombified piglins aren't stacked. With /ws simulate it tells me that they can be stacked and on the configuration file they are whitelisted:
  - ZOMBIFIED_PIGLIN . I also tried putting them as - ZOMBIFIED_PIGLIN: [] but the problem persists.

### To Reproduce

Whitelist zombified piglins

**Comment by OmerBenGera** [comment]
Please upload your entire config to pastebin and send a link to it here

**Comment by Ammutadori075** [comment]
Hi, here the full config
https://pastebin.com/FHtZ5FVx

**Comment by OmerBenGera** [comment]
You cannot have `blacklist` and `whitelist` at the same time, you must choose only one of them.
Anyways, using your config file Zombified Piglins stack as they should.

If you use `/ws simulate` and click on the two Zombified Piglins that don't stack for you, what does it say?

**Comment by Ammutadori075** [comment]
If i use simulate tool it say Result: SUCCESS. They can stack together.
If I spawn it from egg or spawner, they stack regularly. The problem is only when they spawn naturally

**Comment by OmerBenGera** [comment]
> If i use simulate tool it say Result: SUCCESS. They can stack together. If I spawn it from egg or spawner, they stack regularly. The problem is only when they spawn naturally

This means that the mobs spawned too far from each other, and nothing caused them to try and re-stack.
You can enable the stack-interval to force entities to get stacked again after they initially spawned.

**Comment by Ammutadori075** [comment]
Ohhh.... finally :) 
Thanks a lot for your help now they are stacked too.
