### ISSUE TITLE
Stacked Blazes sometimes drop 0 or 1 blaze rods when killed with looting

### ISSUE THREAD

**Issue by reecehunter** [BG-Software-LLC/WildStacker#767]
### Minecraft's Version

Paper 1.19.3

### Plugin's Version

2022.6-b414

### Describe the bug

There seems to be a bug when calculating stacked blaze drops when killing them using a sword with fortune. Large stacks of blazes sometimes drop 0 or 1 blaze rods on death

### To Reproduce

1. Place a large stack of blaze spawners (10000 for testing purposes)
2. Kill the blazes with a looting 3 sword
3. There is a chance they will drop 0 or 1 blaze rods

Note: It happens fairly often. If you want to streamline the results, I'd recommend setting the entity stack limit to 10,000 and then placing a stack of 100,000 blaze spawners.

**Comment by OmerBenGera** [comment]
Do you have instant kill enabled (So the entire stack dies at once)?
Also, please upload your config file to pastebin and send a link to it here

**Comment by reecehunter** [comment]
Yes, forgot to mention that. Here's my config: https://pastebin.com/tjwFyS1Z

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
Does it happen only for blazes?

**Comment by reecehunter** [comment]
Yes only for blazes. I will see if I can produce steps to better replicate the bug

**Comment by OmerBenGera** [comment]
> Yes only for blazes. I will see if I can produce steps to better replicate the bug

Weird, as the same algorithm is used for all mobs, which makes me believe it might be another plugin somehow conflicts with WildStacker.
Try it on a server with only WildStacker installed, let me know if the issue still occurs.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
