### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by ghost** [BG-Software-LLC/WildStacker#770]
### Minecraft's Version

Server Version: 1.8.8 
https://github.com/PaperMC/paper/commit/2ce7ea620a6d9590a9f93b47ac45e240dac7988a
https://papermc.io/downloads/all  -  [2ce7ea6]

Client Version: 1.8.9

### Plugin's Version

2022.6 (?)

### Describe the bug

Breaking a chest duplicates items within them

### To Reproduce

Add the plugin to a 1.8.8 Minecraft server (I also have Vault, ProtocolLib and PlaceholderAPI)
Place an item into a chest and break the chest, works with or without OP 

### Additional Information

I have created a fresh server to test if the bug is consistent, and to my knowledge it is. I have the default configs and everything.
 I'll try to do some further testing to see if I can help spot what's causing the bug.

**Comment by s3babyy** [comment]
https://imgur.com/a/EmypGZj

I've recorded the duplication glitch and can be found on the link above

**Comment by OmerBenGera** [comment]
Update to latest dev build, the issue should be fixed already.

**Comment by Superalex0102** [comment]
Yes, I reported this issue I remember, this is fixed

**Comment by OmerBenGera** [comment]
> Yes, I reported this issue I remember, this is fixed

Yeah I remember it :)
I am making sure it is fixed for @s3babyy as well.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue continues let me know
