### ISSUE TITLE
WildStackers & Boss incompatible maybe?

### ISSUE THREAD

**Issue by Ancienty** [BG-Software-LLC/WildStacker#771]
### Minecraft's Version

1.8.9 Paper

### Plugin's Version

Latest stable version

### Describe the bug

I'm using WildStacker with a boss plugin called "Boss", and when I spawn bosses using this plugin and then hit the boss even for once, it just instantly dies, I thought this could be due to "instant_kill" option in WildStacker or idk "fast-kill" option but disabling them did nothing, I then tried disabling/completely uninstalling WildStacker and the problem just got fixed, hence the reason I'm very sure this is caused by WildStacker.

### To Reproduce

Spawn a boss using the "Boss" premium plugin.
Just hit the boss, doesn't matter what you have in your hand.
The boss dies after a single hit, even if you hit it with your bare hand.

**Comment by OmerBenGera** [comment]
The issue turned to affect every entity on the world, regardless of whether it's a Boss or not.
Check out latest dev build, let me know if it works now.

**Comment by Ancienty** [comment]
I just had the opportunity to test the potential fix, and it's working. Thank you!
