### ISSUE TITLE
WildStacker error with NoCheatPlus

### ISSUE THREAD

**Issue by zNAFTAz** [BG-Software-LLC/WildStacker#772]
### Minecraft's Version

kSpigot 1.12.2

### Plugin's Version

WildStacker 2023.1

### Describe the bug

Can't deal damage with mobs and get kicked by NoCheatPlus when installing latest WildStacker but old version of WildStacker no problem

### To Reproduce

Can't deal damage with mobs and get kicked by NoCheatPlus when installing latest WildStacker but old version of WildStacker no problem

### Additional Information

All are default (config, etc)

**Comment by Ancienty** [comment]
Yeah I have this problem as well

**Comment by zNAFTAz** [comment]
@OmerBenGera Please fix :v

**Comment by OmerBenGera** [comment]
> @OmerBenGera Please fix :v

Why are you tagging me?
I saw your report, patient.

**Comment by OmerBenGera** [comment]
The issue seems to be because of NO_SWING is being detected on entities.
Disable it or try to adjust its configuration timings so it works with WildStacker.

I can't really do anything on my side, therefore I am closing this.
