### ISSUE TITLE
Buged on purpur

### ISSUE THREAD

**Issue by DrCost** [BG-Software-LLC/WildStacker#773]
### Minecraft's Version

 This server is running Tuinity version git-Tuinity-"f87cb79" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[11:06:10 INFO]: Checking version, please wait...
[11:06:10 INFO]: Previous version: git-Purpur-1171 (MC: 1.16.5)
[11:06:10 INFO]: You are 132 version(s) behind

### Plugin's Version

2023.1 latest stable

### Describe the bug

Hi, 

I have problem with 
  superiorskyblock-hook: true // after enabled mobs didnt stacks
  multiply-drops: true // didnt stack mob drops
  
  Tested on iron golem mob spawner

### To Reproduce

Didnt stack mobs, and didnt multiply mobs drops

8x IronGolem die in lava but i getting 2-5 iron_ingot

**Comment by OmerBenGera** [comment]
I don't understand the issue at all.
Give a more detailed explanation of the issue.

Btw, if you enable `superiorskyblock-hook`, you must add an island-setting to the menu so players can toggle entities stacking on their island (which is disabled by default unless you change the config file).

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
