### ISSUE TITLE
MythicMobs and WildStacker

### ISSUE THREAD

**Issue by Ailenlalien** [BG-Software-LLC/WildStacker#775]
### Minecraft's Version

__**Version :** 1.18.2__

### Plugin's Version

2023.1 25/03/2023 15:58:37

### Describe the bug

I would like to remove the one shot only for my Mythicmobs mobs but I can't do it

### To Reproduce

Kill a Mythicmobs mob with oneshot

**Comment by Ancienty** [comment]
Hello,

https://github.com/BG-Software-LLC/WildStacker/issues/771

As stated on the issue above, the developer said this problem was causing all mobs, not only bosses, to get one shot and that he fixed it in the latest developer version, try using that one maybe?

**Comment by OmerBenGera** [comment]
> Hello,
> 
> #771
> 
> As stated on the issue above, the developer said this problem was causing all mobs, not only bosses, to get one shot and that he fixed it in the latest developer version, try using that one maybe?

It only affected 1.8

**Comment by Ailenlalien** [comment]
So I can't remove the oneshot just for my mythicmobs mobs?

**Comment by OmerBenGera** [comment]
> So I can't remove the oneshot just for my mythicmobs mobs?

You can by whitelisting spawn reasons for the naturally spawned mobs.
Add to the whitelist section of one-shot "NATURAL", "SPAWNER", "SPAWNER_EGG" and you should be fine, as MythicMobs mobs have a custom spawn reason "MYTHIC_MOBS"

**Comment by OmerBenGera** [comment]
Is it still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If the issue continues let me know
