### ISSUE TITLE
Villagers get ejected from a minecart when converted to a zombie villager

### ISSUE THREAD

**Issue by Rendrin1** [BG-Software-LLC/WildStacker#776]
### Minecraft's Version

version 1.19.4, paper #484

### Plugin's Version

WildStacker-2023.1-b427.jar

### Describe the bug

Villagers get ejected from a minecart when converted to a zombie villager. this is shouldn't happen normally 

### To Reproduce

Place villager in minecart. Make zombie attack villager until it turns into a zombie villager. The villager will pop out of minecart. 
If you test without Wildstacker this does not happen and the villager stays in the minecart.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
