### ISSUE TITLE
Barrel Stacking Dupe

### ISSUE THREAD

**Issue by whosLevity** [BG-Software-LLC/WildStacker#778]
### Minecraft's Version

Minecraft 1.19.3, Purpur 1.19.3

### Plugin's Version

2023.1

### Describe the bug

Duping/Deleting stacked blocks with barrel stacker. Stacker toggle command is enabled and force cauldron is set to false.

### To Reproduce

I have the stacker toggle command enabled, so that is turned on during the video. To reproduce, just right-click a diamond block onto an existing barrel. It places a "second" barrel. Then when you right-click with an empty hand to retrieve the diamond block it deletes the block and drops a second "barrel" cauldron.

### Additional Information

https://vimeo.com/815244922

**Comment by OmerBenGera** [comment]
This is obviously another plugin interfacing with it.
Disable the other stacking plugin and report back if it still occurs.

**Comment by OmerBenGera** [comment]
Have you found the other plugin?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If the issue continues let me know
