### ISSUE TITLE
Server hard freeze due to (corrupted ?) item entity

### ISSUE THREAD

**Issue by CryLegende** [BG-Software-LLC/WildStacker#779]
### Minecraft's Version

Purpur 1.17.1 (latest 1.17 build)

### Plugin's Version

2023.1 / Dev build #428 and previous builds

### Describe the bug

Sometimes an item on the ground freezes the server. It will not move until a manual stop. 

### To Reproduce

I have the impression that it is caused by an item stack having a lot of items, when the player loads the chunk, the plugin tries to stack tens of thousands of stones for example. This scenario was not a problem like 1 week ago

### Additional Information

Here is the freeze report: [https://pastebin.com/raw/prPBZY54](url)

**Comment by OmerBenGera** [comment]
It doesn't matter how many items are actually in the Item entity, the plugin will handle it the same.
Maybe the chunk is filled with tons of different Item entities?

I need more information on that.

**Comment by CryLegende** [comment]
I have no way to check since the server crashes every time I try to approach it.
However, I don't think this chunk has more than 10 different items on the ground.

At one point I was able see what was happening in one of the buggy chunks, I saw several thousand of stones on the ground, not grouped.. maybe the plugin tries to group them all at once ? (My server is powerful enough to handle much more than few thousand of stones on the ground)

Also, i'm using FAWE so WildStacker disable its own tick limiter on server start.

**Comment by OmerBenGera** [comment]
> I have no way to correctly check the number of items on the ground since the server crashes every time I try to approach it. However, I don't think this chunk has more than 10 different items on the ground.
> 
> At one point I was able see what was happening in one of the buggy chunks, I saw several thousand of stones on the ground, not grouped.. maybe the plugin tries to group them all at once ? (My server is powerful enough to handle much more than few thousand of stones on the ground)
> 
> Also, i'm using FAWE so WildStacker disable its own tick limiter on server start.

Try disabling WildStacker's item stacking, check if you can then access that chunk.

**Comment by CryLegende** [comment]
I was able to access the chunk with WildStacker's item stacking set to false, I didn't see anything strange, so I cleared the dropped items and enabled WildStacker's item stacking back, the server didn't crash anymore by that chunk.

For now, I will do this manipulation each time WildStacker is causing this problem until I found the reason why.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by CryLegende** [comment]
Hey ^^
I don't know, I didn't had the problem since I disabled the item stacking from WildStacker.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue pops up again let me know
