### ISSUE TITLE
Fast kill/Instant kill doesn't work

### ISSUE THREAD

**Issue by theexplosivesguy** [BG-Software-LLC/WildStacker#780]
### Minecraft's Version

1.19.4

### Plugin's Version

Current

### Describe the bug

Doesnt work even though the value is set to true

### To Reproduce

Try and kill a mob from a spawner and none of them instant die

**Comment by OmerBenGera** [comment]
`fast-kill` and `instant-kill` are two different things.
`fast-kill` is used to kill entities fast (so there's no cooldown between hits). `instant-kill` on the other hand is used to kill the entire stack all at once.
Upload your config file to pastebin and send a link to it here.

**Comment by TardyC** [comment]
Im on here it not work with custom damage as player

I want to kill the entire stack and im a player

And i have type 

![image](https://user-images.githubusercontent.com/82113954/230907055-31d9b8c1-7b8d-4808-b4e7-7b264f567dcf.png)

**Comment by TardyC** [comment]
Okay
i will try

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
