### ISSUE TITLE
mob drops from upgraded spawner go crazy

### ISSUE THREAD

**Issue by notiwsy** [BG-Software-LLC/WildStacker#781]
### Minecraft's Version

1.18.2

### Plugin's Version

2023.1

### Describe the bug

the mobs from upgraded spawners drop non stackable items for example: blaze drops blaze rod but its nonstackable exapt its from same mob. and it has lore: affected: with codes idk. i have a clip for details. also I think its a bug from wild chests or wildspawner idk. the video file is too big so I posted it on streamable: https://streamable.com/hfy7w4 this is for wildchest: https://streamable.com/w8d0bv

### To Reproduce

killing upgraded mobs and chunk collector collect the drops also the drops cant be stacked with vanilla items

### Additional Information

https://pastebin.com/dpwahpP0

**Comment by OmerBenGera** [comment]
I dont think its relates to neither WildStacker or WildChests.

Try it on a server with only WildStacker, check if it occurs. If it does not happen, try adding WildChests and test it again.
