### ISSUE TITLE
Invisible Mobs. Bug with WildStacker

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/WildStacker#782]
### Minecraft's Version

Tested 1.19.4 purpur and 1.19.3 (Vanilla server and main server) 

### Plugin's Version

#428 01/04/2023 18:18:15

### Describe the bug

Some hostile mobs are invisible and it appears that they do not spawn. However, it seems that they do spawn but are invisible!

### To Reproduce

Place some spawners and you will see that some mobs, such as zombies, do not spawn, but they are invisible. However, if you manually place the spawn egg for a zombie, the mob count increases.

This also happens when you set it to night.

As you can see in the video, it works without WildStacker.

### Additional Information

I send you the video https://www.youtube.com/watch?v=F0GW-7z2sPI

See also this video demostration https://www.youtube.com/watch?v=8HcYgVY0yQs

**Comment by Distolfix** [comment]
(Default config)

**Comment by OmerBenGera** [comment]
Test it on a server with only WildStacker installed.
Let me know if it still occurs.

**Comment by Distolfix** [comment]
Ok

**Comment by Distolfix** [comment]
same bug with only wildstacker

**Comment by Distolfix** [comment]
Some hostile mobs have this problem.. for example skeleton

**Comment by OmerBenGera** [comment]
What happens if you click on the spawner?
It should show you the reason for not being able to spawn the mobs.

**Comment by Distolfix** [comment]
![image](https://user-images.githubusercontent.com/73421268/231516971-9283e780-adc7-4b45-a048-16d612625792.png)

**Comment by Distolfix** [comment]
![image](https://user-images.githubusercontent.com/73421268/231517018-f80768d2-c975-4b95-8879-7bf01faa2aa8.png)

**Comment by Distolfix** [comment]
I close the ticket. If the problem comes back I will reopen it
