### ISSUE TITLE
Dupe Glitch (autopickup)

### ISSUE THREAD

**Issue by LuukPlay** [BG-Software-LLC/WildStacker#783]
### Minecraft's Version

Paper 1.19.4
Build #510

### Plugin's Version

⚡️ WildStacker ⚡️ Spawners | Entities | Drops | Blocks ⚡️ 1.19.4 support! 2023.1

### Describe the bug

dupe glitch with any autopickup or drop2inv plugin
example plugins:
https://www.spigotmc.org/resources/autopickup-1-19-support.70157/
https://www.spigotmc.org/resources/%E2%AD%90-drop2inventory-plus-%E2%AD%90.87784/

### To Reproduce

Practical example:
2x dirt // on the ground
I break one more dirt block, it comes into my inventory(autopickup) and also increases the stack to 3x dirt.

When the block is broken it should come to the inventory only, not to pile on the ground and into the inventory. I don't think it's a plugin bug, maybe it's just lack of compatibility with other plugins, maybe it would be good if there was an autopickup functionality or add compatibility with some plugin that offers this function.

**Comment by LuukPlay** [comment]
waiting for support...

**Comment by OmerBenGera** [comment]
I cannot replicate the issue with the first plugin (didn't test the other one)
Are you able to replicate the issue on a server with only WildStacker and AutoPickup installed?

**Comment by LuukPlay** [comment]
yes, really a server only with the two does not occur this bug, it must be some other plugin of mine

**Comment by OmerBenGera** [comment]
If you find the plugin that causes this, let me know :)
