### ISSUE TITLE
1/2 Hitting all Mobs

### ISSUE THREAD

**Issue by Mddwg** [BG-Software-LLC/WildStacker#784]
### Minecraft's Version

Client: 1.8.9
Server: 1.8.8

### Plugin's Version

2023.1-b425

### Describe the bug

No matter what I tried, players can 1 hit every mob. Including Withers and EnderDragons...

### To Reproduce

Just install WildStacker version 2023.1-b425 on a server

### Additional Information

I've tried having only WildStacker installed with default config, but the issue is still persistent..

**Comment by Mddwg** [comment]
I just checked if I have any special potion effects or anything. I do not, it's just, happening...
Also, this can be done with any item in your hand, even an open hand will do the trick..

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.

**Comment by Mddwg** [comment]
Yap, latest fixed it. Thank you <3
