### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by TheDumbledodo** [BG-Software-LLC/WildStacker#785]
### Minecraft's Version

1.19.4 Purpur 1957

### Plugin's Version

WildStacker-2023.1-b1

### Describe the bug

Server crashes, all the plugins get unloaded and it freezes.
https://pastebin.pl/view/0a08f7d0

### To Reproduce

I don't know, it's happening in my server with players online.

**Comment by OmerBenGera** [comment]
Please upload the entire logs to pastebin and send a link to it here

**Comment by TheDumbledodo** [comment]
Here you go https://pastebin.pl/view/d865782a

**Comment by Lecer69** [comment]
I think the issue is WildStacker doesn't support 1.19.4 rn.

**Comment by TheDumbledodo** [comment]
<img width="1253" alt="javaw_WFyhGDcY0z" src="https://user-images.githubusercontent.com/73080312/231976104-f96165f5-4d9a-47c8-b1ae-2cb05ce6b686.png">
This is what's crashing the server but I don't know how it got unstacked
maybe the stack size was to high or something?

**Comment by OmerBenGera** [comment]
Your pigs exceed the max possible stack size.
Not sure why the rest of the pigs didnt stack tho

Upload your config file to pastebin and send a link to it here

**Comment by TheDumbledodo** [comment]
wait I'm sending it

**Comment by TheDumbledodo** [comment]
https://pastebin.pl/view/04fc2e94

**Comment by OmerBenGera** [comment]
This link does not work.
Use another website, such as pastebin.com or hastebin.com

**Comment by TheDumbledodo** [comment]
sorry for the late response but here's the configuration
https://pastebin.com/Pam6WsPD

**Comment by OmerBenGera** [comment]
Disable the stack interval, or at least increase it to a reasonable value (minimum of 200)
Also, why you have such large spawners? It makes no sense.

**Comment by TheDumbledodo** [comment]
Well it is OP Survival so I can't do anything about that, is it possible for you to rebase it to BigInteger or something?

**Comment by OmerBenGera** [comment]
> Well it is OP Survival so I can't do anything about that, is it possible for you to rebase it to BigInteger or something?

No.
Entities have a max limit of 2.14 billion and that's more than enough.
If you each that limit, new mob will spawn and there's no issue with that.

**Comment by Lecer69** [comment]
We don't know when it happens and still we have this problem and it happened with vindicators today

**Comment by Lecer69** [comment]
randomly unstacks the stacked mob for no reason

**Comment by OmerBenGera** [comment]
As I already said, mobs don't get unstacked out of nowhere; they weren't stacked in first place.
Find out how to replicate the issue so it can be fixed.

**Comment by Lecer69** [comment]
Where can I upload video higher than 10 MB? github doesn't let me to do that.

**Comment by OmerBenGera** [comment]
> Where can I upload video higher than 10 MB? github doesn't let me to do that.

You should use a third-party website (such as Youtube)

**Comment by Lecer69** [comment]
> > Where can I upload video higher than 10 MB? github doesn't let me to do that.
> 
> You should use a third-party website (such as Youtube)

https://youtu.be/1twiJYyVPVs (I recorded 1080p I don't know why the quaility is low)

**Comment by Lecer69** [comment]
[WildStackerConfig.zip](https://github.com/BG-Software-LLC/WildStacker/files/11522362/WildStackerConfig.zip)
the config

**Comment by TheDumbledodo** [comment]
@OmerBenGera please check this video thanks :))

**Comment by OmerBenGera** [comment]
Do not tag me please.

Upload your config to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
Do not tag me.
Do you have any plugins on the server other than WildStacker?

**Comment by TheDumbledodo** [comment]
sorry, there are no other plugins other than WildStacker on that server.

**Comment by OmerBenGera** [comment]
It doesn't make a lot of sense, for no reason the mobs spawn and get stacked after a lot of time.
This is not the behavior of WildStacker.

**Comment by Lecer69** [comment]
> It doesn't make a lot of sense, for no reason the mobs spawn and get stacked after a lot of time. This is not the behavior of WildStacker. Does this behavior still occurs if you disable the `stack-interval` (Set it to 0)?

I already sent you the config, the `stack-inverval` is 0

**Comment by OmerBenGera** [comment]
Does it happen if you use Paper instead of Purpur?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by TheDumbledodo** [comment]
It's probably fixed after the update.
