### ISSUE TITLE
killed_by_player drops don't work with instant_kill 

### ISSUE THREAD

**Issue by moveEAX** [BG-Software-LLC/WildStacker#786]
### Minecraft's Version

1.19.3

### Plugin's Version

2023.1

### Describe the bug

There a specifiy drops to entities (e.g. blaze rods from BLAZE) that only drop when minecraft registered the entity was killed by a player or it dies up to 3 seconds after a player hit.
If you kill stacked entities with instant_kill even if they die from it in less than 3 seconds the player-kill-only drops wont get dropped.

### To Reproduce

- get a stacked entity (e.g. x10 blaze)
- hit it about 1-3 seconds before it will die
- kill it with instant_kill damage causes
-> no player-only drop

### Additional Information

Config: 
https://pastebin.com/Ad7c6ESa

**Comment by OmerBenGera** [comment]
Upload the loot table you configured to pastebin and send a link to it here.

**Comment by moveEAX** [comment]
https://pastebin.com/sF369Rsc

**Comment by OmerBenGera** [comment]
Your loot-table does not contain any restriction to how the blaze is killed for the blaze rods to be dropped.

**Comment by OmerBenGera** [comment]
It this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
