### ISSUE TITLE
Instant_kills won't get counted in the statistics (or quest plugins)

### ISSUE THREAD

**Issue by moveEAX** [BG-Software-LLC/WildStacker#787]
### Minecraft's Version

1.19.3

### Plugin's Version

2023.1

### Describe the bug

It is similar to the player-kill issue.
If the entity dies within 3 seconds after a player hit from instant kill damage causes it won't be registered in the statistics.
It is only working when the instant_kill damage cause is ENTITY_ATTACK, but then the player is the last hit anyway.

### To Reproduce

- get a stacked entity (e.g. x10 PIG)
- hit it 1-3s seconds before it will die
- kill it with instant kill damage cause (e.g- HOT_FLOOR)
-> won't get counted

### Additional Information

https://pastebin.com/Ad7c6ESa

**Comment by OmerBenGera** [comment]
Test it without WildStacker, as it seems to still occur for me.
I am pretty sure you must be the cause of the death to get statistics registered to you. Which means, you must deal the last damage that kills the entity.

**Comment by OmerBenGera** [comment]
In this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
