### ISSUE TITLE
Endermite die automatically

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#789]
### Minecraft's Version

1.19.3 paper

### Plugin's Version

wildstacker b423 (default config)

### Describe the bug

When I use an endermite spawner, endermite auto die after 1-2mn

### To Reproduce
- Just placed a spawner
- endermite spawn
- Wait 2mn, the stack die
https://youtu.be/SPoDkHj1xYQ

### Additional Information

I even tried with another spawner plugin, and it's the same.

**Comment by OmerBenGera** [comment]
In minecraft vanilla, endermites seems to have "lifetime" and after 2400 ticks they just vanish.
This is also documented in the minecraft wiki.

Not related to WildStacker, closing this :)
