### ISSUE TITLE
Wildstacker incompatible with most 'Mob Collector' plugins

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#791]
### Minecraft's Version

1.8.8 Paperfork WineSpigot

### Plugin's Version

Latest dev build(2023.1 b-1), also happens on all versions as well.

### Describe the bug

Well, it collects inaccurate amount of mobs with mob collectors, even with x1 Spawner only

I tried all these collector plugins:
AbyssCollectors(Paid) - Private
CustomsCollectors(Paid) - https://www.spigotmc.org/resources/customschunkcollectors-1-8-1-18.91542/
RedCollectors(Paid) - https://www.spigotmc.org/resources/redcollectors-undergoing-rewrite.73759/ 
(On redcollectors, u can see it states that there is a dupe bug with wildstacker on collection)
![image](https://user-images.githubusercontent.com/89855789/235503680-f68f139c-a1b6-4a52-a527-e2a614226fdf.png)

and they're all having the same issue with wildstacker, it collects mobs way more and way faster than it should be, thus making collection way too broken.

### To Reproduce

Contact me for a collector plugin, then place a collector + 1 spawner, and see how many mobs the collector can collect with x1 spawner only.. and how fast it is.. it doesn't work that way with other spawner plugins, especially silkspawners and vanilla spawners.

### Additional Information

Comparison of Vanilla/Silk spawners vs Wildstacker spawners on collector plugin:

Vanilla/SilkSpawners:
https://streamable.com/ixg2qh
See how accurate the numbers are, with just 1 spawner, it just collects x1-4

Wildstacker spawners:
https://streamable.com/thcdpx
See how inaccurate the numbers are, it collects hundreds with just 1 spawner

This has been around for a long time, but I only reported it now. Wildstacker is not compatible for Faction servers due to this bug, most servers use mob collector plugins, and this bug, it breaks economy as the spawners give overwhelmingly inaccurate numbers and inaccurate speed, way more than it's supposed to be.

**Comment by OmerBenGera** [comment]
Your collector plugins should add support for WildStacker.
I can do nothing regarding this.
