### ISSUE TITLE
WildStacker lag 

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/WildStacker#793]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 8 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

![image](https://user-images.githubusercontent.com/73421268/236485775-3ba6a93b-8c17-4196-8a5a-c8a4761b9719.png)

### Describe the bug

The server is lagging with WildStacker https://spark.lucko.me/C0DS0mtqvl

Here i send you my tps and if you look i have a problem for spawners there is a lag with position... and for spawners but i set spawner merged 

### To Reproduce

No

### Additional Information

https://pastebin.com/4scR9rYh

**Comment by OmerBenGera** [comment]
I can't open the spark profiler, as it no longer exists.
However, I see that you have stack-interval of entities set to 2. This is insanely too low. You should put it at 200 minimum.
Let me know if it helps.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
