### ISSUE TITLE
Bug with spawner

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/WildStacker#794]
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

2023.1

### Describe the bug

I use a plugin called SpawnerMeta. The developer uses your API. Taking into account that a single spawner can spawn 16 mobs, when the spawner spawns the stack of 16 mobs, when it tries to spawn a second time only 1 mob will be added to the stack. I only have this problem on the Paper side, I tested it on Spigot and it works.
Do you have a solution?

### To Reproduce

Put a spawner (with the SpawnerMeta plugin) that can generate for example 16 mobs.
First generation of the spawner there are 16 mobs.
Second generation of the spawner there are 17 mobs.
So only 1 mob has been generated and added to the stack of 16.

**Comment by Xitryne** [comment]
I use the last build of Paper for 1.17.1 and it also does it for 1.19.4 of Paper

**Comment by OmerBenGera** [comment]
I dont know what SpawnerMeta does that breaks the plugin.
Contact them for support.
