### ISSUE TITLE
Unilimited Spawner Spawn (Then Crash)

### ISSUE THREAD

**Issue by tester2024** [BG-Software-LLC/WildStacker#795]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.1-b1

### Describe the bug

check video

### To Reproduce

1. Wait for spawn mobs (24x)
2. Move mobs into one block

**Comment by tester2024** [comment]
https://streamable.com/lnqzsf

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue
Please upload your config file of WildStacker to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by tester2024** [comment]
https://github.com/BG-Software-LLC/WildStacker/issues/785

**Comment by tester2024** [comment]
its my server config

**Comment by OmerBenGera** [comment]
Does it still occur?
If so, please upload your config again to pastebin and send a link to it here

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
