### ISSUE TITLE
Color on mob nametag disappears

### ISSUE THREAD

**Issue by J4im3x0** [BG-Software-LLC/WildStacker#797]
### Minecraft's Version

Pufferfish version git-Pufferfish-68 (MC: 1.19.4)

### Plugin's Version

WildStacker version 2023.1

### Describe the bug

If I kill a stacked mob, the next mob that appears does not have the color in the nametag

### To Reproduce

Kill a stacked mob

### Additional Information

![image](https://user-images.githubusercontent.com/36940599/236716504-2e818f0f-2d33-40c9-9388-7ed0c1fb89b1.png)

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
Try replicating it yourself on a server with only WildStacker installed.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
