### ISSUE TITLE
Spawners not working on 1.19.4

### ISSUE THREAD

**Issue by J4im3x0** [BG-Software-LLC/WildStacker#798]
### Minecraft's Version

Pufferfish version git-Pufferfish-68 (MC: 1.19.4)

### Plugin's Version

WildStacker version 2023.1

### Describe the bug

For any reason if I use WildStacker on my server the spawns doesn't spawn mobs (if I remove WS from the server the spawners works correctly)
This is caused by spawners-override setting in config.yml, if I use WG behaviour on 1.19.4 does not work mob spawning.

### To Reproduce

The same as described bug

### Additional Information

![image](https://user-images.githubusercontent.com/36940599/236716788-b6079a24-98b1-45f6-8e49-f11b6ee858b4.png)

**Comment by OmerBenGera** [comment]
Does it happen only after you disable the `spawners-override` feature or when it is enabled?

**Comment by TurretedAsh** [comment]
I can also confirm by changing it to False the Spawner will start to work and mobs will spawn. However when enabled it Stops the spawn and gives us reason why its not working. And seems to be no fix on that. So we have to Disable it for mobs to spawn at this stage

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
