### ISSUE TITLE
Nerfed sheep can't recover his wool

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#799]
### Minecraft's Version

1.9.3 paper g388

### Plugin's Version

b1

### Describe the bug

When you nerf sheeps, sheep with wool can eat grass, but sheared sheep can't, but they need to in order to recover their wool

### To Reproduce

- Place two sheep on a grass_block
- shear one
- wait some minutes
The sheared sheep won't eat grass, so it won't recover his wool, but the other sheep (not sheared) ate grass
![image](https://github.com/BG-Software-LLC/WildStacker/assets/31826333/ac6eb026-0510-4140-a7bb-3f49c49d1734)

**Comment by OmerBenGera** [comment]
WS uses Spigot's nerfing system. Therefore, if they dont eat grass, you will have to patch your spigot to allow them to eat grass while being nerfed.

**Comment by WarnDa** [comment]
Opened an issue on spigot, thanks ! :)
