### ISSUE TITLE
Issue with upgradeablehoppers instant suction

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#800]
### Minecraft's Version

paper 1.19.3

### Plugin's Version

b1

### Describe the bug

When breaking a barrels with a lot of blocks in it, once the inventory of the player is full, it drops the excess, but if you got a upgradeablehoppers hopper with suction instant near you, the hopper will suction the item but only 64, and you'll lost your items.

### To Reproduce

- use wildstacker with stacked items
- activate barrels
- stack a barrel with more than 5000 items
- place an upgradeablehoppers hopper with direct-suction
- break the barrel

**Video :** 
https://youtu.be/ZZWk24_wBdU

### Additional Information

I already opened an issue on upgradeablehoppers side, he can fix it himself, the issue isn't on his side
![image](https://github.com/BG-Software-LLC/WildStacker/assets/31826333/7563a594-b333-47f2-8405-f5dff75cc9f9)
So my idea for this was to change how item are dropped if you don't have enough space in your inventory while breaking a barrel. It's using the same system as essentials /give.
Using essentials, if you give too much items to the players, it drops the excess without issue and they are correctly suctionned by upgradeablehoppers.

**Comment by Angeschossen** [comment]
I was kinda able to find a solution. Please keep this open for now. I'm not sure about the consequences of this fix.

**Comment by OmerBenGera** [comment]
How do I get a suction that instantly picks up items?

**Comment by WarnDa** [comment]
> How do I get a suction that instantly picks up 

Need to change in the plugins file the hoppers.yml with « instant-suction » to true
I can give you the file in 1hr on discord once at home.
But dev added a fix that seems working (I’m using the fix since 3 days)

**Comment by OmerBenGera** [comment]
> > How do I get a suction that instantly picks up
> 
> Need to change in the plugins file the hoppers.yml with « instant-suction » to true I can give you the file in 1hr on discord once at home. But dev added a fix that seems working (I’m using the fix since 3 days)

@Angeschossen What was the issue and how did you fix it?

**Comment by WarnDa** [comment]
> I was kinda able to find a solution. Please keep this open for now. I'm not sure about the consequences of this fix.

The issue is here again, a player just reproduced the issue again

**Comment by OmerBenGera** [comment]
WildStacker drops the items as any other plugin would drop them.
The only difference is that WildStacker changes some things with the item before it is actually being added to the world.

**Comment by WarnDa** [comment]
> WildStacker drops the items as any other plugin would drop them. The only difference is that WildStacker changes some things with the item before it is actually being added to the world.

And this make an issue and items disapear when dropping the on floor, but it doesn't happen when it's given object by essentials using /give <player>

Here : 
- a player place a barrel of blocks (with something like 3k blocks)
- he puts an hopper using "direct-suction: true" near the barrel
- he breaks the barrel, and the items that can't be put in the inventory disappear.

Dev "fixed" it on latest update, but it introduces a dupe issue between wildstacker and upgradeablehoppers (if you place two hopper with direct-suction near them, if you drop an item each hopper get it, so it doubles the amount of items).

And before the patch to fix this barrel issue, the dupe bug wasn't present.

**Comment by OmerBenGera** [comment]
> > WildStacker drops the items as any other plugin would drop them. The only difference is that WildStacker changes some things with the item before it is actually being added to the world.
> 
> And this make an issue and items disapear when dropping the on floor, but it doesn't happen when it's given object by essentials using /give
> 
> Here :
> 
> * a player place a barrel of blocks (with something like 3k blocks)
> * he puts an hopper using "direct-suction: true" near the barrel
> * he breaks the barrel, and the items that can't be put in the inventory disappear.
> 
> Dev "fixed" it on latest update, but it introduces a dupe issue between wildstacker and upgradeablehoppers (if you place two hopper with direct-suction near them, if you drop an item each hopper get it, so it doubles the amount of items).
> 
> And before the patch to fix this barrel issue, the dupe bug wasn't present.

Should be reported over UpgradeableHopper, not WildStacker.

**Comment by WarnDa** [comment]
> > > WildStacker drops the items as any other plugin would drop them. The only difference is that WildStacker changes some things with the item before it is actually being added to the world.
> > 
> > 
> > And this make an issue and items disapear when dropping the on floor, but it doesn't happen when it's given object by essentials using /give
> > Here :
> > 
> > * a player place a barrel of blocks (with something like 3k blocks)
> > * he puts an hopper using "direct-suction: true" near the barrel
> > * he breaks the barrel, and the items that can't be put in the inventory disappear.
> > 
> > Dev "fixed" it on latest update, but it introduces a dupe issue between wildstacker and upgradeablehoppers (if you place two hopper with direct-suction near them, if you drop an item each hopper get it, so it doubles the amount of items).
> > And before the patch to fix this barrel issue, the dupe bug wasn't present.
> 
> Should be reported over UpgradeableHopper, not WildStacker.

As he doesn't want to support all stacking plugin, he wants to remove wildstacker support on his plugins.. So that's why I searched another way to fix this, and thought it could be fixed on wildstacker side

**Comment by OmerBenGera** [comment]
> > > > WildStacker drops the items as any other plugin would drop them. The only difference is that WildStacker changes some things with the item before it is actually being added to the world.
> > > 
> > > 
> > > And this make an issue and items disapear when dropping the on floor, but it doesn't happen when it's given object by essentials using /give
> > > Here :
> > > 
> > > * a player place a barrel of blocks (with something like 3k blocks)
> > > * he puts an hopper using "direct-suction: true" near the barrel
> > > * he breaks the barrel, and the items that can't be put in the inventory disappear.
> > > 
> > > Dev "fixed" it on latest update, but it introduces a dupe issue between wildstacker and upgradeablehoppers (if you place two hopper with direct-suction near them, if you drop an item each hopper get it, so it doubles the amount of items).
> > > And before the patch to fix this barrel issue, the dupe bug wasn't present.
> > 
> > 
> > Should be reported over UpgradeableHopper, not WildStacker.
> 
> As he doesn't want to support all stacking plugin, he wants to remove wildstacker support on his plugins.. So that's why I searched another way to fix this, and thought it could be fixed on wildstacker side

If he removes support for stacked items, then it won't work at all and you'll lose items.
There will be nothing I can do regarding this.

**Comment by WarnDa** [comment]
Here you can see the issue : 
https://youtu.be/FRh2Q1b2T28
I'm using an hopper with direct-suction (take item directly before they are dropped on the floor)

- If items are being dropped from the barrel, the hopper only suction 1 stack and other blocks disapear
- If items are being dropped by /give from essentials, hopper take 5 stacks and other items are dropped on the floor
(And when he fixed this bugs on version 4.12.19, it created another dupe issue, as described above)

That's why it looked more from a wildstacker side issue, but we will wait Angeschossen on this.
