### ISSUE TITLE
StackedEntity exceeding max stacked size

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BG-Software-LLC/WildStacker#801]
### Minecraft's Version

14.05 05:37:24 [Server] INFO Current: git-Purpur-1895 (MC: 1.19.3)*
14.05 05:37:24 [Server] INFO Previous: git-Purpur-1632 (MC: 1.18.2)
14.05 05:37:24 [Server] INFO * You are 38 version(s) behind
14.05 05:37:24 [Server] INFO Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

14.05 05:37:42 [Server] INFO WildStacker version 2023.1
14.05 05:37:42 [Server] INFO Stacking drops, entities, blocks and spawners into one object!
14.05 05:37:42 [Server] INFO Website: https://bg-software.com/
14.05 05:37:42 [Server] INFO Author: Ome_R

### Describe the bug

On some circumstances entities are beeing merged, when they shouldnt and therefore exceeding maximum stack limit.

I've found out that the EntityStackEvent is not beeing fired in that cases.

### To Reproduce

The easiest way is to reproduce problem is to create some stacks that are a little bit lower than maximum and:
a) create spawners that will be spawning more creatures
b) start killing them
Eventually this would happen. It may take a while.

Some players said that its also reproducible without spawners (but it doesnt have to be true)

Dont have spawner stacking enabled.

I've recorded a video, when the bug is shown: https://youtu.be/m9zI0RIK-1I

Plugin's config: https://pastebin.com/DtiBVvEf

**Comment by OmerBenGera** [comment]
Please upload your config file to pastebin and send a link to it here

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
