### ISSUE TITLE
WildStacker merge crackshot's grenades projectiles

### ISSUE THREAD

**Issue by Fredh1000** [BG-Software-LLC/WildStacker#802]
### Minecraft's Version

WindSpigot 1.8.8, also work on Paper 1.8.8

### Plugin's Version

latest stable build (2023.1)

### Describe the bug

WildStacker's items merger also merge crackshot's grenades projectiles.

### To Reproduce

Video: https://www.youtube.com/watch?v=oSaQoCCXnXA

**Comment by OmerBenGera** [comment]
You can configure it in the config file to only stack items that have a maximum delay pickup. Find the value that works with crackshot.
If it doesnt help, ask them to cancel the pickup item event so WildStacker does not interface with it.
