### ISSUE TITLE
Blacklisted Entities are stacking

### ISSUE THREAD

**Issue by Dweezy750** [BG-Software-LLC/WildStacker#803]
### Minecraft's Version

purpurmc, 1.19.4

### Plugin's Version

Lastest Dev: WildStacker-2023.1-b1.jar

### Describe the bug

In my case, 'Villagers' gets stacked but they should NOT.

### To Reproduce

Rename a villager with a name_tag (see the blacklisted names)
In my case wait for a spawner spawning villager. at 10 villager's they get stacked, in meantime i rename them with name_tag.
If 10 villagers are spawend, they get stacked, even with different profession, different names.

Blacklisted Names & stack-checks are ignored in this case.

### Additional Information

FORMATS are not correct here, because of copy/paste

config.yml
entities:
  enabled: true

  stack-checks:
      VILLAGER_PROFESSION: true

  name-blacklist:
  - trader1
  - trader2
  - trader3
  - trader4
  - trader5
  - trader6
  - trader7
  - trader8
  - trader9
  - trader10
  - villager1
  - villager2
  - villager3
  - villager4
  - villager5
  - villager6
  - villager7
  - villager8
  - villager9
  - villager10
  
    minimum-required:
    VILLAGER: 10

  limits:
    all: 4096

**Comment by OmerBenGera** [comment]
Please upload your config file to pastebin and send a link to it here

**Comment by J4im3x0** [comment]
I am having the same issue with zombie villagers,
https://hastebin.com/share/egukikaqoc.yaml

**Comment by OmerBenGera** [comment]
If you spawn two zombie villagers with an egg (or a summon command), do they still stack together?
If not, run `/ws simulate` and click the two of them, what do you get in chat?

**Comment by Dweezy750** [comment]
If you spawn 2 zombie villagers, /ws simulate says: VILLAGER_PROFESSION. They cannot stack together.

**Comment by OmerBenGera** [comment]
> If you spawn 2 zombie villagers, /ws simulate says: VILLAGER_PROFESSION. They cannot stack together.

Get two zombie villagers that have the same profession (or for the testing, disable this stack check in the config file), then check if it says they are blacklisted.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
