### ISSUE TITLE
I can steal spawners even if i have spawner deny permission in claims

### ISSUE THREAD

**Issue by Fredh1000** [BG-Software-LLC/WildStacker#805]
### Minecraft's Version

WindSpigot 1.8.8

### Plugin's Version

latest stable: 2023.1

### Describe the bug

I can steal spawners from the wildstacker gui inside any claim, even if I have the spawner permission set to deny

### To Reproduce

Video: https://www.youtube.com/watch?v=WnUaovcQioA

**Comment by OmerBenGera** [comment]
Disable the break menu.
There is nothing to do regarding this.
