### ISSUE TITLE
display bug when items fall stacker then recover a second time

### ISSUE THREAD

**Issue by Naunau99** [BG-Software-LLC/WildStacker#806]
### Minecraft's Version

1.17

### Plugin's Version

WildStacker-2023.1.jar

### Describe the bug

When a player breaks a storage unit, the items are stacked on the ground but when a player picks them up for the first time without being able to take everything, the rest will become invisible but can still be picked up. 
To see the bug in video:
https://youtu.be/OV0gg0BkXpk

### To Reproduce

Put 3k of blocks in a storage unit on a server then break the storage unit, pick up a first part and leave the rest on the ground which will become invisible.

**Comment by OmerBenGera** [comment]
This is a bug with the spigot jar you use, nothing to do with WildStacker.
