### ISSUE TITLE
Issue with Mob Health being adjusted without insta kill feature toggled on

### ISSUE THREAD

**Issue by H0ud1n11** [BG-Software-LLC/WildStacker#807]
### Minecraft's Version

Paper Spigot 1.8.8

### Plugin's Version

WildStacker-2023.1

### Describe the bug

All mobs on the server are 2 hits with a fist and they proceed to die. Is this working as intended or is there a way to change this? Players on my server are unable to use certain grinders because the mob's health gets adjusted. 

### To Reproduce

1. Find a mob, through natural spawning or mob spawner
2. Hit mob twice with any item including fists
3. Mob dies

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it still occurs.

**Comment by H0ud1n11** [comment]
Switching to the Dev build fixed the issue! Thank you!!
