### ISSUE TITLE
Barrels can be broken by non allowed players (BentoBox)

### ISSUE THREAD

**Issue by J4im3x0** [BG-Software-LLC/WildStacker#808]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-70 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 19c244b on HEAD)
You are on the latest version!

### Plugin's Version

WildStacker version 2023.1-b1

### Describe the bug

I use BentoBox SkyBlock,

Not island members can remove blocks from stacked barrels

### To Reproduce

Right click to a barrel in a non allowed island

### Additional Information

Video: https://streamable.com/awqquq

**Comment by OmerBenGera** [comment]
Ask BentoBox to disable interaction with cauldrons, or ask them to somehow configure the list of protected blocks.

**Comment by OmerBenGera** [comment]
> I think that is not the solution, since for example you do a check for spawners menu (I think), wouldn't be easier to make a hook with bentobox?
> 
> Thanks

I dont do any check on the spawners.
It is  not possible to check every plugin that has claims feature for access, it will never end.
SuperiorSkyblock, for example, ha s a feature where you can configure all interactable blocks, which then you can add spawners, cauldrons or any other block to it.

**Comment by J4im3x0** [comment]
Do you know where that setting is?
Thanks

**Comment by OmerBenGera** [comment]
> Do you know where that setting is? Thanks

In SuperiorSkyblock? You can find an interactables.yml file where you can list all the interactable blocks.

**Comment by J4im3x0** [comment]
In bentobox
