### ISSUE TITLE
spawner bug with skyblock

### ISSUE THREAD

**Issue by liyola** [BG-Software-LLC/WildStacker#809]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.1

### Describe the bug

the spawners stack dont work with supiriorskyblock when u stack spawners it dusnt count them only says 1 spawner to the island even if we stack 5 or 10 and after we brake the spawners that 1 stays counted to the island

### To Reproduce

not counting or removing them correctly

**Comment by OmerBenGera** [comment]
Run `/is admin debug block_place`, then place a spawner and make it stack to another.
Do you see anything in console afterwards?

**Comment by liyola** [comment]
still the same

**Comment by OmerBenGera** [comment]
Run `/is admin debug block_place`, then place a spawner and check what is printed to console.
Then, place another spawner so they stack together, and see if you get the same message.

**Comment by liyola** [comment]
placed 3 but only gives 1 message at the first one placed in console:

DefaultIslandBlocksTrackerAlgorithm::trackBlock {_Liyola_} {SPAWNER:COW} {1}

**Comment by OmerBenGera** [comment]
Test it on a server with only WildStacker and SuperiorSkyblock installed

**Comment by OmerBenGera** [comment]
Sounds like another plugin interfaces with SSB and WS.
Try adding plugins one by one until the issue occurs again.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
