### ISSUE TITLE
Fix-Stack config setting not working

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildStacker#811]
### Minecraft's Version

Current: git-Purpur-1876 (MC: 1.19.3)*

### Plugin's Version

WildChests version 2023.1

### Describe the bug

When breaking a chest with 25 totems in it in different slots, you get a stack of 25 totems in one slot. Doesn't matter if fix-stack config setting is set to true or false, I've tried both, both do the same thing.

### To Reproduce

Put 25 totems in chest. Break Chest.

**Comment by OmerBenGera** [comment]
As soon as I enable `fix-stack`, picking up items will be split in my inventory and will not exceed their initial max stack size.
Do you mind taking a video of the issue?

**Comment by DuneSciFye** [comment]
Here you go: https://streamable.com/3hz6fj

**Comment by OmerBenGera** [comment]
Are you sure this is related to WildStacker?
The items are not even dropped on ground, they are instantly added into your inventory, which is not the behavior of WildStacker.
Try replicating it on a server with only WildStacker installed.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
