### ISSUE TITLE
Dig spawner with silk touch doesn't work.

### ISSUE THREAD

**Issue by IncludivicS** [BG-Software-LLC/WildStacker#813]
### Minecraft's Version

git-Paper-45

### Plugin's Version

WildStacker version 2023.2-b5

### Describe the bug

get nothing after dig the spawner. with this setting
silk-touch:
    # Should spawners get dropped when mining them using a silk-touch pickaxe?
    enabled: true

    # Should the spawner item go straight into the player's inventory instead of dropping on ground?
    drop-to-inventory: false

    # A list of worlds that silk touch will work in.
    # If you want silk touch to work inside all the worlds, use "worlds: []"
    worlds: []

    # Should spawners get dropped without silktouch?
    # If enabled, only players with wildstacker.nosilkdrop will be able to get the spawners.
    drop-without-silk: false

    # Chance of spawners to be dropped after break of silk touch.
    break-chance: 100

    # The minimum required level for silk touch.
    minimum-level: 1

### To Reproduce

just mining spawner with  above setting.

**Comment by OmerBenGera** [comment]
It works fine for me.
Try replicating the issue on a server with only WS installed.

**Comment by IncludivicS** [comment]
I need to regenerate config file when update to 1.20 thanks for the help,
