### ISSUE TITLE
High Timings

### ISSUE THREAD

**Issue by m3hdd** [BG-Software-LLC/WildStacker#814]
### Minecraft's Version

git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

2023.3

### Describe the bug

Hello, I ran a couple of spark profiles on my server and wildstacker seems to be extremely high compared to the others.. 
![image](https://github.com/BG-Software-LLC/WildStacker/assets/138067455/a390d511-6caf-4fef-a879-004fb123aac6)

### To Reproduce

N/A

**Comment by OmerBenGera** [comment]
Please provide me with the spark profilers you took.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
