### ISSUE TITLE
slimes multiply Bug

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#815]
### Minecraft's Version

Paper git-Paper-60 (MC: 1.20.1)

### Plugin's Version

WildStacker-2023.2-b5

### Describe the bug

when you bring the small slimefun to the big one it multiplies, you can do it infinitely like this, after it becomes big you just have to kill it and repeat the process

### To Reproduce

bug: https://youtu.be/0MzhdPlmCZI

### Additional Information

how do I make small slimes not reproduce with big ones

**Comment by SrMonsterYT** [comment]
well I solved this problem when I put this option:

SLIME_SIZE: false

the problem is that when there is 1 slimefun without intelligence that are born by spawners, it does not group, now when 1 natural slime comes close to 1 slime without intelligence it groups even so the small slime in the big one, could you add an option that prohibits the small slime to go to the big slime?

**Comment by SrMonsterYT** [comment]
In short, when it is natural for mobs to group, the small ones go to the big slime, can you add an option where it prevents small slimes from grouping with big slimes?

video: https://youtu.be/4crPPJsygAA

**Comment by OmerBenGera** [comment]
You can disable it by setting `SLIME_SIZE` to true.

**Comment by SrMonsterYT** [comment]
> 



> In short, when it is natural for mobs to group, the small ones go to the big slime, can you add an option where it prevents small slimes from grouping with big slimes?
> 
> video: https://youtu.be/4crPPJsygAA

if you watch this video it shows that slime without AI, do not join, more when the slime has AI, they join even with the option active
