### ISSUE TITLE
Spawner bug on restart

### ISSUE THREAD

**Issue by DarkStark2** [BG-Software-LLC/WildStacker#816]
### Minecraft's Version

git-Paper-65 (MC: 1.20.1)

### Plugin's Version

2023.2-b5

### Describe the bug

Hello.
I seem to be getting a weird bug, that happens whenever I restart server with stacked spawners.
When I place spawner of size 1024 for example, it works fine without issues, however when I restart server it randomly breaks and stops functioning properly. It only spawns 1 mob instead of the size of 1024 spawners. The "time until Spawn" counts down every 4 seconds instead of 1 second and whenever I do /wildstacker debug on the spawner it prints out this in console https://pastebin.com/g0zFyF78
Here is link to latest log: https://mclo.gs/SBjfKbq

### To Reproduce

When I tried to reproduce the bug, I had a stack of 1024 iron golem spawners on 1 chunk border, then stack of 3072 iron golem spawners on side of another chunk. The stack of 3072 functioned normally after restart, however the stack of 1024 was broken. This happened with fresh wildstacker config without anything being modified.

### Additional Information

Did some more testing, it seems to happen if I restart whenever I am on island and then when I join the server back I instantly get spawned at the same place in island. The moment I go to spawn and then back to island the spawner is fixed. If I restart server while being at spawn then go to island the spawners work fine.

**Comment by OmerBenGera** [comment]
Does it happen if you only use WildStacker installed?
Also, the debug messages, are they related to the same spawner or you switched between spawners you debug?

**Comment by DarkStark2** [comment]
With WildStacker alone and no other plugins couldn't reproduce it. However when I tested with SuperiorSkyblock2 (Version 2023.2-b40) and tested it on island again, could reproduce it (Having only wildstacker and superiorskyblock2 installed)
The debug in logs are from spawner that was functioning fine and spawner that was broken.

**Comment by DarkStark2** [comment]
Forgot to add, it breaks when I restart and the spawn timer goes down to 6 seconds

**Comment by OmerBenGera** [comment]
Try disabling the spawner rates upgrade, let me know if it helps.

**Comment by DarkStark2** [comment]
That still didn't solve it. However I found a new discovery. It seems to only break spawners that are in the chunk I am in when I restart the server. Spawners in chunks by me work fine, the ones inside the chunk I was in break.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by DarkStark2** [comment]
The first time it counts down, it is still broken. Works as 1 spawner and counts down every 4 seconds. However after first spawn it works properly again.

**Comment by DarkStark2** [comment]
After restarting another time, couldn't replicate it anymore so seems to be fixed.
