### ISSUE TITLE
Please provide a translation for error spawner

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/WildStacker#818]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.2

### Describe the bug

![image](https://github.com/BG-Software-LLC/WildStacker/assets/73421268/b69b51a0-e050-447a-84e3-f2c156a0f681)

I prefer to add the translation files for spawner errors. They are not present in the default file

### To Reproduce

no

**Comment by Distolfix** [comment]
For example I can't translate: Not enough space to spawn entity

**Comment by OmerBenGera** [comment]
This is not a bug.
Use the features request tab instead.
