### ISSUE TITLE
[ChunkTaskScheduler

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#820]
### Minecraft's Version

Pufferfish 1.20.1 version #15

### Plugin's Version

WildStacker-2023.2-b5.jar

### Describe the bug

error: https://mclo.gs/WQwGWKQ

error 2: https://mclo.gs/6wS321g

I went to the site and found this: -14768 89 -8112

image: https://prnt.sc/ag-ay-ENZbfX
image 2: https://prnt.sc/EKEhjxy5rgqV

video of the entire site where the problem occurred: https://youtu.be/sfJlSiKh58w

I used clearlagg to delete all entities see:  https://prnt.sc/ETX8YiKHDOoH

it simply seems that it has many entities, this had already happened in version 1.19.4 and I had already reported it, I am 100% sure that it is the wildstacker, this has already happened once, when 1 minion killed the wildstacker dropped so much item that the server crashed more now I don't know what I heard, because there are no minions only wildstacker.

### To Reproduce

I don't know

**Comment by OmerBenGera** [comment]
The videos show nothing.
How to replicate the issue?
Also, try it on a server with only WS installed.

**Comment by SrMonsterYT** [comment]
> 

I can not replicate the problem this happened out of nowhere, and it had already happened in version 1.19.4, so much villager was born that the server crashed, more I'm sure it's the wildstacker

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
