### ISSUE TITLE
Could not pass event ChunkLoadEvent to WildStacker v2023.2

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/WildStacker#822]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-61 (MC: 1.19.3)

### Plugin's Version

WildStacker v2023.2

### Describe the bug

Please look at this Pastebin. https://pastebin.com/XjxsicxZ

### To Reproduce

![image](https://github.com/BG-Software-LLC/WildStacker/assets/73421268/b15064f9-e358-4ea4-8ac3-a074166b1c96)

![image](https://github.com/BG-Software-LLC/WildStacker/assets/73421268/f0652dfd-a626-45e3-b2b7-b2cc52a4db17)

This screenshot was obtained after sending the error to pufferifsh. This bug appears to be caused by wildstackers

### Additional Information

Related to https://github.com/BG-Software-LLC/WildStacker/issues/819

**Comment by OmerBenGera** [comment]
The code that triggers the bug is as follows:
```
Arrays.stream(chunk.getTileEntities()).filter(blockState -> blockState instanceof CreatureSpawner)
		.forEach(blockState -> plugin.getNMSSpawners().updateStackedSpawner(WStackedSpawner.of(blockState.getBlock())));
```
This is clearly an issue with Pufferfish.
If they refuse to fix it, I recommend switching to Paper.
