### ISSUE TITLE
bug wither boss

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#823]
### Minecraft's Version

Pufferfish git-Pufferfish-15 (MC: 1.20.1)

### Plugin's Version

WildStacker-2023.2-b5.jar

### Describe the bug

https://youtu.be/sFm6itDHJSk

### To Reproduce

wither kill mobs

**Comment by OmerBenGera** [comment]
Can't replicate the issue.
Try replicating the issue on a server with only WS installed.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
