### ISSUE TITLE
Stacked spawners loss

### ISSUE THREAD

**Issue by MasonooN** [BG-Software-LLC/WildStacker#824]
### Minecraft's Version

PaperMC 1.12.2

### Plugin's Version

21/07/2023 14:05:10 - dev build

### Describe the bug

So whenever the spawner stack is over 127 it doesn't pickup the spawners when you try and mine while shifting them. So lets say you had 127 spawners stacked it would work and give it to you but if you have more than 127 and you tried to mine it while shifting to pickup all it just makes the whole stack disappears. Same with the give spawner command if its over 127 it doesn't work

### To Reproduce

Same as describe bug

### Additional Information

Not really

**Comment by OmerBenGera** [comment]
Upload your config file to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
