### ISSUE TITLE
Not enough space

### ISSUE THREAD

**Issue by z4doesthings** [BG-Software-LLC/WildStacker#825]
### Minecraft's Version

1.16.5

### Plugin's Version

latest dev build, latest stable release

### Describe the bug

spawners doesnt spawn and keeps saying not enough space when theres obviously enough space, chickens, cow, bee works fine, this happened with creeper and slime, and some hostile mobs too, i already set spawners override to true and added no spawn conditions for all mobs but the issue still occurs.

### To Reproduce

place a spawner, wait for it to spawn and it wont spawn because theres not enough space, happens for hostile mobs

**Comment by OmerBenGera** [comment]
The "no space" error means that the spawner cannot find a valid block to spawn the entities on.
This is nothing to do with WildStacker, its minecraft mechanism.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
