### ISSUE TITLE
5xTadpole generates only 1xFrog

### ISSUE THREAD

**Issue by Dweezy750** [BG-Software-LLC/WildStacker#826]
### Minecraft's Version

1.20.1

### Plugin's Version

Lastest, 2023.2

### Describe the bug

Stacked tadpole's like 5x tadpole -> when growing in age and become a frog -> only generating 1xfrog

### To Reproduce

spawn 3x tadpole, feed them with slime, see result

**Comment by OmerBenGera** [comment]
Add `METAMORPHOSIS` to the `filtered-transforms` section in the config file.
I also added it by default in latest dev builds
