### ISSUE TITLE
Stacked spawners bug over time.

### ISSUE THREAD

**Issue by Woeben** [BG-Software-LLC/WildStacker#827]
### Minecraft's Version

Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### Plugin's Version

2023.2

### Describe the bug

After a seemingly random amount of time, stacked spawners lose their hologram and spawn as if they are not stacked. /ws info still shows the correct amount. Only replacing the spawners seems to fix this issue.

### To Reproduce

Place a stacked amount of spawners and wait.

### Additional Information

![image](https://github.com/BG-Software-LLC/WildStacker/assets/49917554/59fd0763-f1e1-45b5-aff9-8390e0170680)

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it fixes the issue.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
