### ISSUE TITLE
Remove spawners upgrade sales

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildStacker#829]
### Minecraft's Version

paper 1.8.8

### Plugin's Version

Stable build 2023.2

### Describe the bug

On my server I have the WildStacker plugin, WildTools and WildChests. I've just noticed that the spawners I've upgraded can be sold with sell sticks and sell chests. But in my shop I've deactivated the sale of spawners, when I sell with a sell stick x1 I notice that it's the accumulation of the investment on a spawner.
The problem is that I have sell sticks that are x2, so it's possible to make infinite money. 
Is it possible to patch this problem?

### To Reproduce

Use WildTools and WildStacker. Upgrade your spawner en sell it with sell stick.

**Comment by OmerBenGera** [comment]
If you configure your shop to not include spawners in them, sell wands or sell chests will not work for spawners.
Not a bug.
