### ISSUE TITLE
[ERROR] Could not pass event BlockPlaceEvent to WildStacker

### ISSUE THREAD

**Issue by MousePak** [BG-Software-LLC/WildStacker#830]
### Minecraft's Version

paper 1.20.1

[Server] [INFO] This server is running Paper version git-Paper-"6520ca1" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6520ca1)
[Server] [INFO] You are running the latest version

### Plugin's Version

Dev #8 04/08/2023 14:17:28

### Describe the bug

running the latest paper + latest dev WildStacker build returns errors // fails to function 

15.08 21:59:24 [Server] [ERROR] Could not pass event BlockPlaceEvent to WildStacker v2023.2
15.08 21:59:24 [Server] [INFO] java.lang.IllegalArgumentException: Can't spawn EntityType null from mobspawners!
15.08 21:59:24 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1201.spawner.SyncedCreatureSpawnerImpl.setSpawnedType(SyncedCreatureSpawnerImpl.java:57) ~[WildStacker-2023.2.jar:?]
15.08 21:59:24 [Server] [INFO] at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.handleSpawnerPlace(SpawnersProvider_Default.java:143) ~[WildStacker-2023.2.jar:?]
15.08 21:59:24 [Server] [INFO] at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:157) ~[WildStacker-2023.2.jar:?]
15.08 21:59:24 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor664.execute(Unknown Source) ~[?:?]
15.08 21:59:24 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
15.08 21:59:24 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-"6520ca1"]
15.08 21:59:24 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
15.08 21:59:24 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:24 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:24 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
15.08 21:59:24 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:446) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:24 [Server] [INFO] at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:417) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:24 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:600) ~[?:?]
15.08 21:59:24 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2003) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
15.08 21:59:29 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

- Install   latest versions of WildStacker + Paper 
- Place spawners

**Comment by OmerBenGera** [comment]
You're not using dev build 8 as you mentioned, you use latest stable version.
Please update and let me know if it still occurs.

**Comment by MousePak** [comment]
@OmerBenGera You are correct, tried both with same error from what I could see but paste old log file on first post in error


----
Rerunning for git WildStacker v2023.2-b8
----

18.08 18:32:40 [Server] [ERROR] Could not pass event BlockPlaceEvent to WildStacker v2023.2-b8
18.08 18:32:40 [Server] [INFO] java.lang.IllegalArgumentException: Can't spawn EntityType null from mobspawners!
18.08 18:32:40 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1201.spawner.SyncedCreatureSpawnerImpl.setSpawnedType(SyncedCreatureSpawnerImpl.java:57) ~[WildStacker-2023.2-b8.jar:?]
18.08 18:32:40 [Server] [INFO] at com.bgsoftware.wildstacker.hooks.SpawnersProvider_Default.handleSpawnerPlace(SpawnersProvider_Default.java:143) ~[WildStacker-2023.2-b8.jar:?]
18.08 18:32:40 [Server] [INFO] at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:159) ~[WildStacker-2023.2-b8.jar:?]
18.08 18:32:40 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor671.execute(Unknown Source) ~[?:?]
18.08 18:32:40 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
18.08 18:32:40 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-"6520ca1"]
18.08 18:32:40 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
18.08 18:32:40 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:40 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:40 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
18.08 18:32:40 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:446) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:40 [Server] [INFO] at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:417) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:40 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:597) ~[?:?]
18.08 18:32:40 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2003) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-"6520ca1"]
18.08 18:32:42 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Do you know maybe what item was held when the event occurred?
Or in other words, do you know how to replicate the issue?

**Comment by OmerBenGera** [comment]
I fixed the issue in latest dev builds. It was caused by spawner items that don't have an actual spawner type.
I am not sure how you obtained such items, but I made it so they will be defaulted to PIG spawners.
If this is not the behavior you'd expect from these spawners, let me know and I'll try to change it.
