### ISSUE TITLE
NAN-Health error with mythicmobs 

### ISSUE THREAD

**Issue by Weyl1** [BG-Software-LLC/WildStacker#832]
### Minecraft's Version

version git-Pufferfish-22 (MC: 1.20.1)

### Plugin's Version

2023.2-b8
Mythicmobs 5.4.0-SNAPSHOT-ad1bbcbf

### Describe the bug

error in the console

[18:58:41 ERROR]: [STDERR] [net.minecraft.world.entity.EntityLiving] [NAN-HEALTH] 282f9e67-b33f-4d6d-b370-02fe01b29236 had NaN health set

### To Reproduce

/

### Additional Information

https://mclo.gs/p1JoP8Y

**Comment by OmerBenGera** [comment]
WildStacker changes the health of mobs the same, it doesn't care if it is a MythicMobs or not.
Also, it changes the health to 0 and not NaN, which makes me believe it is not related to WS.

**Comment by Weyl1** [comment]
Okay, because I only have this problem with the new version of mythicmobs, and I read that it was probably related to a stack plugin.

**Comment by OmerBenGera** [comment]
Does it still happen if you remove WildStacker?

**Comment by Weyl1** [comment]
I still have the same problem :/ sorry I thought it came from stacking

**Comment by OmerBenGera** [comment]
I see.
I recommend removing plugins one by one until you find the plugin that caused the issue.
Make sure you update me if you find the plugin :)
