### ISSUE TITLE
Error "Skipping Entity with id" when i place spawner

### ISSUE THREAD

**Issue by NoltoxGit** [BG-Software-LLC/WildStacker#834]
### Minecraft's Version

Purpur-2044 (1.20.1)

### Plugin's Version

2023.2-b9

### Describe the bug

When a player place a spawner (without op permission), it spam my console with the error:
```log
[23:51:08 WARN]: Skipping Entity with id
[23:51:08 WARN]: Location: Survie 0.0,0.0,0.0
```
And also when my server start.
### To Reproduce

- Use my config
- Use a player without OP permissions
- Give a spawner (for exemple zombie)
- Place a spawner
- Check the console
- Restart the server
- Re-check the console during the restart

### Additional Information

Here is my [config](https://pastebin.com/SVRQkkkN).
Here is my [logs](https://mclo.gs/bEKQtrF).
Here is video for illustrate the bug:

https://github.com/BG-Software-LLC/WildStacker/assets/75265787/b14a8c83-49d1-4df1-a615-c81fe91ed5c5

**Comment by Mdsh9** [comment]
Same here
