### ISSUE TITLE
Chunk Limit for entities isnt working

### ISSUE THREAD

**Issue by Chiefink5** [BG-Software-LLC/WildStacker#835]
### Minecraft's Version

[17:22:17 INFO]: This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### Plugin's Version

[17:21:48 INFO]: WildStacker version 2023.2
[17:21:48 INFO]: Stacking drops, entities, blocks and spawners into one object!
[17:21:48 INFO]: Website: https://bg-software.com/
[17:21:48 INFO]: Author: Ome_R

### Describe the bug

Entity objects in a chunk limit is not working like i think it should.. id assume it means to cap how many stacks of entites are allowed in a chunk, but when i set it to 6, there are at least 10 stacks allowed to spawn in one chunk. 

### To Reproduce

set `chunk-limit:` to a small integer
reload plugin
place a spawner in a chunk and allow mobs to stack until the defined integer
notice how they continue to spawn even after limit has been reached

### Additional Information

im also using a plugin called `SpawnerMeta`, and they have WildStacker listed as a supported plugin. could possibly be an issue with WildStacker reading mobs spawned from SpawnerMeta?

**Comment by OmerBenGera** [comment]
Try it on a server with only WS installed, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?
I also want you to know that if entities move into the chunk (either by walking into it, or by being pushed), the plugin will not attempt to stop them - it will only stop new mobs from spawning in that chunk.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
