### ISSUE TITLE
Server counts all the spawners in the stack as ONE, gives me a huge error message

### ISSUE THREAD

**Issue by LaChankla21** [BG-Software-LLC/WildStacker#836]
### Minecraft's Version

1.20.1 Spigot

### Plugin's Version

WildStacker-2023.2.jar

### Describe the bug

Whenever our server restarts it counts all the placed spawners in the stack as one, and some of the spawners stop at 0s when spawning.

[04:04:00 INFO]: [WildStacker] NMSSpawners::updateStackedSpawner baseSpawner=com.bgsoftware.wildstacker.nms.v1201.spawner.StackedBaseSpawner@32d1534c

EXACT ERROR

### To Reproduce

Restart server, gives this huge error.

**Comment by OmerBenGera** [comment]
Update to latest dev build.
If the issue continues, let me know.
