### ISSUE TITLE
Cannot Blacklist MythicMobs from Stacking

### ISSUE THREAD

**Issue by FlameBeast25** [BG-Software-LLC/WildStacker#842]
### Minecraft's Version

1.19.4

### Plugin's Version

v[2023.2]

### Describe the bug

Cannot Blacklist MythicMobs from Stacking, or I don't know how to do it.

### To Reproduce

Well idk how to blacklist them or if there even is functionality for this so yeah.

**Comment by OmerBenGera** [comment]
Add `MYTHIC_MOBS` to the blacklist section.

**Comment by FlameBeast25** [comment]
thanks
