### ISSUE TITLE
1870 - WildStacker failed main thread check

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#844]
### Minecraft's Version

Pufferfish version git-Pufferfish-15 (MC: 1.20.1)

### Plugin's Version

WildStacker-2023.2-b9.jar

### Describe the bug

https://mclo.gs/GXBke86

### To Reproduce

I don't know how it happened

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue continues let me know
