### ISSUE TITLE
Spawners can bypass the merge-radius. 

### ISSUE THREAD

**Issue by Jordyn114** [BG-Software-LLC/WildStacker#845]
### Minecraft's Version

Paper version git-Paper-524 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9846d0d)

### Plugin's Version

WildStacker-2023.2-b9

### Describe the bug

Spawners placed in multiples can bypass the merge-radius if the multiple you're placing + the multiple already placed exceeds maximum stack size. I've tested two different spawner types (cows and wither skeletons) and both gave same results.

### To Reproduce

Method one:
1) Set `shift-place-stack: true` in config.yml.
2) Have a stack of spawners less than your maximum stack size
3) Shift-place multiple spawners (enough to go over maximum stack size) within the merge-radius of the previous stack
4) You will now have two separate stacks that bypass merge-radius

Method two:
1) Set `shift-get-whole-stack: true` in config.yml.
2) Have a stack of spawners less than your maximum stack size
3) Pick up multiple spawners (enough to go over maximum stack size) from another stack by shifting to get a single stacked item.
4) Place that item within the merge-radius of the previous stack
5) You will now have two separate stacks that bypass merge-radius

### Additional Information

https://imgur.com/a/pbgOTn1

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send a link to it here

**Comment by Jordyn114** [comment]
https://pastebin.com/uj4r8FRp

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
