### ISSUE TITLE
WildStacker Nerfed Guardians Issue

### ISSUE THREAD

**Issue by DJGamer98765** [BG-Software-LLC/WildStacker#846]
### Minecraft's Version

Paper 1.20.1

### Plugin's Version

2023.2-b9

### Describe the bug

Guardians are the only mobs coming out of spawners that are not nerfed.

### To Reproduce

Add "GUARDIAN:SPAWNER" to the whitelist for nerfed entities and place a guardian spawner down.

**Comment by OmerBenGera** [comment]
Right click a Guardian using an inspect tool (/ws inspect) and check if it is nerfed.

**Comment by DJGamer98765** [comment]
> Right click a Guardian using an inspect tool (/ws inspect) and check if it is nerfed.

It states "Nerfed: True" but guardians are still moving around and attacking players when no other mob is doing that.

**Comment by DJGamer98765** [comment]
Hello?

**Comment by OmerBenGera** [comment]
I cannot replicate the issue.
Does it happen if you spawn a guardian with a spawn egg?

**Comment by DJGamer98765** [comment]
It happens with both spawners and spawn eggs

**Comment by OmerBenGera** [comment]
Seems to work fine for me.

**Comment by DJGamer98765** [comment]
That’s great but it’s not for my server. Every other mob works just fine except for the guardians and I would like to know how this can be fixed.

**Comment by OmerBenGera** [comment]
I suspect that another plugin somehow interfaces with this.
Try it on a server with only WildStacker installed, let me know if it occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by DJGamer98765** [comment]
Yeah I tried it with only WildStacker and it was still happening.

**Comment by OmerBenGera** [comment]
What version of Paper/Spigot do you use?
Give me the exact output of `/version`

**Comment by DJGamer98765** [comment]
git-Paper-196

**Comment by OmerBenGera** [comment]
Please take a video of the issue, as I cannot replicate it myself.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
