### ISSUE TITLE
Reflection of the fireball counting as the ghast killing itself

### ISSUE THREAD

**Issue by Ordwen** [BG-Software-LLC/WildStacker#847]
### Minecraft's Version

paper-1.20.1-171

### Plugin's Version

WildStacker 2023.2 - stable build.

### Describe the bug

The problem concerns the WildStacker API, more specifically the EntityUnstackEvent.

When a ghast is killed by a player using a bow or sword, the source is indicated as a player (via the `EntityUnstackEvent#getUnstackSource()` method). On the other hand, if the player kills the ghast by reflecting its fireball, the source is indicated as the ghast itself. 

It is therefore impossible to determine that it was a player who caused the death of the ghast in this case.

### To Reproduce

Using this code, kill a ghast with any weapon. You'll see that the source is you. Then kill the ghast by reflecting its fireball. You'll see that it counts as if the ghast had killed itself.

```Java
@EventHandler
    public void onWildStackerEntityUnstackEvent(EntityUnstackEvent event) {
        System.out.println("EntityUnstackEvent");
        if (event.isCancelled()) return;
        if (event.getUnstackSource() == null) return;

        final Entity entity = event.getEntity().getLivingEntity();

        System.out.println("killed entity: " + entity.getType());
        System.out.println("killed by: " + event.getUnstackSource().getType());

        if (event.getUnstackSource() instanceof Player player) {
            // my stuff
        }
    }
```

### Additional Information

![image](https://github.com/BG-Software-LLC/WildStacker/assets/44400540/e9e474d7-20a3-411b-abd4-1849d04ee4bd)

I killed the first ghast with a crossbow.
The second was killed by reflecting its fireball.

**Comment by OmerBenGera** [comment]
Is it the same if you listen to EntityDeathEvent?

**Comment by Ordwen** [comment]
From the `EntityDeathEvent` the `getEntity()` method returns a `LivingEntity`, from which we can call the `getKiller()` method to get the player who is reflecting the fireballs.

But from the `EntityUnstackEvent`, we can call `getEntity().getLivingEntity()` to get the entity, but `getKiller()` returns null in this case. 

For example:

```Java

/**
* We can get the killer directly from the LivingEntity given by the event. 
* In our case, the killer is the player who reflected the fireball.
*/
@EventHandler
public void onEntityDeathEvent(EntityDeathEvent event) {
      final LivingEntity entity = event.getEntity();
      if (entity.getKiller() != null) {
         // do stuff
}

/**
* But in the EntityUnstackEvent, we need to firstly get the Entity and then the LivingEntity.
* And in our case, the getKiller() always return null.
*/
@EventHandler
public void onEntityUnstackEvent(EntityUnstackEvent event) {
        final LivingEntity entity = event.getEntity().getLivingEntity();
        if (entity.getKiller() != null) {
           // do stuff
        }
}
```

I don't know how you're handling the calls to the event, but if you're also using the `EntityDeathEvent`, maybe you can assign the result of the `EntityDeathEvent#getEntity().getKiller()` to the result of the `EntityUnstackEvent#getUnstackSource()` method?

**Comment by OmerBenGera** [comment]
Why aren't you using EntityDeathEvent then?

**Comment by Ordwen** [comment]
I'm integrating WildStacker into my plugin. As a result, when the EntityDeathEvent is called, I do nothing if WildStacker is used, as it also has its own event. 

I can of course add a condition to EntityDeathEvent specifically for the ghast... I just wanted to point this out to you as I assume this is not the expected behavior.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now.

**Comment by Ordwen** [comment]
Will do as soon as possible, thank you!

**Comment by Ordwen** [comment]
Sorry, it doesn't seem to work with build b14.

![image](https://github.com/BG-Software-LLC/WildStacker/assets/44400540/8b8fbd1f-216d-4594-a905-33031fe8706f)
![image](https://github.com/BG-Software-LLC/WildStacker/assets/44400540/04da8838-667f-4ea4-b9ea-842ad682619f)

Here is my code: 

```Java
@EventHandler
public void onWildStackerEntityUnstackEvent(EntityUnstackEvent event) {
    System.out.println("EntityUnstackEvent");
    if (event.isCancelled()) return;

    final Entity entity = event.getEntity().getLivingEntity();
    final boolean isEntityFromSpawner = EntitySource.isEntityFromSpawner(entity);
    EntitySource.removeEntityFromSpawner(entity);

    if (!WildStackerEnabled.isEnabled()) return;
    if (event.getUnstackSource() == null) return;
    if (isEntityFromSpawner) return;

    System.out.println(entity.getType() + " was killed by " + event.getUnstackSource().getType());

    if (event.getUnstackSource() instanceof Player player) {
        System.out.println("Player");
        setPlayerQuestProgression(player, event.getEntity().getType(), null, event.getAmount(), QuestType.KILL, null);
    }
}
```

**Comment by OmerBenGera** [comment]
When a ghast kills an entity with their fireball, it will detect the killer as the ghast.
If you are the one that reflects the fireball, it will detect you as a killer.
I tested it and it seems to work fine.

**Comment by Ordwen** [comment]
It doesn't seem to be working for me.
![wildstacker_reflect](https://github.com/BG-Software-LLC/WildStacker/assets/44400540/a7f8f153-298a-478a-951d-1a9a8249d913)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Ordwen** [comment]
It perfectly works, thank you! 😄
