### ISSUE TITLE
WildStacker keeps crashing the server

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#849]
### Minecraft's Version

1.18.2

### Plugin's Version

WildStacker version 2023.2-b14

### Describe the bug

The plugin keeps crashing my server, this is the 7th time today.

### To Reproduce

-

### Additional Information

https://pastebin.com/ZZXGm79j

**Comment by OmerBenGera** [comment]
Your server freezed when an entity spawned.
Take a timings sample and find out what causes lag that a simple spawning of an entity freezes your server.

**Comment by Superalex0102** [comment]
> Your server freezed when an entity spawned.
> 
> Take a timings sample and find out what causes lag that a simple spawning of an entity freezes your server.

https://timings.aikar.co/dev/?id=7cebe349cbd2468c8949b4c9cd03a5b6

**Comment by OmerBenGera** [comment]
WildChest's ticking is probably the cause of the crash, your server really struggles with it.
Do you mind taking a spark profiler so we can look into what the reason WildChests takes so many of the tick usage?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
