### ISSUE TITLE
Can't add spawners with default tier

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#851]
### Minecraft's Version

1.18.2

### Plugin's Version

WildStacker version 2023.2-b14

### Describe the bug

Check the video, but in short: If the spawner is upgradable, with the default upgrade you can't add spawners via the menu.

### To Reproduce

https://youtu.be/MhudBjQ5ekQ

**Comment by OmerBenGera** [comment]
Upload your config file to pastebin and send a link to it here.

**Comment by Superalex0102** [comment]
> Upload your config file to pastebin and send a link to it here.

https://pastebin.com/wQWajNP3

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
