### ISSUE TITLE
Wildstacker spawn upgrade not stacking

### ISSUE THREAD

**Issue by SpYoXDOT** [BG-Software-LLC/WildStacker#852]
### Minecraft's Version

1.19.4

### Plugin's Version

WildStacker-2023.2-b8.jar

### Describe the bug

When we up the spawner in the upgrade menu the entity is not stacked it create a lot of stacked entity but not in one stack

### To Reproduce

take a basic spawner without upgrade and up them at the first upgrade

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
