### ISSUE TITLE
Stacking issue

### ISSUE THREAD

**Issue by xStephie** [BG-Software-LLC/WildStacker#855]
### Minecraft's Version

1.20.1 and paper

### Plugin's Version

WildStacker-2023.2-b19.jar

### Describe the bug

# Blacklisted entities are entities that won't get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable blacklisted entities, use "blacklist: []"
  blacklist:
  - all

  # Whitelisted entities are entities that will get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable whitelisted entities, use "whitelist: []"
  whitelist:
  - SPAWNER

### To Reproduce

I am wanting only spawner mobs to stack and all mobs arent stacking please help

**Comment by xStephie** [comment]
# Blacklisted entities are entities that won't get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable blacklisted entities, use "blacklist: []"
  blacklist:
  - all

  # Whitelisted entities are entities that will get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable whitelisted entities, use "whitelist: []"
  whitelist:
  - SPAWNER

**Comment by xStephie** [comment]
![image](https://github.com/BG-Software-LLC/WildStacker/assets/146554129/11592676-a544-49fc-a5f3-4fc168cbe6ab)

**Comment by OmerBenGera** [comment]
Set the `blacklist` section to `[]`

**Comment by xStephie** [comment]
> Set the `blacklist` section to `[]`

Thanks so much
