### ISSUE TITLE
Plugins not working for 1.19.2

### ISSUE THREAD

**Issue by Tkade1** [BG-Software-LLC/WildStacker#857]
### Minecraft's Version

Server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### Plugin's Version

WildChests: [WildChests-2023.3-b24.jar]

WildStacker: [WildStacker-2023.3-b22.jar

### Describe the bug

Both plugins in the console are saying unsupported version.

### To Reproduce

Start up server, and the bugs don't show until you attempt the commands.

### Additional Information

PASTEBIN [WildChests]
https://pastebin.com/rw0uZdW1

PASTEBIN  [WildStacker]
https://pastebin.com/k37DVc8y

**Comment by OmerBenGera** [comment]
Update to 1.19.4
Only recent versions of each major version is supported
