### ISSUE TITLE
Mobs not able to be damaged.

### ISSUE THREAD

**Issue by Tkade1** [BG-Software-LLC/WildStacker#859]
### Minecraft's Version

WineSpigot 1.8.8

### Plugin's Version

WildStacker [2023.3] -- no dev builds

### Describe the bug

Using my alternate account  (default)  rank, I cant kill/hit mobs without the plugin being disabled.

OP  works.

### To Reproduce

1. Start server
2. Join server
3. Try to kill a mob on a non-op account
4. Disable WildStacker
5. Players can hit mobs

### Additional Information

https://pastebin.com/LtrEMdn7

**Comment by Tkade1** [comment]
No console  errors either. Just an absolute dull situation

**Comment by Tkade1** [comment]
I see you have support for 1.8.9, is there any build that is  1.8.8?

**Comment by OmerBenGera** [comment]
Test it on a regular Spigot/Paper server and only WildStacker installed, let me know if it still occurs
