### ISSUE TITLE
WildStacker and  MythicMobs conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#861]
### Minecraft's Version

Pufferfish version git-Pufferfish-27

### Plugin's Version

WildStacker-2023.3-b22

### Describe the bug

   when a command reward in mythicmobs at 100%, it only happens after I kill 2-4 mobs, plus if I remove the wildstacker from the server it works 100% 

Blaze_King:
  Type: BLAZE
  Drops:
  - cmd{c="eco give <trigger.name> 100"} 1 1.0
  Display: '&4&lRei Blaze'

### To Reproduce

when I remove the wildstacker the plugin works correctly

video: https://youtu.be/M7LqqNMm6H0

**Comment by SrMonsterYT** [comment]
@OmerBenGera the problem still occurs with updated versions of both wildstacker and MythicMobs

**Comment by SrMonsterYT** [comment]
@OmerBenGera this issue was never fixed, how do I make wildstacker ignore all mobs from MythicMobs

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue using default config of both plugins.
I only added a command to the drops of `SkeletalKnight`

**Comment by SrMonsterYT** [comment]
> I cannot seem to replicate the issue using default config of both plugins. I only added a command to the drops of `SkeletalKnight`

when I delete wildstacker the problem is solved, I reported it to MythicMobs they told me that the problem is in wildstacker, I tested it only with these plugins:

MythicMobs
MythicCrucible
ModelEngine-4.0.5
ItemsAdder
LoneLibs
protocolLib

**Comment by OmerBenGera** [comment]
> > I cannot seem to replicate the issue using default config of both plugins. I only added a command to the drops of `SkeletalKnight`
> 
> when I delete wildstacker the problem is solved, I reported it to MythicMobs they told me that the problem is in wildstacker, I tested it only with these plugins:
> 
> MythicMobs MythicCrucible ModelEngine-4.0.5 ItemsAdder LoneLibs protocolLib

Get rid of all the plugins, keep only WildStacker and MythicMovs, default config files. Let me know if you manage to replicate it.

**Comment by SrMonsterYT** [comment]
> > > I cannot seem to replicate the issue using default config of both plugins. I only added a command to the drops of `SkeletalKnight`
> > 
> > 
> > when I delete wildstacker the problem is solved, I reported it to MythicMobs they told me that the problem is in wildstacker, I tested it only with these plugins:
> > MythicMobs MythicCrucible ModelEngine-4.0.5 ItemsAdder LoneLibs protocolLib
> 
> Get rid of all the plugins, keep only WildStacker and MythicMobs, default config files. Let me know if you manage to replicate it.

I was able to replicate the problem with just these 2 plugins

video: https://youtu.be/4l-tjgbgxSw

video without wildstacker: https://youtu.be/BN1DqoSB4Nw

server: version git-Paper-454 (MC: 1.20.4)

plugins:

- WildStacker-2024.1-b53
- MythicMobs-5.6.1-SNAPSHOT

my mob config MythicMobs: https://mclo.gs/a2m7D4D

I've already deleted the wildstacker folder and let it generate a new one, but the problem is still there. The problem is solved when wildstacker is removed.

I've already changed the MOB, I've already added it to the blacklist: 

 - CREEPER:CHUNK_GEN
  - CREEPER:CUSTOM
  - CREEPER
  - ARMOR_STAND
  - MYTHIC_MOBS
  - UNKNOWN
  - MYTHIC_MOBS:CHUNK_GEN
  
  I've done all the possible tests

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by SrMonsterYT** [comment]
> Check out latest dev build, let me know if it is fixed

yes fixed, thanks! <3
