### ISSUE TITLE
Invisble Diamond blocks with barrels

### ISSUE THREAD

**Issue by Stijn-TryHardKoala** [BG-Software-LLC/WildStacker#862]
### Minecraft's Version

![Schermafbeelding 2023-10-29 121014](https://github.com/BG-Software-LLC/WildStacker/assets/77848884/e3f09ad7-082b-49fe-acea-5cb71c6bf980)
minecraft version: 1.19.4

### Plugin's Version

![Schermafbeelding 2023-10-29 121115](https://github.com/BG-Software-LLC/WildStacker/assets/77848884/dedacd4a-6b21-4ec8-81ab-a3f7cc7b9810)

dev build: laste version

### Describe the bug

you place diamond block becomes a barrel you add 6000 or so then you break it then it says for example 6000x diamond block then you pick it up then your inventory is full then the rest becomes invisible then you place it again if you then walk to where you first broke then pick up invisible diamond block

### To Reproduce

you place diamond block becomes a barrel you add 6000 or so then you break it then it says for example 6000x diamond block then you pick it up then your inventory is full then the rest becomes invisible then you place it again if you then walk to where you first broke then pick up invisible diamond block

### Additional Information

https://medal.tv/games/minecraft/clips/1AYxFis3VWJAAj/d1337jCqDdom?invite=cr-MSxrM2MsNTgxMzg5MjQs

**Comment by OmerBenGera** [comment]
There's a plugin or something that blocks the armor stands from spawning in.
Try it on a server with only WildStacker installed, let me know if it still occurs

**Comment by KoalaDevelopment** [comment]
I've already found the problem

**Comment by KoalaDevelopment** [comment]
https://medal.tv/games/minecraft/clips/1BSlNQKQi6vMu5/d1337tSMhClD?invite=cr-MSxyZ0gsNTgxMzg5MjQs
![Schermafbeelding 2023-11-04 000033](https://github.com/BG-Software-LLC/WildStacker/assets/77848884/7bd1e06d-9d22-4fc1-9f1f-65015c405f3f)
it still does not work

**Comment by Tkade1** [comment]
Similar issue as well. I had 4000x gunpowder on the floor. Went to pick it up and received 2304  (full inventory) while the remain  items on the floor became invisible. After using /clearinventory (essentials), i went to the same area they were dropped, and received the remaining amount.

**Comment by OmerBenGera** [comment]
> https://medal.tv/games/minecraft/clips/1BSlNQKQi6vMu5/d1337tSMhClD?invite=cr-MSxyZ0gsNTgxMzg5MjQs ![Schermafbeelding 2023-11-04 000033](https://user-images.githubusercontent.com/77848884/280428905-7bd1e06d-9d22-4fc1-9f1f-65015c405f3f.png) it still does not work

Take a video of the issue when you try it on a server with only WildStacker installed.

**Comment by OmerBenGera** [comment]
> Similar issue as well. I had 4000x gunpowder on the floor. Went to pick it up and received 2304 (full inventory) while the remain items on the floor became invisible. After using /clearinventory (essentials), i went to the same area they were dropped, and received the remaining amount that was invisible.

This is not relevant to this issue at all.

**Comment by KoalaDevelopment** [comment]
bro that video was from the server where wildstacker was only plugin

**Comment by OmerBenGera** [comment]
> bro that video was from the server where wildstacker was only plugin

The original video was about the block display inside the barrel disappears. The video you showed me is about items on the ground, which is irrelevant to the issue.
Take a video of the original issue, regarding the block display disappearing from barrels on a server with only WildStacker installed.
Regarding the invincible items on ground, open a new issue, as this is a different bug.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by KoalaDevelopment** [comment]
the gene that see in video is me problem/bug
https://github.com/BG-Software-LLC/WildStacker/issues/862#issuecomment-1825945811

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
