### ISSUE TITLE
Instant-Kill Issue for Fall Damage

### ISSUE THREAD

**Issue by Tkade1** [BG-Software-LLC/WildStacker#863]
### Minecraft's Version

WineSpigot version 1_8_R3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/WildStacker/assets/141796186/2178a999-87ad-43aa-bbf1-ec37e40553cf)

### Describe the bug

Mobs don't instantly die from fall damage when added the "Fall" DamageCauseEvent to the list of instant kills.

### To Reproduce

1. Hit single mob or stacked mobs from a block that will send them down more than 3 blocks.
OR
2. When mobs spawn from spawners above to hit the ground (as on my server its about 20 blocks above the hopper system)

### Additional Information

Like it's described in the config & the webpage for DamageCauses.
Fall: When dropped from more than 3 blocks

WildStacker config:
https://pastebin.com/tXJeYtD5

**Comment by Tkade1** [comment]
Also in the WildStacker config...
The  Instant-kill section
- FALL 
doesnt work

**Comment by Tkade1** [comment]
**FIRST ISSUE HAS BEEN RESOLVED!**

Currently still having issues where the Instant--Kill Sectioon for Fall isnt working

**Comment by OmerBenGera** [comment]
As described in the config file, `instant-kill` will kill the entire stack when it dies, and not unstack it one by one.
Therefore, the mobs need to actually die, then it will kill the entire stack.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
