### ISSUE TITLE
Linked spawner entities are ignoring their mob limits

### ISSUE THREAD

**Issue by airoons** [BG-Software-LLC/WildStacker#868]
### Minecraft's Version

1.20.2

### Plugin's Version

2023.3

### Describe the bug

Let's imagine a situation. In pre spawner spawn event 8x stacked spawner will spawn one 8x stacked mob. There are multiple "candidates" that could be stacked into. It goes through them, counts their size and in the end creates ONE mob by merging nearby ones. 

https://github.com/BG-Software-LLC/WildStacker/blob/master/src/main/java/com/bgsoftware/wildstacker/listeners/SpawnersListener.java#L854C17-L854C37

You are not checking or limiting that line to respect the entity stack limit for the entity type.

### To Reproduce

I described it in the section above.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
