### ISSUE TITLE
bug slimeball drops

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#869]
### Minecraft's Version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### Plugin's Version

WildStacker-2023.3-b25

### Describe the bug

video: https://youtu.be/D7JWInum_gE

I removed the wildstacker and saw that in vanilla it only drops slime balls when the smallest slime is killed

### To Reproduce

kill slimes

**Comment by OmerBenGera** [comment]
Only the smallest slimes are dropping slime balls.
I cannot see the video as it is private.

**Comment by SrMonsterYT** [comment]
sorry, here https://youtu.be/i53bfCm-_rM

I've already tested it with just the wildstacker and it also happens, and ignore the magna cube drop, but if you want I can also make a video showing just the wildstacker on the server

**Comment by OmerBenGera** [comment]
I added the ability to filter out drops by slime size, so now you can limit slime balls and magma cream only to small slimes.
Regenerate the loot tables of Slimes and Magma Cubes, let me know if it fixes the issue.

If you want to add it manually, add `slime-size` filter, and set it to 1 as shown here:
```
{
  "pairs": [
    {
      "slime-size": 1,
      "chance": 100,
      "items": [
        ...
      ]
    }
  ]
}
```

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue continues let me know
