### ISSUE TITLE
Bug slime size

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#870]
### Minecraft's Version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### Plugin's Version

WildStacker-2023.3-b24

### Describe the bug

i got this error on the console and it turned out that the small slime were grouping together with the big slime, i had already set this up so it wouldn't happen but it is happening and this error occurs

error: https://mclo.gs/QA4y3Tm

I had already solved this problem but the problem came back when I updated the jar, I tested it on version 25 and it's also happening, players took advantage of the bug I had to reset baltop

### To Reproduce

video: https://youtu.be/I1ipqINDgNs

**Comment by SrMonsterYT** [comment]
I've tried everything, I've reset the configuration, updated protocollib, switched to paper, put only wildstacker and nothing has worked :(

**Comment by OmerBenGera** [comment]
The error comes from BLOCK_DISPLAY, which doesn't make a lot of sense.
I suspect it's another plugin somehow messing with slimes.

Try it on a server with only WildStacker installed, default config files.
Let me know if the error still occurs.

**Comment by SrMonsterYT** [comment]
I've already deleted my configuration and made everything from scratch, then when I restart the server the bug happens, could you see my configuration and see what I did wrong it doesn't make sense I haven't touched anything just update the jar, it's been about 5-6 months now

https://mclo.gs/4rOmsFX

**Comment by SrMonsterYT** [comment]
well I did all the tests there are, and the solution was to activate the option:

# Settings related to overriding spawners.
  spawners-override:
    # Should spawners behavior be overridden by WildStacker?
    # When enabled, you should see better performance from spawners.
    enabled: true
    # Configure spawn conditions for entities that are spawned by spawners
    # You can find more information regarding this by visiting the official wiki:
    # https://wiki.bg-software.com/#/wildstacker/spawn-conditions/
    spawn-conditions:
      EXAMPLE_MOB: []
      
      
      solved the problem, but what happens now is that the slime doesn't join up with the small slime, it stays separate, generating large, medium and small slimes.
      
      video: https://youtu.be/VPEJNKl5zXo
      
      I took a new configuration and put mine in, and I activated this option and it worked, but if I deactivate it the bug happens, this is proof that the problem is not with me, it doesn't make any sense.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works even if you disable `spawners-override`.

**Comment by SrMonsterYT** [comment]
yes it's been fixed, this small and large slime thing shouldn't be optional to choose, it should be by default that the small slime never enters the large one, this is the second time this has happened, after a few updates

**Comment by OmerBenGera** [comment]
Hopefully it will not happen again :)
