### ISSUE TITLE
Could not pass event PreSpawnerSpawnEvent to Wildstacker v2023.3

### ISSUE THREAD

**Issue by EcoSMP** [BG-Software-LLC/WildStacker#871]
### Minecraft's Version

1.20.2 purpur-1.20.2-2092.jar

### Plugin's Version

2023.3 we have also tried the latest dev build.

### Describe the bug

Error spamming console ever since our server updated to 1.20.2:

https://pastebin.com/ArAJRHah

### To Reproduce

I'm not sure how to reproduce it. We have been using the same configs for two years without an issue until earlier this week when we updated to 1.20.2 and these errors started spamming the console constantly.

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.
