### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildStacker#873]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15566 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 2967518)

### Plugin's Version

WildStacker version 2023.3

### Describe the bug

Server crash

### To Reproduce

Unsure

### Additional Information

[latest.log](https://github.com/BG-Software-LLC/WildStacker/files/13750013/latest.log)

**Comment by OmerBenGera** [comment]
Your server lagged-out and crashed.
Take a timings / spark reports and find the root-cause of the lag.
