### ISSUE TITLE
Countdown continues after last hit

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#874]
### Minecraft's Version

Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) 

### Plugin's Version

WildStacker-2023.3-b31

### Describe the bug

After hitting a stacked mob and you stop hitting it, it continues to countdown and drop items. 
I thought this issue was fixed ages ago.

### To Reproduce

Hit a stacked mob. The faster you hit it, the faster it continues.

### Additional Information

https://medal.tv/games/minecraft/clips/1KAhgucNhhFlxO/lMod7Xk5zOKQ?invite=cr-MSxjaDgsMjA2NjQxMzMyLA

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue on a server with only WildStacker installed?
I see all the mobs around the player getting killed, which makes me believe this is not a direct bug within WildStacker itself.

**Comment by OmerBenGera** [comment]
Any news regarding this?
