### ISSUE TITLE
Axolotl amount bug when place with bucket.

### ISSUE THREAD

**Issue by IncludivicS** [BG-Software-LLC/WildStacker#876]
### Minecraft's Version

 git-Paper-361 (MC: 1.20.4)

### Plugin's Version

WildStacker version 2023.3-b32

### Describe the bug

The Axolotl when place with bucket it came out with last salmon or cod amount

### To Reproduce

pick up stacked cod or salmon with bucket and release them then pick up axolotl with the same bucket and place axolotl down.

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue
Can you take a video of it?
Upload it to YT or any other online streaming service and send a link to it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
