### ISSUE TITLE
Look like lootable not working when you have killedby... or killer

### ISSUE THREAD

**Issue by IncludivicS** [BG-Software-LLC/WildStacker#877]
### Minecraft's Version

This server is running Paper version git-Paper-361 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5e978d3)

### Plugin's Version

WildStacker version 2023.3-b32

### Describe the bug

killedByPlayer Or KILLER NOT choose in lootable

### To Reproduce

Just having killedByPlayer killedByCharged or Killer in Pair.

**Comment by OmerBenGera** [comment]
I do not understand what does not work from your report.
Please send me the entire loot table file, and tell me exactly what does not work.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue continues let me know
