### ISSUE TITLE
Support Version

### ISSUE THREAD

**Issue by NixsSa2d** [BG-Software-LLC/WildStacker#878]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/WildStacker/assets/150930296/1c572929-260e-4e2c-8428-8a0747e756f5)
![image](https://github.com/BG-Software-LLC/WildStacker/assets/150930296/295e9a08-35a4-4c69-a711-229f73a5a948)
d9bb123b)
![image](https://github.com/BG-Software-LLC/WildStacker/assets/150930296/bddc7821-39ef-4b59-9447-a926339d476c)

### Plugin's Version

 2023.3

### Describe the bug

.

### To Reproduce

.

### Additional Information

.

**Comment by NixsSa2d** [comment]
![image](https://github.com/BG-Software-LLC/WildStacker/assets/150930296/3d65f615-03a4-474a-8196-32a638f5272a)

**Comment by OmerBenGera** [comment]
Use latest dev build
