### ISSUE TITLE
drop table issue after upgrade from dev 27 to dev28

### ISSUE THREAD

**Issue by hkkongou** [BG-Software-LLC/WildStacker#881]
### Minecraft's Version

1.20.1 purpur

### Plugin's Version

WildStacker-2023.3-b27
WildStacker-2023.3-b28

### Describe the bug

after upgrade to b28 version or above, wither skeleton drop table(default one) does not drop any skulls.
haven't check other mobs.

### To Reproduce

upgrade version b28 or above
kill a wither skeleton with looting 100 sword
in b27 or below version is 100% drop 1 head
in b28 or above does not drop any head

**Comment by WarnDa** [comment]
Saw the same behavior on Blaze !

**Comment by IncludivicS** [comment]
Same #877 issue.

**Comment by OmerBenGera** [comment]
Duplicate of #877
