### ISSUE TITLE
Set expToDrop for the BlockExpEvent to 0 if block is a spawner.

### ISSUE THREAD

**Issue by ChimpGamer** [BG-Software-LLC/WildStacker#882]
### Minecraft's Version

Paper 1.20.4 build 385

### Plugin's Version

2023.3 build 32

### Describe the bug

WildStacker doesn't set the expToDrop to 0 for the BlockExpEvent when breaking a spawner. This causes weird behavior with other plugins that use the expToDrop value from the BlockExpEvent.

### To Reproduce

```kt
fun BlockExpEvent.onBlockExp() {
    println("expToDrop=$expToDrop") // Is not 0 when breaking a spawner
}
```

**Comment by OmerBenGera** [comment]
Same as in Vanilla, when a player breaks a spawner, he gets exp.
Thus, the BlockExpEvent has a value of non-zero.

Why would WildStacker need to set it to 0?

**Comment by ChimpGamer** [comment]
Because you can farm exp with silk touch pickaxes.

**Comment by OmerBenGera** [comment]
I recommend getting a plugin that stops exp from being dropped by spawners.

**Comment by OmerBenGera** [comment]
I am closing this for now
