### ISSUE TITLE
Issue with converting spawners using spawn eggs

### ISSUE THREAD

**Issue by alek4032** [BG-Software-LLC/WildStacker#886]
### Minecraft's Version

Pufferfish+ version 1.20.1

### Plugin's Version

Stable build 2023.3

### Describe the bug

You're able to convert stacks of spawners with just a single spawn egg. 

### To Reproduce

Step 1: Place a stack of spawners - in our case we tried with 32 stacked slime spawners
Step 2: Place 1 spawn egg in your main hand and 31 spawn eggs somewhere else in your inventory
Step 3: Convert the spawner with the 1 spawn egg in your main hand

Result: Only 1 spawn egg is taken from your main hand, the other 31 in your inventory stays and the 1 egg successfully converted the entire 32 stack spawner

### Additional Information

https://github.com/BG-Software-LLC/WildStacker/assets/119686785/220c53fb-8d04-4002-b212-1ad3a1bfc9d8

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by alek4032** [comment]
> Check out latest dev build, let me know if it is fixed

It is fixed, thank you very much!
