### ISSUE TITLE
Mob Drops Lootables 

### ISSUE THREAD

**Issue by Saadi43** [BG-Software-LLC/WildStacker#889]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.3

### Describe the bug

So here is the thing i want custom drops for my mobspawners i set it up is it possible to make it so the the player dont get drops of default upgrade when they upgrade it to liek obsidian upgrade 

### To Reproduce

    ladders:
      '1':

# Here you can configurable all features related to stacked entities.
        entities:
        - RAVAGER
        default:
          next-upgrade: obsidian
          nearby-players: 16
          icon:
            type: BOOK
            name: '&fDefault '
            lore:
            - '&8Information'
            - '&fThis spawner upgrade is default.'
            - '&7 '
            - '&5&lINFOTMATION'
            - ' &5| &fSpawn Delay Range&f: &d%min-spawn-delay%-%max-spawn-delay%'
            - ' &5| &fSpawn Count&f:&d%spawn-count%'
            - ' &5| &fMax Nearby Entities&f: &d%max-nearby-entities%'
            - ' &5| &fRequired Player Range&f: &d%required-player-range%'
            - ' &5| &fSpawn Range&f: &d%spawn-range%'
            - ''
        obsidian:
          id: 1
          display: '&7 (&fCrying Obsidian&7)'
          cost: 150000000
          icon:
            type: CRYING_OBSIDIAN
            name: '&fCrying Obsidian'
            lore:
            - '&8Information'
            - '&7 '
            - '&2&lINFORMATION'
            - ' &2| &7Spawn Delay Range&f: &a%min-spawn-delay%-%max-spawn-delay%'
            - ' &2| &7Spawn Count&f: &a%spawn-count%'
            - ' &2| &7Max Nearby Entities&f: &a%max-nearby-entities%'
            - ' &2| &7Required Player Range&f: &a%required-player-range%'
            - ' &2| &7Spawn Range&f: &a%spawn-range%'
            - ''
            - '&2&lPRICE: &a150,000,000 &7(150M)'
            - ''
            - '&2&l[&a&l!&2&l]&a Click here to buy this spawner upgrade!'

### Additional Information

{
  "pairs": [
    {
      "chance": 100,
      "items": [
        {
          "type": "NETHER_STAR",
          "chance": 100,
          "min": 0,
          "max": 2,
          "looting": true
        }
      ]
    },
    {
      "upgrade": "obsidian",
      "chance": 100,
      "items": [
        {
          "type": "ZOMBIE_HEAD",
          "chance": 1,
          "min": 1,
          "max": 1
        }
      ]
    }
  ]
}

**Comment by OmerBenGera** [comment]
https://wiki.bg-software.com/wildstacker/overview/spawners-stacker/spawner-upgrades#custom-drops

This should work.

**Comment by Saadi43** [comment]
Yeah it fixed is there any way if possible so player need for eg like
spawner.upgrade.zombie.1
1 is upgrade
And also chunk limit permissions like
Spawner.place.chunk.100

**Comment by OmerBenGera** [comment]
I don't understand

**Comment by Saadi43** [comment]
Like there is a chunk limit for mob spawners right is there a way to
upgrade for one person by permissions so the player with perm
spawner.play.chunk.100
Can place more in a single chunk

And also there are spawners upgrades is there a way to make it so people
need permission to upgrade the Spawners

**Comment by OmerBenGera** [comment]
I am not gonna add such thing for now
You can make a feature request by looking at the discussions tab.

I am closing this for now :)
