### ISSUE TITLE
Random Wildstacker Error

### ISSUE THREAD

**Issue by DJDanTheMan** [BG-Software-LLC/WildStacker#895]
### Minecraft's Version

1.20.1 and  Paper-196

### Plugin's Version

WildStacker-2023.3-b36

### Describe the bug

 I randomly see this message in the console https://pastebin.com/Nv75xe7n

### To Reproduce

Not sure how to reduce it just randomly happened

**Comment by OmerBenGera** [comment]
Your server crashed because it lagged out
Run timings report and find out what causes your server to hang.
