### ISSUE TITLE
EconomyShopGUI error on startup

### ISSUE THREAD

**Issue by RedbrickCobra66** [BG-Software-LLC/WildStacker#896]
### Minecraft's Version

1.20.4

### Plugin's Version

latest stable build

### Describe the bug

on server start up it throws these errors in console 

[Server] [INFO] [EconomyShopGUI] [[INFO]]: WildStacker found, integrating...
29.02 23:24:39 [Server] [ERROR] Error occurred while enabling EconomyShopGUI v6.4.2 (Is it up to date?)
29.02 23:24:39 [Server] [INFO] java.lang.NoClassDefFoundError: com/bgsoftware/wildstacker/api/WildStackerAPI
29.02 23:24:39 [Server] [INFO] at me.gypopo.economyshopgui.providers.SpawnerManager.setup(SpawnerManager.java:71) ~[EconomyShopGUI-6.4.2.jar:?]
29.02 23:24:39 [Server] [INFO] at me.gypopo.economyshopgui.providers.SpawnerManager.setup(SpawnerManager.java:115) ~[EconomyShopGUI-6.4.2.jar:?]
29.02 23:24:39 [Server] [INFO] at me.gypopo.economyshopgui.providers.SpawnerManager.init(SpawnerManager.java:44) ~[EconomyShopGUI-6.4.2.jar:?]
29.02 23:24:39 [Server] [INFO] at me.gypopo.economyshopgui.EconomyShopGUI.onEnable(EconomyShopGUI.java:183) ~[EconomyShopGUI-6.4.2.jar:?]
29.02 23:24:39 [Server] [INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
29.02 23:24:39 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
29.02 23:24:39 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
29.02 23:24:39 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: com.bgsoftware.wildstacker.api.WildStackerAPI
29.02 23:24:39 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.4.jar:git-Paper-"e9e0bc1"]
29.02 23:24:39 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
29.02 23:24:39 [Server] [INFO] ... 16 more
29.02 23:24:39 [Server] [INFO] [EconomyShopGUI] Disabling EconomyShopGUI v6.4.2

### To Reproduce

putting the plugin on the server and restarting it

### Additional Information

none

**Comment by OmerBenGera** [comment]
Contact them for support, nothing to do regarding WildStacker.
