### ISSUE TITLE
Could not pass event SpawnerSpawnEvent to WildStacker

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#899]
### Minecraft's Version

Pufferfish version git-Pufferfish-46 (MC: 1.20.4)

### Plugin's Version

WildStacker v2023.3-b40

### Describe the bug

when I updated the server to version 1.20.4, these errors started in the console:

https://mclo.gs/LxYTQvE

### To Reproduce

use minecraft version 1.20.4 and the latest version of wildstacker.

### Additional Information

i just updated the minecraft jar to 1.20.4, and the wildstacker jar and these errors started.

**Comment by OmerBenGera** [comment]
Seems like a bug with Pufferfish tbh
Does it work if you try it on Paper?

**Comment by SrMonsterYT** [comment]
> Seems like a bug with Pufferfish tbh Does it work if you try it on Paper?

I haven't tested it, but all my plugins work normally with pufferfish, it's a fork of paper

**Comment by OmerBenGera** [comment]
Test it on Paper, check if it still occurs.

**Comment by OmerBenGera** [comment]
> > Update Pufferfish, check if it still occurs. If it does, then try it on Paper.
> > For no reason it doesn't let WildStacker to spawn a Guardian
> 
> https://mclo.gs/5jI65UC I don't want to switch to paper, pufferfish is better for me, and I have 113 plugins on my server and none of them have a problem with pufferfish, only wildstacker, is there any way to ignore guardian? so as not to generate these errors?

None of your other plugins spawn guardians.
You can either use Paper or contact Pufferfish for support.

This is not related to WildStacker, and therefore I am closing this report.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by SrMonsterYT** [comment]
> Check out latest dev build, let me know if it is fixed

this update solved the error and it also seems that the wildstacker was what was generating the memory leak on my server, I'll confirm this today and let you know here, but the error has been corrected, just don't report it as completed so I can confirm that the memory leak has also been corrected.

**Comment by OmerBenGera** [comment]
There is another report for the memory leak, update me in there
Closing this for now
