### ISSUE TITLE
Spawners becoming pig on chunk load

### ISSUE THREAD

**Issue by Rockin21** [BG-Software-LLC/WildStacker#904]
### Minecraft's Version

This server is running Pufferfish+ version git-PufferfishPlus-"a9f972b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a9f972b on HEAD)

### Plugin's Version

2023.3.b34 (latest production build)

### Describe the bug

Spawners change to pig at random when a player leaves a chunk and returns, and or logs off and logs back in. The spawners in question are NOT modified by another plugin. There is no difference in the age of the spawners, meaning it isnt just newer placed spawners converting. Some players have spawners that have been placed over a **year** that have not been touched at all suddenly turn to pig.

Spawners do not change in to pig when placed. **Only upon entering a chunk**

### To Reproduce

Place a spawner, leave the chunk and come back, or relog.

**Comment by OmerBenGera** [comment]
Check it on latest dev build, let me know if it still occurs.

**Comment by Rockin21** [comment]
Running the latest dev now, will let you know how it goes

**Comment by Rockin21** [comment]
This is no longer happened on the latest dev build.

**Comment by OmerBenGera** [comment]
Interesting.
If the issue occurs again, let me know. For now, I am closing this as it seems to be fixed.
