### ISSUE TITLE
Wrong amount of mobs spawned

### ISSUE THREAD

**Issue by RVSkeLe** [BG-Software-LLC/WildStacker#905]
### Minecraft's Version

purpur 1.16.5

### Plugin's Version

2023.3

### Describe the bug

The amount of mobs spawned are somehow different than the original spawner amount. The amount is pretty random, for example I tried with a x10 spawner and the amount of mobs spawned ranged from 1 to sometimes even 21.
The bug still exists for unstacked entities. The issue still happens when wildstacker is the only plugin installed.

### To Reproduce

Take a stacked spawner with amount >1, you'll see the amount ranging from the original stacked spawner value.

**Comment by RVSkeLe** [comment]
UPDATE: I set listen-paper-pre-spawn-event to false and it fixed the issue, but I think that the cost is performance in spawners

**Comment by OmerBenGera** [comment]
A x10 spawner can spawn between 1 to 40 mobs, depends on the spawn count of the spawner.
I don't see an issue in here to be honest.

**Comment by RVSkeLe** [comment]
> A x10 spawner can spawn between 1 to 40 mobs, depends on the spawn count of the spawner. I don't see an issue in here to be honest.

Sorry but I'm quite ignorant on this topic, could you explain to me what the spawn count is and how do i change it?

**Comment by OmerBenGera** [comment]
> > A x10 spawner can spawn between 1 to 40 mobs, depends on the spawn count of the spawner. I don't see an issue in here to be honest.
> 
> Sorry but I'm quite ignorant on this topic, could you explain to me what the spawn count is and how do i change it?

spawn-count is a vanilla nbt data of spawners that tells how many mobs a spawner may spawn. By default, it is set to 4. Therefore, a spawner may spawn between 0 and 4 mobs per spawning cycle. If no mobs were spawned, it tries to spawn mobs again. If you have a x10 stacked spawner, it will attempt to spawn between 0 and 40 mobs. If no mobs were spawned, it tries to spawn mobs again - similar to vanilla. Using the spawner upgrades, you can edit the default spawn count of spawners to another value.

**Comment by OmerBenGera** [comment]
If anything else pops up, make sure you open a new issue
