### ISSUE TITLE
Donkey/Mule chest dupe

### ISSUE THREAD

**Issue by alek4032** [BG-Software-LLC/WildStacker#907]
### Minecraft's Version

Pufferfish+ version git-PufferfishPlus-"a9f972b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a9f972b on HEAD)

### Plugin's Version

WildStacker-2023.3-b45 (Latest dev build as of today)

### Describe the bug

If you breed stacked donkeys/mules with a chest attached and items inside of them, the items duplicate. Tested with both smart breeding on/off and it happens for them both.

### To Reproduce

Step 1: Get x2 or above stacked donkeys/mules from spawner or natural.
Step 2: Place saddle and chest onto it.
Step 3: Breed it with another 2 or above stack of donkey/mules.
Step 4: You have now successfully duped the donkey/mule with the chest, and the items inside also duped.

### Additional Information

Here's a video showing how to replicate the dupe: https://youtu.be/jON26XXYglI

Here's our config if its needed: https://pastebin.com/Ha11qefX

I tested this dupe on a completely empty server with only the following plugins installed: Wildstacker, Plugman, Viaversion and Essentials

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by alek4032** [comment]
> Check out latest dev build, let me know if it is fixed

Hey, can confirm that it no longer dupes. Awesome. Thank you!
