### ISSUE TITLE
Kill-Task causes the deleted mobs to be seen as killed by the player.

### ISSUE THREAD

**Issue by pykew** [BG-Software-LLC/WildStacker#908]
### Minecraft's Version

LightSpigot 1.20.1 
(still happens on regular paper)

### Plugin's Version

2023.3-b45

### Describe the bug

If you kill mobs exactly before the kill task running, you get credited "for killing all the deleted mobs". (It doesn't happen 100% of the times)

### To Reproduce

Kill mobs before a kill task will run (10 seconds in advance)
- https://www.youtube.com/watch?v=44fy_syNLMg

### Additional Information

On the main server I am using a plugin that brings back the 1.8 pvp system (DeluxeCombat), but I tested the same thing in localhost without any special plugins (only wildstacker, essx, and jobsreborn) and it still happens.

**Comment by OmerBenGera** [comment]
The kill task removes entities from the world, and it does not kill them.
How do you see that you get credit for killing them?

(P.S - the video is private)

**Comment by pykew** [comment]
Hello!

Oops, the video **is now public**. Almost (if not all) every plugin that rewards for killing a mob (ex. JobsReborn with the hunter job, or any MobCoins plugin) will give a huge amount of rewards, equivalent to the amount of mobs despawned by the kill task.

**Comment by OmerBenGera** [comment]
Contact the other plugins regarding this.
WildStacker removes the entities from the world by using Entity#remove. If they register is as a "kill", it's their fault.

**Comment by OmerBenGera** [comment]
I am closing this as it doesn't seem like a bug of WildStacker
