### ISSUE TITLE
Stacked Mobs glitching when killing one

### ISSUE THREAD

**Issue by MidasCraftMC** [BG-Software-LLC/WildStacker#914]
### Minecraft's Version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version

### Plugin's Version

Version 2023.3-b50

### Describe the bug

https://i.imgur.com/GJ0WlSr.png

When killing one mob in a stack, it glitches like this for the rest of them

### To Reproduce

Use the config added and just kill a stacked mob

### Additional Information

config: https://mclo.gs/owC4ZP2

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
