### ISSUE TITLE
Stacked spawners don't spawn well

### ISSUE THREAD

**Issue by Fredh1000** [BG-Software-LLC/WildStacker#916]
### Minecraft's Version

WineSpigot 1.8.8

### Plugin's Version

WildStacker-2024.1

### Describe the bug

When I place stacked spawners, they will not spawn mobs correctly.

### To Reproduce

You have to place stacked spawners and they will not spawn mobs correctly.

### Additional Information

Here are some videos where I show a version of WildStacker that works correctly and then the latest one:

Video 1 (WildStacker-2024.1 with the problem described): https://www.youtube.com/watch?v=uoEgjvoblyE
Video 2 (WildStacker-2023.3-b22 without any problems): https://www.youtube.com/watch?v=q4RfvD9Ysbo

**Comment by OmerBenGera** [comment]
The videos are private.

**Comment by Fredh1000** [comment]
Ops, now the videos should work.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Fredh1000** [comment]
Now it works without any problems, thanks for the support!
