### ISSUE TITLE
Depot invalid

### ISSUE THREAD

**Issue by KendaFR** [BG-Software-LLC/WildStacker#917]
### Minecraft's Version

1.8

### Plugin's Version

1.8

### Describe the bug

Unresolved dependency: 'com.bgsoftware:WildStackerAPI:jar:latest'

### To Reproduce

I have created a plugin, but api is not valid

**Comment by OmerBenGera** [comment]
Use
`implementation 'com.bgsoftware:WildStackerAPI:2024.1'`
