### ISSUE TITLE
Lead duplication glitch

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BG-Software-LLC/WildStacker#924]
### Minecraft's Version

```
25.06 23:40:20 [Server] INFO Checking version, please wait...
25.06 23:40:20 [Server] INFO Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
25.06 23:40:20 [Server] INFO * You are running the latest version
25.06 23:40:20 [Server] INFO Previous: git-Purpur-2152 (MC: 1.20.4)
```

### Plugin's Version

2024.1-b62

### Describe the bug

When you tie stacked mob with lead to fence, every time you kill it new lead appears

### To Reproduce

1. Get stacked animal
2. Tie it to the fence
3. Kill the animal
4. Every time animal gets killed it drops new lead

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
