### ISSUE TITLE
Upgraded Spawner mobs not stacking due to custom name

### ISSUE THREAD

**Issue by deadspidervenom** [BG-Software-LLC/WildStacker#925]
### Minecraft's Version

1.20.6

### Plugin's Version

DEV #62

### Describe the bug

If the stacking check "NAME_TAG" is set to true, mobs spawned from a upgraded spawner will not stack.

![image](https://github.com/BG-Software-LLC/WildStacker/assets/12871122/ca4e59a2-2690-425e-af50-f3d471f1ca0e)

### To Reproduce

Edit and update config so that spawner upgrades are usable on all mobs
Go in game and place a valid spawner
Upgrade until a valid version

**Comment by deadspidervenom** [comment]
Small update

If the option is set to false. While mobs will stack, they will not update the display to match the current stack amount.

Below picture is of a spawner that is capable of spawning rapidly a large amount of mobs. This stack should be 200+ right now but is only displaying as 1.
![image](https://github.com/BG-Software-LLC/WildStacker/assets/12871122/f60b1cc7-6cdd-4c93-bd84-48e317f663e4)

**Comment by deadspidervenom** [comment]
Its also not considering the stack a valid stack via commands.
![image](https://github.com/BG-Software-LLC/WildStacker/assets/12871122/d6f88a79-cad5-4d3e-ba2f-844aebf8226a)

**Comment by OmerBenGera** [comment]
I supect you have another plugin causing this to occur, as I cannot replicate it myself.
Try replicating it on a server with only WildStacker installed.

**Comment by deadspidervenom** [comment]
> I supect you have another plugin causing this to occur, as I cannot replicate it myself. Try replicating it on a server with only WildStacker installed.

![image](https://github.com/BG-Software-LLC/WildStacker/assets/12871122/3cd3f551-f79b-4c65-be62-1e5515c68234)

These are the only plugins installed, the bare minimum to upgrade of the plugins on my server and worldedit to quickly change blocks to enable/disable the spawner.

**Comment by deadspidervenom** [comment]
![image](https://github.com/BG-Software-LLC/WildStacker/assets/12871122/9f6d4ef9-41fe-4c16-b127-85e7dabbc251)
Only essentials vault and wildstacker installed.

**Comment by deadspidervenom** [comment]
Grabbed the NBT of the ones not stacking and the stacking one

Stacking one
`x844 Zombie (Diamond+++) has the following entity data: {Paper.SpawnReason: "SPAWNER", DeathTime: 0s, BukkitValues: {"wildstacker:stackamount": 692, "wildstacker:spawncause": "SPAWNER", "wildstacker:upgrade": 7}, Bukkit.updateLevel: 2, LeftHanded: 0b, OnGround: 1b, AbsorptionAmount: 0.0f, IsBaby: 0b, Attributes: [{Name: "minecraft:generic.knockback_resistance", Modifiers: [{Name: "Random spawn bonus", Amount: 0.0011183010579956271d, Operation: 0, UUID: [I; -1654213372, -1753528872, -1784240995, -1831000807]}], Base: 0.0d}, {Name: "minecraft:generic.follow_range", Modifiers: [{Name: "Random spawn bonus", Amount: -0.016863007474344428d, Operation: 1, UUID: [I; -189579114, 705318706, -1653431202, 1308715476]}], Base: 35.0d}, {Name: "minecraft:zombie.spawn_reinforcements", Base: 0.0392354037680652d}, {Name: "minecraft:generic.movement_speed", Base: 0.23000000417232513d}, {Name: "minecraft:generic.max_health", Base: 20.0d}], Invulnerable: 0b, Brain: {memories: {}}, Paper.Origin: [9.396631340779717d, 36.0d, -32.88378673581996d], Bukkit.Aware: 1b, CustomNameVisible: 1b, HandDropChances: [0.085f, 0.085f], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Rotation: [134.90851f, 0.0f], HurtByTimestamp: 0, CanBreakDoors: 0b, WorldUUIDMost: -7368508025070923999L, CustomName: '{"text":"","extra":[{"text":"x844 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Zombie","italic":true,"color":"white"},{"text":" (","italic":false,"color":"gray"},{"text":"Diamond","italic":false,"color":"aqua"},{"text":"+++","italic":false,"color":"blue"},{"text":")","italic":false,"color":"gray"}]}', InWaterTime: -1, ArmorItems: [{}, {}, {}, {}], HandItems: [{}, {}], Air: 300s, UUID: [I; 719282384, 540689596, -1825948020, 638179129], Spigot.ticksLived: 1947, Paper.OriginWorld: [I; -1715614467, -1056420063, -1904705186, 2091869668], DrownedConversionTime: -1, FallDistance: 0.0f, WorldUUIDLeast: -8180646480299727388L, Motion: [0.0d, -0.0784000015258789d, 0.0d], Pos: [-6.412596132402131d, 36.0d, -39.272367600175706d], Fire: -1s, CanPickUpLoot: 0b, Health: 20.0f, HurtTime: 0s, FallFlying: 0b, PersistenceRequired: 0b, PortalCooldown: 0, Paper.ShouldBurnInDay: 1b}`

Non-stacking
`x1 Zombie (Diamond+++) has the following entity data: {Paper.SpawnReason: "SPAWNER", DeathTime: 0s, BukkitValues: {"wildstacker:stackamount": 1, "wildstacker:spawncause": "SPAWNER", "wildstacker:upgrade": 7, "wildstacker:nametag": 1b}, Bukkit.updateLevel: 2, LeftHanded: 0b, OnGround: 1b, AbsorptionAmount: 0.0f, IsBaby: 0b, Attributes: [{Name: "minecraft:generic.armor", Base: 2.0d}, {Name: "minecraft:generic.knockback_resistance", Modifiers: [{Name: "Random spawn bonus", Amount: 0.02091583898223611d, Operation: 0, UUID: [I; 733178169, 293817037, -1940176814, 220924314]}], Base: 0.0d}, {Name: "minecraft:generic.follow_range", Modifiers: [{Name: "Random spawn bonus", Amount: -0.027900433581691926d, Operation: 1, UUID: [I; 551328030, -1231532674, -1722512206, -1971461296]}], Base: 35.0d}, {Name: "minecraft:zombie.spawn_reinforcements", Base: 0.004188712392030919d}, {Name: "minecraft:generic.movement_speed", Base: 0.23000000417232513d}, {Name: "minecraft:generic.max_health", Base: 20.0d}, {Name: "minecraft:generic.armor_toughness", Base: 0.0d}], Invulnerable: 0b, Brain: {memories: {}}, Paper.Origin: [6.8516563943706d, 38.0d, -37.68201428358967d], Bukkit.Aware: 1b, CustomNameVisible: 1b, HandDropChances: [0.085f, 0.085f], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Rotation: [192.53427f, 0.0f], HurtByTimestamp: 0, CanBreakDoors: 0b, WorldUUIDMost: -7368508025070923999L, CustomName: '{"text":"","extra":[{"text":"x1 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Zombie","italic":true,"color":"white"},{"text":" (","italic":false,"color":"gray"},{"text":"Diamond","italic":false,"color":"aqua"},{"text":"+++","italic":false,"color":"blue"},{"text":")","italic":false,"color":"gray"}]}', InWaterTime: -1, ArmorItems: [{id: "minecraft:chainmail_boots", count: 1}, {id: "minecraft:chainmail_leggings", count: 1}, {}, {}], HandItems: [{}, {}], Air: 300s, UUID: [I; -446906807, 1965443940, -1977373314, -788604427], Spigot.ticksLived: 3465, Paper.OriginWorld: [I; -1715614467, -1056420063, -1904705186, 2091869668], DrownedConversionTime: -1, FallDistance: 0.0f, WorldUUIDLeast: -8180646480299727388L, Motion: [0.016812905291966492d, -0.0784000015258789d, -0.05923492608132947d], Pos: [8.29190685118579d, 36.0d, -26.533983711061573d], Fire: -1s, CanPickUpLoot: 0b, Health: 20.0f, HurtTime: 0s, FallFlying: 0b, PersistenceRequired: 0b, PortalCooldown: 0, Paper.ShouldBurnInDay: 1b}`

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it still occurs.
(Try it on new mobs, not the old ones that were not stacked)

**Comment by deadspidervenom** [comment]
> Use latest dev build, let me know if it still occurs. (Try it on new mobs, not the old ones that were not stacked)

Alright, ill check this after i wake tomorrow.

**Comment by deadspidervenom** [comment]
> Use latest dev build, let me know if it still occurs. (Try it on new mobs, not the old ones that were not stacked)

seems to be fixed, even with all my plugins installed.

![image](https://github.com/BG-Software-LLC/WildStacker/assets/12871122/4a9976b6-f6c1-4f37-945c-caafd88fd9aa)

Out of curiosity, what was the actual cause. I am not to familiar with plugin creation.

**Comment by deadspidervenom** [comment]
So i was curious, could this be an issue with a paper server type? As i noticed in the "/plugins" command this plugin is marked as "Bukkit".

After some testing, things i've noticed.

• Once a stackable mob spawns non-stacking mobs stop spawning.
• If an unstackable mob spawns it usually spawns more than 1 mob based on the spawn count of the upgraded spawner with only exception being if a stackable mob spawns with it than its 1-4 unstackable and 1 stackable
• Stackable mobs tend to be the only spawn for that spawn with the sole exception of previously mentioned spawning
• All unstackable mobs are unkillable with with your kill command

**Comment by OmerBenGera** [comment]
Please upload your entire config file to pastebin and send a link to it here

**Comment by deadspidervenom** [comment]
[config.txt](https://github.com/user-attachments/files/16114285/config.txt)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by deadspidervenom** [comment]
> Check out latest dev build, let me know if it is fixed

sorry for the late reply, got your response soon after i got internet back and need time to catch up on stuff. I've tested it and it seems to have been fixed.

May i ask what the cause was?

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it is fixed
> 
> sorry for the late reply, got your response soon after i got internet back and need time to catch up on stuff. I've tested it and it seems to have been fixed.
> 
> May i ask what the cause was?

Upgraded mobs were considered to have custom names (using a nametag), therefore they were not stacked together.
