### ISSUE TITLE
[BUG] Spawn Reason not recognizing TRIAL_SPAWNER

### ISSUE THREAD

**Issue by OreoKirby** [BG-Software-LLC/WildStacker#929]
### Minecraft's Version

Paper version 1.21-40-master@b45d9b6

### Plugin's Version

WildStacker-2024.1-b64

### Describe the bug

When a mob is spawned by a Trial Spawner the SpawnReason has a value of CHUNK_GEN or DEFAULT instead of TRIAL_SPAWNER.

![Screen Shot 2024-07-03 at 2 56 39 PM](https://github.com/BG-Software-LLC/WildStacker/assets/1530615/77754b39-6ede-4147-93c7-af483fa7b35f)

### To Reproduce

1. Obtain a Trial Spawner item in Creative Mode.
2. Obtain a Zombie Spawn Egg item in Creative Mode.
3. Place the Trial Spawner.
4. Right-Click the Trial Spawner with the Zombie Spawn Egg.
5. Set game mode to Survival.
6. Execute the "/stacker inspect PLAYERNAME 1" command to get an Inspect Tool.
7. Wait for a Zombie Mob to spawn via the Trial Spawner.
8. Right-Click the spawned Zombie with the Inspect Tool.
9. Check the Spawn Reason: VALUE

### Additional Information

With the addition of Trial structures in 1.21; the above issue poses a deterrent for using both "auto-stacking" and kill-task". Mobs being spawned by Trial Spawners can not be blacklisted with the `TRIAL_SPAWNER` SpawnReason and are stacking/being removed during a Trial event. This significantly effects players experiencing or farming trials for rewards.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
> Updated plugin to 2024.1-b66:
> 
> "Spawn Reason" is still showing a value of DEFAULT. I thought maybe there was a potential it would have been from a manually placed Trial Spawner, but using the /locate command and trying a naturally generated one yielded the same result.

In Paper, the TRIAL_SPAWNER does not exist - only in Spigot afaik
Maybe an updated version of Paper has this fixed.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
