### ISSUE TITLE
[BUG] Infinate Item Dupe

### ISSUE THREAD

**Issue by P376EM2** [BG-Software-LLC/WildStacker#930]
### Minecraft's Version

This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker-2024.1-b64.jar

### Describe the bug

When using a hopper minecraft to pull stacked enteties through a block to place in a chest on another hopper it puills the item but doesnt decrease the stack size shown and still keeps pulling the items resulting in a infinite amount

### To Reproduce

Place A Hopper With A Rail On Top Then a Hopper Minecart with a block above that and then put a stacked set of items on the block

### Additional Information

https://pastebin.com/dEknGLyC
![image](https://github.com/BG-Software-LLC/WildStacker/assets/25124064/05e492a1-c9fb-4d24-b9cf-b1f33181a2a3)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
