### ISSUE TITLE
Spawners turn into pigs

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#933]
### Minecraft's Version

Paper version 1.21-46-master@2fa5e0e (2024-07-06T21:32:48Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker-2024.1-b66

### Describe the bug

When placing down the spawners, they are the correct type, but it says "Pig" above them in the hologram and once you mine the spawners, they turn into pig spawners.

Video: https://medal.tv/games/minecraft/clips/idPaTc8G6eveOTRQx/d1337gcrb45n?invite=cr-MSw2ZnAsNzM1MDU0Myw

This error also shows up on server start: https://pastebin.com/GgnWP1EK

This is a fresh installation of the plugin so there is no old configs or such doing stuff.

### To Reproduce

Try the plugin on Paper 1.21.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Sckaletz** [comment]
It fixed the problem. Thanks.
