### ISSUE TITLE
Fire aspect not working on mobs

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#935]
### Minecraft's Version

Paper version 1.21-62-master@5a503d7 (2024-07-12T18:53:26Z)

### Plugin's Version

WildStacker-2024.1-b71

### Describe the bug

When stacked mobs are killed with a sword with fire aspect, they don't drop cooked food. Ex. cows drop regular beef.

This is what my looting table looks like for cows. It's the same issue with other mobs. In this example it's set as "burnable", but it has no effect.

    {
      "chance": 100,
      "items": [
        {
          "type": "BEEF",
          "chance": 100,
          "min": 1,
          "max": 3,
          "looting": true,
          "burnable": {
            "type": "COOKED_BEEF"
          }
        }
      ]
    },

### To Reproduce

Try to kill a stack of cows or other mobs with fire aspect on the sword.

**Comment by Spaex** [comment]
Same Issue here

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Spaex** [comment]
Fixed it. Thank you very much Omer for your work!:)
