### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by patrikkoudelka** [BG-Software-LLC/WildStacker#937]
### Minecraft's Version

1.21 Purpur
[17:41:56 INFO]: Current Purpur Version: 1.21-2262-458dc18 (MC: 1.21)*
* You are 1 version(s) behind

### Plugin's Version

Newest dev build, 71

### Describe the bug

Plugin is not enabled

### To Reproduce

-----

### Additional Information

Log here: https://pastebin.com/rfyG1ziJ

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Koudyasek** [comment]
Better, thank you!
