### ISSUE TITLE
Stacks disappearing when chunk unload

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/WildStacker#94]
Hey, I already wrote this on discord wildstacker support channel but no one could answer:

Mobs amount "stacks" are disappearing after chunk unload.

It wasn't happening with old versions, I only had superiorskyblock, essentials and wildstacker installed. With wildstacker older version wasn't happening, so it's a wildstacker issue on latest devs.

Working fine with wildstacker-3.0.1: https://i.gyazo.com/7d72cb48bb396497eda95f4ad20a9920.mp4
Not working with latest version of wildstacker "jenkins one": https://gyazo.com/e512db1c3f2e9860138a2f7f96c9e490

Same plugins on both versions, 1.8.8 paper

**Comment by OmerBenGera** [comment]
Next time open an issue using the format, not sure why you skipped it.

Anyways, I'll check that out, might be because you have a plugin that removes effects from entities.
What version of Paper are you using exactly?

**Comment by ArefyNetwork** [comment]
> Next time open an issue using the format, not sure why you skipped it.
> 
> Anyways, I'll check that out, might be because you have a plugin that removes effects from entities.
> What version of Paper are you using exactly?

Hey, sorry for not following the format, didn't see that. I only have essentials, worldguard, worldedit and wildstacker/superiorskyblock on both gifs, so it can't be other plugin.

For the paper, I'm using paper 1.8.8

Thanks again, I'm xNekio#9001 from discord, if you need more proof just pm me!

**Comment by OmerBenGera** [comment]
I tried to replicate the issue, and couldn't do that. The entity stack sizes were saved as they should.
Using git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by ArefyNetwork** [comment]
Still happening with git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT) 

Try using clearlag to unload chunks immediately with /lagg unloadchunks "with any plugin, without clearlag doesn't work too, but you have to wait like 5 minutes to get that chunk unloaded"

https://gyazo.com/beddeb2cbec1affc23b82af858e8cb49

**Comment by OmerBenGera** [comment]
I just closed the server to get the server to unload the chunks.
Also, it takes no time to get the chunk unloaded, not sure from where you got the 5 minute as the time to unload chunks

**Comment by ArefyNetwork** [comment]
If you close the server, mobs are saved on wildstacker database I guess, so they won't remove, try with /lagg unloadchunks as I said, go to spawn or to another location and then run /lagg unloadchunks and go back where the mob was (like I did on the gif). It's happening without clearlagg too so isn't a clearlagg issue

**Comment by OmerBenGera** [comment]
Maybe the clearlag command somehow doesnt call the ChunkUnloadEvent? Data of entities is saved when chunks are unloaded, no matter if the server is closed or not.

**Comment by ArefyNetwork** [comment]
You can clearly see here without any plugin "even without clearlag", after waiting 5 minutes cows are removed: https://www.youtube.com/watch?v=wzZHh1V1kFc

**Comment by OmerBenGera** [comment]
> 
> 
> You can clearly see here without any plugin "even without clearlag", after waiting 5 minutes cows are removed: https://www.youtube.com/watch?v=wzZHh1V1kFc hopes this video show it better

Ah my bad, I missed the part that clearlagg isn't the issue.
I will make more debugging and see why it occurs.
Just so you know, the entities data is saved as custom effects on entities, maybe it gives you an idea what can cause it 0.0

**Comment by ArefyNetwork** [comment]
> > You can clearly see here without any plugin "even without clearlag", after waiting 5 minutes cows are removed: https://www.youtube.com/watch?v=wzZHh1V1kFc hopes this video show it better
> 
> Ah my bad, I missed the part that clearlagg isn't the issue.
> I will make more debugging and see why it occurs.
> Just so you know, the entities data is saved as custom effects on entities, maybe it gives you an idea what can cause it 0.0

Thanks, hope you see where is the issue :)

And I can't have an idea of why it could occur because I tested it with 0 plugins and still happening :S so it should be wildstacker issue as it was working properly in the older version like I said "wildstacker-3.0.1: https://i.gyazo.com/7d72cb48bb396497eda95f4ad20a9920.mp4"

**Comment by OmerBenGera** [comment]
> 
> 
> > > You can clearly see here without any plugin "even without clearlag", after waiting 5 minutes cows are removed: https://www.youtube.com/watch?v=wzZHh1V1kFc hopes this video show it better
> > 
> > 
> > Ah my bad, I missed the part that clearlagg isn't the issue.
> > I will make more debugging and see why it occurs.
> > Just so you know, the entities data is saved as custom effects on entities, maybe it gives you an idea what can cause it 0.0
> 
> Thanks, hope you see where is the issue :)
> 
> And I can't have an idea of why it could occur because I tested it with 0 plugins and still happening :S so it should be wildstacker issue as it was working properly in the older version like I said "wildstacker-3.0.1: https://i.gyazo.com/7d72cb48bb396497eda95f4ad20a9920.mp4"

Older versions of WildStacker don't matter. The way data of entities were changed a couple of time due to other issues with the old way (the db got really large at some point due to unused data)

**Comment by ArefyNetwork** [comment]
Oh so it should be an issue of the actual save system no? As wasn't happening before with old versions

**Comment by OmerBenGera** [comment]
> 
> 
> Oh so it should be an issue of the actual save system no? As wasn't happening before with old versions

Yeah, maybe. The issue is that the effects aren't saved at the first place, or they aren't loaded. One of them causing the data of entities to get removed - when I success to replicate it, I can start working on fixing it

**Comment by ArefyNetwork** [comment]
> > Oh so it should be an issue of the actual save system no? As wasn't happening before with old versions
> 
> Yeah, maybe. The issue is that the effects aren't saved at the first place, or they aren't loaded. One of them causing the data of entities to get removed - when I success to replicate it, I can start working on fixing it

Perfect, would recommend you using /lagg unloadchunks as I said to unload chunks faster, just go to spawn and then go back to where mob stacked was, repeat it if doesn't work on the first time :)

**Comment by OmerBenGera** [comment]
> 
> 
> > > Oh so it should be an issue of the actual save system no? As wasn't happening before with old versions
> > 
> > 
> > Yeah, maybe. The issue is that the effects aren't saved at the first place, or they aren't loaded. One of them causing the data of entities to get removed - when I success to replicate it, I can start working on fixing it
> 
> Perfect, would recommend you using /lagg unloadchunks as I said to unload chunks faster, just go to spawn and then go back to where mob stacked was, repeat it if doesn't work on the first time :)

Wait, sometimes it works well but sometimes it doesn't?

**Comment by ArefyNetwork** [comment]
> > > > Oh so it should be an issue of the actual save system no? As wasn't happening before with old versions
> > > 
> > > 
> > > Yeah, maybe. The issue is that the effects aren't saved at the first place, or they aren't loaded. One of them causing the data of entities to get removed - when I success to replicate it, I can start working on fixing it
> > 
> > 
> > Perfect, would recommend you using /lagg unloadchunks as I said to unload chunks faster, just go to spawn and then go back to where mob stacked was, repeat it if doesn't work on the first time :)
> 
> Wait, sometimes it works well but sometimes it doesn't?

Yeah, if you aren't using clearlagg to unload chunks, it's harder to replicate it, if you leave the chunk it doesn't disappear, you've to wait maybe 5 minutes on another location and then go back, sometimes stack disappear in 2 minutes.. depending

**Comment by OmerBenGera** [comment]
Not sure what I am doing wrong, but it still works for me.
I used ClearLag this time and it works as well.

1. I teleported to 1000, 1000
2. Spawned a cow with a stack size of 50 there
3. Teleported to 0, 0
4. Used /lagg unloadchunks
5. Teleported back to 1000, 1000

**Comment by ArefyNetwork** [comment]
Try spawning them from a spawner instead of eggs: 

For me I'm still having the issue: https://gyazo.com/e27db83e47f55a98d9cb1782d0ca4b59

**Comment by OmerBenGera** [comment]
> 
> 
> Try spawning them from a spawner instead of eggs:
> 
> For me I'm still having the issue: https://gyazo.com/e27db83e47f55a98d9cb1782d0ca4b59

Show me your config

**Comment by ArefyNetwork** [comment]
Sure, https://pastebin.com/uvQY0Fyy

**Comment by OmerBenGera** [comment]
Still works fine for me.

**Comment by ArefyNetwork** [comment]
You did what I tell you? That's weird

1. Set home with /sethome
2. Place a spawner, wait until this stack cows like ~200 cows
3. Go to /spawn
4. Use /lagg unloadchunks
5. Use /home to go where the spawner/cows were
6. Now there should be only 1 cow
7. Repeat the process if you still seeing ~200 cows

**Comment by OmerBenGera** [comment]
Yeah, that's what I did. Weird.
Were you able to replicate the issue on another server with fresh config files and everything?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ArefyNetwork** [comment]
Hey sorry, didn't see github. Yeah it's still happening, when chunk is unloaded, stack amount is removed too, and when you load it again you'll only see one mob.

**Comment by OmerBenGera** [comment]
> Hey sorry, didn't see github. Yeah it's still happening, when chunk is unloaded, stack amount is removed too, and when you load it again you'll only see one mob.

I cant replicate it.
Open a new issue using the appropriate format and correct the information in the report.
