### ISSUE TITLE
spawner-override/spawn=condations is not working

### ISSUE THREAD

**Issue by AlFr3on111** [BG-Software-LLC/WildStacker#941]
### Minecraft's Version

1.20.6 purpur-2233
i use last dev build wildstacker

### Plugin's Version

last dev build wildstacker 2024.1-b71

### Describe the bug

i want make all entities spawn in all condations but its not working (it was working in old versions)
after updating to minecraft 1.20.6 purpur and last dev build of wildstacke, this feature is not working

here pic of my config and there's no errors in console
![image](https://github.com/user-attachments/assets/e9943c44-2e68-4b90-9a3a-de6c39c49e23)

### To Reproduce

do the same config or follow the wiki
it will not work at all

### Additional Information

i tested the plugin on new server to see if there's another plugin override it but no its not!

**Comment by OmerBenGera** [comment]
The `ALL` value in `spawn-conditions` was never supported.
Maybe will be added in the future. For now, just use all the individual entity types.
