### ISSUE TITLE
CUSTOM ITEMS NOT WORKING

### ISSUE THREAD

**Issue by mikeyies** [BG-Software-LLC/WildStacker#945]
### Minecraft's Version

1.20.4 paper

### Plugin's Version

latest spigot version

### Describe the bug

i use this plugin along with their skyblock plugin. I asked for support in the discord, didn't recieve any. I tried to open a ticket but it says you need to pay to open a ticket? My question is:

i use [https://www.spigotmc.org/resources/✨customdrops✨custom-block-mob-drops-custom-conditions-actions-custom-block-break-speed.107927/](https://www.spigotmc.org/resources/%E2%9C%A8customdrops%E2%9C%A8custom-block-mob-drops-custom-conditions-actions-custom-block-break-speed.107927/) for custom mob drops, no matter how big the size of the stack, when moves are killed (ie fall damage) they only dro p1

I still have no support on this, other than that theplugin works well apart from the names of the mob stacks often glitching out.

### To Reproduce

Make it work with this plugin

### Additional Information

I will also change my review to 5 stars, this is the only issue I find with the plugin, apart from it I am very happy

**Comment by OmerBenGera** [comment]
You should contact the developers of CustomDrops to add support to WildStacker, or just use the built-in system of WildStacker for changing custom drops of mobs.

**Comment by OmerBenGera** [comment]
> I have done research and don't see any built-in system with wildstacker for custom drops...

There is a folder called loot table, where you can edit loot of any mob. It is also documented on the wiki page.

**Comment by mikeyies** [comment]
I see, and do you have any support for this? https://github.com/BG-Software-LLC/WildStacker/issues/949
