### ISSUE TITLE
Golem spawners turn into pig spawners

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildStacker#948]
### Minecraft's Version

1.8.8

### Plugin's Version

2024.1

### Describe the bug

When we set spawners to golems and then leave the zone, spawners become pigs, which blocks the appearance of golems. We can see that when we break a spawner, the message clearly indicates that it's a pig, even if we can see that it's a golem inside.

### To Reproduce

Use this configuration ; 

[config (1).txt](https://github.com/user-attachments/files/16549727/config.1.txt)

**Comment by OmerBenGera** [comment]
Update WildStacker to latest stable/dev build, let me know if is still happens

**Comment by iJuju68** [comment]
It's good il latest dev build thx !!!
