### ISSUE TITLE
Mobs not stacking bug or issue with a config option

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/WildStacker#952]
### Minecraft's Version

This server is running WineSpigot version 1_8_R3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

2024.2-b75

### Describe the bug

Using the default configuation as is. When leaving spawner stacking enabled mobs do stack but soon as you disable spawner stacking mobs don't stack anymore.

### To Reproduce

The same steps i produced but every player is on a different spigot version so i can't really tell you any other way unless you wanna join my server and test it yourself. I'd give you access to my test server panel.

### Additional Information

When Enabled: https://gyazo.com/ca180ed69ce90c8fdbb9e6698568f1f8
When disabled: https://gyazo.com/ae13317f9c24ed66aabc65056ee013d4

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by DebuffPvP** [comment]
It did not fix the issue sorry for the late reply i just got home from outta town

**Comment by DebuffPvP** [comment]
any update on this?

**Comment by OmerBenGera** [comment]
Send me your config file please.
Upload it to pastebin and send a link to it here

**Comment by DebuffPvP** [comment]
https://pastebin.com/kxCnvzGM There you go

**Comment by DebuffPvP** [comment]
let me know if you know or find the issue

**Comment by DebuffPvP** [comment]
any news?

**Comment by DebuffPvP** [comment]
Any news @OmerBenGera

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by DebuffPvP** [comment]
yep it's now fixed thanks.
