### ISSUE TITLE
spawner stacking

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#958]
### Minecraft's Version

This server is running Paper version 1.21.1-77-master@4ff58c4 (2024-09-12T18:05:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b84

### Describe the bug

spawners are not stacking after place while using survival gamemode - when i have creative gamemode it works fine

I believe the problem is connected with SilkSpawners plugin as it does not detect placing while being in creative gamemode
- when i am in survival gamemode silspawners detect spawner placing and the issue with stacking happens (maybe it's connected...)

silkspawners plugin: https://www.spigotmc.org/resources/silkspawners-%E2%98%85-ready-to-rock-1-8-8-1-21-supported-%E2%98%85.7811/updates

### To Reproduce

place spawner next to the previous one

**Comment by OmerBenGera** [comment]
Probably related to SilkSpawners
Contact them for support, or just uninstall the plugin and use WildStacker's features.
