### ISSUE TITLE
DUPE GLITCH for spawners

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#960]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b84
I use SilkSpawners 8.1.0 also 

### Describe the bug

use wind charge (1.21 item) on spawner and it will drop copied spawner + not get destroyed by the explosion

this error pops up in the console while doing it:
https://pastebin.com/Sr3G1jbH

setting this explosiondropchance (in silkspawners config) to 0 makes the glitch not happening + console erorr not popping up BUT it makes the spawner not being dropped at all (from explosion)
```
# Percentage of dropping a spawner block when TNT or creepers explode
explosionDropChance: 100
```

### To Reproduce

as explained above

**Comment by homerek111** [comment]
it actually might be the issue with silkspawners as i am testing it right now without wildstacker and it still happens - nevertheless error was from wildstacker so maybe there is something interesting for you...

**Comment by homerek111** [comment]
> it actually might be the issue with silkspawners as i am testing it right now without wildstacker and it still happens - nevertheless error was from wildstacker so maybe there is something interesting for you...

nvm - tried it without silkspawners (only with wildstacker) and the issue was also happening

**Comment by Asknis** [comment]
I was also made aware of this dupe, here a clip.

https://medal.tv/games/minecraft/clips/iS3jeBtsWALpMZgPC?invite=cr-MSxPaEEsMTM5NzI5MjM3LA

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

seems to be fixed on wildstacket side - thx 
i still have the same issue with silkspawners :/

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it is fixed
> 
> seems to be fixed on wildstacket side - thx i still have the same issue with silkspawners :/

I cant fix it for them sadly.
I'd recommend to get rid of SilkSpawners or try to contact their developer.
Closing this for now
