### ISSUE TITLE
[BUG] Duplication glitch with buckets

### ISSUE THREAD

**Issue by 69Slowpoke** [BG-Software-LLC/WildStacker#963]
### Minecraft's Version

1.21.1

### Plugin's Version

Most up to date version

### Describe the bug

When drinking milk from the buckets, 1 turns into 2 empty buckets and so on. Started with 2 buckets, ended on 7 stacks. 

I checked the settings but couldnt find anything in it that could cause this. 

### To Reproduce

Drink milk from an unstacked cow like video shows. 

### Additional Information

https://youtu.be/b6tHVk1nv_U

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
