### ISSUE TITLE
Double Damage

### ISSUE THREAD

**Issue by Crappervok** [BG-Software-LLC/WildStacker#968]
### Minecraft's Version

1.21

### Plugin's Version

2024.3

### Describe the bug

So! i have a code, the problem is it runs 2 time, it take the damage 2x i think, or just take the iron sword damage, and it adds the hitcounter 2, not 1, so i think it runs 2 time. If i disable the WildStracker, it work perfectly. this is the code:     @EventHandler
    public void onPlayerAttack(EntityDamageByEntityEvent event) {
        if (event.getDamager() instanceof Player) {
            Player player = (Player) event.getDamager();
            ItemStack item = player.getInventory().getItemInMainHand();

            if (item != null && item.getType() == Material.IRON_SWORD) {
                String displayName = ChatColor.stripColor(item.getItemMeta().getDisplayName());

                if (displayName.equals(ChatColor.stripColor(SOUL_SWORD_NAME))) {
                    if (event.getEntity() instanceof LivingEntity) {
                        LivingEntity target = (LivingEntity) event.getEntity();

                        int hitCounter = hitCounterMap.getOrDefault(player.getUniqueId(), 0) + 1;
                        hitCounterMap.put(player.getUniqueId(), hitCounter);

                        if (hitCounter % 4 == 0) {
                            int[] doubleDamageValues = {24, 26, 28, 30, 32};
                            int randomDoubleDamage = doubleDamageValues[random.nextInt(doubleDamageValues.length)];
                            event.setDamage(randomDoubleDamage);
                            hitCounterMap.put(player.getUniqueId(), 0);
                        } else {
                            int randomBaseDamage = 12 + random.nextInt(5);
                            event.setDamage(randomBaseDamage);
                        }
                    }
                }
            }
        }
    }

### To Reproduce

So! i have a code, the problem is it runs 2 time, it take the damage 2x i think, or just take the iron sword damage, and it adds the hitcounter 2, not 1, so i think it runs 2 time. If i disable the WildStracker, it work perfectly.

### Additional Information

it dosnt need an image

**Comment by OmerBenGera** [comment]
The issue is that one of the events are cancelled by WildStacker but you don't ignore it.
You can either add ignoreCancelled=true to your EventHandler, or check if the event is cancelled and return.

**Comment by Crappervok** [comment]
Yea, it fixed the hitcounter double add, but it taking the iron sword damage, and the randomdamage, how can i cancel the iron sword damage?

**Comment by OmerBenGera** [comment]
Why wouldn't it take durability from the iron sword? You use it to hit the mob

**Comment by Crappervok** [comment]
What is this? Inject custom HandlerList to EntityDamageEvent that will forward all damage events only to WildStacker

**Comment by Crappervok** [comment]
Ohh, i fixed it, its my fault sorry!

**Comment by Crappervok** [comment]
Thanks for your help!!

**Comment by OmerBenGera** [comment]
> What is this? Inject custom HandlerList to EntityDamageEvent that will forward all damage events only to WildStacker

WildStacker handles all damages of entities so it can better handle killing of stacked entities.
The new mechanism will make only WildStacker's listener of EntityDamageEvent to be called - then, WildStacker will re-call the EntityDamageEvent to notify all the other plugins.

This makes it so you don't really need to use ignoreCancelled as the original event is only forwarded to WildStacker. You should still use ignoreCancelled as other plugins may still cancel the event.

**Comment by Crappervok** [comment]
Thanks for your help !!!

**Comment by OmerBenGera** [comment]
You welcome!
