### ISSUE TITLE
loottables drops issues

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#969]
### Minecraft's Version

1.21.1

### Plugin's Version

#91

### Describe the bug

wildstacker loottables are a little bit outdated...

biggest issue:
for example 1.21 mechanics for pillagers have changed - now killing pillager captain shouldn't give you ominous effect - it should drop you 1-5lvl ominous_bottle instead
i dont know how to configurate it for captain pillager at all...

i checked some random mob files and for example bogged.json should have some drop chances for arrow of poison but it does not have it in loottables file - there might be more drops like that one
![obraz](https://github.com/user-attachments/assets/48100694-a028-46cd-97a2-8da10092f3d0)

### To Reproduce

-

**Comment by homerek111** [comment]
@OmerBenGera please take a look especially at pillagers as it is a gamebreaking change on 1.21+ version

**Comment by homerek111** [comment]
![obraz](https://github.com/user-attachments/assets/bee6812f-8f34-4179-a39f-7c3e630f363a)
oh and remember that raid captain can have more forms that just pillager (vindicator/evoker/illusioner)

**Comment by homerek111** [comment]
I attach all mob files updated to the newest drops (by me)
in stray.yml and bogged.yml there is essentials give command to give tipped_arrows as i didnt know how to code it properly (you can change it)

the only issue remaining is drop for pillager captain that i described above (idk how to solve it myself)

[lottables_all_files.zip](https://github.com/user-attachments/files/17685017/lottables_all_files.zip)

**Comment by homerek111** [comment]
@OmerBenGera any news about pillager drop issue? :)

**Comment by homerek111** [comment]
@OmerBenGera take a look at that please

**Comment by OmerBenGera** [comment]
@homerek111 Stop spamming the issues.
I will look into it whenever I can.

**Comment by OmerBenGera** [comment]
All the reported bugs should be fixed in latest dev build.
Make sure you regenerate the loot tables by deleting the loot tables folder.

**Comment by homerek111** [comment]
```
    {
      "captain": true,
      "chance": 100,
      "items": [
        {
          "type": "OMINOUS_BOTTLE",
          "chance": 100,
          "min": 1,
          "max": 1,
          "amplifier": {
            "min": 0,
            "max": 4
          }
        }
      ]
    },
```

**Comment by OmerBenGera** [comment]
> > All the reported bugs should be fixed in latest dev build. Make sure you regenerate the loot tables by deleting the loot tables folder.
> 
> @OmerBenGera it seems that it drops ominous bottle from all pillagers (not raid captains only)

My bad, should be fixed in latest dev build as well

**Comment by homerek111** [comment]
> > > All the reported bugs should be fixed in latest dev build. Make sure you regenerate the loot tables by deleting the loot tables folder.
> > 
> > 
> > @OmerBenGera it seems that it drops ominous bottle from all pillagers (not raid captains only)
> 
> My bad, should be fixed in latest dev build as well

@OmerBenGera you didnt add captain lines in illusioner mob - it seems that he can be a captain as well 
- i added it manually but idk if your code respects it 

![obraz](https://github.com/user-attachments/assets/ccd22afc-fb6b-403d-a4cf-38a002e702a8)

**Comment by OmerBenGera** [comment]
> > > > All the reported bugs should be fixed in latest dev build. Make sure you regenerate the loot tables by deleting the loot tables folder.
> > > 
> > > 
> > > @OmerBenGera it seems that it drops ominous bottle from all pillagers (not raid captains only)
> > 
> > 
> > My bad, should be fixed in latest dev build as well
> 
> @OmerBenGera you didnt add captain lines in illusioner mob - it seems that he can be a captain as well
> 
> * i added it manually but idk if your code respects it
> 
> ![obraz](https://private-user-images.githubusercontent.com/93496464/386702962-ccd22afc-fb6b-403d-a4cf-38a002e702a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTQzMTIsIm5iZiI6MTczMTc1NDAxMiwicGF0aCI6Ii85MzQ5NjQ2NC8zODY3MDI5NjItY2NkMjJhZmMtZmI2Yi00MDNkLWE0Y2YtMzhhMDAyZTcwMmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDEwNDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYTQxODkxZDA1OTJmZjkwZTQ5MDM3OGU1MzZhNTFmNjAxNmRjOTBlMGYwNDYyZWNlMTk0NmM1MjY0N2MxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dMfh1pWA5Vzsgj4ec05kABRgvysL89TINBGEGwl1mw0)

Added it as well, thanks!
Anything else that was not yet solved?

**Comment by homerek111** [comment]
> > > > > All the reported bugs should be fixed in latest dev build. Make sure you regenerate the loot tables by deleting the loot tables folder.
> > > > 
> > > > 
> > > > @OmerBenGera it seems that it drops ominous bottle from all pillagers (not raid captains only)
> > > 
> > > 
> > > My bad, should be fixed in latest dev build as well
> > 
> > 
> > @OmerBenGera you didnt add captain lines in illusioner mob - it seems that he can be a captain as well
> > 
> > * i added it manually but idk if your code respects it
> > 
> > ![obraz](https://private-user-images.githubusercontent.com/93496464/386702962-ccd22afc-fb6b-403d-a4cf-38a002e702a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTQzMTIsIm5iZiI6MTczMTc1NDAxMiwicGF0aCI6Ii85MzQ5NjQ2NC8zODY3MDI5NjItY2NkMjJhZmMtZmI2Yi00MDNkLWE0Y2YtMzhhMDAyZTcwMmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDEwNDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYTQxODkxZDA1OTJmZjkwZTQ5MDM3OGU1MzZhNTFmNjAxNmRjOTBlMGYwNDYyZWNlMTk0NmM1MjY0N2MxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dMfh1pWA5Vzsgj4ec05kABRgvysL89TINBGEGwl1mw0)
> 
> Added it as well, thanks! Anything else that was not yet solved?

should be everything here :D

**Comment by homerek111** [comment]
@OmerBenGera bro... it took me 1 hour to find out that #100 widlstacker build breaks pvp on my servers xd
- it makes pvp possible everywhere (on pvp disabled regions as well)

i downgraded to #96 as i dont know which version starts with that bug (it has to be #97 #98 #99 or #100)

i changed permissions system on my server with the same restart that i added that update xd i thought i broke it with permissions and had to check it one by one :P

**Comment by OmerBenGera** [comment]
Open a new bug report.
Send there what plugin you use to disable pvp
