### ISSUE TITLE
Wind Charges from Beezes Duplicate Stacked Spawners on Hit

### ISSUE THREAD

**Issue by gre3x** [BG-Software-LLC/WildStacker#971]
### Minecraft's Version

1.21.1 (Latest Purpur)

### Plugin's Version

2024.3-b91

### Describe the bug

Breeze projectiles hitting a stacked spawner cause the spawner to pop off and duplicate. This happens every time that the breeze wind charge hits.

No errors in console appear during this.

### To Reproduce

1. Place a stacked spawner (2+ spawner)
2. Have a Breeze mob shoot the stacked spawner
3. Notice drops duplicate

### Additional Information

Video to recreate:

https://github.com/user-attachments/assets/6bf2283f-132a-42c7-ad77-d35d319bd889

**Comment by OmerBenGera** [comment]
Check out latest dev build,  should be fixed

**Comment by gre3x** [comment]
Yes confirmed fixed now thank you @OmerBenGera !

**Comment by OmerBenGera** [comment]
You welcome :)
