### ISSUE TITLE
Stupid System Related issue i believe

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/WildStacker#973]
### Minecraft's Version

This server is running WineSpigot version 1_8_R3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Build 96

### Describe the bug

mac os operating systems do this when you change the config files or lang files because os devices generate ds store files when you save a file could you generate a fix so that it ignores those files.

### To Reproduce

N/A

### Additional Information

https://pastebin.com/ZNuEBR30

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by DebuffPvP** [comment]
it's fixed thanks
