### ISSUE TITLE
Lands plugin support

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#975]
### Minecraft's Version

1.21.1

### Plugin's Version

#96 dev 

### Describe the bug

Hello, could you please add the biggest plots plugin (Lands) support - as now players can open spawner GUI on someone’s land and steal their spawners by picking them up via gui. 

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Ask them to prevent clicking on spawners or somehow let ypu configure which blocks are interactables
Or, just disable the menu.
