### ISSUE TITLE
chunk limit does not respect stack

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#976]
### Minecraft's Version

1.21.1

### Plugin's Version

dev #96  

### Describe the bug

setting chunk-limit in config does not respect stacks. you can place one spawner stacked more than configurated amount. I think it should respect stacks or at least give option to respect it or not in config.

```
  # Set a maximum amount of spawner objects in a chunk.
  # If you want to disable the feature, set it to 0.
  chunk-limit: 8
```

### To Reproduce

stack spawners in amount over chunk-limit

**Comment by OmerBenGera** [comment]
Not intended to check for stack sizes, as stated in the config comment:
"Set a maximum amount of spawner **objects** in a chunk."

**Comment by homerek111** [comment]
> Not intended to check for stack sizes, as stated in the config comment: "Set a maximum amount of spawner **objects** in a chunk."
> 
> You can set the spawner limit to 8, then set the chunk limit to 1.

Then it would be limited to 1 spawner type which is not the best :/

If you are thinking about improving the plugin it would be a nice feature to make it possible to respect spawner stacks (the same way as it works on superiorskyblock island limiter - it counts each spawner from stack there)

**Comment by OmerBenGera** [comment]
Not looking into an advanced spawners limiter feature for now.

**Comment by homerek111** [comment]
> Not looking into an advanced spawners limiter feature for now.

@OmerBenGera if something has changed - this feature seems to be very useful and worth adding :P
