### ISSUE TITLE
The function of names-toggle will cause players to disconnect.

### ISSUE THREAD

**Issue by Noogear** [BG-Software-LLC/WildStacker#979]
### Minecraft's Version

leaf 1.21.1

### Plugin's Version

2024.4

### Describe the bug

https://mclo.gs/aGMwl7n

### To Reproduce

Using the command to disable item names will cause players to disconnect and result in error reports in the console.

**Comment by Noogear** [comment]
Consider using PacketEvents instead?  As is well known, ProtocolLib hardly provides prompt support for these issues.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Noogear** [comment]
> Check out latest dev build, let me know if it is fixed

Well done! You are the most responsive author I have ever met.
