### ISSUE TITLE
pillagers [captains]

### ISSUE THREAD

**Issue by GothkittyGirl** [BG-Software-LLC/WildStacker#980]
### Minecraft's Version

1.21.1

### Plugin's Version

latest

### Describe the bug

pillager captains dont seem to be spawning at all with the new update and all i did was wipe my configs

### To Reproduce

just kill pillagers

**Comment by OmerBenGera** [comment]
WildStacker does not modify the way mobs spawn

**Comment by GothkittyGirl** [comment]
ominus bottles still not dropping :/

**Comment by GothkittyGirl** [comment]
had a captain spawn and all i got was the banner

**Comment by GothkittyGirl** [comment]
Uploading 1124(2).mp4…

**Comment by GothkittyGirl** [comment]
https://github.com/user-attachments/assets/bb1c1c22-c256-4b78-bbd2-9b76f24f3a56

**Comment by GothkittyGirl** [comment]
{
  "pairs": [
    {
      "chance": 100,
      "items": [
        {
          "type": "ARROW",
          "chance": 100,
          "min": 0,
          "max": 2,
          "looting": true
        }
      ]
    },
    {
      "captain": true,
      "chance": 100,
      "items": [
        {
          "type": "OMINOUS_BOTTLE",
          "chance": 100,
          "min": 1,
          "max": 1,
          "amplifier": {
            "min": 0,
            "max": 4
          }
        }
      ]
    },
    {
      "killer": [
        "WITHER"
      ],
      "chance": 100,
      "items": [
        {
          "type": "WITHER_ROSE",
          "chance": 100
        }
      ]
    }
  ]
}

Default config too

**Comment by OmerBenGera** [comment]
Try it on a server with only WildStacker installed.
If the issue still occurs, open a new bug report.
