### ISSUE TITLE
upgrade mobs don't stack

### ISSUE THREAD

**Issue by Cennethdk** [BG-Software-LLC/WildStacker#984]
### Minecraft's Version

Mc version 1.21.3 
Server Paper version 1.21.1-131

### Plugin's Version

stable build version  2024.4 

### Describe the bug

when i upgrade my entity spawner, then the entitys don't stack when its the same mob.

### To Reproduce

Idk

### Additional Information

My config

https://pastebin.com/LP7ux3uf
![image](https://github.com/user-attachments/assets/e47ff331-201b-4ee5-a617-98d7fc71eda5)

**Comment by OmerBenGera** [comment]
Change your entities custom name to the following:
```
'&3&l{0}x &b&o{1}{3}'
```
You had an extra `&f` color which was not needed, and it caused conflicts between the vanillia naming and plugin's naming of mobs.
