### ISSUE TITLE
IslandNPC it thinks it is an entity.

### ISSUE THREAD

**Issue by Cennethdk** [BG-Software-LLC/WildStacker#985]
### Minecraft's Version

Mc version 1.21.3
Server Paper version 1.21.1-131

### Plugin's Version

stable build version 2024.4

### Describe the bug

WildStacker removes it because it thinks it is an entity.

### To Reproduce

https://github.com/user-attachments/assets/4b1ca3be-2536-408f-8d1a-497873b73006

### Additional Information

link to pluginet https://builtbybit.com/resources/islandnpc-any-mob-type-automatic.40362/

**Comment by OmerBenGera** [comment]
Support was added in latest dev build of WildStacker
