### ISSUE TITLE
Vehicles plugin support

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#986]
### Minecraft's Version

1.21.1

### Plugin's Version

newest dev build # 106  

### Describe the bug

Hello, WildStacker plugin makes weired glitch in Vehicles plugin. When WildStacker is enabled on the server it is impossible to open fuel gui in the vehicles from Vehicles plugin.... (vehicles are things like cars/helicopters/etc made with armorstands)
- Fuel gui should open after pressing SHIFT+LMB on the vehicle but WildStacker somehow blocks it...

There is no error in console or anything else. When i disable WildStacker this issue does not happen.

Vehicles plugin:
https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

Is there anything we can do to fix this plugin compatibility?

### To Reproduce

-

**Comment by OmerBenGera** [comment]
I contacted their developer, hopefully he will respond soon :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed

**Comment by homerek111** [comment]
> Check out latest dev build, this should be fixed

seems to be fixed, thanks
