### ISSUE TITLE
[!] Armor and guns problem when stack

### ISSUE THREAD

**Issue by smscentras** [BG-Software-LLC/WildStacker#988]
### Minecraft's Version

Purpur 1.21.1

### Plugin's Version

2024.4

### Describe the bug

Throw 3 chestplates on the ground for example, the information shows that there are three of them, but when you pick them up from the ground, you only get one! This problem for weapons and armor ONLY.

### To Reproduce

Throw 3 chestplates on the ground for example, the information shows that there are three of them, but when you pick them up from the ground, you only get one! This problem for weapons and armor ONLY.

**Comment by OmerBenGera** [comment]
Does this happen if you enable fix-stack?

**Comment by smscentras** [comment]
> Does this happen if you enable fix-stack?

helped alot, thank you.
