### ISSUE TITLE
Chicken spawned from thrown eggs are not beeing stacked

### ISSUE THREAD

**Issue by qwerio** [BG-Software-LLC/WildStacker#990]
### Minecraft's Version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.3-2358-16ce24a (MC: 1.21.3)

### Plugin's Version

WildStacker version 2024.4
Stacking drops, entities, blocks and spawners into one object!
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

Chicken spawned from thrown eggs by hand or dispenser are not being stacked

### To Reproduce

Just throw eggs

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by atilapan** [comment]
This also seems to be resolved.
