### ISSUE TITLE
Villagers could duplicate when turning into Zombie Villagers 

### ISSUE THREAD

**Issue by atilapan** [BG-Software-LLC/WildStacker#992]
### Minecraft's Version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.3-2358-16ce24a (MC: 1.21.3)

### Plugin's Version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*\n* You are running the latest version\nPrevious: 1.21.3-2358-16ce24a (MC: 1.21.3)
WildStacker version 2024.4
Stacking drops, entities, blocks and spawners into one object!
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

Villages when attacked by zombies and infected sometimes duplicate. Instead of one Villager turning into one Zombie Villager, there are sometimes two Zombie Villagers so for particular reason. And they both seem to keep everything about the original Villager.

### To Reproduce

Install plugin
Switch difficulty to Hard (not sure if Normal is affected)
Spawn a Villager and a Zombie
Wait for the Zombie to kill the Villager
And watch... there is some percent chance instead of one you will get two zombie villagers

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed

**Comment by atilapan** [comment]
What a coincidence I was also checking out the bug and I think I actually found the issue. The zombie sometimes could hit the Villagers a second time which would cause eventually `checkForZombieVillager` to be called twice. Just a question as this seems to only affect Zombie Villages, couldn't we just despawn the Villager before the Zombie Villager is spawned?

**Comment by OmerBenGera** [comment]
> What a coincidence I was also checking out the bug and I think I actually found the issue. The zombie sometimes could hit the Villagers a second time which would cause eventually `checkForZombieVillager` to be called twice. Just a question as this seems to only affect Zombie Villages, couldn't we just despawn the Villager before the Zombie Villager is spawned?

Right, that was the issue and it has been fixed :)
Closing this
