### ISSUE TITLE
stacked water buckets lost after putting them in chest using SHIFT+mouse

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/WildStacker#995]
### Minecraft's Version

This server is running Paper version 1.21.1-128-master@d348cb8 (2024-10-21T16:23:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.4-b107

### Describe the bug

as title says: when you put stacked water buckets into chest using SHIFT+mouse they are disappearing and only 1 water bucket stays in the chest (it seems that they are all showed up there for millisecond and after that only 1 is in chest)

### To Reproduce

put stacked water buckets into chest

**Comment by OmerBenGera** [comment]
Duplicate of #972
